#include "ultra64.h"
#include "global.h"

#define SFX_PARAMS(distParam, randParam, flags)                 \
    (((distParam) << SFX_PARAM_01_SHIFT) & SFX_PARAM_01_MASK) | \
        (((randParam) << SFX_PARAM_67_SHIFT) & SFX_PARAM_67_MASK) | (flags)

SoundParams sEnemyBankParams[] = {
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_CRY
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_FIRE
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DODO_J_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DODO_J_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_CRY
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_DAMAGE
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_DEAD
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_DODO_K_WALK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_FIRE
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_GOMA_WALK
    { 0x20, SFX_PARAMS(1, 2, 0) },           // NA_SE_EN_GOMA_HIGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_CLIM
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_DOWN
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_CRY1
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_CRY2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_DAM1
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_DAM2
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_DEAD
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_GOMA_UNARI
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_EGG1
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_EGG2
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_GOMA_BJR_WALK
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_CRY
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_DAM1
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_DAM2
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_DEMO_EYE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_LAST
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_UNARI2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_FAINT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_FREEZE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_CRY
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DODO_M_DEAD
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_MOVE
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_DOWN
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_UP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_THROW_MASIC
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_EAT
    { 0x44, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DD_THUNDER
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIZA_ONGND
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_RIZA_CRY
    { 0x32, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_RIZA_ATTACK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_RIZA_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIZA_WARAU
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_RIZA_DEAD
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIZA_WALK
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIZA_JUMP
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALKID_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALKID_ATTACK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STALKID_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STALKID_DEAD
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FLOORMASTER_SLIDING
    { 0x18, SFX_PARAMS(0, 2, 0) },           // NA_SE_EN_TEKU_WALK_WATER
    { 0x38, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_LIGHT_ARROW_HIT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TUBOOCK_FLY
    { 0x28, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STAL_WARAU
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STAL_SAKEBI
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STAL_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STAL_DEAD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_WOLFOS_APPEAR
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STAL_WALK
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_WOLFOS_CRY
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_WOLFOS_ATTACK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FFLY_ATTACK
    { 0x20, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FFLY_FLY
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FFLY_DEAD
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_WOLFOS_DAMAGE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_AMOS_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_AMOS_WAVE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_AMOS_DEAD
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_AMOS_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_AMOS_VOICE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_SHELL_MOUTH
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_SHELL_DEAD
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_WOLFOS_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_COLI
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_DODO_K_COLI2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_ROLL
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_BREATH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_DRINK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_DOWN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_OTAKEBI
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_END
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_LAST
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DODO_K_LAVA
    { 0x18, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_FLOAT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DARKWAVE_M
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_BREATH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_TAIL
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_WOLFOS_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_J_EAT
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DEKU_MOUTH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DEKU_ATTACK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DEKU_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DEKU_DEAD
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DEKU_JR_MOUTH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DEKU_JR_ATTACK
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DEKU_JR_DEAD
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DEKU_SCRAPE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TAIL_FLY
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TAIL_CRY
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_TAIL_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_SPARK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_DOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_UP
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_LAUGH
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STALTU_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STAL_JUMP
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_TEKU_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_TEKU_DEAD
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TEKU_WALK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_PO_KANTERA
    { 0x20, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_PO_FLY
    { 0x20, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_PO_AWAY
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_APPEAR
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_DISAPPEAR
    { 0x38, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_DAMAGE
    { 0x40, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_DEAD
    { 0x40, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_DEAD2
    { 0x14, SFX_PARAMS(1, 2, 0) },           // NA_SE_EN_EXTINCT
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOLON_LAND_BIG
    { 0x40, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIZA_DOWN
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DODO_M_GND
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NUTS_UP
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NUTS_DOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NUTS_THROW
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NUTS_WALK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_NUTS_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_NUTS_DEAD
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NUTS_FAINT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_PO_BIG_GET
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_ROLL
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STALWALL_DEAD
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_PO_SISTER_DEAD
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BARI_SPLIT
    { 0x28, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_TEKU_REVERSE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_LAND2
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TEKU_LAND_WATER
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_LAST_DAMAGE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALWALL_ROLL
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALWALL_DASH
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TEKU_JUMP_WATER
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TEKU_LAND_WATER2
    { 0x38, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FALL_AIM
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FALL_UP
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FALL_CATCH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FALL_LAND
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FALL_WALK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FALL_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FALL_DEAD
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_KAICHO_FLUTTER
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIRI_FLY
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIRI_JUMP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIRI_SPARK
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BIRI_DEAD
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BIRI_BUBLE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BARI_ROLL
    { 0x34, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GOMA_JR_FREEZE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BARI_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_FIRE
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_FANTOM_TRANSFORM
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FANTOM_THUNDER
    { 0x20, SFX_PARAMS(3, 1, 0) },           // NA_SE_EN_FANTOM_SPARK
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_FANTOM_FLOAT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_MASIC1
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_MASIC2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_FIRE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_HIT_THUNDER
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FANTOM_ATTACK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_STICK
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_FANTOM_EYE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FANTOM_LAST
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_THUNDER_GND
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_DAMAGE
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_LAUGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_DAMAGE2
    { 0x30, SFX_PARAMS(3, 0, SFX_FLAG_10) }, // NA_SE_EN_FANTOM_VOICE
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_KAICHO_DAMAGE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_ATTACK_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_FIRE_DEMO
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_KAICHO_CRY
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_KAICHO_ATTACK
    { 0x18, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_MORIBLIN_WALK
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_MORIBLIN_SLIDE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_MORIBLIN_ATTACK
    { 0x14, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MORIBLIN_VOICE
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MORIBLIN_SPEAR_AT
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MORIBLIN_SPEAR_NORM
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MORIBLIN_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MORIBLIN_DASH
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_ROCK
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_FLOAT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_JUMP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_LAND
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_SINK
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OCTAROCK_BUBLE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_OCTAROCK_DEAD1
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_OCTAROCK_DEAD2
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_WING
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_MOUTH
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_LAUGH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_BITE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLE_DOWN
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BUBLE_DEAD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLEFALL_FIRE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_APPEAR
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_ROAR
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_MAHI1
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_MAHI2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_KNOCKOUT
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_DAMAGE1
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_DAMAGE2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_ROCK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_SW_NAIL
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_BURN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_FIRE
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BARI_DAMAGE
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CORE_LAND
    { 0x28, SFX_PARAMS(3, 2, 0) },           // NA_SE_EN_MOFER_CORE_MOVE_WT
    { 0x28, SFX_PARAMS(2, 2, 0) },           // NA_SE_EN_MOFER_CORE_SMJUMP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MONBLIN_GNDWAVE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_MONBLIN_HAM_DOWN
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_MONBLIN_HAM_UP
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BUBLE_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_REDEAD_CRY
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_REDEAD_AIM
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_REDEAD_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_REDEAD_DEAD
    { 0x34, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_REDEAD_ATTACK
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NYU_MOVE
    { 0x38, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_NYU_HIT_STOP
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_KAICHO_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_PO_LAUGH
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_CRY
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PO_ROLL
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_PO_LAUGH2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_APPEAR
    { 0x32, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_ATTACK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_WAVE
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CATCH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CUT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_MOVE_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_BUBLE_DEMO
    { 0x28, SFX_PARAMS(2, 2, 0) },           // NA_SE_EN_MOFER_CORE_JUMP
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_DEAD
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_LASTVOICE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CORE_ROLL
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CORE_FLY
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOLON_WAKE_UP
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOLON_SIT_DOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_CHICKEN_FLUTTER
    { 0x20, SFX_PARAMS(0, 2, 0) },           // NA_SE_EN_DEKU_WAKEUP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_BITE
    { 0x18, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_WALK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_GRIP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_HAND_AT
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DAIOCTA_MAHI
    { 0x18, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DAIOCTA_SPLASH
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_DAIOCTA_VOICE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DAIOCTA_DAMAGE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DAIOCTA_SINK
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DAIOCTA_DEAD
    { 0x40, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_DAIOCTA_DEAD2
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_HIT_THUNDER
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_APPEAR_MS
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_TRANSFORM
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_MS_FIRE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_FIRE_EXP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_POWERUP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_SHOOT_FREEZE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_MS_FREEZE
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_TWINROBA_MASIC_SET
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_CUTBODY
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_HIT_GND_IMP
    { 0x38, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_DAMAGE_VOICE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_REFL_FIRE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_REFL_FREEZE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_CUTBODY
    { 0x38, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_DAMAGE
    { 0x40, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_DEAD
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOLON_EYE_BIG
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOLON_GOOD_BIG
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_TWINROBA_FB_FLY
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_TWINROBA_FLY
    { 0x24, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_UNARI
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_ROLL
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_SHOOT_FIRE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_THROW_MASIC
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DARUNIA_HIT_BREAST
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DARUNIA_HIT_LINK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_OWL_FLUTTER
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_VALVAISA_LAND
    { 0x18, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_IRONNACK_WALK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_SWING_AXE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_STAGGER_DEMO
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_OFF_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_LAND1_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_LAND2_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_LAND3_DEMO
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FLOORMASTER_ATTACK
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FLOORMASTER_SM_WALK
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FLOORMASTER_SM_DEAD
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FLOORMASTER_RESTORE
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FLOORMASTER_EXPAND
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FLOORMASTER_SPLIT
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLOORMASTER_SM_STICK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FLOORMASTER_SM_LAND
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_WAVE_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_FINGER_DEMO
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_ARMOR_HIT
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_NUTS_CUTBODY
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_BALINADE_LEVEL
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_DAMAGE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_FAINT
    { 0x30, SFX_PARAMS(3, 2, 0) },           // NA_SE_EN_BALINADE_BREAK
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_STICK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_THUNDER
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_BALINADE_BL_SPARK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_BL_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_BREAK2
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_HIT_RINK
    { 0x20, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_WAVE_GND
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_AWA_BOUND
    { 0x20, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_AWA_BREAK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BROB_WAVE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_NYU_DEAD
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_EIER_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_EIER_DEAD
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_EIER_FLUTTER
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_EIER_FLY
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_TAIKO_LOW
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_TAIKO_HIGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_CLAP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_FLY_ATTACK
    { 0x28, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PIHAT_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_PIHAT_FLY
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_PIHAT_DAMAGE
    { 0x28, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_PIHAT_LAND
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_HAND_DOWN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_HAND_UP
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_HAND_DAMAGE
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_BALINADE_HAND_DEAD
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOMA_JR_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOMA_JR_CRY
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GOMA_JR_DAM1
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GOMA_JR_DAM2
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GOMA_JR_DEAD
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOMA_EGG1
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOMA_EGG2
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_GANON_BODY_SPARK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_HAND_WAVE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_CATCH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_LAND
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_HAND_FLY
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_SHADEST_SHAKEHAND
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_DAMAGE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_DAMAGE_HAND
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_DISAPPEAR
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_CHARGE_MASIC
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_THROW_BIG
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_FREEZE
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_DEAD
    { 0x10, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIMOS_ROLL_HEAD
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIMOS_LAZER
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIMOS_LAZER_GND
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BIMOS_AIM
    { 0x14, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLEWALK_WALK
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_BUBLEWALK_AIM
    { 0x28, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BUBLEWALK_REVERSE
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BUBLEWALK_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_BUBLEWALK_DEAD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_YUKABYUN_FLY
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_TWINROBA_FLY_DEMO
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_FLAME_KICK
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_FLAME_RUN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_ROLL
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_MAN_RUN
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_MAN_DAMAGE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_LAUGH
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FLAME_MAN_SLIDE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FLAME_FIRE_ATTACK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_PIHAT_SM_FLY
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_PIHAT_SM_DEAD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIVA_APPEAR
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_AKINDONUTS_HIDE
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_RIVA_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_RIVA_DEAD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_RIVA_MOVE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_FLAME_MAN_SURP
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_LAST
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_SHADEST_MOVE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_SHADEST_PRAY
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_ROAR
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_LIKE_WALK
    { 0x28, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_LIKE_UNARI
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_LIKE_DRINK
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_LIKE_EAT
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_LIKE_THROW
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_LIKE_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_LIKE_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_SWORD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GERUDOFT_ATTACK
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GERUDOFT_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GERUDOFT_DEAD
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_DAMAGE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_ANUBIS_FIRE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_ANUBIS_FIREBOMB
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_DEAD1
    { 0x40, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_ANUBIS_DEAD
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_MUSI_LAND
    { 0x44, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_DEAD2
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_EIER_ATTACK
    { 0x18, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_EIER_CRY
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_FREEZAD_BREATH
    { 0x38, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FREEZAD_DAMAGE
    { 0x40, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_FREEZAD_DEAD
    { 0x18, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_LAUGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_HIDE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_DAMAGE
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_HAND_DEAD
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_DEADHAND_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_BREAK_PILLAR2
    { 0x36, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_BREAK_PILLAR
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_HIT_GND
    { 0x28, SFX_PARAMS(2, 2, 0) },           // NA_SE_EN_MGANON_BREATH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_LAUGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_LAUGH2
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY434
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_SHOOT_VOICE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_SENSE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_DIE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY438
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_DAMAGE2
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_SHOOTVC
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_LAUGH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY442
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_TWINROBA_YOUNG_WINK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY444
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY445
    { 0x28, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_DAMAGE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_DASH
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_DEAD
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_PULLOUT
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_IRONNACK_WAKEUP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY451
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY452
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_DUMMY453
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GERUDOFT_BREATH
    { 0x20, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_LAUGH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_VOICE_DEMO
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_THROW
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_AT_RETURN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_HIT_GND
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DAMAGE1
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DAMAGE2
    { 0x20, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DOWN
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_RESTORE
    { 0x44, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DEAD
    { 0x30, SFX_PARAMS(3, 2, 0) },           // NA_SE_EN_GANON_BREATH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_TOKETU
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_CASBREAK
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_BIGMASIC
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GANON_DARKWAVE
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_FANTOM_ST_LAUGH
    { 0x20, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_MGANON_WALK
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_STAND
    { 0x20, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_UNARI
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALGOLD_ROLL
    { 0x30, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_KDOOR_WAVE
    { 0x40, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_KDOOR_HIT
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_KDOOR_BREAK
    { 0x34, SFX_PARAMS(2, 0, 0) },           // NA_SE_EN_KDOOR_HIT_GND
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MGANON_SWDIMP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_WAVE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_STALTU_DOWN_SET
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_DUMMY482
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_LAND
    { 0x24, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOMA_BJR_LAND2
    { 0x34, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_GOMA_JR_LAND
    { 0x20, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_GOMA_JR_LAND2
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_TWINROBA_FIGHT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_PO_BIG_CRY
    { 0x08, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_MUSI_SINK
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_EN_STALGOLD_UP_CRY
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_GOLON_CRY
    { 0x38, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MOFER_CORE_DAMAGE
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_DAIOCTA_LAND_WATER
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_RIVA_BIG_APPEAR
    { 0x34, SFX_PARAMS(0, 0, SFX_FLAG_13) }, // NA_SE_EN_MONBLIN_HAM_LAND
    { 0x08, SFX_PARAMS(0, 0, 0) },           // NA_SE_EN_MUSI_WALK
    { 0x40, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_MIMICK_BREATH
    { 0x34, SFX_PARAMS(3, 0, 0) },           // NA_SE_EN_STALWALL_LAUGH
};

SoundParams sPlayerBankParams[] = {
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_GROUND
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_SAND
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_CONCRETE
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_DIRT
    { 0x20, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_WALK_WATER0
    { 0x20, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_WALK_WATER1
    { 0x20, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_WALK_WATER2
    { 0x20, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_WALK_MAGMA
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_GRASS
    { 0x20, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_WALK_IRON
    { 0x20, SFX_PARAMS(0, 2, SFX_FLAG_10) },               // NA_SE_PL_WALK_LADDER
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_WALK_GLASS
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_WALK_WALL
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_WALK_HEAVYBOOTS
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_14
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_WALK_ICE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_SAND
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_CONCRETE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_DIRT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_WATER0
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_WATER1
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_WATER2
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_MAGMA
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_GRASS
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_IRON
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_LADDER
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_GLASS
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_DUMMY28
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_HEAVYBOOTS
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_DUMMY30
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_JUMP_ICE
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_SAND
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_CONCRETE
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_DIRT
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_WATER0
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_WATER1
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_WATER2
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_MAGMA
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_GRASS
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_IRON
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_LADDER
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_GLASS
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_44
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_HEAVYBOOTS
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_46
    { 0x40, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_LAND_ICE
    { 0x30, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_SLIPDOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_CLIMB_CLIFF
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SIT_ON_HORSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_GET_OFF_HORSE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_TAKE_OUT_SHIELD
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_CHANGE_ARMS
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_CATCH_BOOMERANG
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_55
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_56
    { 0x30, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_SWIM
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_THROW
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_BODY_BOUND
    { 0x40, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_ROLL
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_SKIP
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) },               // NA_SE_PL_BODY_HIT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_DAMAGE
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_SAND
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_CONCRETE
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_DIRT
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_WATER0
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_WATER1
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_WATER2
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_MAGMA
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_GRASS
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_IRON
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_LADDER
    { 0x30, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_SLIP_GLASS
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY76
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_HEAVYBOOTS
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY78
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_ICE
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_SAND
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_CONCRETE
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_DIRT
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_WATER0
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_WATER1
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_WATER2
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_MAGMA
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_GRASS
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_IRON
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_LADDER
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_WOOD
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_92
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_HEAVYBOOTS
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_94
    { 0x80, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_ICE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_96
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_97
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_98
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_FACE_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DIVE_BUBBLE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_MOVE_BUBBLE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_METALEFFECT_KID
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_METALEFFECT_ADULT
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SPARK
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PULL_UP_PLANT
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PULL_UP_ROCK
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_IN_BUBBLE
    { 0x30, SFX_PARAMS(3, 0, 0) },                         // NA_SE_PL_PULL_UP_BIGROCK
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SWORD_CHARGE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_FREEZE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PULL_UP_POT
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_KNOCK
    { 0x30, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_CALM_HIT
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_CALM_PAT
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SUBMERGE
    { 0x30, SFX_PARAMS(3, 0, 0) },                         // NA_SE_PL_FREEZE_S
    { 0x30, SFX_PARAMS(1, 0, 0) },                         // NA_SE_PL_ICE_BROKEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_ICE_LELEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PUT_OUT_ITEM
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PULL_UP_WOODBOX
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_MAGIC_FIRE
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_MAGIC_WIND_NORMAL
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) },               // NA_SE_PL_MAGIC_WIND_WARP
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11 | SFX_FLAG_10) }, // NA_SE_PL_MAGIC_SOUL_NORMAL
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_ARROW_CHARGE_FIRE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_ARROW_CHARGE_ICE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },               // NA_SE_PL_ARROW_CHARGE_LIGHT
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_128
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_129
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_130
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_PULL_UP_RUTO
    { 0x20, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_132
    { 0x20, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_133
    { 0x20, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_134
    { 0x20, SFX_PARAMS(0, 1, 0) },                         // NA_SE_PL_DUMMY_135
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_136
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_137
    { 0x20, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_DUMMY_138
    { 0x20, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_139
    { 0x20, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_140
    { 0x20, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_141
    { 0x20, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_142
    { 0x20, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_143
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_144
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_145
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_146
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_147
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_148
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_149
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_150
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_151
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_152
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_153
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_154
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_155
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_156
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_157
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_158
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_159
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_160
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_161
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_162
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_163
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_164
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_165
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_166
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_167
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_168
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_169
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_170
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_171
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_172
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_173
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_174
    { 0x40, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_175
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_SAND
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_CONCRETE
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_DIRT
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_WATER0
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_181
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_182
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_183
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_184
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_185
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_186
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_WOOD
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_CRAWL_ICE
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_189
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_190
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) },               // NA_SE_PL_DUMMY_191
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11 | SFX_FLAG_10) }, // NA_SE_PL_MAGIC_SOUL_FLASH
    { 0x30, SFX_PARAMS(0, 2, 0) },                         // NA_SE_PL_ROLL_DUST
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_192
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_MAGIC_SOUL_BALL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SPIRAL_HEAL_BEAM
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_BOUND_NOWEAPON
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PLANT_GROW_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PLANT_TALLER
    { 0x60, SFX_PARAMS(2, 0, 0) },                         // NA_SE_PL_MAGIC_WIND_VANISH
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_HOBBERBOOTS_LV
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_PLANT_MOVE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11) },               // NA_SE_EV_WALL_MOVE_SP
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_204
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_205
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_206
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_207
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_SAND_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_CONCRETE_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_DIRT_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_WATER0_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_WATER1_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_WATER2_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_MAGMA_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_GRASS_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_IRON_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_GLASS_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_WOOD_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_220
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_DUMMY_221
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_HEAVYBOOTS_LEVEL
    { 0x30, SFX_PARAMS(0, 0, 0) },                         // NA_SE_PL_SLIP_ICE_LEVEL
};

SoundParams sItemBankParams[] = {
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_15) }, // NA_SE_IT_SWORD_IMPACT
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_SWORD_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_PUTAWAY
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_PICKOUT
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) }, // NA_SE_IT_ARROW_SHOT
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) }, // NA_SE_IT_BOOMERANG_THROW
    { 0x60, SFX_PARAMS(3, 2, 0) },           // NA_SE_IT_SHIELD_BOUND
    { 0x30, SFX_PARAMS(0, 1, SFX_FLAG_10) }, // NA_SE_IT_BOW_DRAW
    { 0x80, SFX_PARAMS(3, 1, 0) },           // NA_SE_IT_SHIELD_REFLECT_SW
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_ARROW_STICK_HRAD
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_HAMMER_HIT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_HOOKSHOT_CHAIN
    { 0x30, SFX_PARAMS(1, 0, SFX_FLAG_10) }, // NA_SE_IT_SHIELD_REFLECT_MG
    { 0x50, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_BOMB_IGNIT
    { 0x90, SFX_PARAMS(2, 0, 0) },           // NA_SE_IT_BOMB_EXPLOSION
    { 0x50, SFX_PARAMS(2, 0, 0) },           // NA_SE_IT_BOMB_UNEXPLOSION
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_BOOMERANG_FLY
    { 0x40, SFX_PARAMS(2, 0, 0) },           // NA_SE_IT_SWORD_STRIKE
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_HAMMER_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_HOOKSHOT_REFLECT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_ARROW_STICK_CRE
    { 0x34, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_ARROW_STICK_OBJ
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DUMMY
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DUMMY2
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_SWING_HARD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DUMMY3
    { 0x40, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_WALL_HIT_HARD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_WALL_HIT_SOFT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_STONE_HIT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_WOODSTICK_BROKEN
    { 0x30, SFX_PARAMS(0, 2, 0) },           // NA_SE_IT_LASH
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_SHIELD_POSTURE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_SLING_SHOT
    { 0x20, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_SLING_DRAW
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_CHARGE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_ROLLING_CUT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_STRIKE_HARD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SLING_REFLECT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_REMOVE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_HOOKSHOT_READY
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_HOOKSHOT_RECEIVE
    { 0x60, SFX_PARAMS(3, 1, 0) },           // NA_SE_IT_HOOKSHOT_STICK_OBJ
    { 0x30, SFX_PARAMS(1, 0, 0) },           // NA_SE_IT_SWORD_REFLECT_MG
    { 0x30, SFX_PARAMS(1, 0, SFX_FLAG_10) }, // NA_SE_IT_DEKU
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_WALL_HIT_BUYO
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_PUTAWAY_STN
    { 0xA0, SFX_PARAMS(2, 0, 0) },           // NA_SE_IT_ROLLING_CUT_LV1
    { 0xA0, SFX_PARAMS(2, 0, 0) },           // NA_SE_IT_ROLLING_CUT_LV2
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_BOW_FLICK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_BOMBCHU_MOVE
    { 0x60, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_CHARGE_LV1
    { 0x60, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_CHARGE_LV2
    { 0x60, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_CHARGE_LV3
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) }, // NA_SE_IT_SLING_FLICK
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SWORD_STICK_STN
    { 0x60, SFX_PARAMS(1, 2, 0) },           // NA_SE_IT_REFLECTION_WOOD
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_REFLECT_MG2
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_MAGIC_ARROW_SHOT
    { 0x60, SFX_PARAMS(3, 0, SFX_FLAG_15) }, // NA_SE_IT_EXPLOSION_FRAME
    { 0x60, SFX_PARAMS(3, 0, SFX_FLAG_15) }, // NA_SE_IT_EXPLOSION_ICE
    { 0x60, SFX_PARAMS(3, 0, SFX_FLAG_15) }, // NA_SE_IT_EXPLOSION_LIGHT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_14) }, // NA_SE_IT_FISHING_REEL_SLOW
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_14) }, // NA_SE_IT_FISHING_REEL_HIGH
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_PULL_FISHING_ROD
    { 0x80, SFX_PARAMS(3, 0, 0) },           // NA_SE_IT_DM_FLYING_GOD_PASS
    { 0x80, SFX_PARAMS(3, 0, 0) },           // NA_SE_IT_DM_FLYING_GOD_DASH
    { 0x30, SFX_PARAMS(3, 0, 0) },           // NA_SE_IT_DM_RING_EXPLOSION
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DM_RING_GATHER
    { 0x30, SFX_PARAMS(0, 1, 0) },           // NA_SE_IT_INGO_HORSE_NEIGH
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_EARTHQUAKE
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DUMMY4
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_KAKASHI_JUMP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_FLAME
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_SHIELD_BEAM
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_FISHING_HIT
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_GOODS_APPEAR
    { 0x80, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_MAJIN_SWORD_BROKEN
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_HAND_CLAP
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_MASTER_SWORD_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_IT_DUMMY5
};

SoundParams sEnvBankParams[] = {
    { 0x70, SFX_PARAMS(0, 1, SFX_FLAG_10 | SFX_FLAG_9) },                // NA_SE_EV_DOOR_OPEN
    { 0x80, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_DOOR_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_EXPLOSION
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_HORSE_WALK
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_HORSE_RUN
    { 0x40, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_HORSE_NEIGH
    { 0x30, SFX_PARAMS(0, 2, SFX_FLAG_10) },                             // NA_SE_EV_RIVER_STREAM
    { 0x38, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_WATER_WALL_BIG
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_OUT_OF_WATER
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_DIVE_WATER
    { 0x80, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_ROCK_SLIDE
    { 0xA0, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_MAGMA_LEVEL
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BRIDGE_OPEN
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BRIDGE_CLOSE
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BRIDGE_OPEN_STOP
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BRIDGE_CLOSE_STOP
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_WALL_BROKEN
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_CHICKEN_CRY_N
    { 0x30, SFX_PARAMS(0, 1, 0) },                                       // NA_SE_EV_CHICKEN_CRY_A
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_CHICKEN_CRY_M
    { 0x60, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SLIDE_DOOR_OPEN
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_FOOT_SWITCH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_GROAN
    { 0x30, SFX_PARAMS(2, 2, 0) },                                       // NA_SE_EV_BOMB_DROP_WATER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_JUMP
    { 0x40, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_LAND
    { 0x38, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_SLIP
    { 0x28, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FAIRY_DASH
    { 0x60, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SLIDE_DOOR_CLOSE
    { 0x70, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_STONE_BOUND
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_STONE_STATUE_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TBOX_UNLOCK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TBOX_OPEN
    { 0xA0, SFX_PARAMS(0, 0, SFX_FLAG_13 | SFX_FLAG_3) },                // NA_SE_SY_TIMER
    { 0x20, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_FLAME_IGNITION
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SPEAR_HIT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11) },                             // NA_SE_EV_ELEVATOR_MOVE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_15 | SFX_FLAG_11) },               // NA_SE_EV_WARP_HOLE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_15) },                             // NA_SE_EV_LINK_WARP
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_PILLAR_SINK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WATER_WALL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RIVER_STREAM_S
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RIVER_STREAM_F
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_LAND2
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },                             // NA_SE_EV_HORSE_SANDDUST
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DUMMY45
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LIGHTNING
    { 0x30, SFX_PARAMS(0, 2, 0) },                                       // NA_SE_EV_BOMB_BOUND
    { 0x60, SFX_PARAMS(2, 1, 0) },                                       // NA_SE_EV_WATERDROP
    { 0x10, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TORCH
    { 0xA0, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_MAGMA_LEVEL_M
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FIRE_PILLAR
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_4) },                              // NA_SE_EV_FIRE_PLATE
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BLOCK_BOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_METALDOOR_SLIDE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_METALDOOR_STOP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BLOCK_SHAKE
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_BOX_BREAK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HAMMER_SWITCH
    { 0xA0, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_MAGMA_LEVEL_L
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SPEAR_FENCE
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },                             // NA_SE_EV_GANON_HORSE_NEIGH
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_10) },                             // NA_SE_EV_GANON_HORSE_GROAN
    { 0x70, SFX_PARAMS(3, 0, SFX_FLAG_4) },                              // NA_SE_EV_FANTOM_WARP_S
    { 0x60, SFX_PARAMS(0, 0, SFX_FLAG_15) },                             // NA_SE_EV_FANTOM_WARP_L
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_15) },                             // NA_SE_EV_FOUNTAIN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KID_HORSE_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KID_HORSE_RUN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KID_HORSE_NEIGH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KID_HORSE_GROAN
    { 0x30, SFX_PARAMS(3, 0, SFX_FLAG_13) },                             // NA_SE_EV_WHITE_OUT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LIGHT_GATHER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TREE_CUT
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13 | SFX_FLAG_4) },                // NA_SE_EV_VOLCANO
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GUILLOTINE_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GUILLOTINE_BOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ROLLCUTTER_MOTOR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_CHINETRAP_DOWN
    { 0x30, SFX_PARAMS(1, 0, 0) },                                       // NA_SE_EV_PLANT_BROKEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SHIP_BELL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FLUTTER_FLAG
    { 0x40, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TRAP_BOUND
    { 0x30, SFX_PARAMS(2, 3, 0) },                                       // NA_SE_EV_ROCK_BROKEN
    { 0x70, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_FANTOM_WARP_S2
    { 0x60, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_FANTOM_WARP_L2
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_COFFIN_CAP_OPEN
    { 0x60, SFX_PARAMS(1, 0, 0) },                                       // NA_SE_EV_COFFIN_CAP_BOUND
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_WIND_TRAP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TRAP_OBJ_SLIDE
    { 0x90, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_METALDOOR_OPEN
    { 0x90, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_METALDOOR_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BURN_OUT
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_BLOCKSINK
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13 | SFX_FLAG_12 | SFX_FLAG_11) }, // NA_SE_EV_CROWD
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WATER_LEVEL_DOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_NAVY_VANISH
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_LADDER_DOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WEB_VIBRATION
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WEB_BROKEN
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_ROLL_STAND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BUYODOOR_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BUYODOOR_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WOODDOOR_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_METALGATE_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_IT_SCOOP_UP_WATER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FISH_LEAP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KAKASHI_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KAKASHI_ROLL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BOTTLE_CAP_OPEN
    { 0x30, SFX_PARAMS(3, 0, SFX_FLAG_11) },                             // NA_SE_EV_JABJAB_BREATHE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SPIRIT_STONE
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_TRIFORCE_FLASH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FALL_DOWN_DIRT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_NAVY_FLY
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_NAVY_CRASH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WOOD_HIT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SCOOPUP_WATER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DROP_FALL
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_WOOD_GEAR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TREE_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HORSE_RUN_LEVEL
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_ELEVATOR_MOVE2
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_ELEVATOR_STOP
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_TRE_BOX_APPEAR
    { 0x40, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_CHAIN_KEY_UNLOCK
    { 0x1C, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SPINE_TRAP_MOVE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HEALING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GREAT_FAIRY_APPEAR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GREAT_FAIRY_VANISH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RED_EYE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ROLL_STAND_2
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WALL_SLIDE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TRE_BOX_FLASH
    { 0x60, SFX_PARAMS(0, 0, SFX_FLAG_9) },                              // NA_SE_EV_WINDMILL_LEVEL
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11) },                             // NA_SE_EV_GOTO_HEAVEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_POT_BROKEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_PL_PUT_DOWN_POT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DIVE_INTO_WATER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_JUMP_OUT_WATER
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_GOD_FLYING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TRIFORCE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_AURORA
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DEKU_DEATH
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BUYOSTAND_RISING
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BUYOSTAND_FALL
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) },                             // NA_SE_EV_BUYOSHUTTER_OPEN
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) },                             // NA_SE_EV_BUYOSHUTTER_CLOSE
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_STONEDOOR_STOP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_S_STONE_REVIVAL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_MEDAL_APPEAR_S
    { 0x30, SFX_PARAMS(0, 2, 0) },                                       // NA_SE_EV_HUMAN_BOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_MEDAL_APPEAR_L
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_EARTHQUAKE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SHUT_BY_CRYSTAL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GOD_LIGHTBALL_2
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RUN_AROUND
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11) },                             // NA_SE_EV_CONSENTRATION
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_11) },                             // NA_SE_EV_TIMETRIP_LIGHT
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_BUYOSTAND_STOP_A
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BUYOSTAND_STOP_U
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_OBJECT_FALL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_JUMP_CONC
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ICE_MELT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FIRE_PILLAR_S
    { 0x20, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BLOCK_RISING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_NABALL_VANISH
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_15) },                             // NA_SE_EV_SARIA_MELODY
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LINK_WARP_OUT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FIATY_HEAL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_CHAIN_KEY_UNLOCK_B
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_WOODBOX_BREAK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_PUT_DOWN_WOODBOX
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LAND_DIRT
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FLOOR_ROLLING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DOG_CRY_EVENING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_JABJAB_HICCUP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_NALE_MAGIC
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FROG_JUMP
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_ICE_FREEZE
    { 0x60, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_BURNING
    { 0x30, SFX_PARAMS(0, 2, 0) },                                       // NA_SE_EV_WOODPLATE_BOUND
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_13) },                             // NA_SE_EV_GORON_WATER_DROP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_JABJAB_GROAN
    { 0x30, SFX_PARAMS(1, 0, 0) },                                       // NA_SE_EV_DARUMA_VANISH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BIGBALL_ROLL
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ELEVATOR_MOVE3
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_DIAMOND_SWITCH
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_FLAME_OF_FIRE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RAINBOW_SHOWER
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FLYING_AIR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_PASS_AIR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_COME_UP_DEKU_JR
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SAND_STORM
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TRIFORCE_MARK
    { 0xA0, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_GRAVE_EXPLOSION
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LURE_MOVE_W
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_POT_MOVE_START
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DIVE_INTO_WATER_L
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_OUT_OF_WATER_L
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_GANON_MANTLE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DIG_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WOOD_BOUND
    { 0x30, SFX_PARAMS(0, 3, 0) },                                       // NA_SE_EV_WATER_BUBBLE
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_ICE_BROKEN
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_FROG_GROW_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WATER_CONVECTION
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_GROUND_GATE_OPEN
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_FACE_BREAKDOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FACE_EXPLOSION
    { 0x30, SFX_PARAMS(3, 2, SFX_FLAG_14) },                             // NA_SE_EV_FACE_CRUMBLE_SLOW
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ROUND_TRAP_MOVE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_HIT_SOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ICE_SWING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_DOWN_TO_GROUND
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KENJA_ENVIROMENT_0
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KENJA_ENVIROMENT_1
    { 0x80, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_SMALL_DOG_BARK
    { 0x60, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ZELDA_POWER
    { 0x90, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RAIN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_IRON_DOOR_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_IRON_DOOR_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_WHIRLPOOL
    { 0x60, SFX_PARAMS(3, 3, 0) },                                       // NA_SE_EV_TOWER_PARTS_BROKEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_COW_CRY
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_METAL_BOX_BOUND
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_ELECTRIC_EXPLOSION
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_HEAVY_THROW
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FROG_CRY_0
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_FROG_CRY_1
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_COW_CRY_LV
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_RONRON_DOOR_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_BUTTERFRY_TO_FAIRY
    { 0xA0, SFX_PARAMS(0, 0, SFX_FLAG_11) },                             // NA_SE_EV_FIVE_COUNT_LUPY
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_STONE_GROW_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_STONE_LAUNCH
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_STONE_ROLLING
    { 0x30, SFX_PARAMS(2, 0, 0) },                                       // NA_SE_EV_TOGE_STICK_ROLLING
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_TOWER_ENERGY
    { 0x30, SFX_PARAMS(3, 0, 0) },                                       // NA_SE_EV_TOWER_BARRIER
    { 0x20, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_CHIBI_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_KNIGHT_WALK
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_PILLAR_MOVE_STOP
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_ERUPTION_CLOUD
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LINK_WARP_OUT_LV
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_LINK_WARP_IN
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_OCARINA_BMELO_0
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_OCARINA_BMELO_1
    { 0x30, SFX_PARAMS(0, 0, 0) },                                       // NA_SE_EV_EXPLOSION_FOR_RENZOKU
};

SoundParams sSystemBankParams[] = {
    { 0xC0, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WIN_OPEN
    { 0xC0, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WIN_CLOSE
    { 0xB0, SFX_PARAMS(0, 0, SFX_FLAG_5) }, // NA_SE_SY_CORRECT_CHIME
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GET_RUPY
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_MESSAGE_WOMAN
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_MESSAGE_MAN
    { 0x50, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_ERROR
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_5) }, // NA_SE_SY_TRE_BOX_APPEAR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DECIDE
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CURSOR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CANCEL
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_HP_RECOVER
    { 0x20, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_ATTENTION_ON
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_13
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_14
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_LOCK_OFF
    { 0x28, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_LOCK_ON_HUMAN
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_17
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_18
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CAMERA_ZOOM_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CAMERA_ZOOM_DOWN
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_21
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_22
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_ATTENTION_ON_OLD
    { 0x18, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_MESSAGE_PASS
    { 0x2C, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WARNING_COUNT_N
    { 0x2C, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WARNING_COUNT_E
    { 0x20, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_HITPOINT_ALARM
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_28
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DEMO_CUT
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_NAVY_CALL
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GAUGE_UP
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_32
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_33
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_34
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_PIECE_OF_HEART
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GET_ITEM
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WIN_SCROLL_LEFT
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WIN_SCROLL_RIGHT
    { 0x20, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_OCARINA_ERROR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CAMERA_ZOOM_UP_2
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CAMERA_ZOOM_DOWN_2
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GLASSMODE_ON
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GLASSMODE_OFF
    { 0x60, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_HIT_SOUND
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_MESSAGE_END
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_RUPY_COUNT
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_LOCK_ON
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_GET_BOXITEM
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WHITE_OUT_L
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WHITE_OUT_S
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_WHITE_OUT_T
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_START_SHOT
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_METRONOME
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_ATTENTION_URGENCY
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_METRONOME_LV
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FSEL_CURSOR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FSEL_DECIDE_S
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FSEL_DECIDE_L
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FSEL_CLOSE
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FSEL_ERROR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_SET_FIRE_ARROW
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_SET_ICE_ARROW
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_SET_LIGHT_ARROW
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_SYNTH_MAGIC_ARROW
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_METRONOME_2
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_KINSTA_MARK_APPEAR
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_FIVE_COUNT_LUPY
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_CARROT_RECOVER
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_EV_FAIVE_LUPY_COUNT
    { 0x30, SFX_PARAMS(0, 0, 0) },          // NA_SE_SY_DUMMY_71
};

SoundParams sOcarinaBankParams[] = {
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_OCARINA
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_5) },               // NA_SE_OC_ABYSS
    { 0x30, SFX_PARAMS(2, 1, SFX_FLAG_10 | SFX_FLAG_9) }, // NA_SE_OC_DOOR_OPEN
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_SECRET_WARP_IN
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_SECRET_WARP_OUT
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_SECRET_HOLE_OUT
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_REVENGE
    { 0x30, SFX_PARAMS(0, 0, 0) },                        // NA_SE_OC_HINT_MOVIE
};

SoundParams sVoiceBankParams[] = {
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWORD_N
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWORD_L
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_LASH
    { 0x20, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HANG
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_CLIMB_END
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DAMAGE_S
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FREEZE
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FALL_S
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FALL_L
    { 0x30, SFX_PARAMS(2, 1, SFX_FLAG_10) }, // NA_SE_VO_LI_BREATH_REST
    { 0x30, SFX_PARAMS(2, 1, SFX_FLAG_10) }, // NA_SE_VO_LI_BREATH_DRINK
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DOWN
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_TAKEN_AWAY
    { 0x50, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HELD
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SNEEZE
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWEAT
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DRINK
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_RELAX
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWORD_PUTAWAY
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_GROAN
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_AUTO_JUMP
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_NALE
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SURPRISE
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_FROL
    { 0x30, SFX_PARAMS(2, 2, SFX_FLAG_10) }, // NA_SE_VO_LI_PUSH
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HOOKSHOT_HANG
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_LAND_DAMAGE_S
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_NULL_0x1b
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_ATTACK
    { 0x80, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_BL_DOWN
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DEMO_DAMAGE
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_ELECTRIC_SHOCK_LV
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWORD_N_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_ROLLING_CUT_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_LASH_KID
    { 0x20, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HANG_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_CLIMB_END_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DAMAGE_S_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FREEZE_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FALL_S_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_FALL_L_KID
    { 0x30, SFX_PARAMS(2, 1, SFX_FLAG_10) }, // NA_SE_VO_LI_BREATH_REST_KID
    { 0x30, SFX_PARAMS(2, 1, SFX_FLAG_10) }, // NA_SE_VO_LI_BREATH_DRINK_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DOWN_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_TAKEN_AWAY_KID
    { 0x50, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HELD_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SNEEZE_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWEAT_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DRINK_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_RELAX_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SWORD_PUTAWAY_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_GROAN_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_AUTO_JUMP_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_NALE_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_SURPRISE_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_FROL_KID
    { 0x30, SFX_PARAMS(1, 2, SFX_FLAG_10) }, // NA_SE_VO_LI_PUSH_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_HOOKSHOT_HANG_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_LAND_DAMAGE_S_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_NULL_0x1b_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_MAGIC_ATTACK_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_BL_DOWN_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_DEMO_DAMAGE_KID
    { 0x30, SFX_PARAMS(2, 0, SFX_FLAG_10) }, // NA_SE_VO_LI_ELECTRIC_SHOCK_LV_KID
    { 0x60, SFX_PARAMS(0, 0, SFX_FLAG_5) },  // NA_SE_VO_NAVY_ENEMY
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_5) },  // NA_SE_VO_NAVY_HELLO
    { 0x30, SFX_PARAMS(0, 0, SFX_FLAG_5) },  // NA_SE_VO_NAVY_HEAR
    { 0x60, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_NAVY_CALL
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_NA_HELLO_3
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x45
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x46
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x47
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x48
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x49
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4a
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4b
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4c
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4d
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4e
    { 0x30, SFX_PARAMS(0, 0, 0) },           // NA_SE_VO_DUMMY_0x4f
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_TA_SLEEP
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_TA_SURPRISE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_TA_CRY_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_TA_CRY_1
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_IN_CRY_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_IN_LOST
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_IN_LASH_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_IN_LASH_1
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_FR_LAUGH_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_FR_SMILE_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NB_AGONY
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NB_CRY_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NB_NOTICE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NA_HELLO_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NA_HELLO_1
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NA_HELLO_2
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_CRASH
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_DISCOVER
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_FALL
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_LAUGH_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_LIFT
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_THROW
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_RT_UNBALLANCE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_ST_DAMAGE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_ST_ATTACK
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_HURRY
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_MEET
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_QUESTION
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_SIGH_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_SMILE_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_SURPRISE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z0_THROW
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_SK_CRY_0
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_SK_CRY_1
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_SK_CRASH
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_SK_LAUGH
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_SK_SHOUT
    { 0x30, SFX_PARAMS(3, 1, SFX_FLAG_15) }, // NA_SE_VO_Z1_CRY_0
    { 0x30, SFX_PARAMS(3, 1, SFX_FLAG_15) }, // NA_SE_VO_Z1_CRY_1
    { 0x30, SFX_PARAMS(3, 1, SFX_FLAG_15) }, // NA_SE_VO_Z1_OPENDOOR
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z1_SURPRISE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_Z1_PAIN
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_KZ_MOVE
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_NB_LAUGH
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_IN_LAUGH
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_DUMMY_0x7d
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_DUMMY_0x7e
    { 0x30, SFX_PARAMS(1, 1, SFX_FLAG_15) }, // NA_SE_VO_DUMMY_0x7f
};

SoundParams* gSoundParams[7] = {
    sPlayerBankParams, sItemBankParams,    sEnvBankParams,   sEnemyBankParams,
    sSystemBankParams, sOcarinaBankParams, sVoiceBankParams,
};
