#ifndef OBJECT_SPOT18_OBJ_H
#define OBJECT_SPOT18_OBJ_H 1

extern Vtx object_spot18_objVtx_000000[];
extern Gfx gGoronCityVaseLidDL[];
extern CamData gGoronCityVaseLidColCamDataList[];
extern SurfaceType gGoronCityVaseLidColSurfaceType[];
extern CollisionPoly gGoronCityVaseLidColPolygons[];
extern Vec3s gGoronCityVaseLidColVertices[];
extern CollisionHeader gGoronCityVaseLidCol;
extern Vtx object_spot18_objVtx_0003A0[];
extern Gfx gGoronCityDoorDL[];
extern CamData gGoronCityDoorColCamDataList[];
extern SurfaceType gGoronCityDoorColSurfaceType[];
extern CollisionPoly gGoronCityDoorColPolygons[];
extern Vec3s gGoronCityDoorColVertices[];
extern CollisionHeader gGoronCityDoorCol;
extern u64 gGoronCityVaseTLUT[];
extern u64 gGoronCityVaseTex_580[];
extern u64 gGoronCityVaseTex_D80[];
extern Vtx object_spot18_objVtx_000F80[];
extern Gfx gGoronCityVaseDL[];
extern CamData gGoronCityVaseColCamDataList[];
extern SurfaceType gGoronCityVaseColSurfaceType[];
extern CollisionPoly gGoronCityVaseColPolygons[];
extern Vec3s gGoronCityVaseColVertices[];
extern CollisionHeader gGoronCityVaseCol;
extern Vtx object_spot18_objVtx_002180[];
extern Gfx gGoronCityStatueSpearDL[];
extern CamData gGoronCityStatueSpearColCamDataList[];
extern SurfaceType gGoronCityStatueSpearColSurfaceType[];
extern CollisionPoly gGoronCityStatueSpearColPolygons[];
extern Vec3s gGoronCityStatueSpearColVertices[];
extern CollisionHeader gGoronCityStatueSpearCol;
extern Vtx object_spot18_objVtx_002650[];
extern Gfx gGoronCityStatueDL[];
extern CamData gGoronCityStatueColCamDataList[];
extern SurfaceType gGoronCityStatueColSurfaceType[];
extern CollisionPoly gGoronCityStatueColPolygons[];
extern Vec3s gGoronCityStatueColVertices[];
extern CollisionHeader gGoronCityStatueCol;
extern u64 gGoronCitySpearLeafTex[];
extern u64 gGoronCitySpearTipTex[];
extern u64 gGoronCitySpearHandleTex[];
extern u64 gGoronCityStatuePattern1Tex[];
extern u64 gGoronCityStatuePattern2Tex[];
extern u64 gGoronCityStatueTex_7010[];
extern u64 gGoronCityStatueAngryFaceTex[];
extern u64 gGoronCityStatueNeutralFaceTex[];
extern u64 gGoronCityStatueHappyFaceTex[];
extern u64 gGoronCityVaseLidTex[];
extern u64 gGoronCityVaseLidHandleTex[];
extern u64 gGoronCityDoorTex[];

#endif
