.table table_enemy
entry enemy_dodongo_walk
entry enemy_dodongo_breathe
entry enemy_dodongo_flame
entry enemy_dodongo_hurt
entry enemy_dodongo_die
entry enemy_boss_dodongo_exhale
entry enemy_boss_dodongo_hurt
entry enemy_boss_dodongo_die
entry enemy_boss_dodongo_walk
entry enemy_boss_dodongo_flame
entry enemy_boss_gohma_walk
entry enemy_boss_gohma_walk_ceiling
entry enemy_boss_gohma_climb
entry enemy_boss_gohma_fall
entry enemy_boss_gohma_roar
entry enemy_boss_gohma_growl
entry enemy_boss_gohma_hurt
entry enemy_boss_gohma_hurt_eye
entry enemy_boss_gohma_die
entry enemy_boss_gohma_birth
entry enemy_larvae_egg_land
entry enemy_larvae_egg_break
entry enemy_larvae_walk
entry enemy_larvae_chirp
entry enemy_larvae_hurt
entry enemy_larvae_cry
entry enemy_larvae_die
entry enemy_boss_gohma_eyeroll
entry enemy_boss_gohma_dissolve
entry enemy_boss_gohma_thrust
entry enemy_boss_gohma_paralyzed
entry enemy_larvae_paralyzed
entry enemy_dodongo_jr_yell
entry enemy_dodongo_jr_die
entry enemy_dodongo_jr_walk
entry enemy_dodongo_jr_burrow
entry enemy_dodongo_jr_emerge
entry enemy_ganondorf_throw_orb
entry enemy_dodongo_jr_eat
entry enemy_ganondorf_hit_light
entry enemy_lizalfos_land
entry enemy_lizalfos_cry
entry enemy_lizalfos_attack_shout
entry enemy_lizalfos_hurt
entry enemy_lizalfos_laugh
entry enemy_lizalfos_die
entry enemy_lizalfos_walk
entry enemy_lizalfos_jump
entry enemy_stalkid_walk
entry enemy_stalkid_attack
entry enemy_stalkid_hurt
entry enemy_stalkid_die
entry enemy_floormaster_slide
entry enemy_tektite_turn_water
entry enemy_destroyed_light_arrow
entry enemy_pot_fly
entry enemy_stalfos_laugh
entry enemy_stalfos_attack
entry enemy_stalfos_hurt
entry enemy_stalfos_die
entry enemy_wolfos_spawn
entry enemy_stalfos_walk
entry enemy_wolfos_howl
entry enemy_wolfos_attack
entry enemy_keese_attack
entry enemy_keese_fly
entry enemy_keese_die
entry enemy_wolfos_hurt
entry enemy_armos_hop
entry enemy_armos_awaken
entry enemy_armos_die
entry enemy_armos_hurt
entry enemy_armos_roar
entry enemy_shell_open
entry enemy_shell_die
entry enemy_wolfos_die
entry enemy_boss_dodongo_demo_wall
entry enemy_boss_dodongo_wall_hit
entry enemy_boss_dodongo_roll
entry enemy_boss_dodongo_inhale
entry enemy_boss_dodongo_swallow
entry enemy_boss_dodongo_paralyzed
entry enemy_boss_dodongo_roar
entry enemy_boss_dodongo_dying_groan
entry enemy_boss_dodongo_fossilize
entry enemy_boss_dodongo_lava
entry enemy_ganondorf_fly
entry enemy_ganondorf_vortex_charge
entry enemy_dodongo_inhale
entry enemy_dodongo_swipe
entry enemy_wolfos_walk
entry enemy_dodongo_jr_eat
entry enemy_big_baba_chomp
entry enemy_big_baba_attack
entry enemy_big_baba_hurt
entry enemy_big_baba_die
entry enemy_deku_baba_chomp
entry enemy_deku_baba_attack
entry enemy_deku_baba_die
entry enemy_deku_baba_slide
entry enemy_tailpasaran_fly
entry enemy_tailpasaran_cry
entry enemy_tailpasaran_die
entry enemy_ganondorf_charge
entry enemy_skulltula_drop
entry enemy_skulltula_climb
entry enemy_skulltula_quiver
entry enemy_skulltula_hurt
entry enemy_stalfos_jump
entry enemy_tektite_hurt
entry enemy_tektite_die
entry enemy_tektite_turn_ground
entry enemy_poe_attack_charge
entry enemy_poe_float
entry enemy_poe_retreat
entry enemy_poe_appear
entry enemy_poe_vanish
entry enemy_poe_hurt
entry enemy_poe_die
entry enemy_poe_transform
entry enemy_dissolve
entry enemy_goron_land
entry enemy_lizalfos_land_flat
entry enemy_dodongo_jr_land
entry enemy_scrub_emerge
entry enemy_scrub_burrow
entry enemy_scrub_spit
entry enemy_scrub_walk
entry enemy_scrub_hurt
entry enemy_scrub_die
entry enemy_shop_scrub_cry
entry enemy_big_poe_get_soul
entry enemy_skulltula_pivot
entry enemy_skullwall_die
entry enemy_poe_sister_die
entry enemy_bari_split
entry enemy_tektite_flip
entry enemy_boss_gohma_fall
entry enemy_tektite_land_water1
entry enemy_final_hit
entry enemy_skullwall_rotate
entry enemy_skullwall_dash
entry enemy_tektite_jump_water
entry enemy_tektite_land_water2
entry enemy_wallmaster_fall
entry enemy_wallmaster_retreat
entry enemy_wallmaster_grab
entry enemy_larvae_egg_land
entry enemy_floormaster_walk
entry enemy_floormaster_hurt
entry enemy_floormaster_die
entry enemy_guay_fly
entry enemy_biri_float
entry enemy_biri_fly
entry enemy_biri_shock
entry enemy_biri_die
entry enemy_biri_die_bubbles
entry enemy_bari_spin
entry enemy_larvae_paralyzed
entry enemy_bari_die
entry enemy_ganondorf_orb_trail
entry enemy_phantom_reveal
entry enemy_phantom_lightning
entry enemy_ganondorf_charge
entry enemy_ganondorf_fly
entry enemy_witch_charge
entry enemy_phantom_painting_enter
entry enemy_ganondorf_orb_trail
entry enemy_ganondorf_lightning_hit
entry enemy_phantom_attack_unused
entry enemy_phantom_staff
entry enemy_phantom_eyes
entry enemy_phantom_die_roar
entry enemy_phantom_orb_dissipate
entry enemy_phantom_hurt
entry enemy_phantom_die
entry enemy_phantom_laugh
entry enemy_phantom_hurt_orb
entry enemy_phantom_shout
entry enemy_guay_hurt
entry enemy_ganondorf_charge_major
entry enemy_ganondorf_magic_fire
entry enemy_guay_chirp
entry enemy_guay_attack
entry enemy_moblin_walk
entry enemy_moblin_slide
entry enemy_moblin_attack_shout
entry enemy_moblin_grunt
entry enemy_moblin_spear_point
entry enemy_moblin_spear_relax
entry enemy_moblin_die
entry enemy_moblin_dash
entry enemy_octorok_rock_break
entry enemy_octorok_float
entry enemy_octorok_jump
entry enemy_tektite_land_water1
entry enemy_octorok_dive
entry enemy_octorok_bubble
entry enemy_octorok_die
entry enemy_octorok_death_gasp
entry enemy_keese_fly
entry enemy_bubble_dash
entry enemy_bubble_cry
entry enemy_bubble_attack
entry enemy_bubble_flame_appear
entry enemy_bubble_flame_vanish
entry enemy_bubble_die
entry enemy_dodongo_flame
entry enemy_boss_volvagia_hole
entry enemy_boss_volvagia_roar
entry enemy_boss_gohma_hurt_eye
entry enemy_volvagia_fall
entry enemy_volvagia_paralyzed
entry enemy_boss_gohma_hurt
entry enemy_boss_volvagia_cry
entry enemy_boss_volvagia_rock
entry enemy_boss_volvagia_swipe
entry enemy_boss_gohma_die
entry enemy_boss_dodongo_fossilize
entry enemy_boss_dodongo_flame
entry enemy_biri_die
entry enemy_dodongo_jr_land
entry enemy_boss_morpha_water_move
entry enemy_tektite_turn_water
entry enemy_moblin_club_shockwave
entry enemy_moblin_club_strike
entry enemy_moblin_club_lift
entry enemy_bubble_hurt
entry enemy_redead_moan
entry enemy_redead_scream
entry enemy_redead_hurt
entry enemy_redead_die
entry enemy_redead_attack
entry enemy_spike_trap_roll
entry enemy_spike_trap_rock
entry enemy_guay_die
entry enemy_poe_laugh
entry enemy_poe_sister_cry
entry enemy_poe_sister_attack
entry enemy_poe_sister_laugh
entry enemy_boss_morpha_rise
entry enemy_boss_morpha_attack
entry enemy_boss_morpha_toss
entry enemy_boss_morpha_grab
entry enemy_boss_morpha_caught
entry enemy_boss_morpha_demo_move
entry enemy_boss_morpha_demo_bubble
entry enemy_tektite_jump_water
entry enemy_boss_morpha_die
entry enemy_boss_morpha_die_cry
entry enemy_boss_morpha_water_spin
entry enemy_witch_charge
entry enemy_goron_wake
entry enemy_goron_sit
entry enemy_unused
entry enemy_cucco_flap
entry enemy_deadhand_bite
entry enemy_deadhand_move
entry enemy_deadhand_grabbed
entry enemy_deadhand_grab
entry enemy_big_octo_paralyzed
entry enemy_big_octo_walk
entry enemy_big_octo_grunt
entry enemy_big_octo_hurt
entry enemy_big_octo_stop
entry enemy_big_octo_die
entry enemy_big_octo_die2
entry enemy_phantom_lightning
entry enemy_boss_twinrova_appear
entry enemy_boss_twinrova_transform
entry enemy_boss_twinrova_fire_charge
entry enemy_boss_twinrova_fire_hit
entry enemy_boss_twinrova_charge
entry enemy_boss_twinrova_ice_beam
entry enemy_boss_twinrova_ice_charge
entry enemy_boss_twinrova_cast
entry enemy_boss_ganondorf_struck
entry enemy_boss_dodongo_demo_wall
entry enemy_boss_twinrova_hurt_cry_old
entry enemy_boss_twinrova_ice_reflected
entry enemy_boss_twinrova_fire_reflected
entry enemy_boss_ganondorf_struck
entry enemy_boss_twinrova_hit_beam_young
entry enemy_boss_twinrova_die_young
entry enemy_biggoron_blind
entry enemy_biggoron_happy
entry enemy_boss_twinrova_spirit_fly
entry enemy_boss_twinrova_fly
entry enemy_boss_twinrova_hover
entry enemy_poe_sister_attack
entry enemy_ganondorf_orb_trail
entry enemy_phantom_painting_enter
entry enemy_darunia_chest_pound
entry enemy_darunia_head_pat
entry enemy_owl_fly
entry enemy_goron_land
entry enemy_knuckle_walk
entry enemy_knuckle_attack
entry enemy_knuckle_clank
entry enemy_knuckle_stagger
entry enemy_knucle_armor_loss
entry enemy_knuckle_armor_rebound1
entry enemy_knuckle_armor_rebound2
entry enemy_knuckle_armor_rebound3
entry enemy_floormaster_attack
entry enemy_floormaster_mini_walk
entry enemy_floormaster_mini_die
entry enemy_floormaster_mini_grow
entry enemy_floormaster_grow_done
entry enemy_floormaster_split
entry enemy_floormaster_mini_grab
entry enemy_floormaster_mini_land
entry enemy_knuckle_warcry
entry enemy_knuckle_snap
entry enemy_knuckle_armor_hurt
entry enemy_boss_ganondorf_struck
entry enemy_boss_barinade_pulse
entry enemy_boss_barinade_hurt
entry enemy_boss_barinade_weak_hurt
entry enemy_boss_barinade_die
entry enemy_boss_twinrova_hurt
entry enemy_boss_barinade_bari_attach
entry enemy_boss_barinade_beam
entry enemy_biri_shock
entry enemy_biri_die
entry enemy_boss_barinade_tentacle_break
entry enemy_ganondorf_lightning_hit
entry enemy_boss_dodongo_roll
entry enemy_shabom_bounce
entry enemy_shabom_pop
entry enemy_blob_wave
entry enemy_octorok_rock_break
entry enemy_stinger_hurt
entry enemy_stinger_die
entry enemy_stinger_submerge
entry enemy_stinger_glide
entry enemy_boss_bongo_drum_low
entry enemy_boss_bongo_drum_high
entry enemy_boss_bongo_clap
entry enemy_deadhand_grab
entry enemy_peahat_rise
entry enemy_peahat_fly
entry enemy_peahat_hurt
entry enemy_peahat_land
entry enemy_deadhand_grab
entry enemy_tentacle_wind_up
entry enemy_peahat_hurt
entry enemy_tentacle_die
entry enemy_larvae_walk
entry enemy_larvae_chirp
entry enemy_larvae_hurt
entry enemy_larvae_cry
entry enemy_larvae_die
entry enemy_larvae_egg_land
entry enemy_larvae_egg_break
entry enemy_boss_ganon_transform
entry enemy_boss_bongo_hand_wave
entry enemy_wallmaster_grab
entry enemy_goron_land
entry enemy_boss_bongo_hand_attack
entry enemy_boss_bongo_hand_shake
entry enemy_boss_bongo_hurt
entry enemy_boss_bongo_hand_hurt
entry enemy_boss_bongo_vanish
entry enemy_ganondorf_charge_major
entry enemy_boss_barinade_beam
entry enemy_boss_bongo_paralyze
entry enemy_boss_bongo_die
entry enemy_beamos_idle
entry enemy_beamos_beam
entry enemy_beamos_ground_hit
entry enemy_beamos_charging
entry enemy_torch_slug_crawl
entry enemy_torch_slug_target
entry enemy_tektite_flip
entry enemy_torch_slug_hurt
entry enemy_torch_slug_die
entry enemy_tile_fly
entry enemy_firedancer_hurt
entry enemy_boss_twinrova_fly
entry enemy_firedancer_kick
entry enemy_moblin_club_shockwave
entry enemy_firedancer_spin
entry enemy_firehead_run
entry enemy_firehead_hurt
entry enemy_firedancer_laugh
entry enemy_deku_baba_slide
entry enemy_boss_volvagia_hole
entry enemy_peahat_jr_fly
entry enemy_keese_die
entry enemy_leever_emerge
entry enemy_shop_scrub_burrow
entry enemy_boss_gohma_hurt
entry enemy_leever_die
entry enemy_blob_wave
entry enemy_firehead_cry
entry enemy_boss_bongo_dissipate
entry enemy_boss_bongo_charge
entry enemy_boss_bongo_chant
entry enemy_boss_ganon_roar
entry enemy_torch_slug_crawl
entry enemy_boss_morpha_grab
entry enemy_boss_dodongo_swallow
entry enemy_boss_gohma_eyeroll
entry enemy_scrub_spit
entry enemy_boss_gohma_hurt
entry enemy_like_like_die
entry enemy_boss_ganon_attack
entry enemy_gerudo_attack
entry enemy_gerudo_hurt
entry enemy_gerudo_defeat
entry enemy_boss_ganon_hurt
entry enemy_dodongo_flame
entry enemy_anubis_fire_hit
entry enemy_boss_ganon_penultimate_hit
entry enemy_anubis_die
entry enemy_wolfos_walk
entry enemy_boss_ganon_die
entry enemy_stinger_attack
entry enemy_stinger_cry
entry enemy_boss_twinrova_ice_beam
entry enemy_freezard_hurt
entry enemy_freezard_die
entry enemy_deadhand_laugh
entry enemy_deadhand_burrow
entry enemy_deadhand_hurt
entry enemy_big_baba_die
entry enemy_deadhand_die
entry enemy_knuckle_stump_break
entry enemy_knuckle_pillar_break
entry enemy_knuckle_axe_stuck
entry enemy_boss_ganon_paralyze
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_boss_vocals
entry enemy_goron_land
entry enemy_deadhand_burrow
entry enemy_boss_ganon_growl
entry enemy_gold_skull_spin
entry enemy_blob_wave
entry enemy_armos_hop
entry enemy_knuckle_stump_break
entry enemy_armos_hop
entry enemy_boss_ganon_sword_clank
entry enemy_deadhand_grab
entry enemy_skulltula_creak
entry enemy_floormaster_grow_done
entry enemy_dodongo_jr_land
entry enemy_stalfos_walk
entry enemy_dodongo_jr_land
entry enemy_stalfos_walk
entry enemy_boss_twinrova_bicker
entry enemy_big_poe_caught_soul
entry enemy_bug_burrow
entry enemy_gold_skull_cry
entry enemy_goron_child_cry
entry enemy_boss_gohma_hurt
entry enemy_tektite_land_water1
entry enemy_deadhand_burrow
entry enemy_goron_land
entry enemy_bug_walk
entry enemy_boss_twinrova_ice_beam
entry enemy_skulltula_quiver

.channel enemy_dodongo_walk
instr FONT01_INSTR_GUNSHOT
envelope envelope_68DC
ldlayer 0, layer_354D
end

.layer layer_354D
portamento 0x81, 34, 80
notedv PITCH_C3, 0x1E, 100
end

.channel enemy_dodongo_breathe
ldlayer 0, layer_3559
end

.layer layer_3559
instr FONT01_INSTR_DODONGO_ROAR
notedv PITCH_D4, 0x50, 100
end

.channel enemy_dodongo_flame
instr 2
ldlayer 0, layer_3565
end

.layer layer_3565
notedv PITCH_F2, 30000, 100
rjump layer_3565

.channel enemy_dodongo_hurt
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_3574
ldlayer 1, layer_4829
end

.layer layer_3574
portamento 0x81, 36, 255
notedv PITCH_E4, 0xA, 100
portamento 0x81, 44, 255
notedv PITCH_B3, 0x24, 100
end

.channel enemy_dodongo_die
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_358F
ldlayer 1, layer_3591
ldlayer 2, layer_4829
end

.layer layer_358F
transpose -6

.layer layer_3591
portamento 0x81, 38, 255
notedv PITCH_GF4, 0xA, 100
portamento 0x81, 46, 255
notedv PITCH_DF4, 0x5A, 100
end

.channel enemy_boss_dodongo_exhale
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_683C
ldlayer 0, layer_35AC
ldlayer 1, layer_35AE
end

.layer layer_35AC
transpose -12

.layer layer_35AE
portamento 1, 34, 20
notedv PITCH_B3, 0x5A, 100
end

.channel enemy_boss_dodongo_walk
instr FONT01_INSTR_GUNSHOT
ldlayer 0, layer_35CA
ldlayer 1, layer_35C6
ldlayer 2, layer_35C2
end

.layer layer_35C2
notedv PITCH_B3, 0x50, 100
end

.layer layer_35C6
notedv PITCH_D3, 0x50, 100
end

.layer layer_35CA
notedv PITCH_F2, 0x50, 100
end

.channel enemy_boss_dodongo_flame
instr 2
ldlayer 0, layer_35D9
ldlayer 1, layer_35D7
end

.layer layer_35D7
transpose -12

.layer layer_35D9
notedv PITCH_G3, 30000, 100
rjump layer_35D9

.channel enemy_larvae_egg_break
instr FONT01_INSTR_EGG_CRACK
ldlayer 0, layer_35E5
end

.layer layer_35E5
notedv PITCH_F3, 0x50, 100
end

.channel enemy_boss_gohma_fall
instr FONT01_INSTR_SMASH
ldlayer 0, layer_35F5
ldlayer 1, layer_35F7
ldlayer 2, layer_3606
end

.layer layer_35F5
transpose -8

.layer layer_35F7
envelope envelope_69DC, 240
portamento 0x81, 34, 64
notedv PITCH_C3, 0x32, 100
notedv PITCH_C1, 0x5A, 100
end

.layer layer_3606
envelope envelope_69DC, 240
portamento 0x81, 38, 64
notedv PITCH_E3, 0x32, 100
end

.channel enemy_goron_land
instr FONT01_INSTR_SMASH
ldlayer 0, layer_361B
ldlayer 1, layer_361D
end

.layer layer_361B
transpose -8

.layer layer_361D
envelope envelope_69DC, 250
portamento 0x81, 34, 64
notedv PITCH_C3, 0x62, 100
end

.channel enemy_lizalfos_land_flat
instr FONT01_INSTR_SMASH
ldlayer 0, layer_3631
gain 18
end

.layer layer_3631
envelope envelope_690C, 250
portamento 0x81, 29, 150
notedv PITCH_C3, 0x8, 100
envelope envelope_68EC, 250
portamento 0x81, 27, 150
notedv PITCH_F2, 0x1E, 100
end

.channel enemy_dodongo_jr_land
ldlayer 0, layer_364C
end

.layer layer_364C
instr FONT01_INSTR_SMASH
envelope envelope_68DC, 250
portamento 0x81, 36, 64
notedv PITCH_D3, 0x1E, 100
end

.channel enemy_boss_gohma_walk
instr FONT01_INSTR_SMASH
envelope envelope_68EC
ldlayer 0, layer_3665
gain 16
end

.layer layer_3665
portamento 0x81, 37, 64
notedv PITCH_EF3, 0x28, 100
end

.channel enemy_boss_gohma_climb
instr FONT01_INSTR_TEKTITE_ROTATE
ldlayer 1, layer_3676
ldlayer 0, layer_3678
end

.layer layer_3676
transpose 1

.layer layer_3678
portamento 0x81, 19, 64
notedv PITCH_G2, 0x14, 100
end

.channel enemy_boss_gohma_birth
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_698C
ldlayer 0, layer_368B
gain 18
end

.layer layer_368B
legato
portamento 0x85, 20, 255
notedv PITCH_GF2, 0x28, 100
notedv PITCH_F2, 0x55, 100
end

.channel enemy_larvae_walk
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_369D
end

.layer layer_369D
portamento 0x81, 31, 255
notedv PITCH_C3, 0x5, 100
end

.channel enemy_larvae_chirp
instr FONT01_INSTR_MECH
ldlayer 0, layer_36AB
end

.layer layer_36AB
portamento 0x81, 48, 255
notedv PITCH_GF4, 0x1E, 100
end

.channel enemy_larvae_hurt
ldlayer 0, layer_4829
ldlayer 1, layer_36BD
ldlayer 2, layer_36C1
end

.layer layer_36BD
instr FONT01_INSTR_MECH
rjump layer_36C3

.layer layer_36C1
instr FONT01_INSTR_MONSTER_ROAR
.layer layer_36C3
portamento 0x81, 51, 255
notedv PITCH_B5, 0xA, 100
portamento 0x81, 60, 255
notedv PITCH_E5, 0x12, 100
end

.channel enemy_larvae_cry
ldlayer 0, layer_36D6
end

.layer layer_36D6
instr FONT01_INSTR_MECH
portamento 0x81, 51, 255
notedv PITCH_F5, 0xA, 100
portamento 0x81, 53, 255
notedv PITCH_G5, 0xA, 100
transpose 4
portamento 0x81, 55, 255
notedv PITCH_B5, 0xA, 100
transpose 6
portamento 0x81, 51, 255
notedv PITCH_B5, 0x14, 100
end

.channel enemy_larvae_die
ldlayer 0, layer_3700
ldlayer 1, layer_4829
end

.layer layer_3700
instr FONT01_INSTR_MECH
portamento 0x81, 56, 255
notedv PITCH_C5, 0x5, 100
portamento 0x81, 54, 255
notedv PITCH_BF4, 0xA, 100
portamento 0x81, 51, 255
notedv PITCH_AF4, 0xA, 100
portamento 0x81, 47, 255
notedv PITCH_DF4, 0x14, 100
end

.channel enemy_boss_gohma_walk_ceiling
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3728
ldlayer 1, layer_372C
end

.layer layer_3728
notedv PITCH_E3, 0x50, 100
end

.layer layer_372C
ldelay 0xF
notedv PITCH_C4, 0x50, 100
end

.channel enemy_boss_gohma_hurt_eye
ldlayer 0, layer_374D
ldlayer 1, layer_3739
end

.layer layer_3739
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 39, 255
notedv PITCH_G4, 0x14, 80
notedv PITCH_C4, 0x14, 80
notedv PITCH_E4, 0x14, 80
notedv PITCH_A3, 0x14, 80
end

.layer layer_374D
instr FONT01_INSTR_MONSTER_ROAR
legato
portamento 0x85, 39, 255
notedv PITCH_G4, 0xA, 100
notedv PITCH_C4, 0xA, 100
notedv PITCH_G4, 0xA, 100
notedv PITCH_C4, 0xA, 100
notedv PITCH_G4, 0xA, 100
notedv PITCH_C4, 0x5, 100
end

.channel enemy_larvae_egg_land
instr FONT01_INSTR_SMASH
ldlayer 0, layer_376F
gain 18
end

.layer layer_376F
legato
envelope envelope_68FC, 255
portamento 0x85, 25, 230
notedv PITCH_EF3, 0x5, 100
notedv PITCH_BF2, 0x5, 100
nolegato
ldelay 0x5
legato
envelope envelope_68FC, 255
portamento 0x85, 25, 220
notedv PITCH_EF3, 0x5, 100
notedv PITCH_BF2, 0xA, 100
end

.channel chan_unused_3791
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_3797
end

.layer layer_3797
notedv PITCH_D4, 0x46, 100
end

.channel enemy_keese_attack
instr FONT01_INSTR_KEESE
ldlayer 0, layer_37A3
gain 50
end

.layer layer_37A3
portamento 0x81, 37, 100
notedv PITCH_EF4, 0x32, 100
end

.channel enemy_keese_fly
ldlayer 0, layer_37AF
end

.layer layer_37AF
instr FONT01_INSTR_OWL_FLAP
portamento 0x81, 36, 255
notedv PITCH_E4, 0xA, 100
portamento 0x81, 42, 255
notedv PITCH_DF4, 0x6, 100
end

.channel enemy_dodongo_jr_yell
ldlayer 0, layer_37C7
ldlayer 1, layer_37D3
end

.layer layer_37C7
instr FONT01_INSTR_DODONGO_ROAR
ldelay 0xA
portamento 0x81, 48, 64
notedv PITCH_D5, 0x28, 100
end

.layer layer_37D3
instr FONT01_INSTR_GUNSHOT
envelope envelope_686C, 240
transpose 6
portamento 0x81, 26, 100
notedv PITCH_B5, 0x32, 100
end

.channel enemy_dodongo_jr_die
ldlayer 0, layer_37EA
ldlayer 1, layer_4829
end

.layer layer_37EA
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x81, 48, 255
notedv PITCH_D5, 0xA, 100
portamento 0x81, 55, 255
notedv PITCH_F4, 0x48, 100
end

.channel enemy_boss_gohma_roar
ldlayer 0, layer_3809
ldlayer 1, layer_3802
end

.layer layer_3802
instr FONT01_INSTR_MONSTER_ROAR
notedv PITCH_E4, 0x96, 70
end

.layer layer_3809
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 39, 255
notedv PITCH_D4, 0xA, 100
portamento 0x81, 41, 255
notedv PITCH_F4, 0xC8, 100
end

.channel enemy_boss_gohma_hurt
ldlayer 0, layer_3838
ldlayer 1, layer_3826
ldlayer 2, layer_4829
end

.layer layer_3826
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 42, 64
notedv PITCH_BF4, 0x14, 80
portamento 0x81, 47, 255
notedv PITCH_AF3, 0x24, 80
end

.layer layer_3838
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x81, 39, 255
notedv PITCH_G4, 0xF, 100
portamento 0x81, 44, 255
notedv PITCH_B3, 0x24, 100
end

.channel enemy_boss_gohma_growl
instr FONT01_INSTR_EGG_CRACK
ldlayer 0, layer_3854
ldlayer 1, layer_3852
end

.layer layer_3852
transpose 2

.layer layer_3854
notedv PITCH_C2, 0x64, 100
end

.channel enemy_dodongo_jr_walk
ldlayer 0, layer_385C
end

.layer layer_385C
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_D2, 0x1E, 70
end

.channel enemy_dodongo_jr_burrow
ldlayer 0, layer_3866
end

.layer layer_3866
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_BF2, 0x19, 100
notedv PITCH_AF2, 0x14, 100
notedv PITCH_BF2, 0xF, 100
notedv PITCH_AF2, 0xF, 100
notedv PITCH_BF2, 0xA, 100
notedv PITCH_AF2, 0xF, 100
notedv PITCH_BF2, 0xF, 70
.layer layer_387D
notedv PITCH_AF2, 0xF, 70
notedv PITCH_BF2, 0xF, 70
notedv PITCH_AF2, 0xF, 70
notedv PITCH_BF2, 0xA, 60
notedv PITCH_AF2, 0xA, 60
end

.channel enemy_bug_burrow
ldlayer 0, layer_3891
end

.layer layer_3891
instr FONT01_INSTR_TEKTITE_ROTATE
rjump layer_387D

.channel enemy_bug_walk
ldlayer 0, layer_3899
end

.layer layer_3899
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_AF2, 0x8, 40
notedv PITCH_G2, 0x8, 40
end

.channel enemy_dodongo_jr_emerge
ldlayer 0, layer_38A6
end

.layer layer_38A6
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_GF2, 0x19, 100
notedv PITCH_AF2, 0x14, 100
end

.channel enemy_shop_scrub_burrow
ldlayer 0, layer_38B6
ldlayer 1, layer_3866
end

.layer layer_38B6
transpose -5
rjump layer_3866

.channel enemy_leever_emerge
ldlayer 0, layer_38C1
ldlayer 1, layer_38A6
end

.layer layer_38C1
transpose -2
ldelay 0x3
rjump layer_38A6

.channel enemy_dodongo_jr_eat
instr FONT01_INSTR_GULP_SPEAR
ldlayer 0, layer_38CD
end

.layer layer_38CD
notedv PITCH_C3, 0x30, 100
end

.channel enemy_stalfos_walk
instr FONT01_INSTR_SMASH
ldlayer 0, layer_38D7
end

.layer layer_38D7
portamento 0x81, 35, 64
notedv PITCH_DF3, 0xC, 64
end

.channel enemy_stalfos_laugh
ldlayer 0, layer_38E5
gain 16
end

.layer layer_38E5
instr FONT01_INSTR_PHANTOM_LAUGH_0
notedv PITCH_C4, 0x8C, 100
end

.channel enemy_lizalfos_hurt
ldlayer 0, layer_38F6
ldlayer 1, layer_3907
ldlayer 2, layer_4829
end

.layer layer_38F6
instr FONT01_INSTR_LIZALFOS
portamento 0x81, 33, 255
notedv PITCH_DF4, 0xF, 100
portamento 0x81, 38, 255
notedv PITCH_AF2, 0x28, 100
end

.layer layer_3907
instr FONT01_INSTR_MOBLIN_GROWL
notedv PITCH_C5, 0x5, 100
notedv PITCH_B4, 0x5, 100
notedv PITCH_A4, 0x5, 100
notedv PITCH_E4, 0x5, 100
end

.channel enemy_lizalfos_laugh
ldlayer 0, layer_391A
end

.layer layer_391A
instr FONT01_INSTR_LAUGHTER
portamento 0x81, 44, 255
notedv PITCH_C4, 0x14, 100
end

.channel enemy_lizalfos_die
ldlayer 0, layer_392E
ldlayer 1, layer_393F
ldlayer 2, layer_4829
end

.layer layer_392E
instr FONT01_INSTR_LIZALFOS
portamento 0x81, 35, 255
notedv PITCH_E3, 0xF, 100
portamento 0x81, 31, 255
notedv PITCH_C3, 0x1E, 100
end

.layer layer_393F
instr FONT01_INSTR_MOBLIN_GROWL
notedv PITCH_AF5, 0x5, 100
notedv PITCH_F5, 0x5, 100
notedv PITCH_DF5, 0x5, 100
notedv PITCH_BF4, 0x5, 100
end

.channel enemy_stalfos_hurt
ldlayer 0, layer_3958
.channel chan_3951
ldlayer 1, layer_3962
ldlayer 2, layer_4829
end

.layer layer_3958
instr FONT01_INSTR_PHANTOM_MOAN
portamento 0x81, 47, 100
notedv PITCH_G4, 0x50, 100
end

.layer layer_3962
instr FONT01_INSTR_POT_BREAK
notedv PITCH_G3, 0x5, 100
notedv PITCH_G3, 0x5, 100
end

.channel enemy_stalkid_hurt
ldlayer 0, layer_3970
rjump chan_3951

.layer layer_3970
transpose 19
rjump layer_3958

.channel enemy_stalfos_die
ldlayer 0, layer_3984
.channel chan_3977
ldlayer 1, layer_3997
ldlayer 2, layer_4829
gain 20
vibfreq 50
vibdepth 10
end

.layer layer_3984
instr FONT01_INSTR_PHANTOM_MOAN
legato
portamento 0x85, 43, 200
notedv PITCH_AF4, 0x1E, 100
notedv PITCH_A3, 0x8C, 100
notedv PITCH_E4, 0xC8, 100
end

.layer layer_3997
instr FONT01_INSTR_POT_BREAK
notedv PITCH_G3, 0x5, 100
notedv PITCH_G3, 0xF, 100
end

.channel enemy_stalkid_die
ldlayer 0, layer_39A5
rjump chan_3977

.layer layer_39A5
transpose 14
rjump layer_3984

.channel enemy_firehead_cry
ldlayer 0, layer_39A5
end

.channel enemy_lizalfos_walk
ldlayer 0, layer_39B1
end

.layer layer_39B1
instr FONT01_INSTR_LIZALFOS
transpose 48
notedv PITCH_DF4, 0xA, 80
end

.channel enemy_lizalfos_land
ldlayer 0, layer_39BD
end

.layer layer_39BD
instr FONT01_INSTR_LIZALFOS
transpose 48
notedv PITCH_E4, 0xA, 80
notedv PITCH_D4, 0xA, 80
end

.channel enemy_lizalfos_jump
ldlayer 0, layer_39DD
ldlayer 1, layer_39D2
ldlayer 2, layer_39ED
end

.layer layer_39D2
instr FONT01_INSTR_LIZALFOS
transpose 48
notedv PITCH_E4, 0xA, 100
notedv PITCH_GF4, 0xA, 100
end

.layer layer_39DD
instr FONT01_INSTR_GUNSHOT
envelope envelope_686C, 240
transpose 4
portamento 0x81, 26, 50
notedv PITCH_B5, 0x50, 100
end

.layer layer_39ED
instr FONT01_INSTR_MOBLIN_GROWL
ldelay 0xA
notedv PITCH_EF4, 0x5, 100
notedv PITCH_D4, 0x5, 100
notedv PITCH_C4, 0x5, 100
notedv PITCH_C4, 0x5, 100
end

.channel enemy_armos_hop
instr FONT01_INSTR_SMASH
ldlayer 0, layer_3A04
end

.layer layer_3A04
portamento 0x81, 39, 200
notedv PITCH_A3, 0x14, 100
end

.channel enemy_armos_awaken
instr FONT01_INSTR_SMASH
envelope envelope_690C
ldlayer 1, layer_3A18
ldlayer 0, layer_3A2E
end

.layer layer_3A18
notedv PITCH_E2, 0xA, 100
notedv PITCH_GF2, 0xA, 100
notedv PITCH_E2, 0xA, 100
notedv PITCH_GF2, 0xA, 100
notedv PITCH_E2, 0xA, 100
notedv PITCH_GF2, 0xA, 100
notedv PITCH_E2, 0xA, 100
end

.layer layer_3A2E
instr FONT01_INSTR_PHANTOM_WAIL
envelope envelope_699C, 250
legato
portamento 0x85, 23, 255
notedv PITCH_C4, 0x1E, 100
notedv PITCH_F3, 0x52, 100
end

.channel enemy_armos_die
ldlayer 0, layer_3A47
ldlayer 1, layer_4829
end

.layer layer_3A47
instr FONT01_INSTR_PHANTOM_WAIL
envelope envelope_699C, 240
legato
portamento 0x85, 37, 200
notedv PITCH_GF4, 0x1E, 100
notedv PITCH_GF3, 0x64, 100
end

.channel enemy_armos_roar
instr FONT01_INSTR_PHANTOM_WAIL
envelope envelope_699C
gain 19
ldlayer 0, layer_3A64
end

.layer layer_3A64
legato
portamento 0x85, 23, 255
notedv PITCH_C4, 0x1E, 100
notedv PITCH_F3, 0x52, 100
end

.channel enemy_stalfos_attack
ldlayer 0, layer_3A79
ldlayer 1, layer_3A87
gain 20
end

.layer layer_3A79
instr FONT01_INSTR_STALFOS_ATTACK
legato
portamento 0x85, 30, 30
notedv PITCH_BF4, 0x14, 100
notedv PITCH_A4, 0x14, 100
end

.layer layer_3A87
instr FONT01_INSTR_GERUDO_ATTACK
envelope envelope_682C, 240
ldelay 0xA
notedv PITCH_B3, 0x1E, 100
end

.channel enemy_armos_hurt
ldlayer 0, layer_3A9A
ldlayer 1, layer_4829
end

.layer layer_3A9A
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 39, 100
notedv PITCH_F4, 0x1E, 100
notedv PITCH_C4, 0x1E, 100
end

.channel enemy_boss_dodongo_demo_wall
instr FONT01_INSTR_GUNSHOT
ldlayer 0, layer_3AB4
ldlayer 1, layer_3ABF
ldlayer 2, layer_3ACA
end

.layer layer_3AB4
notedv PITCH_GF3, 0x14, 100
envelope envelope_688C, 240
notedv PITCH_AF2, 0x64, 100
end

.layer layer_3ABF
notedv PITCH_BF3, 0x14, 100
envelope envelope_688C, 240
notedv PITCH_C3, 0x64, 100
end

.layer layer_3ACA
notedv PITCH_DF4, 0x14, 100
envelope envelope_688C, 240
notedv PITCH_EF3, 0x64, 100
end

.channel enemy_boss_dodongo_wall_hit
instr FONT01_INSTR_GUNSHOT
ldlayer 0, layer_3ADE
ldlayer 1, layer_3AE9
end

.layer layer_3ADE
notedv PITCH_GF3, 0x14, 100
envelope envelope_688C, 240
notedv PITCH_AF2, 0x32, 100
end

.layer layer_3AE9
notedv PITCH_B3, 0x14, 100
envelope envelope_688C, 240
notedv PITCH_DF3, 0x32, 100
end

.channel enemy_boss_dodongo_roll
ldlayer 0, layer_3B01
ldlayer 1, layer_3AFF
vibfreq 20
vibdepth 100
end

.layer layer_3AFF
transpose 12

.layer layer_3B01
instr FONT01_INSTR_BOULDER
.layer layer_3B03
notedv PITCH_C4, 30000, 100
rjump layer_3B03

.channel enemy_boss_dodongo_inhale
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_3B14
ldlayer 1, layer_3B12
end

.layer layer_3B12
transpose -4

.layer layer_3B14
legato
portamento 0x81, 27, 255
notedv PITCH_F3, 0xAA, 100
.layer layer_3B1D
notedv PITCH_F3, 30000, 100
rjump layer_3B1D

.channel enemy_boss_dodongo_swallow
instr FONT01_INSTR_GULP_SPEAR
ldlayer 0, layer_3B2E
ldlayer 1, layer_3B30
gain 24
end

.layer layer_3B2E
transpose -2

.layer layer_3B30
notedv PITCH_C3, 0x46, 100
end

.channel enemy_boss_dodongo_paralyzed
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_683C
ldlayer 0, layer_3B40
ldlayer 1, layer_3B42
end

.layer layer_3B40
transpose -4

.layer layer_3B42
legato
portamento 0x85, 15, 255
notedv PITCH_D2, 0x32, 100
notedv PITCH_B1, 0x32, 100
nolegato
rjump layer_3B42

.channel enemy_dodongo_inhale
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_3B56
end

.layer layer_3B56
notedv PITCH_E3, 30000, 100
rjump layer_3B56

.channel enemy_big_baba_chomp
instr FONT01_INSTR_BABA_ATTACK
ldlayer 0, layer_3B62
end

.layer layer_3B62
notedv PITCH_F3, 0x1E, 100
end

.channel enemy_big_baba_attack
ldlayer 0, layer_3B6A
end

.layer layer_3B6A
instr FONT01_INSTR_BABA_LUNGE
transpose 48
portamento 0x81, 39, 200
notedv PITCH_E4, 0x32, 100
end

.channel enemy_big_baba_hurt
ldlayer 0, layer_3B7D
ldlayer 1, layer_4829
end

.layer layer_3B7D
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 44, 255
notedv PITCH_C5, 0xA, 100
portamento 0x81, 53, 255
notedv PITCH_F4, 0x1E, 100
end

.channel enemy_big_baba_die
ldlayer 0, layer_3B99
ldlayer 1, layer_4829
vibfreq 100
vibdepth 127
end

.layer layer_3B99
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_69AC, 255
legato
portamento 0x85, 31, 255
notedv PITCH_C4, 0x1E, 100
notedv PITCH_C3, 0x78, 100
end

.channel enemy_shell_die
ldlayer 0, layer_3BB9
ldlayer 1, layer_4BA9
ldlayer 2, layer_4829
vibfreq 48
vibdepth 128
end

.layer layer_3BB9
transpose 3
rjump layer_3B99

.channel enemy_deku_baba_chomp
instr FONT01_INSTR_BABA_ATTACK
ldlayer 0, layer_3BC3
end

.layer layer_3BC3
notedv PITCH_F4, 0xF, 100
end

.channel enemy_deku_baba_attack
ldlayer 0, layer_3BCB
end

.layer layer_3BCB
instr FONT01_INSTR_BABA_LUNGE
transpose 48
portamento 0x81, 48, 255
notedv PITCH_C5, 0x1E, 100
end

.channel enemy_deku_baba_die
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_684C
ldlayer 0, layer_3BE7
ldlayer 1, layer_4829
vibfreq 100
vibdepth 127
end

.layer layer_3BE7
legato
portamento 0x85, 49, 200
notedv PITCH_GF5, 0x1E, 100
notedv PITCH_GF4, 0x32, 100
end

.channel enemy_deku_baba_slide
ldlayer 0, layer_3BFC
instr FONT01_INSTR_TEKTITE_ROTATE
envelope envelope_68BC
end

.layer layer_3BFC
portamento 0x81, 13, 255
notedv PITCH_G1, 0x38, 80
end

.channel enemy_keese_die
ldlayer 0, layer_3C0B
ldlayer 1, layer_4829
end

.layer layer_3C0B
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 44, 255
notedv PITCH_C5, 0xA, 100
portamento 0x81, 53, 255
notedv PITCH_F4, 0x1E, 100
end

.channel enemy_tailpasaran_fly
instr FONT01_INSTR_BABA_LUNGE
ldlayer 0, layer_3C26
vibfreq 64
vibdepth 128
end

.layer layer_3C26
notedv PITCH_BF2, 30000, 80
rjump layer_3C26

.channel enemy_tailpasaran_cry
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3C32
end

.layer layer_3C32
portamento 0x81, 14, 60
notedv PITCH_E2, 0x32, 100
end

.channel enemy_tailpasaran_die
ldlayer 0, layer_3C45
ldlayer 1, layer_4829
vibfreq 112
vibdepth 112
end

.layer layer_3C45
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 35, 96
notedv PITCH_C5, 0x14, 100
portamento 0x81, 44, 207
notedv PITCH_C4, 0x30, 100
end

.channel enemy_skulltula_climb
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3C5F
ldlayer 1, layer_3C67
end

.layer layer_3C5F
portamento 0x81, 39, 100
notedv PITCH_E4, 0x32, 100
end

.layer layer_3C67
ldelay 0x5
portamento 0x81, 37, 100
notedv PITCH_D4, 0x32, 100
end

.channel enemy_skulltula_drop
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3C7A
ldlayer 1, layer_3C82
end

.layer layer_3C7A
portamento 0x81, 43, 100
notedv PITCH_C4, 0x32, 100
end

.layer layer_3C82
ldelay 0x5
portamento 0x81, 41, 100
notedv PITCH_BF3, 0x32, 100
end

.channel enemy_skulltula_quiver
instr FONT01_INSTR_LAUGHTER
envelope envelope_699C
ldlayer 0, layer_3C9B
gain 16
vibfreq 100
vibdepth 127
end

.layer layer_3C9B
notedv PITCH_F1, 0x64, 100
end

.channel enemy_tektite_turn_ground
ldlayer 0, layer_3CA3
end

.layer layer_3CA3
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_C4, 0xA, 70
end

.channel enemy_poe_attack_charge
ldlayer 0, layer_3CB0
ldlayer 1, layer_3CB6
end

.layer layer_3CB0
instr FONT01_INSTR_OWL_FLAP
notedv PITCH_F3, 0x19, 100
end

.layer layer_3CB6
instr FONT01_INSTR_POT_BREAK
notedv PITCH_F3, 0xA, 30
end

.channel enemy_poe_float
instr FONT01_INSTR_POE_DISAPPEAR
envelope envelope_69AC
ldlayer 0, layer_3CC9
vibfreq 20
vibdepth 127
end

.layer layer_3CC9
notedv PITCH_F3, 0x87, 100
rjump layer_3CC9

.channel enemy_poe_retreat
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_3CD9
vibfreq 60
vibdepth 100
end

.layer layer_3CD9
notedv PITCH_E4, 0x32, 100
ldelay 0xA
rjump layer_3CD9

.channel enemy_poe_vanish
instr FONT01_INSTR_POE_DISAPPEAR
envelope envelope_69BC
ldlayer 0, layer_3CED
vibfreq 100
vibdepth 100
end

.layer layer_3CED
portamento 0x81, 43, 255
notedv PITCH_C2, 0x96, 100
end

.channel enemy_poe_appear
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_3D00
vibfreq 100
vibdepth 100
end

.layer layer_3D00
portamento 0x81, 15, 200
notedv PITCH_E4, 0x96, 100
end

.channel enemy_poe_hurt
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_3D14
ldlayer 1, layer_4829
gain 24
end

.layer layer_3D14
portamento 0x81, 49, 200
notedv PITCH_A5, 0xA, 100
portamento 0x81, 60, 155
notedv PITCH_E5, 0x1E, 100
end

.channel enemy_poe_die
ldlayer 0, layer_3D2C
ldlayer 1, layer_4829
gain 24
end

.layer layer_3D2C
instr FONT01_INSTR_POE_DISAPPEAR
portamento 0x81, 49, 200
notedv PITCH_A5, 0xA, 100
portamento 0x81, 60, 155
notedv PITCH_E5, 0x3C, 100
end

.channel enemy_boss_dodongo_roar
ldlayer 0, layer_3D47
ldlayer 1, layer_3D52
ldlayer 2, layer_3D5D
end

.layer layer_3D47
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x85, 11, 50
notedv PITCH_C3, 0x12C, 100
end

.layer layer_3D52
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x85, 13, 50
notedv PITCH_D3, 0x122, 100
end

.layer layer_3D5D
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x81, 12, 255
notedv PITCH_DF2, 0xC8, 100
end

.channel enemy_boss_gohma_eyeroll
instr FONT01_INSTR_EGG_CRACK
ldlayer 0, layer_3D75
ldlayer 1, layer_3D73
gain 18
end

.layer layer_3D73
transpose 4

.layer layer_3D75
portamento 0x81, 3, 200
notedv PITCH_E1, 0x8C, 100
end

.channel enemy_boss_dodongo_die
ldlayer 0, layer_3DB4
ldlayer 1, layer_3D8F
ldlayer 2, layer_3D91
ldlayer 3, layer_4829
vibfreq 20
vibdepth 50
end

.layer layer_3D8F
transpose -6

.layer layer_3D91
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x85, 38, 255
notedv PITCH_E4, 0x1E, 100
notedv PITCH_B2, 0x96, 100
transpose -5
envelope envelope_69DC, 127
portamento 0x85, 31, 255
notedv PITCH_A3, 0x3C, 80
envelope envelope_6A3C, 127
notedv PITCH_D2, 0xE6, 80
end

.layer layer_3DB4
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_69CC, 230
portamento 0x81, 15, 20
notedv PITCH_E3, 0x96, 100
envelope envelope_6A2C, 240
portamento 0x81, 31, 100
notedv PITCH_C2, 0x10E, 100
end

.channel enemy_boss_dodongo_dying_groan
ldlayer 0, layer_3DDF
ldlayer 1, layer_3DEA
ldlayer 2, layer_3DF5
gain 20
vibfreq 70
vibdepth 50
end

.layer layer_3DDF
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x81, 13, 50
notedv PITCH_D3, 0x118, 100
end

.layer layer_3DEA
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x81, 11, 50
notedv PITCH_C3, 0x122, 100
end

.layer layer_3DF5
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x81, 12, 255
notedv PITCH_DF2, 0xC8, 100
end

.channel enemy_boss_dodongo_fossilize
instr 2
ldlayer 0, layer_3E0F
ldlayer 1, layer_3E11
gain 16
vibfreq 10
vibdepth 20
end

.layer layer_3E0F
transpose -8

.layer layer_3E11
notedv PITCH_E2, 30000, 100
rjump layer_3E11

.channel enemy_boss_dodongo_lava
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_682C
gain 20
ldlayer 0, layer_3E25
ldlayer 1, layer_3E29
end

.layer layer_3E25
transpose 42
rjump layer_3E2B

.layer layer_3E29
transpose 48
.layer layer_3E2B
notedv PITCH_C5, 0x46, 100
notedv PITCH_F4, 0x46, 100
notedv PITCH_C4, 0x46, 100
notedv PITCH_BF3, 0x32, 100
notedv PITCH_G3, 0x28, 100
notedv PITCH_EF3, 0x28, 100
notedv PITCH_D3, 0x1E, 100
notedv PITCH_BF2, 0x1E, 100
end

.channel enemy_boss_dodongo_hurt
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_683C
ldlayer 0, layer_3E60
ldlayer 1, layer_3E56
ldlayer 2, layer_3E58
ldlayer 3, layer_4829
end

.layer layer_3E56
transpose -8

.layer layer_3E58
portamento 1, 38, 20
notedv PITCH_EF4, 0x50, 100
end

.layer layer_3E60
portamento 0x85, 31, 150
notedv PITCH_C4, 0x14, 100
notedv PITCH_B3, 0x46, 100
end

.channel enemy_stalfos_jump
ldlayer 0, layer_3E6F
end

.layer layer_3E6F
instr FONT01_INSTR_GUNSHOT
envelope envelope_686C, 255
transpose 4
portamento 0x81, 26, 50
notedv PITCH_B5, 0x50, 100
end

.channel enemy_boss_gohma_die
envelope envelope_687C
ldlayer 0, layer_3E93
ldlayer 1, layer_3E95
ldlayer 2, layer_3EB4
ldlayer 3, layer_4829
vibfreq 20
vibdepth 50
end

.layer layer_3E93
transpose -6

.layer layer_3E95
instr FONT01_INSTR_DINO_ROAR
portamento 0x85, 38, 255
notedv PITCH_E4, 0x1E, 100
notedv PITCH_B2, 0x96, 100
transpose -5
portamento 0x85, 32, 255
notedv PITCH_C4, 0x3C, 80
envelope envelope_6A3C, 200
notedv PITCH_B2, 0xC8, 80
end

.layer layer_3EB4
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_69CC, 200
portamento 0x81, 15, 20
notedv PITCH_E3, 0x96, 100
envelope envelope_6A2C, 200
portamento 0x81, 31, 100
notedv PITCH_C2, 0x12C, 100
end

.channel enemy_scrub_emerge
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3ED8
ldlayer 1, layer_3EDA
end

.layer layer_3ED8
transpose -2

.layer layer_3EDA
portamento 0x81, 31, 64
notedv PITCH_C4, 0x32, 100
end

.channel enemy_scrub_burrow
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_3EEB
ldlayer 1, layer_3EED
end

.layer layer_3EEB
transpose -2

.layer layer_3EED
portamento 0x81, 39, 64
notedv PITCH_E3, 0x32, 100
end

.channel enemy_scrub_spit
instr 2
ldlayer 0, layer_3EFD
gain 32
end

.layer layer_3EFD
portamento 0x81, 31, 64
notedv PITCH_C4, 0xC, 100
end

.channel enemy_scrub_walk
ldlayer 0, layer_3F0C
ldlayer 1, layer_5320
end

.layer layer_3F0C
instr FONT01_INSTR_GRASS_RUSTLE
notedv PITCH_DF4, 0x20, 70
end

.channel enemy_scrub_hurt
ldlayer 0, layer_3F16
end

.layer layer_3F16
instr FONT01_INSTR_SCRUB_DEATH
transpose 4
portamento 0x81, 51, 255
notedv PITCH_B5, 0xA, 100
portamento 0x81, 60, 255
notedv PITCH_E5, 0x19, 100
end

.channel enemy_scrub_die
ldlayer 0, layer_3F2D
end

.layer layer_3F2D
instr FONT01_INSTR_SCRUB_DEATH
portamento 0x81, 59, 255
notedv PITCH_E5, 0xA, 100
portamento 0x81, 51, 255
notedv PITCH_F4, 0x1E, 100
end

.channel enemy_boss_gohma_dissolve
ldlayer 0, layer_3F49
ldlayer 1, layer_3F4B
vibfreq 10
vibdepth 20
end

.layer layer_3F49
transpose -1

.layer layer_3F4B
instr 2
.layer layer_3F4D
notedv PITCH_EF1, 30000, 100
rjump layer_3F4D

.channel enemy_tektite_hurt
instr FONT01_INSTR_GUAY_HURT
envelope envelope_65D8
ldlayer 0, layer_3F5F
ldlayer 1, layer_4829
end

.layer layer_3F5F
portamento 0x81, 36, 255
notedv PITCH_E4, 0xA, 100
portamento 0x81, 44, 255
notedv PITCH_B3, 0x1E, 100
end

.channel enemy_tektite_die
ldlayer 0, layer_3F78
ldlayer 1, layer_3F89
ldlayer 2, layer_4829
end

.layer layer_3F78
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x81, 32, 255
notedv PITCH_C4, 0xA, 100
portamento 0x81, 40, 255
notedv PITCH_G3, 0x5C, 100
end

.layer layer_3F89
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 43, 255
notedv PITCH_B4, 0xF, 80
portamento 0x81, 48, 255
notedv PITCH_EF4, 0x24, 80
end

.channel enemy_stinger_hurt
instr FONT01_INSTR_GUAY_HURT
ldlayer 0, layer_3FA7
ldlayer 1, layer_4829
vibfreq 48
vibdepth 48
end

.layer layer_3FA7
transpose -10
rjump layer_3F5F
end

.channel enemy_stinger_die
ldlayer 0, layer_3FBA
ldlayer 1, layer_3FCB
ldlayer 2, layer_4829
vibfreq 48
vibdepth 48
end

.layer layer_3FBA
instr FONT01_INSTR_DODONGO_ROAR
portamento 0x81, 22, 127
notedv PITCH_DF4, 0x28, 100
portamento 0x81, 38, 255
notedv PITCH_A2, 0x7F, 100
end

.layer layer_3FCB
transpose -12
rjump layer_3F89
end

.channel enemy_skulltula_hurt
ldlayer 0, layer_4829
ldlayer 1, layer_3FD7
end

.layer layer_3FD7
instr FONT01_INSTR_DINO_INHALE
portamento 0x81, 51, 255
notedv PITCH_B5, 0xA, 100
portamento 0x81, 60, 255
notedv PITCH_E5, 0x14, 100
end

.channel enemy_gold_skull_cry
ldlayer 0, layer_3FD7
end

.channel enemy_skulltula_pivot
instr FONT01_INSTR_OWL_FLAP
ldlayer 0, layer_3FF2
end

.layer layer_3FF2
portamento 0x81, 51, 255
notedv PITCH_B5, 0x14, 100
portamento 0x81, 60, 255
notedv PITCH_E5, 0x14, 100
end

.channel enemy_skullwall_die
ldlayer 0, layer_400C
ldlayer 1, layer_4829
vibfreq 100
vibdepth 127
end

.layer layer_400C
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 29, 255
notedv PITCH_BF3, 0x14, 100
notedv PITCH_BF2, 0x3C, 100
end

.channel enemy_dissolve
instr 2
envelope envelope_68DC
ldlayer 0, layer_4023
end

.layer layer_4023
portamento 0x81, 7, 100
notedv PITCH_A1, 0x19, 100
end

.channel enemy_boss_gohma_thrust
instr FONT01_INSTR_MONSTER_ROAR
envelope envelope_68EC
ldlayer 0, layer_4038
vibfreq 100
vibdepth 50
end

.layer layer_4038
portamento 0x81, 45, 250
notedv PITCH_GF3, 0x28, 100
end

.channel enemy_lizalfos_cry
ldlayer 0, layer_404B
ldlayer 1, layer_4057
vibfreq 50
vibdepth 60
end

.layer layer_404B
instr FONT01_INSTR_BABA_LUNGE
transpose 48
portamento 0x81, 32, 100
notedv PITCH_D3, 0x23, 80
end

.layer layer_4057
instr FONT01_INSTR_LIZALFOS
portamento 0x81, 39, 100
notedv PITCH_A3, 0x28, 100
end

.channel enemy_lizalfos_attack_shout
ldlayer 1, layer_406B
ldlayer 0, layer_4077
ldlayer 2, layer_4081
end

.layer layer_406B
instr FONT01_INSTR_BABA_LUNGE
transpose 48
portamento 0x81, 34, 200
notedv PITCH_B3, 0x23, 80
end

.layer layer_4077
instr FONT01_INSTR_LIZALFOS
portamento 0x81, 39, 255
notedv PITCH_F4, 0x32, 100
end

.layer layer_4081
instr FONT01_INSTR_GERUDO_ATTACK
envelope envelope_682C, 240
ldelay 0xA
notedv PITCH_D4, 0x1E, 100
end

.channel enemy_dodongo_swipe
instr FONT01_INSTR_GUNSHOT
envelope envelope_686C
ldlayer 0, layer_4098
gain 20
end

.layer layer_4098
transpose 5
portamento 0x81, 26, 200
notedv PITCH_B5, 0xC8, 100
end

.channel enemy_poe_transform
instr FONT01_INSTR_POE_DISAPPEAR
envelope envelope_69BC
ldlayer 0, layer_40B0
vibfreq 100
vibdepth 100
end

.layer layer_40B0
portamento 0x81, 55, 255
notedv PITCH_C3, 0x50, 100
end

.channel enemy_wallmaster_fall
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_40C1
ldlayer 1, layer_40C3
end

.layer layer_40C1
transpose -6

.layer layer_40C3
notedv PITCH_C3, 0x1A0, 100
end

.channel enemy_wallmaster_retreat
instr FONT01_INSTR_POE_DISAPPEAR
envelope envelope_69FC
ldlayer 0, layer_40D3
gain 16
end

.layer layer_40D3
portamento 0x81, 36, 100
notedv PITCH_C4, 0x78, 100
end

.channel enemy_floormaster_walk
instr FONT01_INSTR_EGG_CRACK
ldlayer 0, layer_40E3
gain 20
end

.layer layer_40E3
portamento 0x81, 9, 128
notedv PITCH_A1, 0xF, 100
end

.channel enemy_floormaster_hurt
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_40F8
ldlayer 1, layer_4829
vibfreq 100
vibdepth 70
end

.layer layer_40F8
legato
portamento 0x85, 42, 128
notedv PITCH_AF4, 0x1E, 100
notedv PITCH_C4, 0x28, 100
end

.channel enemy_floormaster_die
ldlayer 0, layer_410F
ldlayer 1, layer_4829
vibfreq 132
vibdepth 70
end

.layer layer_410F
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 46, 128
notedv PITCH_C5, 0x28, 100
notedv PITCH_E4, 0x30, 100
end

.channel enemy_biri_float
instr FONT01_INSTR_STALFOS_ATTACK
envelope envelope_6A0C
ldlayer 0, layer_4126
end

.layer layer_4126
legato
portamento 0x85, 31, 255
notedv PITCH_A3, 0x32, 100
notedv PITCH_AF2, 0x46, 100
end

.channel enemy_biri_fly
ldlayer 0, layer_414B
ldlayer 1, layer_4139
end

.layer layer_4139
instr 2
envelope envelope_6A0C, 220
legato
portamento 0x85, 27, 200
notedv PITCH_F3, 0x14, 60
notedv PITCH_E2, 0x32, 60
end

.layer layer_414B
instr FONT01_INSTR_STALFOS_ATTACK
envelope envelope_6A0C, 128
legato
portamento 0x85, 31, 200
notedv PITCH_A3, 0x32, 100
notedv PITCH_AF2, 0x46, 100
end

.channel enemy_biri_shock
instr FONT01_INSTR_GANONDORF_ATTACK_0
.channel chan_415F
ldlayer 0, layer_4179
.channel chan_4162
rand 6
stseq 3, layer_4179+1
stseq 3, chan_4172+1
rand 8
stseq 91, layer_4179
.channel chan_4172
ldi 1
call delay_varyingvol
rjump chan_4162

.layer layer_4179
notedv PITCH_C3, 0x50, 80
rjump layer_4179

.channel enemy_boss_ganon_transform
instr FONT01_INSTR_GANONDORF_ATTACK_0
releaserate 208
rjump chan_415F

.channel enemy_biri_die
ldlayer 0, layer_4829
ldlayer 1, layer_418B
end

.layer layer_418B
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 32, 255
notedv PITCH_C4, 0xA, 100
portamento 0x81, 41, 255
notedv PITCH_F3, 0xE, 100
end

.channel enemy_torch_slug_hurt
ldlayer 0, layer_41A6
ldlayer 1, layer_41B8
ldlayer 2, layer_4829
end

.layer layer_41A6
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 32, 64
notedv PITCH_C4, 0x14, 80
portamento 0x81, 37, 255
notedv PITCH_BF2, 0x24, 80
end

.layer layer_41B8
transpose -8
rjump layer_418B

.channel enemy_biri_die_bubbles
ldlayer 0, layer_41C0
end

.layer layer_41C0
instr FONT01_INSTR_WATER_BUBBLES
envelope envelope_6A1C, 249
portamento 0x81, 25, 255
notedv PITCH_G3, 0x90, 100
end

.channel enemy_phantom_reveal
instr FONT01_INSTR_DINO_ROAR
envelope envelope_69CC
ldlayer 0, layer_41E0
vibfreqgrad 70, 110, 18
vibdepthgrad 20, 80, 10
end

.layer layer_41E0
portamento 0x81, 21, 255
notedv PITCH_BF2, 0xE6, 100
end

.channel enemy_phantom_lightning
ldlayer 0, layer_41EF
gain 22
end

.layer layer_41EF
instr FONT01_INSTR_ELECTRIC_ATTACK
notedv PITCH_C4, 0x118, 100
end

.channel enemy_ganondorf_charge
instr FONT01_INSTR_GANONDORF_ATTACK_0
ldlayer 0, layer_41FE
gain 20
end

.layer layer_41FE
notedv PITCH_A3, 0x50, 100
end

.channel enemy_ganondorf_fly
instr FONT01_INSTR_GANONDORF_FLY
ldlayer 0, layer_4208
end

.layer layer_4208
notedv PITCH_D4, 30000, 100
rjump layer_4208

.channel enemy_witch_charge
ldlayer 0, layer_4214
gain 24
end

.layer layer_4214
instr FONT01_INSTR_GANONDORF_CHARGE
notedv PITCH_F4, 0x5A, 100
end

.channel enemy_phantom_painting_enter
ldlayer 0, layer_4220
gain 24
end

.layer layer_4220
instr FONT01_INSTR_SWOOSH
notedv PITCH_D4, 0x5A, 100
end

.channel enemy_phantom_shout
instr FONT01_INSTR_PHANTOM_ATTACK
ldlayer 0, layer_422E
gain 24
end

.layer layer_422E
portamento 0x81, 39, 50
notedv PITCH_F4, 0x30, 100
end

.channel enemy_ganondorf_orb_trail
ldlayer 0, layer_423E
vibfreq 128
vibdepth 128
end

.layer layer_423E
instr 2
legato
portamento 0x81, 37, 255
.layer layer_4245
notedv PITCH_GF3, 0xC8, 100
rjump layer_4245

.channel enemy_boss_twinrova_ice_reflected
ldlayer 0, layer_4256
ldlayer 1, layer_4B32
vibfreq 128
vibdepth 96
end

.layer layer_4256
instr 2
transpose 12
legato
rjump layer_4245

.channel enemy_ganondorf_lightning_hit
ldlayer 0, layer_4261
end

.layer layer_4261
instr FONT01_INSTR_ELECTRIC_ATTACK
notedv PITCH_C5, 0x8C, 100
end

.channel enemy_phantom_attack_unused
instr FONT01_INSTR_THUNDERBURST
envelope envelope_6A5C
ldlayer 0, layer_4273
gain 16
end

.layer layer_4273
notedv PITCH_E3, 0x1C2, 100
end

.channel enemy_phantom_staff
instr FONT01_INSTR_SWOOSH
ldlayer 0, layer_4280
gain 20
end

.layer layer_4280
ldelay 0xF
notedv PITCH_C4, 0x7, 100
notedv PITCH_G4, 0x7, 100
notedv PITCH_C5, 0x7, 100
notedv PITCH_G5, 0x7, 100
notedv PITCH_E4, 0x7, 100
notedv PITCH_B4, 0x7, 100
notedv PITCH_E5, 0x7, 100
notedv PITCH_B5, 0x7, 100
end

.channel enemy_phantom_eyes
instr FONT01_INSTR_GANONDORF_CHARGE
envelope envelope_699C
ldlayer 0, layer_42AA
gain 20
vibfreq 128
vibdepth 20
end

.layer layer_42AA
portamento 0x81, 33, 255
notedv PITCH_DF3, 0x6E, 100
end

.channel enemy_phantom_orb_dissipate
instr FONT01_INSTR_THUNDERBURST
ldlayer 0, layer_42B8
end

.layer layer_42B8
portamento 0x81, 60, 200
notedv PITCH_C3, 0x1E, 100
end

.channel enemy_phantom_die_roar
instr FONT01_INSTR_PHANTOM_WAIL
ldlayer 0, layer_42E9
ldlayer 1, layer_42DD
ldlayer 2, layer_42D4
gain 20
releaserate 244
vibfreq 50
vibdepth 30
end

.layer layer_42D4
portamento 0x81, 46, 100
notedv PITCH_D4, 0xB4, 100
end

.layer layer_42DD
ldelay 0x96
portamento 0x81, 36, 220
notedv PITCH_E3, 0xD2, 100
end

.layer layer_42E9
ldelay 0x14A
portamento 0x81, 31, 200
notedv PITCH_A2, 0x14A, 100
end

.channel enemy_phantom_hurt
ldlayer 0, layer_4301
ldlayer 1, layer_430F
ldlayer 2, layer_4829
gain 20
end

.layer layer_4301
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 39, 100
notedv PITCH_A4, 0x1E, 100
notedv PITCH_C4, 0x3C, 100
end

.layer layer_430F
instr FONT01_INSTR_GANONDORF_ATTACK_0
legato
portamento 0x81, 29, 100
notedv PITCH_E4, 0x14, 68
portamento 0x81, 34, 255
notedv PITCH_G2, 0x24, 68
end

.channel enemy_deadhand_hurt
ldlayer 0, layer_4328
ldlayer 1, layer_4829
end

.layer layer_4328
transpose -7
rjump layer_4301

.channel enemy_phantom_die
ldlayer 0, layer_433B
ldlayer 1, layer_434A
ldlayer 2, layer_434C
ldlayer 3, layer_4829
gain 20
end

.layer layer_433B
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 36, 255
notedv PITCH_GF4, 0x50, 100
notedv PITCH_AF2, 500, 100
end

.layer layer_434A
transpose -16

.layer layer_434C
instr FONT01_INSTR_THUNDERBURST
notedv PITCH_AF4, 0x1C2, 100
end

.channel enemy_deadhand_die
ldlayer 0, layer_435A
ldlayer 1, layer_4829
end

.layer layer_435A
transpose -8
rjump layer_433B

.channel enemy_phantom_hurt_orb
instr FONT01_INSTR_PHANTOM_WAIL
ldlayer 0, layer_436C
gain 20
releaserate 249
vibfreq 127
vibdepth 70
end

.layer layer_436C
legato
portamento 0x85, 30, 100
notedv PITCH_G3, 0x1E, 100
notedv PITCH_C3, 0x14, 100
end

.channel enemy_phantom_laugh
instr FONT01_INSTR_PHANTOM_LAUGH_1
ldlayer 0, layer_4380
gain 16
end

.layer layer_4380
notedv PITCH_BF3, 0x160, 100
end

.channel enemy_moblin_walk
instr FONT01_INSTR_SMASH
envelope envelope_68EC
ldlayer 0, layer_438E
end

.layer layer_438E
portamento 0x81, 28, 64
notedv PITCH_GF2, 0xD, 76
end

.channel enemy_moblin_dash
instr FONT01_INSTR_SMASH
envelope envelope_68EC
ldlayer 0, layer_439F
end

.layer layer_439F
portamento 0x81, 32, 64
notedv PITCH_BF2, 0x1D, 100
end

.channel enemy_moblin_slide
ldlayer 0, layer_43AE
ldlayer 1, layer_43B0
end

.layer layer_43AE
transpose -5

.layer layer_43B0
instr FONT01_INSTR_TEKTITE_ROTATE
notedv PITCH_C2, 0x78, 100
end

.channel enemy_octorok_jump
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_43BC
end

.layer layer_43BC
portamento 0x81, 40, 100
notedv PITCH_AF4, 0x64, 80
end

.channel enemy_octorok_dive
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_43CA
end

.layer layer_43CA
portamento 0x81, 38, 100
notedv PITCH_E3, 0x30, 100
end

.channel enemy_octorok_bubble
ldlayer 0, layer_43D6
end

.layer layer_43D6
instr FONT01_INSTR_STEP_WATER
notedv PITCH_B1, 0x66, 100
end

.channel enemy_octorok_float
instr FONT01_INSTR_STEP_WATER
ldlayer 0, layer_43E2
end

.layer layer_43E2
portamento 0x81, 23, 100
notedv PITCH_BF2, 0x30, 68
end

.channel enemy_tektite_land_water1
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_43F0
end

.layer layer_43F0
portamento 0x81, 47, 100
notedv PITCH_DF4, 0x50, 80
end

.channel enemy_octorok_rock_break
ldlayer 0, layer_43FC
end

.layer layer_43FC
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_68EC, 251
notedv PITCH_A2, 0x2C, 100
end

.channel enemy_bubble_dash
instr FONT01_INSTR_POT_BREAK
ldlayer 0, layer_440C
end

.layer layer_440C
portamento 0x81, 8, 255
notedv PITCH_C2, 0x6, 70
portamento 0x81, 14, 255
notedv PITCH_A1, 0x8, 70
end

.channel enemy_bubble_cry
ldlayer 0, layer_4423
vibfreq 96
vibdepth 128
end

.layer layer_4423
instr FONT01_INSTR_PHANTOM_LAUGH_0
notedv PITCH_E4, 0x54, 100
end

.channel enemy_bubble_flame_appear
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_6A0C
ldlayer 0, layer_443A
vibfreqgrad 70, 110, 18
vibdepthgrad 20, 80, 10
end

.layer layer_443A
portamento 0x81, 19, 255
notedv PITCH_AF2, 0x46, 100
end

.channel enemy_bubble_flame_vanish
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_6A0C
ldlayer 0, layer_4453
vibfreqgrad 70, 110, 18
vibdepthgrad 20, 80, 10
end

.layer layer_4453
portamento 0x81, 23, 255
notedv PITCH_E2, 0x46, 100
end

.channel enemy_moblin_attack_shout
instr FONT01_INSTR_LIZALFOS
ldlayer 0, layer_4463
gain 16
end

.layer layer_4463
portamento 0x81, 17, 255
notedv PITCH_A2, 0x96, 100
end

.channel enemy_moblin_grunt
instr FONT01_INSTR_MOBLIN_GROWL
ldlayer 0, layer_4474
gain 16
end

.layer layer_4474
portamento 0x81, 21, 255
notedv PITCH_DF2, 0x44, 100
end

.channel enemy_moblin_spear_relax
instr FONT01_INSTR_GULP_SPEAR
ldlayer 0, layer_4482
end

.layer layer_4482
transpose 42
notedv PITCH_F4, 0xA, 100
end

.channel enemy_moblin_spear_point
instr FONT01_INSTR_GULP_SPEAR
ldlayer 0, layer_4490
gain 20
end

.layer layer_4490
transpose 44
notedv PITCH_B3, 0x1D, 100
end

.channel enemy_moblin_club_strike
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_449C
end

.layer layer_449C
portamento 0x81, 25, 255
notedv PITCH_F2, 0x78, 100
end

.channel enemy_moblin_club_lift
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_44AA
end

.layer layer_44AA
portamento 0x81, 16, 255
notedv PITCH_B2, 0x78, 100
end

.channel enemy_moblin_die
ldlayer 0, layer_44B9
ldlayer 1, layer_4829
end

.layer layer_44B9
instr FONT01_INSTR_LIZALFOS
legato
portamento 0x85, 23, 200
notedv PITCH_C3, 0x1E, 100
notedv PITCH_DF2, 0x3C, 100
end

.channel enemy_boss_volvagia_rock
instr FONT01_INSTR_EXPLOSION_LAVA
ldlayer 0, layer_44D7
gain 20
rand 4
stseq 107, layer_44D7
releaserate 232
end

.layer layer_44D7
notedv PITCH_F4, 0x32, 100
end

.channel enemy_boss_volvagia_roar
ldlayer 0, layer_44EB
ldlayer 1, layer_44E4
gain 20
end

.layer layer_44E4
instr FONT01_INSTR_THUNDER_HURT
notedv PITCH_D4, 0xA8, 100
end

.layer layer_44EB
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 43, 255
notedv PITCH_GF4, 0xA, 100
portamento 0x81, 45, 255
notedv PITCH_A4, 0xA8, 100
end

.channel enemy_boss_ganon_roar
ldlayer 0, layer_4508
ldlayer 1, layer_450F
ldlayer 2, layer_4513
end

.layer layer_4508
instr FONT01_INSTR_MONSTER_ROAR
notedv PITCH_E4, 0xB4, 100
end

.layer layer_450F
transpose -2
rjump layer_44EB

.layer layer_4513
transpose 6
rjump layer_44E4

.channel enemy_volvagia_fall
ldlayer 0, layer_4532
ldlayer 1, layer_4524
gain 20
vibfreq 120
vibdepth 64
end

.layer layer_4524
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 39, 255
notedv PITCH_F4, 0x14, 80
notedv PITCH_C3, 0x6E, 80
end

.layer layer_4532
instr FONT01_INSTR_THUNDER_HURT
legato
portamento 0x85, 39, 255
notedv PITCH_A4, 0x14, 100
notedv PITCH_C2, 0xC8, 100
end

.channel enemy_volvagia_paralyzed
instr FONT01_INSTR_DINO_ROAR
gain 20
ldlayer 0, layer_4549
end

.layer layer_4549
legato
portamento 0x85, 19, 255
notedv PITCH_GF2, 0x1E, 100
notedv PITCH_B1, 0x1E, 100
end

.channel enemy_boss_volvagia_cry
ldlayer 0, layer_4564
ldlayer 1, layer_455E
gain 20
end

.layer layer_455E
instr FONT01_INSTR_THUNDER_HURT
notedv PITCH_AF4, 0x78, 100
end

.layer layer_4564
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 49, 255
notedv PITCH_C5, 0xA, 100
portamento 0x81, 51, 255
notedv PITCH_EF5, 0x78, 100
end

.channel enemy_boss_ganon_hurt
ldlayer 0, layer_4580
ldlayer 1, layer_4564
ldlayer 2, layer_4584
end

.layer layer_4580
transpose -6
rjump layer_4564

.layer layer_4584
instr FONT01_INSTR_MONSTER_ROAR
legato
portamento 0x85, 40, 200
notedv PITCH_AF4, 0x10, 100
notedv PITCH_D3, 0xB4, 100
end

.channel enemy_boss_volvagia_hole
ldlayer 0, layer_45A0
ldlayer 1, layer_45AC
gain 20
vibfreq 10
vibdepth 20
end

.layer layer_45A0
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_68B4, 220
.layer layer_45A6
notedv PITCH_GF2, 0x118, 100
rjump layer_45A6

.layer layer_45AC
instr 2
.layer layer_45AE
notedv PITCH_B0, 30000, 100
rjump layer_45AE

.channel enemy_boss_volvagia_swipe
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_45BA
end

.layer layer_45BA
portamento 0x81, 28, 255
notedv PITCH_C4, 0x40, 100
end

.channel enemy_redead_moan
instr FONT01_INSTR_GORON_YAWN
ldlayer 0, layer_45CB
ldlayer 1, layer_45CD
end

.layer layer_45CB
ldelay 0x18

.layer layer_45CD
notedv PITCH_E3, 0x170, 80
end

.channel enemy_redead_scream
ldlayer 0, layer_45D9
ldlayer 1, layer_45DF
end

.layer layer_45D9
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_REDEAD_SCREAM, 0x0, 100
end

.layer layer_45DF
instr FONT01_INSTR_DINO_ROAR
portamento 0x81, 30, 255
notedv PITCH_BF3, 0x2E, 100
end

.channel enemy_redead_hurt
instr FONT01_INSTR_GORON_YAWN
ldlayer 0, layer_45F5
ldlayer 1, layer_45F7
ldlayer 2, layer_4829
end

.layer layer_45F5
ldelay 0x18

.layer layer_45F7
portamento 0x81, 34, 255
notedv PITCH_E2, 0x44, 100
end

.channel enemy_redead_die
instr FONT01_INSTR_GORON_YAWN
ldlayer 0, layer_460B
ldlayer 1, layer_460D
ldlayer 2, layer_4829
end

.layer layer_460B
ldelay 0x18

.layer layer_460D
legato
portamento 0x85, 30, 255
notedv PITCH_F3, 0x1E, 100
notedv PITCH_EF2, 0x84, 100
end

.channel enemy_poe_laugh
instr FONT01_INSTR_PHANTOM_LAUGH_1
gain 20
ldlayer 0, layer_4625
ldlayer 1, layer_4627
end

.layer layer_4625
ldelay 0x16

.layer layer_4627
notedv PITCH_BF5, 0x62, 100
end

.channel enemy_poe_sister_attack
instr FONT01_INSTR_GUNSHOT
envelope envelope_686C
ldlayer 0, layer_4634
end

.layer layer_4634
portamento 0x81, 33, 200
notedv PITCH_GF4, 0x22, 100
end

.channel enemy_redead_attack
ldlayer 0, layer_4643
ldlayer 1, layer_4651
end

.layer layer_4643
instr FONT01_INSTR_GORON_YAWN
envelope envelope_68EC, 250
portamento 0x81, 30, 255
notedv PITCH_B2, 0x30, 100
end

.layer layer_4651
instr FONT01_INSTR_SMASH
envelope envelope_692C, 250
portamento 0x81, 17, 50
notedv PITCH_D1, 0x1E, 100
end

.channel enemy_poe_sister_laugh
instr FONT01_INSTR_PHANTOM_LAUGH_1
ldlayer 0, layer_466B
ldlayer 1, layer_466D
ldlayer 2, layer_466F
end

.layer layer_466B
ldelay 0x16

.layer layer_466D
ldelay 0x16

.layer layer_466F
notedv PITCH_GF5, 0x72, 100
end

.channel enemy_poe_sister_cry
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_4679
end

.layer layer_4679
portamento 0x81, 53, 120
notedv PITCH_G4, 0x44, 100
end

.channel enemy_boss_morpha_rise
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_468B
vibfreq 20
vibdepth 36
end

.layer layer_468B
envelope envelope_6A4C, 220
.layer layer_468F
notedv PITCH_A1, 0xFA, 100
rjump layer_468F

.channel enemy_boss_morpha_attack
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_469F
vibfreq 127
vibdepth 84
end

.layer layer_469F
envelope envelope_6A2C, 220
portamento 0x81, 12, 120
.layer layer_46A7
notedv PITCH_A3, 0xD0, 100
rjump layer_46A7

.channel enemy_boss_morpha_toss
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_46B7
vibfreq 20
vibdepth 36
end

.layer layer_46B7
envelope envelope_69BC, 235
legato
portamento 0x85, 0, 255
notedv PITCH_A2, 0x2A, 100
notedv PITCH_A0, 0x52, 100
end

.channel enemy_boss_morpha_grab
instr FONT01_INSTR_PHANTOM_MOAN
ldlayer 0, layer_46CF
gain 16
end

.layer layer_46CF
portamento 0x81, 30, 255
notedv PITCH_C3, 0x72, 100
end

.channel enemy_octorok_death_gasp
instr FONT01_INSTR_LIZALFOS
envelope envelope_68FC
ldlayer 0, layer_46E0
end

.layer layer_46E0
portamento 0x81, 17, 255
notedv PITCH_BF2, 0x8, 100
portamento 0x81, 26, 255
notedv PITCH_EF1, 0xC, 100
end

.channel enemy_octorok_die
instr FONT01_INSTR_LIZALFOS
ldlayer 0, layer_46FC
ldlayer 1, layer_4829
vibfreq 100
vibdepth 100
end

.layer layer_46FC
portamento 0x81, 38, 255
notedv PITCH_G3, 0x84, 100
end

.channel enemy_boss_morpha_demo_move
instr FONT01_INSTR_WATER_BUBBLES
ldlayer 0, layer_470D
panweight 0
end

.layer layer_470D
legato
portamento 0x85, 23, 255
.layer layer_4712
notedv PITCH_F2, 0x2C, 100
notedv PITCH_AF2, 0x2C, 100
rjump layer_4712

.channel enemy_boss_morpha_demo_bubble
instr FONT01_INSTR_WATER_BUBBLES
envelope envelope_6A1C
ldlayer 0, layer_472A
ldlayer 1, layer_472C
panweight 0
gain 20
end

.layer layer_472A
ldelay 0x8

.layer layer_472C
portamento 0x81, 31, 255
notedv PITCH_DF3, 0x74, 100
end

.channel enemy_boss_morpha_caught
ldlayer 0, layer_473B
ldlayer 1, layer_4742
end

.layer layer_473B
instr FONT01_INSTR_WATER_SPLASH_L
notedv PITCH_D4, 0x86, 100
end

.layer layer_4742
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x81, 36, 100
notedv PITCH_B4, 0x10, 80
portamento 0x81, 41, 255
notedv PITCH_D3, 0x6, 80
end

.channel enemy_boss_morpha_die
ldlayer 0, layer_4781
ldlayer 1, layer_479D
vibdepth 144
vibfreq 196
ldi 56
stio 6
.channel chan_4761
ldio 6
stseq 0, layer_4788+1
stseq 0, layer_478B+1
stseq 0, layer_4794+1
stseq 0, layer_4797+1
sub 1
stio 6
sub 4
rbeqz chan_4780
ldi 6
call delay_varyingvol
rjump chan_4761
.channel chan_4780
end

.layer layer_4781
instr FONT01_INSTR_DINO_ROAR
.layer layer_4783
legato
portamento 0x85, 37, 255
.layer layer_4788
notedv PITCH_EF4, 0x1E, 100
.layer layer_478B
notedv PITCH_G3, 0x1E, 100
nolegato
legato
portamento 0x85, 34, 255
.layer layer_4794
notedv PITCH_BF4, 0x1E, 100
.layer layer_4797
notedv PITCH_BF3, 0x1E, 100
nolegato
rjump layer_4783

.layer layer_479D
instr FONT01_INSTR_GORON_YAWN
portamento 0x85, 35, 255
notedv PITCH_DF4, 0xE8, 100
end

.channel enemy_boss_morpha_water_spin
instr FONT01_INSTR_WATER_BUBBLES
ldlayer 0, layer_47AE
end

.layer layer_47AE
legato
portamento 0x85, 25, 128
.layer layer_47B3
notedv PITCH_EF5, 0xC, 100
notedv PITCH_BF2, 0xC, 100
rjump layer_47B3

.channel enemy_boss_morpha_water_move
instr FONT01_INSTR_WATER_BUBBLES
envelope envelope_699C
ldlayer 0, layer_47C9
ldlayer 1, layer_47CB
gain 20
end

.layer layer_47C9
ldelay 0x8

.layer layer_47CB
portamento 0x81, 31, 255
notedv PITCH_B2, 0x60, 100
end

.channel enemy_deadhand_bite
ldlayer 0, layer_47DC
ldlayer 1, layer_47E2
gain 22
end

.layer layer_47DC
instr FONT01_INSTR_PHANTOM_GROWL
notedv PITCH_C4, 0x56, 100
end

.layer layer_47E2
instr FONT01_INSTR_EGG_CRACK
portamento 0x81, 11, 200
notedv PITCH_C2, 0x29, 100
end

.channel enemy_deadhand_move
ldlayer 0, layer_47F2
gain 22
end

.layer layer_47F2
instr FONT01_INSTR_EGG_CRACK
portamento 0x81, 9, 200
notedv PITCH_BF1, 0x29, 100
end

.channel enemy_goron_wake
ldlayer 0, layer_4800
end

.layer layer_4800
instr FONT01_INSTR_GORON
notedv PITCH_GF3, 0x20, 100
end

.channel enemy_goron_sit
ldlayer 0, layer_480A
end

.layer layer_480A
instr FONT01_INSTR_GORON
transpose 48
notedv PITCH_BF3, 0x84, 100
end

.channel enemy_deadhand_grabbed
gain 16
ldlayer 0, layer_481C
ldlayer 1, layer_5095
end

.layer layer_481C
instr FONT01_INSTR_PHANTOM_GROWL
portamento 0x81, 35, 255
notedv PITCH_E3, 0x30, 100
end

.channel enemy_boss_ganondorf_struck
ldlayer 0, layer_4829
# @bug missing end. This bug turns out to be harmless in practice.

.layer layer_4829
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_ENEMY_HURT, 0x0, 100
end

.channel chan_unused_482F
ldlayer 0, layer_4833
end

.layer layer_4833
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_GANONDORF_LAUGH_0, 0x0, 100
end

.channel enemy_big_octo_paralyzed
ldlayer 0, layer_4846
ldlayer 1, layer_4850
gain 16
vibfreq 100
vibdepth 100
end

.layer layer_4846
instr FONT01_INSTR_LIZALFOS
portamento 0x81, 15, 255
notedv PITCH_AF1, 0x54, 100
end

.layer layer_4850
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 24, 100
notedv PITCH_D3, 0x1E, 100
notedv PITCH_A2, 0x2E, 100
end

.channel enemy_big_octo_walk
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_4870
.channel chan_4863
rand 4
stseq 96, layer_4870
ldi 18
call delay_varyingvol
rjump chan_4863

.layer layer_4870
notedv PITCH_F3, 0x12, 100
rjump layer_4870

.channel enemy_big_octo_grunt
instr FONT01_INSTR_GORON
ldlayer 0, layer_487F
gain 18
releaserate 249
end

.layer layer_487F
notedv PITCH_DF3, 0x8, 100
notedv PITCH_BF2, 0x1E, 100
end

.channel enemy_big_octo_hurt
ldlayer 0, layer_4896
ldlayer 1, layer_48A4
ldlayer 2, layer_4829
gain 16
vibfreq 100
vibdepth 100
end

.layer layer_4896
instr FONT01_INSTR_LIZALFOS
legato
portamento 0x85, 25, 255
notedv PITCH_DF3, 0x18, 100
notedv PITCH_GF1, 0x1C, 100
end

.layer layer_48A4
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 30, 100
notedv PITCH_AF3, 0xC, 100
notedv PITCH_EF3, 0x12, 100
end

.channel enemy_big_octo_stop
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_48B8
end

.layer layer_48B8
portamento 0x81, 47, 100
notedv PITCH_DF4, 0x12, 100
portamento 0x81, 47, 100
notedv PITCH_DF4, 0x12, 100
portamento 0x81, 47, 100
notedv PITCH_DF4, 0x12, 100
portamento 0x81, 47, 100
notedv PITCH_DF4, 0x50, 100
end

.channel enemy_big_octo_die
ldlayer 0, layer_48E5
ldlayer 1, layer_48A4
ldlayer 2, layer_4829
gain 16
vibfreq 100
vibdepth 100
end

.layer layer_48E5
instr FONT01_INSTR_LIZALFOS
portamento 0x85, 27, 255
notedv PITCH_AF3, 0x18, 100
notedv PITCH_AF1, 0x66, 100
end

.channel enemy_big_octo_die2
ldlayer 0, layer_48FC
gain 18
vibfreq 100
vibdepth 100
end

.layer layer_48FC
instr FONT01_INSTR_PHANTOM_WAIL
portamento 0x85, 42, 100
notedv PITCH_EF3, 0x70, 100
end

.channel enemy_boss_gohma_paralyzed
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_4913
ldlayer 1, layer_4920
vibfreq 84
vibdepth 100
end

.layer layer_4913
notedv PITCH_AF3, 0x110, 100
envelope envelope_68AC, 240
ldelay 0x88
rjump layer_4913

.layer layer_4920
envelope envelope_68AC, 240
ldelay 0xCC
rjump layer_4913

.channel enemy_final_hit
instr FONT01_INSTR_ELECTRIC_ATTACK
ldlayer 0, layer_4931
gain 20
end

.layer layer_4931
transpose 6
portamento 0x81, 48, 54
notedv PITCH_BF5, 0x2C, 100
end

.channel enemy_boss_morpha_die_cry
ldlayer 0, layer_4959
ldlayer 1, layer_4949
ldlayer 2, layer_494B
vibfreq 20
vibdepth 50
end

.layer layer_4949
transpose 1

.layer layer_494B
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 39, 20
notedv PITCH_E4, 0x10, 100
notedv PITCH_B3, 0x56, 100
end

.layer layer_4959
instr FONT01_INSTR_DINO_ROAR
portamento 0x85, 38, 255
notedv PITCH_E4, 0x14, 80
notedv PITCH_B2, 0x56, 80
end

.channel enemy_shop_scrub_cry
ldlayer 0, layer_496A
end

.layer layer_496A
instr FONT01_INSTR_SCRUB_DEATH
portamento 0x81, 43, 255
notedv PITCH_EF5, 0x8, 80
portamento 0x81, 52, 255
notedv PITCH_AF4, 0x8, 80
end

.channel enemy_skullwall_rotate
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_4984
ldlayer 1, layer_498C
end

.layer layer_4984
portamento 0x81, 31, 100
notedv PITCH_C3, 0x32, 64
end

.layer layer_498C
ldelay 0x5
portamento 0x81, 33, 100
notedv PITCH_D3, 0x32, 64
end

.channel enemy_skullwall_dash
instr FONT01_INSTR_GRASS_RUSTLE
ldlayer 0, layer_499F
ldlayer 1, layer_49A7
end

.layer layer_499F
portamento 0x81, 27, 100
notedv PITCH_E3, 0x32, 64
end

.layer layer_49A7
ldelay 0x5
portamento 0x81, 29, 100
notedv PITCH_GF3, 0x32, 64
end

.channel enemy_boss_twinrova_appear
instr FONT01_INSTR_GANONDORF_CHARGE
envelope envelope_699C
ldlayer 0, layer_49C0
gain 18
vibfreq 128
vibdepth 52
end

.layer layer_49C0
portamento 0x81, 31, 255
notedv PITCH_B2, 0x64, 100
end

.channel enemy_boss_twinrova_transform
ldlayer 0, layer_49D5
ldlayer 1, layer_49DB
gain 20
vibfreq 240
vibdepth 240
end

.layer layer_49D5
instr FONT01_INSTR_GUNSHOT
notedv PITCH_D3, 0x64, 100
end

.layer layer_49DB
instr FONT01_INSTR_DINO_INHALE
portamento 0x81, 7, 255
notedv PITCH_BF3, 0xE6, 84
end

.channel enemy_boss_twinrova_fire_charge
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_49F0
vibfreq 127
vibdepth 84
end

.layer layer_49F0
legato
portamento 0x85, 15, 120
notedv PITCH_C4, 0xC8, 100
.layer layer_49F9
notedv PITCH_C4, 30000, 100
rjump layer_49F9

.channel enemy_boss_twinrova_fire_hit
ldlayer 0, layer_4A09
ldlayer 1, layer_4A0B
ldlayer 2, layer_4A17
end

.layer layer_4A09
transpose -12

.layer layer_4A0B
instr 2
envelope envelope_6A7C, 200
.layer layer_4A11
notedv PITCH_G3, 30000, 100
rjump layer_4A11

.layer layer_4A17
instr FONT01_INSTR_THUNDERBURST
envelope envelope_6A5C, 200
notedv PITCH_GF2, 0x180, 100
end

.channel enemy_boss_twinrova_ice_beam
instr FONT01_INSTR_WIND
ldlayer 0, layer_4A28
end

.layer layer_4A28
legato
portamento 0x85, 10, 102
transpose 10
notedv PITCH_F5, 0x28, 100
transpose 0
.layer layer_4A34
notedv PITCH_F5, 0x64, 100
rjump layer_4A34

.channel enemy_boss_twinrova_fire_reflected
ldlayer 0, layer_4A44
ldlayer 1, layer_4B32
vibfreq 128
vibdepth 96
end

.layer layer_4A44
instr FONT01_INSTR_WIND
transpose 12
legato
rjump layer_4A34
end

.channel enemy_boss_twinrova_ice_charge
instr FONT01_INSTR_WIND
ldlayer 0, layer_4A56
vibfreq 127
vibdepth 84
end

.layer layer_4A56
legato
portamento 0x85, 35, 120
notedv PITCH_AF5, 0xC8, 100
.layer layer_4A5F
notedv PITCH_AF5, 30000, 100
rjump layer_4A5F

.channel enemy_ganondorf_charge_major
instr FONT01_INSTR_WIND
ldlayer 0, layer_4A94
ldlayer 1, layer_4A96
ldlayer 2, layer_4A9E
vibfreq 175
vibdepth 196
ldi 36
stio 6
ldi 191
call delay_varyingvol
.channel chan_4A7C
ldio 6
stseq 0, layer_4AAA+1
stseq 0, layer_4AAD+1
sub 1
stio 6
sub 4
rbeqz chan_4A93
ldi 8
call delay_varyingvol
rjump chan_4A7C
.channel chan_4A93
end

.layer layer_4A94
instr FONT01_INSTR_DINO_INHALE

.layer layer_4A96
envelope envelope_68B4, 249
transpose -4
rjump layer_4A56

.layer layer_4A9E
instr FONT01_INSTR_DODONGO_ROAR
ldelay 0x120
loop 10
legato
portamento 0x85, 27, 255
.layer layer_4AAA
notedv PITCH_F3, 0x1E, 100
.layer layer_4AAD
notedv PITCH_A2, 0x1E, 100
nolegato
loopend
end

.channel enemy_boss_twinrova_cast
instr 2
ldlayer 0, layer_4ABF
gain 20
vibfreq 144
vibdepth 240
end

.layer layer_4ABF
notedv PITCH_AF2, 0x30, 100
end

.channel enemy_darunia_chest_pound
instr FONT01_INSTR_SMASH
ldlayer 0, layer_4AC9
end

.layer layer_4AC9
envelope envelope_68DC, 250
.layer layer_4ACD
portamento 0x81, 26, 64
notedv PITCH_E2, 0xC, 100
rjump layer_4ACD

.channel enemy_darunia_head_pat
instr FONT01_INSTR_SMASH
envelope envelope_692C
ldlayer 0, layer_4ADF
end

.layer layer_4ADF
portamento 0x81, 32, 130
notedv PITCH_GF2, 0x1E, 100
end

.channel enemy_boss_twinrova_hurt_cry_old
ldlayer 0, layer_4261
ldlayer 1, layer_4AEE
end

.layer layer_4AEE
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_WITCH_HURT, 0x0, 100
end

.channel enemy_boss_twinrova_hit_beam_young
ldlayer 0, layer_4261
ldlayer 1, layer_4AFB
end

.layer layer_4AFB
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_WITCH_SHOCK, 0x0, 100
end

.channel enemy_boss_twinrova_die_young
ldlayer 0, layer_4B0B
ldlayer 1, layer_4B12
ldlayer 2, layer_4829
end

.layer layer_4B0B
instr FONT01_INSTR_THUNDERBURST
notedv PITCH_AF4, 0x110, 100
end

.layer layer_4B12
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_TWINROVA_SCREAM, 0x0, 100
end

.channel enemy_boss_twinrova_spirit_fly
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_4B22
vibfreq 112
vibdepth 128
end

.layer layer_4B22
envelope envelope_69DC, 240
legato
portamento 0x85, 3, 255
notedv PITCH_F2, 0x1A, 100
notedv PITCH_A0, 0x20, 100
end

.layer layer_4B32
instr FONTANY_INSTR_8PULSE
envelope envelope_6A7C, 249
.layer layer_4B38
notedv PITCH_GF3, 30000, 100
rjump layer_4B38

.channel enemy_boss_twinrova_charge
ldlayer 0, layer_521B
ldlayer 1, layer_5219
vibfreq 96
vibdepth 240
end

.channel enemy_knuckle_walk
ldlayer 0, layer_4B59
ldlayer 1, layer_4B50
end

.layer layer_4B50
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_BF1, 0x8, 64
notedv PITCH_G2, 0x14, 64
end

.layer layer_4B59
instr FONT01_INSTR_GUNSHOT
envelope envelope_68DC, 249
portamento 0x81, 26, 96
notedv PITCH_DF2, 0x1E, 100
end

.channel enemy_knuckle_attack
ldlayer 0, layer_4B71
ldlayer 1, layer_4B7B
ldlayer 2, layer_4B87
end

.layer layer_4B71
instr FONT01_INSTR_GERUDO_ATTACK
portamento 0x81, 27, 255
notedv PITCH_A2, 0x78, 100
end

.layer layer_4B7B
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_BF1, 0x4, 64
notedv PITCH_G2, 0x6, 64
notedv PITCH_DF3, 0x14, 64
end

.layer layer_4B87
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_KNUCKLE_ATTACK, 0x0, 100
end

.channel enemy_bubble_die
ldlayer 0, layer_4B9B
ldlayer 2, layer_4BA9
.channel chan_4B93
ldlayer 1, layer_4829
vibfreq 128
vibdepth 48
end

.layer layer_4B9B
instr FONT01_INSTR_PHANTOM_MOAN
legato
portamento 0x85, 46, 200
notedv PITCH_C5, 0x20, 100
notedv PITCH_E4, 0x6C, 100
end

.layer layer_4BA9
instr FONT01_INSTR_POT_BREAK
notedv PITCH_G3, 0x5, 100
notedv PITCH_G3, 0x5, 100
end

.channel enemy_bubble_hurt
ldlayer 0, layer_4BB7
rjump chan_4B93

.layer layer_4BB7
transpose 5
rjump layer_4B9B
end

.channel enemy_bubble_attack
ldlayer 0, layer_4BC0
end

.layer layer_4BC0
instr FONT01_INSTR_STALFOS_ATTACK
legato
portamento 0x85, 30, 30
notedv PITCH_AF4, 0x8, 100
notedv PITCH_GF4, 0x12, 100
end

.channel enemy_poe_sister_die
ldlayer 3, layer_4829
.channel chan_4BD1
ldlayer 0, layer_4BDB
ldlayer 1, layer_4BDD
ldlayer 2, layer_4BF3
end

.layer layer_4BDB
ldelay 0x8

.layer layer_4BDD
instr FONT01_INSTR_PHANTOM_LAUGH_1
transpose 12
portamento 0x81, 48, 100
notedv PITCH_E5, 0x1E, 100
portamento 0x85, 51, 100
notedv PITCH_F5, 0x14, 100
notedv PITCH_B4, 0x1E, 100
end

.layer layer_4BF3
instr FONT01_INSTR_PHANTOM_GROWL
legato
transpose 48
portamento 0x85, 47, 200
notedv PITCH_D5, 0x20, 100
notedv PITCH_B2, 0x64, 100
end

.channel enemy_big_poe_get_soul
rjump chan_4BD1

.channel enemy_knuckle_clank
ldlayer 0, layer_4B7B
end

.channel enemy_bari_spin
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_4C0F
end

.layer layer_4C0F
legato
portamento 0x85, 19, 200
notedv PITCH_EF2, 0x18, 100
notedv PITCH_B2, 0x3C, 100
end

.channel enemy_larvae_paralyzed
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_4C25
vibfreq 196
vibdepth 196
end

.layer layer_4C25
portamento 0x81, 62, 255
notedv PITCH_EF3, 0x40, 100
end

.channel enemy_bari_die
ldlayer 0, layer_4C34
ldlayer 1, layer_4829
end

.layer layer_4C34
instr FONT01_INSTR_GUAY_HURT
.layer layer_4C36
portamento 0x81, 32, 255
notedv PITCH_C4, 0xA, 100
portamento 0x81, 34, 255
notedv PITCH_D4, 0xA, 100
portamento 0x81, 36, 255
notedv PITCH_E4, 0xA, 100
portamento 0x81, 45, 255
notedv PITCH_A3, 0xE, 100
end

.channel enemy_bari_split
ldlayer 0, layer_4C57
end

.layer layer_4C57
instr FONT01_INSTR_GULP_SPEAR
transpose 4
rjump layer_4C36

.channel enemy_floormaster_attack
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_4C6A
envelope envelope_699C
vibfreq 112
vibdepth 96
end

.layer layer_4C6A
notedv PITCH_E2, 0x64, 100
end

.channel enemy_floormaster_mini_walk
instr FONT01_INSTR_EGG_CRACK
ldlayer 0, layer_4C74
end

.layer layer_4C74
portamento 0x81, 21, 128
notedv PITCH_A2, 0x8, 100
end

.channel enemy_floormaster_mini_die
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_4C89
ldlayer 1, layer_4829
vibfreq 132
vibdepth 70
end

.layer layer_4C89
legato
portamento 0x85, 56, 128
notedv PITCH_BF5, 0x14, 100
notedv PITCH_D5, 0x2C, 100
end

.channel enemy_floormaster_mini_grow
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_4CA2
envelope envelope_69DC
vibfreq 62
vibdepth 96
end

.layer layer_4CA2
notedv PITCH_AF3, 0x3C, 80
rjump layer_4CA2

.channel enemy_floormaster_grow_done
ldlayer 0, layer_4CAB
end

.layer layer_4CAB
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_694C, 249
legato
portamento 0x85, 7, 150
notedv PITCH_DF1, 0xA, 100
notedv PITCH_DF2, 0x16, 100
end

.channel enemy_floormaster_split
ldlayer 0, layer_4CC1
end

.layer layer_4CC1
transpose 12
rjump layer_4CAB
end

.channel enemy_floormaster_mini_grab
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_4CD3
envelope envelope_69FC
vibfreq 80
vibdepth 64
end

.layer layer_4CD3
legato
portamento 0x85, 6, 255
notedv PITCH_EF3, 0x2A, 69
notedv PITCH_G2, 0x40, 69
rjump layer_4CD3

.channel enemy_floormaster_mini_land
instr FONT01_INSTR_SMASH
ldlayer 0, layer_4CE6
end

.layer layer_4CE6
legato
envelope envelope_68FC, 255
portamento 0x85, 25, 230
notedv PITCH_EF3, 0x5, 80
notedv PITCH_BF2, 0x5, 80
nolegato
ldelay 0x5
legato
envelope envelope_68FC, 255
portamento 0x85, 25, 220
notedv PITCH_EF3, 0x5, 80
notedv PITCH_BF2, 0xA, 80
end

.channel enemy_cucco_flap
instr FONT01_INSTR_OWL_FLAP
ldlayer 0, layer_4D0E
end

.layer layer_4D0E
portamento 0x81, 35, 200
notedv PITCH_B3, 0x20, 100
end

.channel enemy_ganondorf_magic_fire
ldlayer 0, layer_4D23
ldlayer 1, layer_4A09
ldlayer 2, layer_4A0B
ldlayer 3, layer_4A17
end

.layer layer_4D23
ldelay 0x7F
end

.channel enemy_floormaster_slide
instr FONT01_INSTR_SLIDE_BOOTS
ldlayer 0, layer_4D2C
end

.layer layer_4D2C
transpose 48
.layer layer_4D2E
notedv PITCH_C4, 30000, 100
rjump layer_4D2E

.channel enemy_knuckle_armor_rebound2
ldlayer 0, layer_4D4D
ldlayer 1, layer_4D3B
end

.layer layer_4D3B
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_GF1, 0x40, 100
notedv PITCH_GF1, 0x14, 100
notedv PITCH_GF1, 0x10, 84
notedv PITCH_GF1, 0xA, 68
notedv PITCH_GF1, 0xA, 68
end

.layer layer_4D4D
transpose -8
ldelay 0x4
rjump layer_4D3B

.channel enemy_knuckle_armor_rebound3
ldlayer 0, layer_4D3B
end

.channel enemy_knuckle_armor_rebound1
ldlayer 0, layer_4D70
ldlayer 1, layer_4D5E
end

.layer layer_4D5E
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_GF1, 0x8, 100
notedv PITCH_GF1, 0x40, 100
notedv PITCH_GF1, 0x20, 100
notedv PITCH_GF1, 0x30, 84
notedv PITCH_GF1, 0x40, 68
end

.layer layer_4D70
transpose -8
rjump layer_4D5E

.channel enemy_knuckle_stagger
ldlayer 0, layer_4D87
ldlayer 1, layer_4D7B
end

.layer layer_4D7B
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_EF1, 0x6, 100
notedv PITCH_GF1, 0xE, 100
notedv PITCH_C2, 0x10, 100
end

.layer layer_4D87
transpose -5
rjump layer_4D7B

.channel enemy_knucle_armor_loss
ldlayer 0, layer_4D9C
ldlayer 1, layer_4D92
end

.layer layer_4D92
instr FONT01_INSTR_POT_BREAK
portamento 0x81, 8, 200
notedv PITCH_BF1, 0x20, 100
end

.layer layer_4D9C
instr FONT01_INSTR_SLIDE_BOOTS
ldelay 0xE
notedv PITCH_EF1, 0x14, 64
end

.channel enemy_knuckle_warcry
ldlayer 0, layer_4DAB
ldlayer 1, layer_4DBB
end

.layer layer_4DAB
instr FONT01_INSTR_SLIDE_BOOTS
envelope envelope_695C, 249
loop 5
notedv PITCH_C2, 0xA, 100
notedv PITCH_G1, 0x8, 100
loopend
end

.layer layer_4DBB
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_KNUCKLE_CHARGE, 0x0, 100
end

.channel enemy_knuckle_snap
ldlayer 0, layer_4DC7
gain 32
end

.layer layer_4DC7
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_SNAP, 0x0, 100
end

.channel enemy_boss_barinade_pulse
instr FONT01_INSTR_BOULDER
ldlayer 0, layer_4DDA
ldlayer 1, layer_4DDC
vibfreq 40
vibdepth 96
end

.layer layer_4DDA
transpose 6

.layer layer_4DDC
notedv PITCH_A4, 30000, 100
rjump layer_4DDC

.channel enemy_boss_barinade_hurt
ldlayer 0, layer_4E03
ldlayer 1, layer_4DF3
ldlayer 2, layer_4DF5
ldlayer 3, layer_4829
vibfreq 116
vibdepth 210
end

.layer layer_4DF3
transpose 12

.layer layer_4DF5
instr FONT01_INSTR_DINO_ROAR
.layer layer_4DF7
portamento 0x85, 32, 255
notedv PITCH_C4, 0x20, 80
notedv PITCH_B2, 0x90, 80
end

.layer layer_4E03
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x81, 37, 100
notedv PITCH_GF2, 0xB0, 100
end

.channel enemy_tentacle_die
ldlayer 0, layer_4E1F
ldlayer 1, layer_4DF5
ldlayer 2, layer_4E77
ldlayer 3, layer_4829
vibfreq 80
vibdepth 48
end

.layer layer_4E1F
transpose 4
rjump layer_4E03

.channel enemy_boss_barinade_weak_hurt
ldlayer 0, layer_4E3A
ldlayer 1, layer_4E34
ldlayer 2, layer_4E36
ldlayer 3, layer_4829
vibfreq 164
vibdepth 162
end

.layer layer_4E34
transpose 4

.layer layer_4E36
instr FONT01_INSTR_DODONGO_ROAR
rjump layer_4DF7

.layer layer_4E3A
transpose 2
rjump layer_4E03

.channel enemy_boss_barinade_die
ldlayer 0, layer_4E47
ldlayer 1, layer_4E45
end

.layer layer_4E45
transpose 6

.layer layer_4E47
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_694C, 249
legato
portamento 0x85, 19, 150
notedv PITCH_C1, 0xA, 100
notedv PITCH_B2, 0x14, 100
end

.channel enemy_boss_twinrova_hurt
ldlayer 0, layer_4E75
ldlayer 1, layer_4E77
ldlayer 2, layer_4E66
ldlayer 3, layer_4E68
end

.layer layer_4E66
transpose 2

.layer layer_4E68
instr FONT01_INSTR_EXPLOSION_LAVA
portamento 0x85, 34, 255
notedv PITCH_F4, 0x14, 100
notedv PITCH_B2, 0x7F, 100
end

.layer layer_4E75
transpose -2

.layer layer_4E77
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 39, 64
notedv PITCH_F4, 0x12, 100
notedv PITCH_A3, 0xA8, 100
end

.channel enemy_boss_barinade_tentacle_break
ldlayer 0, layer_4E66
ldlayer 1, layer_4E68
end

.channel enemy_boss_barinade_bari_attach
ldlayer 0, layer_4E94
ldlayer 1, layer_4E9E
end

.layer layer_4E94
instr FONT01_INSTR_BABA_LUNGE
portamento 0x81, 35, 50
notedv PITCH_AF2, 0x30, 100
end

.layer layer_4E9E
instr FONT01_INSTR_GANONDORF_ATTACK_0
portamento 0x81, 39, 50
notedv PITCH_DF3, 0x40, 100
end

.channel enemy_boss_barinade_beam
instr FONT01_INSTR_THUNDERBURST
ldlayer 0, layer_4EB7
ldlayer 1, layer_4EB5
vibfreq 196
vibdepth 48
end

.layer layer_4EB5
transpose 8

.layer layer_4EB7
notedv PITCH_A3, 0x1A2, 100
end

.channel enemy_deadhand_grab
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_4EC6
vibfreq 128
vibdepth 160
end

.layer layer_4EC6
portamento 0x81, 22, 255
notedv PITCH_DF2, 0x7F, 100
end

.channel enemy_tentacle_wind_up
instr FONT01_INSTR_GERUDO_ATTACK
ldlayer 0, layer_4ED8
vibfreq 128
vibdepth 160
end

.layer layer_4ED8
portamento 0x81, 16, 255
notedv PITCH_G2, 0x7F, 100
end

.channel enemy_shabom_pop
ldlayer 0, layer_4EF4
ldlayer 1, layer_4EEA
ldlayer 2, layer_4EF9
end

.layer layer_4EEA
instr FONT01_INSTR_GUNSHOT
portamento 0x81, 54, 100
notedv PITCH_B5, 0x60, 100
end

.layer layer_4EF4
ldelay 0x2
rjump layer_4EEA
end

.layer layer_4EF9
instr FONT01_INSTR_STEP_WATER
portamento 0x81, 27, 255
notedv PITCH_F3, 0x14, 100
end

.channel enemy_shabom_bounce
instr FONT01_INSTR_WATER_BUBBLES
ldlayer 0, layer_4F0C
envelope envelope_692C
end

.layer layer_4F0C
portamento 0x85, 39, 100
notedv PITCH_A3, 0x16, 100
notedv PITCH_B4, 0x16, 100
end

.channel enemy_stinger_submerge
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_4F20
envelope envelope_68CC
end

.layer layer_4F20
portamento 0x81, 27, 100
notedv PITCH_F3, 0x34, 100
end

.channel enemy_stinger_glide
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_4F32
vibfreq 80
vibdepth 96
end

.layer layer_4F32
envelope envelope_6A2C, 230
.layer layer_4F36
notedv PITCH_E2, 0xD0, 80
rjump layer_4F36

.channel enemy_stinger_attack
ldlayer 0, layer_4F44
vibfreq 240
vibdepth 160
end

.layer layer_4F44
instr FONT01_INSTR_GUAY_HURT
portamento 0x81, 52, 255
notedv PITCH_GF5, 0x40, 100
end

.channel enemy_stinger_cry
ldlayer 0, layer_4F55
ldlayer 1, layer_4F57
end

.layer layer_4F55
ldelay 0x6

.layer layer_4F57
instr FONT01_INSTR_GUAY_HURT
notedv PITCH_GF5, 0x64, 100
end

.channel enemy_boss_bongo_drum_low
instr FONT01_INSTR_BONGO_BONGO
ldlayer 0, layer_4F6A
ldlayer 1, layer_4F68
gain 24
end

.layer layer_4F68
transpose 2

.layer layer_4F6A
notedv PITCH_C4, 0x40, 100
end

.channel enemy_boss_bongo_drum_high
instr FONT01_INSTR_BONGO_BONGO
ldlayer 0, layer_4F7B
ldlayer 1, layer_4F79
gain 24
end

.layer layer_4F79
transpose 2

.layer layer_4F7B
notedv PITCH_F4, 0x40, 100
end

.channel enemy_owl_fly
instr FONT01_INSTR_OWL_FLAP
ldlayer 0, layer_4F8A
ldlayer 1, layer_4F88
end

.layer layer_4F88
transpose 2

.layer layer_4F8A
portamento 0x81, 23, 200
notedv PITCH_B2, 0x2C, 100
end

.channel enemy_peahat_fly
instr FONT01_INSTR_SWOOSH
ldlayer 0, layer_4F98
end

.layer layer_4F98
notedv PITCH_E5, 0x6, 100
notedv PITCH_GF5, 0x6, 100
notedv PITCH_AF5, 0x6, 100
notedv PITCH_A5, 0x6, 100
notedv PITCH_AF5, 0x6, 100
notedv PITCH_GF5, 0x6, 100
notedv PITCH_E5, 0x6, 100
rjump layer_4F98

.channel enemy_peahat_land
instr FONT01_INSTR_SMASH
ldlayer 0, layer_361B
end

.channel enemy_peahat_rise
instr FONT01_INSTR_SMASH
ldlayer 0, layer_4FBB
end

.layer layer_4FBB
portamento 0x81, 15, 104
notedv PITCH_B3, 0x40, 100
end

.channel enemy_peahat_hurt
ldlayer 0, layer_4FDE
ldlayer 1, layer_4FD1
ldlayer 2, layer_4829
vibfreq 112
vibdepth 160
end

.layer layer_4FD1
instr FONT01_INSTR_DINO_ROAR
portamento 0x85, 40, 255
notedv PITCH_AF4, 0x20, 80
notedv PITCH_G3, 0x40, 80
end

.layer layer_4FDE
instr FONT01_INSTR_MONSTER_ROAR
portamento 0x81, 41, 100
notedv PITCH_EF3, 0x60, 100
end

.channel enemy_boss_twinrova_fly
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_4FF2
vibfreq 96
vibdepth 128
end

.layer layer_4FF2
envelope envelope_6A2C, 230
.layer layer_4FF6
notedv PITCH_GF1, 0x70, 100
rjump layer_4FF6

.channel enemy_boss_twinrova_hover
ldlayer 0, layer_5008
ldlayer 1, layer_5006
vibfreq 16
vibdepth 128
end

.layer layer_5006
transpose 2

.layer layer_5008
instr FONT01_INSTR_DODONGO_ROAR
envelope envelope_6A2C, 230
.layer layer_500E
notedv PITCH_C1, 0x70, 100
rjump layer_500E

.channel enemy_tektite_jump_water
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_5019
end

.layer layer_5019
portamento 0x81, 35, 100
notedv PITCH_DF5, 0x38, 80
end

.channel enemy_tektite_land_water2
instr FONT01_INSTR_WATER_SPLASH_L
ldlayer 0, layer_5027
end

.layer layer_5027
portamento 0x81, 49, 100
notedv PITCH_EF4, 0x38, 80
end

.channel enemy_tektite_turn_water
instr FONT01_INSTR_STEP_WATER
ldlayer 0, layer_5035
end

.layer layer_5035
portamento 0x81, 16, 100
notedv PITCH_E2, 0x30, 68
end

.channel enemy_blob_wave
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_5047
vibfreq 112
vibdepth 240
end

.layer layer_5047
transpose -19
legato
portamento 0x85, 0, 255
notedv PITCH_A2, 0x20, 100
notedv PITCH_A0, 0x20, 100
end

.channel enemy_boss_bongo_clap
ldlayer 0, layer_505C
ldlayer 1, layer_505E
end

.layer layer_505C
transpose -6

.layer layer_505E
instr FONT01_INSTR_GUNSHOT
notedv PITCH_D5, 0x30, 100
end

.channel enemy_boss_bongo_hand_wave
instr FONT01_INSTR_THUNDERBURST
ldlayer 0, layer_506E
vibfreq 128
vibdepth 224
end

.layer layer_506E
notedv PITCH_F3, 0x35, 100
end

.channel enemy_boss_bongo_hand_attack
instr FONT01_INSTR_DODONGO_ROAR
ldlayer 0, layer_5083
ldlayer 1, layer_5081
releaserate 220
vibfreq 112
vibdepth 96
end

.layer layer_5081
transpose 6

.layer layer_5083
notedv PITCH_E2, 0x90, 100
rjump layer_5083

.channel enemy_wallmaster_grab
ldlayer 0, layer_5095
ldlayer 1, layer_5093
ldlayer 2, layer_50A3
end

.layer layer_5093
transpose 2

.layer layer_5095
instr FONT01_INSTR_SMASH
envelope envelope_696C, 250
portamento 0x81, 19, 50
notedv PITCH_E1, 0x20, 100
end

.layer layer_50A3
instr FONT01_INSTR_EGG_CRACK
envelope envelope_696C, 250
portamento 0x81, 15, 50
notedv PITCH_A1, 0x20, 100
end

.channel enemy_boss_bongo_hand_shake
instr FONT01_INSTR_OWL_FLAP
ldlayer 0, layer_50B7
end

.layer layer_50B7
portamento 0x85, 21, 200
notedv PITCH_D3, 0x13, 100
notedv PITCH_GF2, 0x13, 100
end

.channel enemy_boss_bongo_hurt
ldlayer 0, layer_50D3
ldlayer 1, layer_4524
ldlayer 2, layer_4532
ldlayer 3, layer_4829
vibfreq 48
vibdepth 48
end

.layer layer_50D3
instr FONT01_INSTR_SCRUB_DEATH
legato
portamento 0x85, 4, 60
notedv PITCH_D2, 0x32, 100
notedv PITCH_AF1, 0x7F, 100
end

.channel enemy_boss_bongo_hand_hurt
ldlayer 0, layer_50D3
vibfreq 48
vibdepth 48
end

.channel enemy_boss_bongo_vanish
instr FONT01_INSTR_POE_DISAPPEAR
ldlayer 0, layer_50F8
ldlayer 1, layer_50F6
vibfreq 96
vibdepth 80
end

.layer layer_50F6
transpose 6

.layer layer_50F8
portamento 0x81, 27, 255
notedv PITCH_C2, 0x118, 100
end

.channel enemy_beamos_beam
instr FONTANY_INSTR_BELL
ldlayer 0, layer_510B
vibfreq 128
vibdepth 116
end

.layer layer_510B
notedv PITCH_F4, 30000, 64
rjump layer_510B

.channel enemy_beamos_idle
instr FONT01_INSTR_BABA_LUNGE
ldlayer 0, layer_511B
vibfreq 208
vibdepth 96
end

.layer layer_511B
notedv PITCH_F1, 30000, 64
rjump layer_511B

.channel enemy_beamos_ground_hit
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_5127
end

.layer layer_5127
notedv PITCH_DF1, 30000, 100
rjump layer_5127

.channel enemy_beamos_charging
ldlayer 0, layer_45DF
vibfreq 160
vibdepth 160
end

.channel enemy_tektite_flip
instr FONT01_INSTR_WATER_BUBBLES
ldlayer 0, layer_5142
ldlayer 1, layer_5144
vibfreq 176
vibdepth 160
end

.layer layer_5142
transpose -5

.layer layer_5144
portamento 0x85, 39, 100
notedv PITCH_E3, 0x10, 100
notedv PITCH_DF5, 0x13, 100
end

.channel enemy_torch_slug_crawl
ldlayer 0, layer_5160
ldlayer 1, layer_5156
end

.layer layer_5156
instr FONT01_INSTR_EGG_CRACK
portamento 0x81, 8, 255
notedv PITCH_C2, 0x40, 100
end

.layer layer_5160
ldelay 0x8
rjump layer_5156

.channel enemy_torch_slug_target
ldlayer 0, layer_516C
vibfreq 64
vibdepth 96
end

.layer layer_516C
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 39, 255
notedv PITCH_D4, 0x8, 100
notedv PITCH_A3, 0x20, 100
end

.channel enemy_torch_slug_die
ldlayer 0, layer_5188
ldlayer 1, layer_418B
ldlayer 2, layer_4829
vibfreq 64
vibdepth 192
end

.layer layer_5188
instr FONT01_INSTR_DINO_ROAR
legato
portamento 0x85, 25, 255
notedv PITCH_GF3, 0x14, 80
notedv PITCH_GF2, 0x60, 80
end

.channel enemy_tile_fly
instr FONT01_INSTR_SWOOSH
ldlayer 0, layer_519C
end

.layer layer_519C
loop 6
notedv PITCH_C5, 0x9, 100
notedv PITCH_D5, 0x9, 100
notedv PITCH_E5, 0x9, 100
loopend

.layer layer_51A8
envelope envelope_697C, 255
.layer layer_51AC
notedv PITCH_GF5, 0x6, 100
notedv PITCH_AF5, 0x6, 100
notedv PITCH_BF5, 0x6, 100
notedv PITCH_AF5, 0x6, 100
rjump layer_51AC

.channel enemy_firedancer_kick
instr 2
ldlayer 0, layer_51C0
end

.layer layer_51C0
notedv PITCH_A2, 0x30, 100
end

.channel enemy_firedancer_spin
ldlayer 0, layer_51CB
ldlayer 1, layer_51D9
end

.layer layer_51CB
instr FONT01_INSTR_BOULDER
.layer layer_51CD
transpose 12
envelope envelope_6A7C, 224
.layer layer_51D3
notedv PITCH_C5, 30000, 100
rjump layer_51D3

.layer layer_51D9
instr FONT01_INSTR_GANONDORF_FLY
rjump layer_51CD

.channel enemy_firehead_run
instr FONT01_INSTR_SMASH
ldlayer 0, layer_51E3
end

.layer layer_51E3
portamento 0x81, 20, 64
notedv PITCH_BF1, 0xD, 100
end

.channel enemy_firehead_hurt
ldlayer 0, layer_51F6
ldlayer 1, layer_4829
vibfreq 64
vibdepth 208
end

.layer layer_51F6
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 47, 100
notedv PITCH_F5, 0x14, 100
notedv PITCH_AF4, 0x24, 100
end

.channel enemy_firedancer_hurt
ldlayer 0, layer_4301
end

.channel enemy_firedancer_laugh
ldlayer 0, layer_521B
ldlayer 1, layer_5219
ldlayer 2, layer_5226
ldlayer 3, layer_5228
vibfreq 48
vibdepth 32
end

.layer layer_5219
transpose 2

.layer layer_521B
instr 2
portamento 0x81, 21, 255
notedv PITCH_B4, 0xE0, 100
end

.layer layer_5226
transpose 1

.layer layer_5228
instr FONT01_INSTR_PHANTOM_LAUGH_1
notedv PITCH_F4, 0xE0, 100
end

.channel enemy_moblin_club_shockwave
instr FONT01_INSTR_DINO_INHALE
ldlayer 0, layer_523A
ldlayer 1, layer_523C
releaserate 224
end

.layer layer_523A
transpose -6

.layer layer_523C
notedv PITCH_GF2, 30000, 100
rjump layer_523C

.channel enemy_peahat_jr_fly
instr FONT01_INSTR_SWOOSH
ldlayer 0, layer_524B
envelope envelope_697C
end

.layer layer_524B
notedv PITCH_GF5, 0x6, 80
notedv PITCH_AF5, 0x6, 80
notedv PITCH_BF5, 0x6, 80
notedv PITCH_AF5, 0x6, 80
rjump layer_524B

.channel enemy_boss_bongo_paralyze
ldlayer 0, layer_4524
ldlayer 1, layer_4532
vibfreq 48
vibdepth 48
end

.channel enemy_boss_bongo_die
ldlayer 0, layer_5277
ldlayer 1, layer_5275
ldlayer 2, layer_5286
ldlayer 3, layer_4829
vibfreq 70
vibdepth 86
end

.layer layer_5275
transpose 2

.layer layer_5277
instr FONT01_INSTR_MONSTER_ROAR
.layer layer_5279
legato
portamento 0x85, 27, 127
notedv PITCH_A3, 0x28, 100
notedv PITCH_E3, 0xC8, 100
end

.layer layer_5286
instr FONT01_INSTR_THUNDER_HURT
transpose 12
rjump layer_5279

.channel enemy_boss_bongo_dissipate
ldlayer 0, layer_529A
ldlayer 1, layer_52A6
ldlayer 2, layer_52A8
vibfreq 20
vibdepth 20
end

.layer layer_529A
instr FONT01_INSTR_DINO_INHALE
.layer layer_529C
envelope envelope_6A7C, 200
.layer layer_52A0
notedv PITCH_C2, 30000, 100
rjump layer_52A0

.layer layer_52A6
transpose -1

.layer layer_52A8
instr 2
rjump layer_529C

.channel enemy_boss_bongo_charge
ldlayer 0, layer_52BC
ldlayer 1, layer_52C4
ldlayer 2, layer_52BA
vibfreq 96
vibdepth 84
end

.layer layer_52BA
transpose 4

.layer layer_52BC
instr FONT01_INSTR_DINO_INHALE
.layer layer_52BE
notedv PITCH_A2, 30000, 100
rjump layer_52BE

.layer layer_52C4
instr FONT01_INSTR_BOULDER
.layer layer_52C6
notedv PITCH_A4, 30000, 80
rjump layer_52C6

.channel enemy_boss_bongo_chant
instr FONT01_INSTR_BONGO_BONGO
ldlayer 0, layer_52D2
end

.layer layer_52D2
transpose 48
notedv PITCH_BF2, 0xE0, 100
end

.channel enemy_like_like_die
ldlayer 0, layer_3FBA
ldlayer 1, layer_5188
ldlayer 2, layer_4829
vibfreq 64
vibdepth 192
end

.channel enemy_leever_die
ldlayer 0, layer_3F78
ldlayer 1, layer_400C
ldlayer 2, layer_4829
vibfreq 112
vibdepth 48
end

.channel enemy_gerudo_attack
ldlayer 0, layer_4081
ldlayer 1, layer_52FC
end

.layer layer_52FC
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_GERUDO_ATTACK, 0x0, 80
end

.channel enemy_gerudo_hurt
ldlayer 0, layer_5309
ldlayer 1, layer_4829
end

.layer layer_5309
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_GERUDO_HURT, 0x0, 100
end

.channel enemy_gerudo_defeat
ldlayer 0, layer_5316
ldlayer 1, layer_4829
end

.layer layer_5316
instr FONTANY_INSTR_SFX
notedv FONT01_EFFECT_GERUDO_DEFEAT, 0x0, 100
end

.channel enemy_wolfos_walk
ldlayer 0, layer_5320
end

.layer layer_5320
instr FONT01_INSTR_SMASH
portamento 0x81, 44, 64
notedv PITCH_GF3, 0x5, 72
end

.channel enemy_anubis_die
ldlayer 0, layer_5335
ldlayer 1, layer_533C
vibfreq 56
vibdepth 50
end

.layer layer_5335
instr 2
notedv PITCH_C3, 0xC8, 100
end

.layer layer_533C
instr FONT01_INSTR_PHANTOM_WAIL
legato
portamento 0x85, 32, 200
notedv PITCH_D4, 0x10, 100
notedv PITCH_EF3, 0x96, 100
end

.channel enemy_anubis_fire_hit
ldlayer 0, layer_534F
end

.layer layer_534F
instr FONT01_INSTR_EXPLOSION_LAVA
legato
portamento 0x85, 30, 255
notedv PITCH_B3, 0x20, 100
notedv PITCH_E2, 0x50, 100
end

.channel enemy_destroyed_light_arrow
ldlayer 0, layer_5365
vibfreq 208
vibdepth 208
end

.layer layer_5365
instr FONT01_INSTR_DINO_INHALE
legato
transpose 15
portamento 0x85, 39, 239
notedv PITCH_DF3, 0x18, 100
notedv PITCH_B5, 0x38, 100
end

.channel enemy_freezard_hurt
ldlayer 0, layer_3A9A
ldlayer 1, layer_3962
ldlayer 2, layer_4829
end

.channel enemy_freezard_die
ldlayer 0, layer_3A47
ldlayer 1, layer_3962
ldlayer 2, layer_4829
end

.channel enemy_deadhand_burrow
ldlayer 0, layer_538D
end

.layer layer_538D
instr FONT01_INSTR_EXPLOSION_LAVA
envelope envelope_68B4, 220
notedv PITCH_D4, 0x64, 100
end

.channel enemy_deadhand_laugh
instr FONT01_INSTR_PHANTOM_LAUGH_1
ldlayer 0, layer_539F
gain 16
end

.layer layer_539F
portamento 0x81, 35, 239
notedv PITCH_AF2, 0xE0, 100
end

.channel enemy_knuckle_armor_hurt
ldlayer 0, layer_53B3
ldlayer 1, layer_4829
vibfreq 224
vibdepth 96
end

.layer layer_53B3
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_A2, 0x40, 100
end

.channel enemy_knuckle_pillar_break
ldlayer 0, layer_53C0
ldlayer 1, layer_53B3
end

.layer layer_53C0
instr FONT01_INSTR_EXPLOSION_LAVA
notedv PITCH_AF3, 0x4, 100
notedv PITCH_BF3, 0x4, 100
notedv PITCH_DF4, 0x5, 100
notedv PITCH_F4, 0x7, 100
notedv PITCH_B3, 0x30, 100
end

.channel enemy_knuckle_stump_break
ldlayer 0, layer_53C0
end

.channel enemy_knuckle_axe_stuck
ldlayer 0, layer_364C
ldlayer 1, layer_53B3
end

.channel enemy_boss_ganon_attack
ldlayer 0, layer_4220
ldlayer 1, layer_53E4
end

.layer layer_53E4
instr FONT01_INSTR_ELECTRIC_ATTACK
notedv PITCH_B5, 0x5A, 70
end

.channel enemy_pot_fly
instr FONT01_INSTR_SWOOSH
ldlayer 0, layer_51A8
end

.channel enemy_ganondorf_vortex_charge
ldlayer 0, layer_5008
ldlayer 1, layer_53FB
vibfreq 48
vibdepth 240
end

.layer layer_53FB
instr FONT01_INSTR_DINO_INHALE
.layer layer_53FD
notedv PITCH_A2, 30000, 64
rjump layer_53FD

.channel enemy_boss_vocals
instr FONTANY_INSTR_SFX
ldio 4
sub 176
stseq 0, layer_5417  # set semitone = sound id - 176
ldseq addr_541C
stseq 0, layer_5417+2
ldlayer 0, layer_5417
end

.layer layer_5417
notedvg 0, 0x0, 100, 0
end

.array addr_541C
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100
byte 100

.channel enemy_ganondorf_throw_orb
ldlayer 0, layer_4220
ldlayer 1, layer_4214
end

.channel enemy_ganondorf_hit_light
ldlayer 0, layer_434A
ldlayer 1, layer_434C
end

.channel enemy_shell_open
ldlayer 0, layer_5458
ldlayer 1, layer_5460
end

.layer layer_5458
instr FONT01_INSTR_EGG_CRACK
ldelay 0x8
notedv PITCH_G2, 0x25, 100
end

.layer layer_5460
instr FONT01_INSTR_BABA_ATTACK
notedv PITCH_DF3, 0x2D, 100
end

.channel enemy_spike_trap_roll
instr FONT01_INSTR_SLIDE_BOOTS
ldlayer 0, layer_546C
end

.layer layer_546C
notedv PITCH_EF2, 0xA, 50
notedv PITCH_F2, 0xA, 50
notedv PITCH_G2, 0xA, 50
rjump layer_546C

.channel enemy_stalkid_walk
ldlayer 0, layer_547B
end

.layer layer_547B
instr FONT01_INSTR_EGG_CRACK
notedv PITCH_DF3, 0xE, 70
end

.channel enemy_stalkid_attack
ldlayer 0, layer_5488
ldlayer 1, layer_4081
end

.layer layer_5488
instr FONT01_INSTR_PHANTOM_LAUGH_1
transpose 14
notedv PITCH_C5, 0x30, 100
end

.channel enemy_boss_ganon_paralyze
ldlayer 0, layer_549E
ldlayer 1, layer_54A0
ldlayer 2, layer_54AE
vibfreq 20
vibdepth 50
end

.layer layer_549E
ldelay 0x14

.layer layer_54A0
instr FONT01_INSTR_MONSTER_ROAR
.layer layer_54A2
legato
portamento 0x85, 28, 255
notedv PITCH_F2, 0x30, 100
notedv PITCH_EF2, 0x48, 100
end

.layer layer_54AE
instr FONT01_INSTR_DINO_ROAR
transpose 4
rjump layer_54A2

.channel enemy_boss_ganon_die
ldlayer 0, layer_54C5
ldlayer 1, layer_54C7
ldlayer 2, layer_54E9
ldlayer 3, layer_54EB
vibfreq 20
vibdepth 50
end

.layer layer_54C5
ldelay 0xA

.layer layer_54C7
instr FONT01_INSTR_MONSTER_ROAR
loop 4
portamento 0x81, 30, 107
notedv PITCH_F4, 0x8C, 100
.layer layer_54D3
legato
portamento 0x85, 39, 255
notedv PITCH_G4, 0x30, 100
notedv PITCH_AF3, 0x48, 100
nolegato
loopend
portamento 0x81, 35, 255
notedv PITCH_BF2, 0xFA, 100
end

.layer layer_54E9
ldelay 0xA

.layer layer_54EB
instr FONT01_INSTR_DINO_ROAR
loop 4
portamento 0x81, 44, 107
notedv PITCH_A4, 0x8C, 100
.layer layer_54F7
legato
portamento 0x85, 47, 255
notedv PITCH_BF4, 0x32, 100
notedv PITCH_D4, 0x48, 100
nolegato
loopend
portamento 0x81, 37, 255
notedv PITCH_C3, 0xC8, 100
end

.channel enemy_boss_ganon_penultimate_hit
ldlayer 0, layer_551B
ldlayer 1, layer_551D
ldlayer 2, layer_5523
vibfreq 20
vibdepth 50
end

.layer layer_551B
ldelay 0xD

.layer layer_551D
instr FONT01_INSTR_MONSTER_ROAR
loop 1
rjump layer_54D3

.layer layer_5523
instr FONT01_INSTR_DINO_ROAR
loop 1
rjump layer_54F7

.channel enemy_wolfos_spawn
instr FONT01_INSTR_ANIMALS
ldlayer 0, layer_552F
end

.layer layer_552F
portamento 0x81, 42, 40
notedv PITCH_G4, 0x7F, 100
end

.channel enemy_wolfos_attack
ldlayer 0, layer_553E
ldlayer 1, layer_4081
end

.layer layer_553E
instr FONT01_INSTR_ANIMALS
portamento 0x81, 35, 72
notedv PITCH_F4, 0x40, 100
end

.channel enemy_wolfos_hurt
instr FONT01_INSTR_ANIMALS
ldlayer 0, layer_5551
ldlayer 1, layer_4829
end

.layer layer_5551
legato
portamento 0x85, 39, 192
notedv PITCH_F4, 0x20, 100
notedv PITCH_DF4, 0x20, 100
end

.channel enemy_wolfos_die
instr FONT01_INSTR_ANIMALS
ldlayer 0, layer_5566
ldlayer 1, layer_4829
end

.layer layer_5566
legato
portamento 0x85, 39, 128
notedv PITCH_B4, 0x1C, 100
notedv PITCH_AF4, 0x60, 100
end

.channel enemy_wolfos_howl
instr FONT01_INSTR_ANIMALS
ldlayer 0, layer_5578
end

.layer layer_5578
notedv PITCH_D4, 0x70, 75
end

.channel enemy_guay_hurt
ldlayer 0, layer_5583
ldlayer 1, layer_4829
end

.layer layer_5583
instr FONT01_INSTR_GUAY_HURT
legato
portamento 0x85, 34, 255
notedv PITCH_C4, 0xA, 100
notedv PITCH_A3, 0x1E, 100
end

.channel enemy_guay_die
ldlayer 0, layer_5598
ldlayer 1, layer_4829
end

.layer layer_5598
instr FONT01_INSTR_GUAY_HURT
legato
portamento 0x85, 39, 255
notedv PITCH_G3, 0xF, 100
notedv PITCH_DF2, 0x60, 100
end

.channel enemy_guay_chirp
ldlayer 0, layer_55AE
vibfreq 112
vibdepth 64
end

.layer layer_55AE
instr FONT01_INSTR_ANIMALS
transpose 48
notedv PITCH_C4, 0xC, 100
notedv PITCH_D4, 0x14, 100
end

.channel enemy_guay_attack
ldlayer 0, layer_55C1
vibfreq 112
vibdepth 64
end

.layer layer_55C1
instr FONT01_INSTR_ANIMALS
transpose 48
notedv PITCH_F4, 0xC, 100
notedv PITCH_D4, 0x12, 100
notedv PITCH_E4, 0xC, 100
notedv PITCH_D4, 0x10, 100
end

.channel enemy_guay_fly
instr FONT01_INSTR_OWL_FLAP
ldlayer 0, layer_55D8
end

.layer layer_55D8
portamento 0x81, 22, 200
notedv PITCH_D3, 0x26, 68
end

.channel enemy_biggoron_blind
ldlayer 0, layer_55E4
end

.layer layer_55E4
instr FONT01_INSTR_GORON
transpose 48
notedv PITCH_BF3, 0x45, 100
end

.channel enemy_biggoron_happy
ldlayer 0, layer_55F3
ldlayer 1, layer_55F5
end

.layer layer_55F3
ldelay 0xC

.layer layer_55F5
instr FONT01_INSTR_GORON_YAWN
transpose 48
notedv PITCH_C4, 0x7F, 100
end

.channel enemy_boss_ganon_growl
ldlayer 0, layer_5604
ldlayer 1, layer_5606
end

.layer layer_5604
ldelay 0x14

.layer layer_5606
instr FONT01_INSTR_MONSTER_ROAR
legato
portamento 0x85, 19, 191
notedv PITCH_GF2, 0x34, 100
notedv PITCH_E2, 0xC0, 100
end

.channel enemy_gold_skull_spin
ldlayer 0, layer_561C
ldlayer 1, layer_5626
end

.layer layer_561C
instr FONT01_INSTR_GRASS_RUSTLE
portamento 0x81, 31, 100
notedv PITCH_C3, 0x32, 80
end

.layer layer_5626
instr FONT01_INSTR_SLIDE_BOOTS
ldelay 0x10
transpose 24
notedv PITCH_C2, 0x6, 36
notedv PITCH_F2, 0x6, 36
notedv PITCH_C3, 0x6, 36
notedv PITCH_F3, 0x6, 36
notedv PITCH_C4, 0x6, 36
end

.channel enemy_boss_ganon_sword_clank
ldlayer 0, layer_5643
ldlayer 1, layer_5647
end

.layer layer_5643
transpose 44
rjump layer_5649

.layer layer_5647
transpose 48
.layer layer_5649
instr FONT01_INSTR_WITCH_ARGUE
notedv PITCH_EF4, 0x7F, 100
end

.channel enemy_skulltula_creak
instr FONT01_INSTR_MECH
ldlayer 0, layer_5655
end

.layer layer_5655
notedv PITCH_EF3, 0x40, 100
end

.channel enemy_boss_twinrova_bicker
instr FONT01_INSTR_WITCH_ARGUE
ldlayer 0, layer_5675
.channel chan_565E
rand 32
stseq 40, layer_5675+1
stseq 40, chan_566E+1
rand 6
stseq 100, layer_5675
.channel chan_566E
ldi 1
call delay_varyingvol
rjump chan_565E

.layer layer_5675
notedv PITCH_C3, 0x50, 100
rjump layer_5675

.channel enemy_big_poe_caught_soul
instr FONT01_INSTR_DINO_ROAR
ldlayer 0, layer_5684
vibfreq 56
vibdepth 64
end

.layer layer_5684
envelope envelope_6A2C, 230
.layer layer_5688
notedv PITCH_DF2, 0xD0, 56
rjump layer_5688

.channel enemy_goron_child_cry
ldlayer 0, layer_5696
vibfreq 54
vibdepth 128
end

.layer layer_5696
instr FONT01_INSTR_GORON
transpose 48
portamento 0x81, 46, 255
notedv PITCH_GF3, 0x70, 88
end

.channel enemy_spike_trap_rock
ldlayer 0, layer_56AA
vibfreq 224
vibdepth 96
end

.layer layer_56AA
instr FONT01_INSTR_SLIDE_BOOTS
notedv PITCH_A2, 0x40, 76
end

.channel enemy_unused
end

.filter filter_enemy0
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter filter_enemy1
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter filter_enemy2
filter 0, 0, 0, 0, 0, 0, 0, 0
