#include "ultra64.h"
#include "z64.h"
#include "macros.h"
#include "vr_K4VR_pal_static.h"
#include "vr_ALVR_static.h"
#include "vr_ALVR_pal_static.h"
#include "vr_DGVR_static.h"
#include "vr_DGVR_pal_static.h"
#include "vr_FCVR_static.h"
#include "vr_FCVR_pal_static.h"
#include "vr_GLVR_static.h"
#include "vr_GLVR_pal_static.h"
#include "vr_IPVR_static.h"
#include "vr_IPVR_pal_static.h"
#include "vr_K3VR_static.h"
#include "vr_K3VR_pal_static.h"
#include "vr_K4VR_static.h"
#include "vr_K5VR_static.h"
#include "vr_K5VR_pal_static.h"
#include "vr_KHVR_static.h"
#include "vr_KHVR_pal_static.h"
#include "vr_KKRVR_static.h"
#include "vr_KKRVR_pal_static.h"
#include "vr_KR3VR_static.h"
#include "vr_KR3VR_pal_static.h"
#include "vr_KSVR_static.h"
#include "vr_KSVR_pal_static.h"
#include "vr_LBVR_static.h"
#include "vr_LBVR_pal_static.h"
#include "vr_LHVR_static.h"
#include "vr_LHVR_pal_static.h"
#include "vr_MDVR_static.h"
#include "vr_MDVR_pal_static.h"
#include "vr_MNVR_static.h"
#include "vr_MNVR_pal_static.h"
#include "vr_MLVR_static.h"
#include "vr_MLVR_pal_static.h"
#include "vr_NSVR_static.h"
#include "vr_NSVR_pal_static.h"
#include "vr_RUVR_static.h"
#include "vr_RUVR_pal_static.h"
#include "vr_SP1a_static.h"
#include "vr_SP1a_pal_static.h"
#include "vr_TTVR_static.h"
#include "vr_TTVR_pal_static.h"
#include "vr_ZRVR_static.h"
#include "vr_ZRVR_pal_static.h"

u64 gMidosHouseBgTLUT[] = {
#include "assets/textures/backgrounds/midos_house_tlut.rgba16.inc.c"
};

u64 gMidosHouseBg2TLUT[] = {
#include "assets/textures/backgrounds/midos_house2_tlut.rgba16.inc.c"
};

u64 gMidosHouseBg3TLUT[] = {
#include "assets/textures/backgrounds/midos_house3_tlut.rgba16.inc.c"
};

