SRC_DIRS += \
    src/overlays/actors/ovl_En_Vase \
    src/overlays/actors/ovl_En_M_Fire1 \
    src/overlays/actors/ovl_Obj_Blockstop \
    src/overlays/actors/ovl_En_Arow_Trap \
    src/overlays/actors/ovl_Door_Toki \
    src/overlays/actors/ovl_Bg_Gnd_Nisekabe \
    src/overlays/actors/ovl_Bg_Umajump \
    src/overlays/actors/ovl_En_Boom \
    src/overlays/actors/ovl_En_It \
    src/overlays/actors/ovl_En_Eg \
    src/overlays/actors/ovl_Obj_Roomtimer \
    src/overlays/actors/ovl_Bg_Spot18_Futa \
    src/overlays/actors/ovl_Item_Inbox \
    src/overlays/actors/ovl_En_Torch \
    src/overlays/actors/ovl_En_OE2 \
    src/overlays/actors/ovl_En_Nutsball \
    src/overlays/actors/ovl_En_Bird \
    src/overlays/actors/ovl_Bg_Spot00_Break \
    src/overlays/effects/ovl_Effect_Ss_Hahen/ \
    src/overlays/effects/ovl_Effect_Ss_KiraKira/ \
    src/overlays/effects/ovl_Effect_Ss_Stick/ \
    src/overlays/effects/ovl_Effect_Ss_Fcircle/ \
    src/overlays/effects/ovl_Effect_Ss_Bubble/ \
    src/overlays/effects/ovl_Effect_Ss_Bomb2/ \
    src/overlays/effects/ovl_Effect_Ss_Kakera/ \
    src/overlays/effects/ovl_Effect_Ss_K_Fire/ \
    src/overlays/effects/ovl_Effect_Ss_Dead_Ds/ \
    src/overlays/effects/ovl_Effect_Ss_Sibuki2/ \
    src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/ \
    src/overlays/effects/ovl_Effect_Ss_Extra/ \
    src/overlays/effects/ovl_Effect_Ss_HitMark/ \
    src/overlays/effects/ovl_Effect_Ss_G_Magma2/ \
    src/overlays/effects/ovl_Effect_Ss_Solder_Srch_Ball/ \
    src/overlays/effects/ovl_Effect_Ss_Stone1/ \
    src/overlays/effects/ovl_Effect_Ss_G_Ripple/ \
    src/overlays/effects/ovl_Effect_Ss_Ice_Smoke/ \
    src/overlays/effects/ovl_Effect_Ss_Bomb/ \
    src/overlays/effects/ovl_Effect_Ss_G_Splash/ \
    src/overlays/effects/ovl_Effect_Ss_En_Fire/ \
    src/overlays/effects/ovl_Effect_Ss_Sibuki/ \
    src/overlays/effects/ovl_Effect_Ss_Blast/ \
    src/overlays/effects/ovl_Effect_Ss_D_Fire/ \
    src/overlays/effects/ovl_Effect_Ss_En_Ice/ \
    src/overlays/effects/ovl_Effect_Ss_Fire_Tail/ \
    src/overlays/effects/ovl_Effect_Ss_G_Fire/ \
    src/overlays/effects/ovl_Effect_Ss_G_Spk/ \
    src/overlays/effects/ovl_Effect_Ss_G_Magma/ \
    src/overlays/effects/ovl_Effect_Ss_Dead_Dd/ \
    src/overlays/effects/ovl_Effect_Ss_Dead_Db/ \
    src/overlays/effects/ovl_Effect_Ss_Dust/ \
    src/overlays/effects/ovl_Effect_Ss_Dt_Bubble/ \
    src/overlays/effects/ovl_Effect_Ss_Dead_Sound/ \
    src/overlays/effects/ovl_Effect_Ss_Ice_Piece/ \
    src/overlays/effects/ovl_Effect_Ss_Lightning/ \
    src/overlays/actors/ovl_Elf_Msg/ \
    src/overlays/actors/ovl_En_Horse_Zelda/ \
    src/overlays/actors/ovl_Bg_Hidan_Kowarerukabe/ \
    src/overlays/actors/ovl_Demo_Geff/ \
    src/overlays/actors/ovl_En_Wonder_Talk/ \
    src/overlays/actors/ovl_En_Mag/ \
    src/overlays/actors/ovl_Arrow_Fire/ \
    src/overlays/actors/ovl_Bg_Mizu_Movebg/ \
    src/overlays/actors/ovl_Bg_Jya_1flift/ \
    src/overlays/actors/ovl_En_fHG/ \
    src/overlays/actors/ovl_Bg_Spot11_Oasis/ \
    src/overlays/actors/ovl_Demo_Sa/ \
    src/overlays/actors/ovl_Arms_Hook/ \
    src/overlays/actors/ovl_Bg_Spot17_Funen/ \
    src/overlays/actors/ovl_En_Okarina_Tag/ \
    src/overlays/actors/ovl_Bg_Mori_Idomizu/ \
    src/overlays/actors/ovl_Boss_Mo/ \
    src/overlays/actors/ovl_Obj_Syokudai/ \
    src/overlays/actors/ovl_Bg_Spot01_Idomizu/ \
    src/overlays/actors/ovl_Bg_Spot16_Doughnut/ \
    src/overlays/actors/ovl_Boss_Fd/ \
    src/overlays/actors/ovl_En_Torch2/ \
    src/overlays/actors/ovl_En_Zf/ \
    src/overlays/actors/ovl_Bg_Mizu_Bwall/ \
    src/overlays/actors/ovl_En_Honotrap/ \
    src/overlays/actors/ovl_Bg_Menkuri_Nisekabe/ \
    src/overlays/actors/ovl_En_Jsjutan/ \
    src/overlays/actors/ovl_En_Tp/ \
    src/overlays/actors/ovl_Bg_Ice_Shelter/ \
    src/overlays/actors/ovl_Bg_Ice_Objects/ \
    src/overlays/actors/ovl_En_Light/ \
    src/overlays/actors/ovl_En_Okarina_Effect/ \
    src/overlays/actors/ovl_En_Poh/ \
    src/overlays/actors/ovl_Boss_Ganon/ \
    src/overlays/actors/ovl_Bg_Hidan_Hamstep/ \
    src/overlays/actors/ovl_En_Mm/ \
    src/overlays/actors/ovl_Bg_Gnd_Darkmeiro/ \
    src/overlays/actors/ovl_En_Ma3/ \
    src/overlays/actors/ovl_Boss_Ganondrof/ \
    src/overlays/actors/ovl_En_Bom_Bowl_Man/ \
    src/overlays/actors/ovl_En_Dodongo/ \
    src/overlays/actors/ovl_En_Po_Relay/ \
    src/overlays/actors/ovl_Bg_Bowl_Wall/ \
    src/overlays/actors/ovl_Bg_Hidan_Rock/ \
    src/overlays/actors/ovl_Demo_Gj/ \
    src/overlays/actors/ovl_Demo_Im/ \
    src/overlays/actors/ovl_Bg_Menkuri_Kaiten/ \
    src/overlays/actors/ovl_Door_Killer/ \
    src/overlays/actors/ovl_Bg_Spot09_Obj/ \
    src/overlays/actors/ovl_En_Attack_Niw/ \
    src/overlays/actors/ovl_En_Cow/ \
    src/overlays/actors/ovl_En_Wf/ \
    src/overlays/actors/ovl_Obj_Hsblock/ \
    src/overlays/actors/ovl_Obj_Elevator/ \
    src/overlays/actors/ovl_En_Holl/ \
    src/overlays/actors/ovl_En_Anubice_Tag/ \
    src/overlays/actors/ovl_Door_Gerudo/ \
    src/overlays/actors/ovl_En_Sth/ \
    src/overlays/actors/ovl_En_Yabusame_Mark/ \
    src/overlays/actors/ovl_Obj_Kibako2/ \
    src/overlays/actors/ovl_Bg_Ydan_Hasi/ \
    src/overlays/actors/ovl_Bg_Menkuri_Eye/ \
    src/overlays/actors/ovl_Demo_Kankyo/ \
    src/overlays/actors/ovl_En_Zl2/ \
    src/overlays/actors/ovl_En_Hintnuts/ \
    src/overlays/actors/ovl_Door_Warp1/ \
    src/overlays/actors/ovl_En_Anubice/ \
    src/overlays/actors/ovl_En_Heishi4/ \
    src/overlays/actors/ovl_En_Wonder_Talk2/ \
    src/overlays/actors/ovl_Bg_Haka_Zou/ \
    src/overlays/actors/ovl_En_Takara_Man/ \
    src/overlays/actors/ovl_En_Horse/ \
    src/overlays/actors/ovl_Demo_Go/ \
    src/overlays/actors/ovl_Bg_Hidan_Hrock/ \
    src/overlays/actors/ovl_En_Bom_Bowl_Pit/ \
    src/overlays/actors/ovl_Bg_Spot11_Bakudankabe/ \
    src/overlays/actors/ovl_Bg_Ice_Turara/ \
    src/overlays/actors/ovl_En_Wood02/ \
    src/overlays/actors/ovl_Obj_Hana/ \
    src/overlays/actors/ovl_Bg_Po_Syokudai/ \
    src/overlays/actors/ovl_En_Wallmas/ \
    src/overlays/actors/ovl_En_Clear_Tag/ \
    src/overlays/actors/ovl_Bg_Mori_Hashigo/ \
    src/overlays/actors/ovl_Bg_Hidan_Kousi/ \
    src/overlays/actors/ovl_En_Trap/ \
    src/overlays/actors/ovl_Bg_Spot17_Bakudankabe/ \
    src/overlays/actors/ovl_Bg_Spot18_Basket/ \
    src/overlays/actors/ovl_Bg_Hidan_Sima/ \
    src/overlays/actors/ovl_En_Pu_box/ \
    src/overlays/actors/ovl_Bg_Relay_Objects/ \
    src/overlays/actors/ovl_En_Firefly/ \
    src/overlays/actors/ovl_En_Dha/ \
    src/overlays/actors/ovl_Bg_Jya_Goroiwa/ \
    src/overlays/actors/ovl_Arrow_Light/ \
    src/overlays/actors/ovl_Obj_Tsubo/ \
    src/overlays/actors/ovl_Bg_Spot01_Objects2/ \
    src/overlays/actors/ovl_En_Js/ \
    src/overlays/actors/ovl_En_Horse_Normal/ \
    src/overlays/actors/ovl_Bg_Mori_Hineri/ \
    src/overlays/actors/ovl_En_Owl/ \
    src/overlays/actors/ovl_Bg_Spot18_Shutter/ \
    src/overlays/actors/ovl_Bg_Jya_Bombchuiwa/ \
    src/overlays/actors/ovl_En_Daiku_Kakariko/ \
    src/overlays/actors/ovl_En_Okuta/ \
    src/overlays/actors/ovl_En_Niw_Lady/ \
    src/overlays/actors/ovl_En_Dnt_Jiji/ \
    src/overlays/actors/ovl_En_Kakasi/ \
    src/overlays/actors/ovl_Bg_Bdan_Objects/ \
    src/overlays/actors/ovl_Bg_Jya_Bigmirror/ \
    src/overlays/actors/ovl_En_Goroiwa/ \
    src/overlays/actors/ovl_Bg_Jya_Amishutter/ \
    src/overlays/actors/ovl_En_Skj/ \
    src/overlays/actors/ovl_Bg_Haka_Huta/ \
    src/overlays/actors/ovl_Bg_Toki_Swd/ \
    src/overlays/actors/ovl_En_Heishi2/ \
    src/overlays/actors/ovl_En_Fish/ \
    src/overlays/actors/ovl_Bg_Gnd_Soulmeiro/ \
    src/overlays/actors/ovl_Bg_Treemouth/ \
    src/overlays/actors/ovl_En_Syateki_Niw/ \
    src/overlays/actors/ovl_En_GeldB/ \
    src/overlays/actors/ovl_Magic_Wind/ \
    src/overlays/actors/ovl_En_Fu/ \
    src/overlays/actors/ovl_Bg_Hidan_Firewall/ \
    src/overlays/actors/ovl_Bg_Hidan_Rsekizou/ \
    src/overlays/actors/ovl_En_Bili/ \
    src/overlays/actors/ovl_En_Toryo/ \
    src/overlays/actors/ovl_Bg_Haka_Ship/ \
    src/overlays/actors/ovl_En_Mu/ \
    src/overlays/actors/ovl_En_Lightbox/ \
    src/overlays/actors/ovl_Bg_Jya_Kanaami/ \
    src/overlays/actors/ovl_En_Tk/ \
    src/overlays/actors/ovl_En_Nb/ \
    src/overlays/actors/ovl_Bg_Spot01_Idohashira/ \
    src/overlays/actors/ovl_Bg_Pushbox/ \
    src/overlays/actors/ovl_En_Gs/ \
    src/overlays/actors/ovl_Bg_Spot12_Saku/ \
    src/overlays/actors/ovl_En_Tana/ \
    src/overlays/actors/ovl_Oceff_Wipe4/ \
    src/overlays/actors/ovl_En_Dekunuts/ \
    src/overlays/actors/ovl_En_Wonder_Item/ \
    src/overlays/actors/ovl_Bg_Spot07_Taki/ \
    src/overlays/actors/ovl_Boss_Sst/ \
    src/overlays/actors/ovl_Bg_Spot08_Iceblock/ \
    src/overlays/actors/ovl_En_Bom/ \
    src/overlays/actors/ovl_En_Ani/ \
    src/overlays/actors/ovl_En_Zl1/ \
    src/overlays/actors/ovl_En_Po_Field/ \
    src/overlays/actors/ovl_En_Encount2/ \
    src/overlays/actors/ovl_En_Ik/ \
    src/overlays/actors/ovl_Demo_Ext/ \
    src/overlays/actors/ovl_En_Eiyer/ \
    src/overlays/actors/ovl_Bg_Spot05_Soko/ \
    src/overlays/actors/ovl_En_Tg/ \
    src/overlays/actors/ovl_En_Test/ \
    src/overlays/actors/ovl_En_Tite/ \
    src/overlays/actors/ovl_En_Mk/ \
    src/overlays/actors/ovl_En_Yukabyun/ \
    src/overlays/actors/ovl_En_Crow/ \
    src/overlays/actors/ovl_Bg_Hidan_Fslift/ \
    src/overlays/actors/ovl_En_Dog/ \
    src/overlays/actors/ovl_En_Ma2/ \
    src/overlays/actors/ovl_En_Weather_Tag/ \
    src/overlays/actors/ovl_Bg_Heavy_Block/ \
    src/overlays/actors/ovl_En_In/ \
    src/overlays/actors/ovl_Bg_Mizu_Shutter/ \
    src/overlays/actors/ovl_En_Fhg_Fire/ \
    src/overlays/actors/ovl_Bg_Ice_Shutter/ \
    src/overlays/actors/ovl_Bg_Mizu_Water/ \
    src/overlays/actors/ovl_Obj_Kibako/ \
    src/overlays/actors/ovl_Boss_Ganon2/ \
    src/overlays/actors/ovl_Obj_Comb/ \
    src/overlays/actors/ovl_En_Fz/ \
    src/overlays/actors/ovl_En_Fr/ \
    src/overlays/actors/ovl_Bg_Ddan_Kd/ \
    src/overlays/actors/ovl_Demo_Effect/ \
    src/overlays/actors/ovl_Bg_Spot16_Bombstone/ \
    src/overlays/actors/ovl_En_Bx/ \
    src/overlays/actors/ovl_Bg_Po_Event/ \
    src/overlays/actors/ovl_Obj_Makekinsuta/ \
    src/overlays/actors/ovl_En_Gm/ \
    src/overlays/actors/ovl_Bg_Spot02_Objects/ \
    src/overlays/actors/ovl_En_Bigokuta/ \
    src/overlays/actors/ovl_En_Sw/ \
    src/overlays/actors/ovl_Bg_Jya_Ironobj/ \
    src/overlays/actors/ovl_En_Bombf/ \
    src/overlays/actors/ovl_Bg_Hidan_Syoku/ \
    src/overlays/actors/ovl_En_Fw/ \
    src/overlays/actors/ovl_Bg_Gnd_Firemeiro/ \
    src/overlays/actors/ovl_Fishing/ \
    src/overlays/actors/ovl_Bg_Jya_Bombiwa/ \
    src/overlays/actors/ovl_En_Encount1/ \
    src/overlays/actors/ovl_En_Ko/ \
    src/overlays/actors/ovl_En_Skjneedle/ \
    src/overlays/actors/ovl_En_Ossan/ \
    src/overlays/actors/ovl_En_Blkobj/ \
    src/overlays/actors/ovl_Boss_Goma/ \
    src/overlays/actors/ovl_En_Butte/ \
    src/overlays/actors/ovl_En_Fire_Rock/ \
    src/overlays/actors/ovl_En_Door/ \
    src/overlays/actors/ovl_En_Hata/ \
    src/overlays/actors/ovl_Eff_Dust/ \
    src/overlays/actors/ovl_Object_Kankyo/ \
    src/overlays/actors/ovl_En_Xc/ \
    src/overlays/actors/ovl_En_Bb/ \
    src/overlays/actors/ovl_En_Fd/ \
    src/overlays/actors/ovl_Demo_Du/ \
    src/overlays/actors/ovl_En_Karebaba/ \
    src/overlays/actors/ovl_En_Heishi1/ \
    src/overlays/actors/ovl_Bg_Ganon_Otyuka/ \
    src/overlays/actors/ovl_En_Kanban/ \
    src/overlays/actors/ovl_Bg_Breakwall/ \
    src/overlays/actors/ovl_Bg_Dy_Yoseizo/ \
    src/overlays/actors/ovl_En_Bdfire/ \
    src/overlays/actors/ovl_Demo_Ec/ \
    src/overlays/actors/ovl_Item_B_Heart/ \
    src/overlays/actors/ovl_Bg_Spot15_Saku/ \
    src/overlays/actors/ovl_En_Mb/ \
    src/overlays/actors/ovl_En_M_Thunder/ \
    src/overlays/actors/ovl_En_Horse_Game_Check/ \
    src/overlays/actors/ovl_En_Part/ \
    src/overlays/actors/ovl_Bg_Spot18_Obj/ \
    src/overlays/actors/ovl_En_Kusa/ \
    src/overlays/actors/ovl_En_Elf/ \
    src/overlays/actors/ovl_En_Horse_Ganon/ \
    src/overlays/actors/ovl_Bg_Zg/ \
    src/overlays/actors/ovl_En_Dekubaba/ \
    src/overlays/actors/ovl_Bg_Bdan_Switch/ \
    src/overlays/actors/ovl_Obj_Lightswitch/ \
    src/overlays/actors/ovl_En_Changer/ \
    src/overlays/actors/ovl_En_Gb/ \
    src/overlays/actors/ovl_Bg_Sst_Floor/ \
    src/overlays/actors/ovl_Bg_Ingate/ \
    src/overlays/actors/ovl_End_Title/ \
    src/overlays/actors/ovl_En_Md/ \
    src/overlays/actors/ovl_En_Dodojr/ \
    src/overlays/actors/ovl_Bg_Gjyo_Bridge/ \
    src/overlays/actors/ovl_Bg_Ydan_Sp/ \
    src/overlays/actors/ovl_En_Shopnuts/ \
    src/overlays/actors/ovl_En_Nwc/ \
    src/overlays/actors/ovl_En_Peehat/ \
    src/overlays/actors/ovl_Bg_Hidan_Sekizou/ \
    src/overlays/actors/ovl_En_Syateki_Itm/ \
    src/overlays/actors/ovl_En_River_Sound/ \
    src/overlays/actors/ovl_Bg_Spot08_Bakudankabe/ \
    src/overlays/actors/ovl_En_Vm/ \
    src/overlays/actors/ovl_En_Bom_Chu/ \
    src/overlays/actors/ovl_Obj_Lift/ \
    src/overlays/actors/ovl_Arrow_Ice/ \
    src/overlays/actors/ovl_Bg_Haka_Megane/ \
    src/overlays/actors/ovl_Bg_Mori_Kaitenkabe/ \
    src/overlays/actors/ovl_En_Box/ \
    src/overlays/actors/ovl_En_Bw/ \
    src/overlays/actors/ovl_En_Viewer/ \
    src/overlays/actors/ovl_Obj_Warp2block/ \
    src/overlays/actors/ovl_Bg_Jya_Lift/ \
    src/overlays/actors/ovl_Bg_Bombwall/ \
    src/overlays/actors/ovl_Oceff_Spot/ \
    src/overlays/actors/ovl_En_Ma1/ \
    src/overlays/actors/ovl_Bg_Spot00_Hanebasi/ \
    src/overlays/actors/ovl_En_Ex_Ruppy/ \
    src/overlays/actors/ovl_En_Weiyer/ \
    src/overlays/actors/ovl_Bg_Gate_Shutter/ \
    src/overlays/actors/ovl_Bg_Haka/ \
    src/overlays/actors/ovl_En_Jj/ \
    src/overlays/actors/ovl_En_Du/ \
    src/overlays/actors/ovl_En_Vb_Ball/ \
    src/overlays/actors/ovl_Bg_Mori_Bigst/ \
    src/overlays/actors/ovl_En_Arrow/ \
    src/overlays/actors/ovl_Bg_Toki_Hikari/ \
    src/overlays/actors/ovl_En_Goma/ \
    src/overlays/actors/ovl_Magic_Dark/ \
    src/overlays/actors/ovl_Bg_Haka_Gate/ \
    src/overlays/actors/ovl_En_Ice_Hono/ \
    src/overlays/actors/ovl_En_Rl/ \
    src/overlays/actors/ovl_En_Rr/ \
    src/overlays/actors/ovl_En_Zl3/ \
    src/overlays/actors/ovl_Obj_Bean/ \
    src/overlays/actors/ovl_En_Hs2/ \
    src/overlays/actors/ovl_En_Rd/ \
    src/overlays/actors/ovl_Magic_Fire/ \
    src/overlays/actors/ovl_En_Skb/ \
    src/overlays/actors/ovl_En_Scene_Change/ \
    src/overlays/actors/ovl_En_Ge2/ \
    src/overlays/actors/ovl_Bg_Ydan_Maruta/ \
    src/overlays/actors/ovl_Bg_Bom_Guard/ \
    src/overlays/actors/ovl_En_Mm2/ \
    src/overlays/actors/ovl_En_St/ \
    src/overlays/actors/ovl_Obj_Mure3/ \
    src/overlays/actors/ovl_En_Ru1/ \
    src/overlays/actors/ovl_En_Zo/ \
    src/overlays/actors/ovl_Boss_Fd2/ \
    src/overlays/actors/ovl_En_Kakasi3/ \
    src/overlays/actors/ovl_Mir_Ray/ \
    src/overlays/actors/ovl_Obj_Timeblock/ \
    src/overlays/actors/ovl_Boss_Tw/ \
    src/overlays/actors/ovl_En_Go/ \
    src/overlays/actors/ovl_Bg_Ddan_Jd/ \
    src/overlays/actors/ovl_En_Dh/ \
    src/overlays/actors/ovl_En_Hy/ \
    src/overlays/actors/ovl_En_Dy_Extra/ \
    src/overlays/actors/ovl_En_Insect/ \
    src/overlays/actors/ovl_Obj_Switch/ \
    src/overlays/actors/ovl_En_Sb/ \
    src/overlays/actors/ovl_En_Cs/ \
    src/overlays/actors/ovl_Bg_Jya_Cobra/ \
    src/overlays/actors/ovl_Bg_Spot12_Gate/ \
    src/overlays/actors/ovl_Obj_Mure/ \
    src/overlays/actors/ovl_Bg_Haka_Trap/ \
    src/overlays/actors/ovl_En_Reeba/ \
    src/overlays/actors/ovl_En_Ssh/ \
    src/overlays/actors/ovl_En_Ms/ \
    src/overlays/actors/ovl_En_Kakasi2/ \
    src/overlays/actors/ovl_En_Po_Sisters/ \
    src/overlays/actors/ovl_En_Ganon_Mant/ \
    src/overlays/actors/ovl_En_Horse_Link_Child/ \
    src/overlays/actors/ovl_Efc_Erupc/ \
    src/overlays/actors/ovl_Door_Ana/ \
    src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/ \
    src/overlays/actors/ovl_Bg_Mori_Elevator/ \
    src/overlays/actors/ovl_Boss_Va/ \
    src/overlays/actors/ovl_Obj_Bombiwa/ \
    src/overlays/actors/ovl_En_Sda/ \
    src/overlays/actors/ovl_En_Ds/ \
    src/overlays/actors/ovl_Bg_Jya_Haheniron/ \
    src/overlays/actors/ovl_En_Dnt_Nomal/ \
    src/overlays/actors/ovl_En_Guest/ \
    src/overlays/actors/ovl_Bg_Gnd_Iceblock/ \
    src/overlays/actors/ovl_Item_Shield/ \
    src/overlays/actors/ovl_En_Kz/ \
    src/overlays/actors/ovl_En_Hs/ \
    src/overlays/actors/ovl_Bg_Haka_MeganeBG/ \
    src/overlays/actors/ovl_Bg_Vb_Sima/ \
    src/overlays/actors/ovl_Demo_Shd/ \
    src/overlays/actors/ovl_En_Anubice_Fire/ \
    src/overlays/actors/ovl_En_Syateki_Man/ \
    src/overlays/actors/ovl_Bg_Spot06_Objects/ \
    src/overlays/actors/ovl_En_Floormas/ \
    src/overlays/actors/ovl_En_Niw_Girl/ \
    src/overlays/actors/ovl_En_Zl4/ \
    src/overlays/actors/ovl_Bg_Hidan_Fwbig/ \
    src/overlays/actors/ovl_En_Brob/ \
    src/overlays/actors/ovl_Bg_Jya_Megami/ \
    src/overlays/actors/ovl_En_Wall_Tubo/ \
    src/overlays/actors/ovl_En_Dns/ \
    src/overlays/actors/ovl_Bg_Haka_Water/ \
    src/overlays/actors/ovl_Bg_Haka_Sgami/ \
    src/overlays/actors/ovl_En_Ganon_Organ/ \
    src/overlays/actors/ovl_Demo_Kekkai/ \
    src/overlays/actors/ovl_Bg_Mori_Hashira4/ \
    src/overlays/actors/ovl_Bg_Spot03_Taki/ \
    src/overlays/actors/ovl_Demo_Ik/ \
    src/overlays/actors/ovl_En_Ishi/ \
    src/overlays/actors/ovl_Obj_Makeoshihiki/ \
    src/overlays/actors/ovl_Item_Etcetera/ \
    src/overlays/actors/ovl_En_Go2/ \
    src/overlays/actors/ovl_En_Po_Desert/ \
    src/overlays/actors/ovl_Bg_Dodoago/ \
    src/overlays/actors/ovl_En_Ny/ \
    src/overlays/actors/ovl_En_Ru2/ \
    src/overlays/actors/ovl_En_Sa/ \
    src/overlays/actors/ovl_En_Heishi3/ \
    src/overlays/actors/ovl_En_Tr/ \
    src/overlays/actors/ovl_Obj_Hamishi/ \
    src/overlays/actors/ovl_En_Ge1/ \
    src/overlays/actors/ovl_En_Am/ \
    src/overlays/actors/ovl_En_Niw/ \
    src/overlays/actors/ovl_En_G_Switch/ \
    src/overlays/actors/ovl_En_Vali/ \
    src/overlays/actors/ovl_Oceff_Storm/ \
    src/overlays/actors/ovl_Oceff_Wipe3/ \
    src/overlays/actors/ovl_En_Ta/ \
    src/overlays/actors/ovl_Bg_Spot15_Rrbox/ \
    src/overlays/actors/ovl_Demo_Tre_Lgt/ \
    src/overlays/actors/ovl_Obj_Oshihiki/ \
    src/overlays/actors/ovl_En_Siofuki/ \
    src/overlays/actors/ovl_Bg_Hidan_Dalm/ \
    src/overlays/actors/ovl_Bg_Mjin/ \
    src/overlays/actors/ovl_Shot_Sun/ \
    src/overlays/actors/ovl_Oceff_Wipe2/ \
    src/overlays/actors/ovl_Obj_Dekujr/ \
    src/overlays/actors/ovl_Item_Ocarina/ \
    src/overlays/actors/ovl_En_Stream/ \
    src/overlays/actors/ovl_Bg_Spot01_Fusya/ \
    src/overlays/actors/ovl_En_Ba/ \
    src/overlays/actors/ovl_player_actor/ \
    src/overlays/actors/ovl_Bg_Haka_Tubo/ \
    src/overlays/actors/ovl_Demo_6K/ \
    src/overlays/actors/ovl_En_Ex_Item/ \
    src/overlays/actors/ovl_Bg_Jya_Block/ \
    src/overlays/actors/ovl_En_Si/ \
    src/overlays/actors/ovl_Door_Shutter/ \
    src/overlays/actors/ovl_Bg_Hidan_Curtain/ \
    src/overlays/actors/ovl_En_Bubble/ \
    src/overlays/actors/ovl_Bg_Jya_Zurerukabe/ \
    src/overlays/actors/ovl_En_Dnt_Demo/ \
    src/overlays/actors/ovl_Demo_Gt/ \
    src/overlays/actors/ovl_Bg_Mizu_Uzu/ \
    src/overlays/actors/ovl_Obj_Ice_Poly/ \
    src/overlays/actors/ovl_Bg_Spot01_Idosoko/ \
    src/overlays/actors/ovl_Boss_Dodongo/ \
    src/overlays/actors/ovl_Oceff_Wipe/ \
    src/overlays/actors/ovl_En_Ge3/ \
    src/overlays/actors/ovl_Elf_Msg2/ \
    src/overlays/actors/ovl_Obj_Mure2/ \
    src/overlays/actors/ovl_En_Daiku/ \
    src/overlays/actors/ovl_En_Fd_Fire/ \
    src/overlays/actors/ovl_En_Diving_Game/ \
    src/overlays/actors/ovl_En_GirlA/ \
    src/overlays/gamestates/ovl_select/ \
    src/overlays/gamestates/ovl_file_choose/ \
    src/overlays/actors/ovl_kaleido_scope/ \
    src/overlays/actors/ovl_En_Tubo_Trap/ \
    src/overlays/gamestates/ovl_title/ \
    src/overlays/gamestates/ovl_opening/ \
