#include "ultra64.h"
#include "z64.h"
#include "macros.h"
#include "vr_cloud2_pal_static.h"
#include "vr_fine0_static.h"
#include "vr_fine0_pal_static.h"
#include "vr_fine1_static.h"
#include "vr_fine1_pal_static.h"
#include "vr_fine2_static.h"
#include "vr_fine2_pal_static.h"
#include "vr_fine3_static.h"
#include "vr_fine3_pal_static.h"
#include "vr_cloud0_static.h"
#include "vr_cloud0_pal_static.h"
#include "vr_cloud1_static.h"
#include "vr_cloud1_pal_static.h"
#include "vr_cloud2_static.h"
#include "vr_cloud3_static.h"
#include "vr_cloud3_pal_static.h"
#include "vr_holy0_static.h"
#include "vr_holy0_pal_static.h"
#include "vr_holy1_static.h"
#include "vr_holy1_pal_static.h"

u64 gSunsetOvercastSkyboxTLUT[] = {
#include "assets/textures/skyboxes/overcast_sunset_tlut.rgba16.inc.c"
};

