#ifndef MARKET_ALLEY_N_SCENE_H
#define MARKET_ALLEY_N_SCENE_H 1

extern SceneCmd market_alley_n_sceneCommands[];
extern ActorEntry market_alley_n_sceneStartPositionList0x000068[];
extern TransitionActorEntry market_alley_n_sceneTransitionActorList_0000B8[];
extern RomFile market_alley_n_sceneRoomList0x0000E8[];
extern EntranceEntry market_alley_n_sceneEntranceList0x0000F0[];
extern u16 market_alley_n_sceneExitList_0000FC[];
extern LightSettings market_alley_n_sceneLightSettings0x000108[];
extern Vec3s market_alley_n_scenePathwayList_000120[];
extern Vec3s market_alley_n_scenePathwayList_00014C[];
extern Vec3s market_alley_n_scenePathwayList_000178[];
extern Path market_alley_n_scenePathList_00019C[];
extern Vec3s market_alley_n_sceneCollisionHeader_0012C0CamPosData[];
extern CamData market_alley_n_sceneCollisionHeader_0012C0CamDataList[];
extern SurfaceType market_alley_n_sceneCollisionHeader_0012C0SurfaceType[];
extern CollisionPoly market_alley_n_sceneCollisionHeader_0012C0Polygons[];
extern Vec3s market_alley_n_sceneCollisionHeader_0012C0Vertices[];
extern CollisionHeader market_alley_n_sceneCollisionHeader_0012C0;

#endif
