beginseg
    name "ovl_En_GirlA"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_GirlA/z_en_girla.o"
endseg

beginseg
    name "ovl_En_Part"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Part/z_en_part.o"
endseg

beginseg
    name "ovl_En_Light"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Light/z_en_light.o"
endseg

beginseg
    name "ovl_En_Door"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Door/z_en_door.o"
endseg

beginseg
    name "ovl_En_Box"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Box/z_en_box.o"
endseg

beginseg
    name "ovl_En_Poh"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Poh/z_en_poh.o"
endseg

beginseg
    name "ovl_En_Okuta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Okuta/z_en_okuta.o"
endseg

beginseg
    name "ovl_En_Bom"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bom/z_en_bom.o"
endseg

beginseg
    name "ovl_En_Wallmas"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.o"
endseg

beginseg
    name "ovl_En_Dodongo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.o"
endseg

beginseg
    name "ovl_En_Firefly"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Firefly/z_en_firefly.o"
endseg

beginseg
    name "ovl_En_Horse"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse/z_en_horse.o"
endseg

beginseg
    name "ovl_En_Arrow"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Arrow/z_en_arrow.o"
endseg

beginseg
    name "ovl_En_Elf"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Elf/z_en_elf.o"
endseg

beginseg
    name "ovl_En_Niw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Niw/z_en_niw.o"
endseg

beginseg
    name "ovl_En_Tite"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tite/z_en_tite.o"
endseg

beginseg
    name "ovl_En_Reeba"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Reeba/z_en_reeba.o"
endseg

beginseg
    name "ovl_En_Peehat"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Peehat/z_en_peehat.o"
endseg

beginseg
    name "ovl_En_Holl"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Holl/z_en_holl.o"
endseg

beginseg
    name "ovl_En_Scene_Change"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Scene_Change/z_en_scene_change.o"
endseg

beginseg
    name "ovl_En_Zf"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zf/z_en_zf.o"
endseg

beginseg
    name "ovl_En_Hata"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hata/z_en_hata.o"
endseg

beginseg
    name "ovl_Boss_Dodongo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.o"
endseg

beginseg
    name "ovl_Boss_Goma"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Goma/z_boss_goma.o"
endseg

beginseg
    name "ovl_En_Zl1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zl1/z_en_zl1_cutscene_data.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zl1/z_en_zl1.o"
endseg

beginseg
    name "ovl_En_Viewer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Viewer/z_en_viewer.o"
endseg

beginseg
    name "ovl_En_Goma"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Goma/z_en_goma.o"
endseg

beginseg
    name "ovl_Bg_Pushbox"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Pushbox/z_bg_pushbox.o"
endseg

beginseg
    name "ovl_En_Bubble"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bubble/z_en_bubble.o"
endseg

beginseg
    name "ovl_Door_Shutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Shutter/z_door_shutter.o"
endseg

beginseg
    name "ovl_En_Dodojr"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dodojr/z_en_dodojr.o"
endseg

beginseg
    name "ovl_En_Bdfire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bdfire/z_en_bdfire.o"
endseg

beginseg
    name "ovl_En_Boom"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Boom/z_en_boom.o"
endseg

beginseg
    name "ovl_En_Torch2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Torch2/z_en_torch2.o"
endseg

beginseg
    name "ovl_En_Bili"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bili/z_en_bili.o"
endseg

beginseg
    name "ovl_En_Tp"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tp/z_en_tp.o"
endseg

beginseg
    name "ovl_En_St"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_St/z_en_st.o"
endseg

beginseg
    name "ovl_En_Bw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bw/z_en_bw.o"
endseg

beginseg
    name "ovl_En_Eiyer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Eiyer/z_en_eiyer.o"
endseg

beginseg
    name "ovl_En_River_Sound"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_River_Sound/z_en_river_sound.o"
endseg

beginseg
    name "ovl_En_Horse_Normal"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Normal/z_en_horse_normal.o"
endseg

beginseg
    name "ovl_En_Ossan"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ossan/z_en_ossan.o"
endseg

beginseg
    name "ovl_Bg_Treemouth"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth_cutscene_data.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth.o"
endseg

beginseg
    name "ovl_Bg_Dodoago"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dodoago/z_bg_dodoago.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Dalm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Dalm/z_bg_hidan_dalm.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Hrock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Hrock/z_bg_hidan_hrock.o"
endseg

beginseg
    name "ovl_En_Horse_Ganon"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Ganon/z_en_horse_ganon.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Rock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Rock/z_bg_hidan_rock.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Rsekizou"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Rsekizou/z_bg_hidan_rsekizou.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Sekizou"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Sekizou/z_bg_hidan_sekizou.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Sima"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Sima/z_bg_hidan_sima.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Syoku"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Syoku/z_bg_hidan_syoku.o"
endseg

beginseg
    name "ovl_En_Xc"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Xc/z_en_xc.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Curtain"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Curtain/z_bg_hidan_curtain.o"
endseg

beginseg
    name "ovl_Bg_Spot00_Hanebasi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot00_Hanebasi/z_bg_spot00_hanebasi.o"
endseg

beginseg
    name "ovl_En_Mb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mb/z_en_mb.o"
endseg

beginseg
    name "ovl_En_Bombf"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bombf/z_en_bombf.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Firewall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Firewall/z_bg_hidan_firewall.o"
endseg

beginseg
    name "ovl_Bg_Dy_Yoseizo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.o"
endseg

beginseg
    name "ovl_En_Zl2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zl2/z_en_zl2.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Fslift"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Fslift/z_bg_hidan_fslift.o"
endseg

beginseg
    name "ovl_En_OE2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_OE2/z_en_oe2.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Hasi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Hasi/z_bg_ydan_hasi.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Maruta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Maruta/z_bg_ydan_maruta.o"
endseg

beginseg
    name "ovl_Boss_Ganondrof"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.o"
endseg

beginseg
    name "ovl_En_Am"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Am/z_en_am.o"
endseg

beginseg
    name "ovl_En_Dekubaba"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.o"
endseg

beginseg
    name "ovl_En_M_Fire1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_M_Fire1/z_en_m_fire1.o"
endseg

beginseg
    name "ovl_En_M_Thunder"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_M_Thunder/z_en_m_thunder.o"
endseg

beginseg
    name "ovl_Bg_Ddan_Jd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ddan_Jd/z_bg_ddan_jd.o"
endseg

beginseg
    name "ovl_Bg_Breakwall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.o"
endseg

beginseg
    name "ovl_En_Jj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Jj/z_en_jj.o"
endseg

beginseg
    name "ovl_En_Horse_Zelda"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.o"
endseg

beginseg
    name "ovl_Bg_Ddan_Kd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ddan_Kd/z_bg_ddan_kd.o"
endseg

beginseg
    name "ovl_Door_Warp1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Warp1/z_door_warp1.o"
endseg

beginseg
    name "ovl_Obj_Syokudai"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.o"
endseg

beginseg
    name "ovl_Item_B_Heart"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_B_Heart/z_item_b_heart.o"
endseg

beginseg
    name "ovl_En_Dekunuts"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.o"
endseg

beginseg
    name "ovl_Bg_Menkuri_Kaiten"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Menkuri_Kaiten/z_bg_menkuri_kaiten.o"
endseg

beginseg
    name "ovl_Bg_Menkuri_Eye"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Menkuri_Eye/z_bg_menkuri_eye.o"
endseg

beginseg
    name "ovl_En_Vali"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Vali/z_en_vali.o"
endseg

beginseg
    name "ovl_Bg_Mizu_Movebg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mizu_Movebg/z_bg_mizu_movebg.o"
endseg

beginseg
    name "ovl_Bg_Mizu_Water"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mizu_Water/z_bg_mizu_water.o"
endseg

beginseg
    name "ovl_Arms_Hook"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Arms_Hook/z_arms_hook.o"
endseg

beginseg
    name "ovl_En_fHG"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_fHG/z_en_fhg.o"
endseg

beginseg
    name "ovl_Bg_Mori_Hineri"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Hineri/z_bg_mori_hineri.o"
endseg

beginseg
    name "ovl_En_Bb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bb/z_en_bb.o"
endseg

beginseg
    name "ovl_Bg_Toki_Hikari"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Toki_Hikari/z_bg_toki_hikari.o"
endseg

beginseg
    name "ovl_En_Yukabyun"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Yukabyun/z_en_yukabyun.o"
endseg

beginseg
    name "ovl_Bg_Toki_Swd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_3.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.o"
endseg

beginseg
    name "ovl_En_Fhg_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fhg_Fire/z_en_fhg_fire.o"
endseg

beginseg
    name "ovl_Bg_Mjin"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mjin/z_bg_mjin.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Kousi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Kousi/z_bg_hidan_kousi.o"
endseg

beginseg
    name "ovl_Door_Toki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Toki/z_door_toki.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Hamstep"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Hamstep/z_bg_hidan_hamstep.o"
endseg

beginseg
    name "ovl_En_Bird"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bird/z_en_bird.o"
endseg

beginseg
    name "ovl_En_Wood02"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wood02/z_en_wood02.o"
endseg

beginseg
    name "ovl_En_Lightbox"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Lightbox/z_en_lightbox.o"
endseg

beginseg
    name "ovl_En_Pu_box"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Pu_box/z_en_pu_box.o"
endseg

beginseg
    name "ovl_En_Trap"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Trap/z_en_trap.o"
endseg

beginseg
    name "ovl_En_Arow_Trap"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Arow_Trap/z_en_arow_trap.o"
endseg

beginseg
    name "ovl_En_Vase"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Vase/z_en_vase.o"
endseg

beginseg
    name "ovl_En_Ta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ta/z_en_ta.o"
endseg

beginseg
    name "ovl_En_Tk"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tk/z_en_tk.o"
endseg

beginseg
    name "ovl_Bg_Mori_Bigst"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Bigst/z_bg_mori_bigst.o"
endseg

beginseg
    name "ovl_Bg_Mori_Elevator"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Elevator/z_bg_mori_elevator.o"
endseg

beginseg
    name "ovl_Bg_Mori_Kaitenkabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Kaitenkabe/z_bg_mori_kaitenkabe.o"
endseg

beginseg
    name "ovl_Bg_Mori_Rakkatenjo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/z_bg_mori_rakkatenjo.o"
endseg

beginseg
    name "ovl_En_Vm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Vm/z_en_vm.o"
endseg

beginseg
    name "ovl_Demo_Effect"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Effect/z_demo_effect.o"
endseg

beginseg
    name "ovl_Demo_Kankyo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data1.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data2.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data3.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data4.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data5.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data6.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data7.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data8.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Fwbig"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Fwbig/z_bg_hidan_fwbig.o"
endseg

beginseg
    name "ovl_En_Floormas"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Floormas/z_en_floormas.o"
endseg

beginseg
    name "ovl_En_Heishi1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.o"
endseg

beginseg
    name "ovl_En_Rd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Rd/z_en_rd.o"
endseg

beginseg
    name "ovl_En_Po_Sisters"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.o"
endseg

beginseg
    name "ovl_Bg_Heavy_Block"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Heavy_Block/z_bg_heavy_block.o"
endseg

beginseg
    name "ovl_Bg_Po_Event"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Po_Event/z_bg_po_event.o"
endseg

beginseg
    name "ovl_Obj_Mure"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Mure/z_obj_mure.o"
endseg

beginseg
    name "ovl_En_Sw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Sw/z_en_sw.o"
endseg

beginseg
    name "ovl_Boss_Fd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Fd/z_boss_fd.o"
endseg

beginseg
    name "ovl_Object_Kankyo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.o"
endseg

beginseg
    name "ovl_En_Du"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Du/z_en_du.o"
endseg

beginseg
    name "ovl_En_Fd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fd/z_en_fd.o"
endseg

beginseg
    name "ovl_En_Horse_Link_Child"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.o"
endseg

beginseg
    name "ovl_Door_Ana"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Ana/z_door_ana.o"
endseg

beginseg
    name "ovl_Bg_Spot02_Objects"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot02_Objects/z_bg_spot02_objects.o"
endseg

beginseg
    name "ovl_Bg_Haka"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka/z_bg_haka.o"
endseg

beginseg
    name "ovl_Magic_Wind"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Magic_Wind/z_magic_wind.o"
endseg

beginseg
    name "ovl_Magic_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Magic_Fire/z_magic_fire.o"
endseg

beginseg
    name "ovl_En_Ru1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ru1/z_en_ru1.o"
endseg

beginseg
    name "ovl_Boss_Fd2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.o"
endseg

beginseg
    name "ovl_En_Fd_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fd_Fire/z_en_fd_fire.o"
endseg

beginseg
    name "ovl_En_Dh"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dh/z_en_dh.o"
endseg

beginseg
    name "ovl_En_Dha"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dha/z_en_dha.o"
endseg

beginseg
    name "ovl_En_Rl"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Rl/z_en_rl.o"
endseg

beginseg
    name "ovl_En_Encount1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Encount1/z_en_encount1.o"
endseg

beginseg
    name "ovl_Demo_Du"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Du/z_demo_du.o"
endseg

beginseg
    name "ovl_Demo_Im"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Im/z_demo_im.o"
endseg

beginseg
    name "ovl_Demo_Tre_Lgt"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Tre_Lgt/z_demo_tre_lgt.o"
endseg

beginseg
    name "ovl_En_Fw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fw/z_en_fw.o"
endseg

beginseg
    name "ovl_Bg_Vb_Sima"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Vb_Sima/z_bg_vb_sima.o"
endseg

beginseg
    name "ovl_En_Vb_Ball"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Vb_Ball/z_en_vb_ball.o"
endseg

beginseg
    name "ovl_Bg_Haka_Megane"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Megane/z_bg_haka_megane.o"
endseg

beginseg
    name "ovl_Bg_Haka_MeganeBG"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_MeganeBG/z_bg_haka_meganebg.o"
endseg

beginseg
    name "ovl_Bg_Haka_Ship"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Ship/z_bg_haka_ship.o"
endseg

beginseg
    name "ovl_Bg_Haka_Sgami"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Sgami/z_bg_haka_sgami.o"
endseg

beginseg
    name "ovl_En_Heishi2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.o"
endseg

beginseg
    name "ovl_En_Encount2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Encount2/z_en_encount2.o"
endseg

beginseg
    name "ovl_En_Fire_Rock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fire_Rock/z_en_fire_rock.o"
endseg

beginseg
    name "ovl_En_Brob"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Brob/z_en_brob.o"
endseg

beginseg
    name "ovl_Mir_Ray"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Mir_Ray/z_mir_ray.o"
endseg

beginseg
    name "ovl_Bg_Spot09_Obj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.o"
endseg

beginseg
    name "ovl_Bg_Spot18_Obj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.o"
endseg

beginseg
    name "ovl_Boss_Va"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Va/z_boss_va.o"
endseg

beginseg
    name "ovl_Bg_Haka_Tubo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Tubo/z_bg_haka_tubo.o"
endseg

beginseg
    name "ovl_Bg_Haka_Trap"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Trap/z_bg_haka_trap.o"
endseg

beginseg
    name "ovl_Bg_Haka_Huta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Huta/z_bg_haka_huta.o"
endseg

beginseg
    name "ovl_Bg_Haka_Zou"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Zou/z_bg_haka_zou.o"
endseg

beginseg
    name "ovl_Bg_Spot17_Funen"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot17_Funen/z_bg_spot17_funen.o"
endseg

beginseg
    name "ovl_En_Syateki_Itm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Syateki_Itm/z_en_syateki_itm.o"
endseg

beginseg
    name "ovl_En_Syateki_Man"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.o"
endseg

beginseg
    name "ovl_En_Tana"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tana/z_en_tana.o"
endseg

beginseg
    name "ovl_En_Nb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Nb/z_en_nb.o"
endseg

beginseg
    name "ovl_Boss_Mo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Mo/z_boss_mo.o"
endseg

beginseg
    name "ovl_En_Sb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Sb/z_en_sb.o"
endseg

beginseg
    name "ovl_En_Bigokuta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.o"
endseg

beginseg
    name "ovl_En_Karebaba"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Karebaba/z_en_karebaba.o"
endseg

beginseg
    name "ovl_Bg_Bdan_Objects"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Bdan_Objects/z_bg_bdan_objects.o"
endseg

beginseg
    name "ovl_Demo_Sa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Sa/z_demo_sa.o"
endseg

beginseg
    name "ovl_Demo_Go"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Go/z_demo_go.o"
endseg

beginseg
    name "ovl_En_In"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_In/z_en_in.o"
endseg

beginseg
    name "ovl_En_Tr"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tr/z_en_tr.o"
endseg

beginseg
    name "ovl_Bg_Spot16_Bombstone"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.o"
endseg

beginseg
    name "ovl_Bg_Hidan_Kowarerukabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Hidan_Kowarerukabe/z_bg_hidan_kowarerukabe.o"
endseg

beginseg
    name "ovl_Bg_Bombwall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Bombwall/z_bg_bombwall.o"
endseg

beginseg
    name "ovl_En_Ru2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ru2/z_en_ru2.o"
endseg

beginseg
    name "ovl_Obj_Dekujr"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Dekujr/z_obj_dekujr.o"
endseg

beginseg
    name "ovl_Bg_Mizu_Uzu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mizu_Uzu/z_bg_mizu_uzu.o"
endseg

beginseg
    name "ovl_Bg_Spot06_Objects"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.o"
endseg

beginseg
    name "ovl_Bg_Ice_Objects"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ice_Objects/z_bg_ice_objects.o"
endseg

beginseg
    name "ovl_Bg_Haka_Water"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Water/z_bg_haka_water.o"
endseg

beginseg
    name "ovl_En_Ma2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ma2/z_en_ma2.o"
endseg

beginseg
    name "ovl_En_Bom_Chu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bom_Chu/z_en_bom_chu.o"
endseg

beginseg
    name "ovl_En_Horse_Game_Check"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.o"
endseg

beginseg
    name "ovl_Boss_Tw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Tw/z_boss_tw.o"
endseg

beginseg
    name "ovl_En_Rr"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Rr/z_en_rr.o"
endseg

beginseg
    name "ovl_En_Ba"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ba/z_en_ba.o"
endseg

beginseg
    name "ovl_En_Bx"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bx/z_en_bx.o"
endseg

beginseg
    name "ovl_En_Anubice"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Anubice/z_en_anubice.o"
endseg

beginseg
    name "ovl_En_Anubice_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Anubice_Fire/z_en_anubice_fire.o"
endseg

beginseg
    name "ovl_Bg_Mori_Hashigo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Hashigo/z_bg_mori_hashigo.o"
endseg

beginseg
    name "ovl_Bg_Mori_Hashira4"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Hashira4/z_bg_mori_hashira4.o"
endseg

beginseg
    name "ovl_Bg_Mori_Idomizu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mori_Idomizu/z_bg_mori_idomizu.o"
endseg

beginseg
    name "ovl_Bg_Spot16_Doughnut"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot16_Doughnut/z_bg_spot16_doughnut.o"
endseg

beginseg
    name "ovl_Bg_Bdan_Switch"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Bdan_Switch/z_bg_bdan_switch.o"
endseg

beginseg
    name "ovl_En_Ma1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ma1/z_en_ma1.o"
endseg

beginseg
    name "ovl_Boss_Ganon"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.o"
endseg

beginseg
    name "ovl_Boss_Sst"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Sst/z_boss_sst.o"
endseg

beginseg
    name "ovl_En_Ny"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ny/z_en_ny.o"
endseg

beginseg
    name "ovl_En_Fr"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fr/z_en_fr.o"
endseg

beginseg
    name "ovl_Item_Shield"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/z_item_shield.o"
endseg

beginseg
    name "ovl_Bg_Ice_Shelter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.o"
endseg

beginseg
    name "ovl_En_Ice_Hono"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ice_Hono/z_en_ice_hono.o"
endseg

beginseg
    name "ovl_Item_Ocarina"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Ocarina/z_item_ocarina.o"
endseg

beginseg
    name "ovl_Magic_Dark"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Magic_Dark/z_magic_dark.o"
endseg

beginseg
    name "ovl_Demo_6K"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_6K/z_demo_6k.o"
endseg

beginseg
    name "ovl_En_Anubice_Tag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Anubice_Tag/z_en_anubice_tag.o"
endseg

beginseg
    name "ovl_Bg_Haka_Gate"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Haka_Gate/z_bg_haka_gate.o"
endseg

beginseg
    name "ovl_Bg_Spot15_Saku"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot15_Saku/z_bg_spot15_saku.o"
endseg

beginseg
    name "ovl_Bg_Jya_Goroiwa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Goroiwa/z_bg_jya_goroiwa.o"
endseg

beginseg
    name "ovl_Bg_Jya_Zurerukabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Zurerukabe/z_bg_jya_zurerukabe.o"
endseg

beginseg
    name "ovl_Bg_Jya_Cobra"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Cobra/z_bg_jya_cobra.o"
endseg

beginseg
    name "ovl_Bg_Jya_Kanaami"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Kanaami/z_bg_jya_kanaami.o"
endseg

beginseg
    name "ovl_Fishing"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Fishing/z_fishing.o"
endseg

beginseg
    name "ovl_Obj_Oshihiki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.o"
endseg

beginseg
    name "ovl_Bg_Gate_Shutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gate_Shutter/z_bg_gate_shutter.o"
endseg

beginseg
    name "ovl_Eff_Dust"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Eff_Dust/z_eff_dust.o"
endseg

beginseg
    name "ovl_Bg_Spot01_Fusya"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot01_Fusya/z_bg_spot01_fusya.o"
endseg

beginseg
    name "ovl_Bg_Spot01_Idohashira"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot01_Idohashira/z_bg_spot01_idohashira.o"
endseg

beginseg
    name "ovl_Bg_Spot01_Idomizu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot01_Idomizu/z_bg_spot01_idomizu.o"
endseg

beginseg
    name "ovl_Bg_Po_Syokudai"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Po_Syokudai/z_bg_po_syokudai.o"
endseg

beginseg
    name "ovl_Bg_Ganon_Otyuka"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ganon_Otyuka/z_bg_ganon_otyuka.o"
endseg

beginseg
    name "ovl_Bg_Spot15_Rrbox"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot15_Rrbox/z_bg_spot15_rrbox.o"
endseg

beginseg
    name "ovl_Bg_Umajump"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.o"
endseg

beginseg
    name "ovl_En_Insect"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Insect/z_en_insect.o"
endseg

beginseg
    name "ovl_En_Butte"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Butte/z_en_butte.o"
endseg

beginseg
    name "ovl_En_Fish"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fish/z_en_fish.o"
endseg

beginseg
    name "ovl_Bg_Spot08_Iceblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot08_Iceblock/z_bg_spot08_iceblock.o"
endseg

beginseg
    name "ovl_Item_Etcetera"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Etcetera/z_item_etcetera.o"
endseg

beginseg
    name "ovl_Arrow_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Arrow_Fire/z_arrow_fire.o"
endseg

beginseg
    name "ovl_Arrow_Ice"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.o"
endseg

beginseg
    name "ovl_Arrow_Light"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Arrow_Light/z_arrow_light.o"
endseg

beginseg
    name "ovl_Obj_Kibako"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Kibako/z_obj_kibako.o"
endseg

beginseg
    name "ovl_Obj_Tsubo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.o"
endseg

beginseg
    name "ovl_En_Wonder_Item"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.o"
endseg

beginseg
    name "ovl_En_Ik"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ik/z_en_ik.o"
endseg

beginseg
    name "ovl_Demo_Ik"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Ik/z_demo_ik.o"
endseg

beginseg
    name "ovl_En_Skj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Skj/z_en_skj.o"
endseg

beginseg
    name "ovl_En_Skjneedle"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Skjneedle/z_en_skjneedle.o"
endseg

beginseg
    name "ovl_En_G_Switch"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.o"
endseg

beginseg
    name "ovl_Demo_Ext"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Ext/z_demo_ext.o"
endseg

beginseg
    name "ovl_Demo_Shd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Shd/z_demo_shd.o"
endseg

beginseg
    name "ovl_En_Dns"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dns/z_en_dns.o"
endseg

beginseg
    name "ovl_Elf_Msg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Elf_Msg/z_elf_msg.o"
endseg

beginseg
    name "ovl_En_Honotrap"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Honotrap/z_en_honotrap.o"
endseg

beginseg
    name "ovl_En_Tubo_Trap"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.o"
endseg

beginseg
    name "ovl_Obj_Ice_Poly"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Ice_Poly/z_obj_ice_poly.o"
endseg

beginseg
    name "ovl_Bg_Spot03_Taki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot03_Taki/z_bg_spot03_taki.o"
endseg

beginseg
    name "ovl_Bg_Spot07_Taki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.o"
endseg

beginseg
    name "ovl_En_Fz"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fz/z_en_fz.o"
endseg

beginseg
    name "ovl_En_Po_Relay"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.o"
endseg

beginseg
    name "ovl_Bg_Relay_Objects"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Relay_Objects/z_bg_relay_objects.o"
endseg

beginseg
    name "ovl_En_Diving_Game"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.o"
endseg

beginseg
    name "ovl_En_Kusa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kusa/z_en_kusa.o"
endseg

beginseg
    name "ovl_Obj_Bean"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Bean/z_obj_bean.o"
endseg

beginseg
    name "ovl_Obj_Bombiwa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Bombiwa/z_obj_bombiwa.o"
endseg

beginseg
    name "ovl_Obj_Switch"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Switch/z_obj_switch.o"
endseg

beginseg
    name "ovl_Obj_Elevator"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Elevator/z_obj_elevator.o"
endseg

beginseg
    name "ovl_Obj_Lift"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Lift/z_obj_lift.o"
endseg

beginseg
    name "ovl_Obj_Hsblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Hsblock/z_obj_hsblock.o"
endseg

beginseg
    name "ovl_En_Okarina_Tag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag_cutscene_data.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.o"
endseg

beginseg
    name "ovl_En_Yabusame_Mark"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Yabusame_Mark/z_en_yabusame_mark.o"
endseg

beginseg
    name "ovl_En_Goroiwa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.o"
endseg

beginseg
    name "ovl_En_Ex_Ruppy"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.o"
endseg

beginseg
    name "ovl_En_Toryo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Toryo/z_en_toryo.o"
endseg

beginseg
    name "ovl_En_Daiku"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Daiku/z_en_daiku.o"
endseg

beginseg
    name "ovl_En_Nwc"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Nwc/z_en_nwc.o"
endseg

beginseg
    name "ovl_En_Blkobj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Blkobj/z_en_blkobj.o"
endseg

beginseg
    name "ovl_Item_Inbox"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Inbox/z_item_inbox.o"
endseg

beginseg
    name "ovl_En_Ge1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ge1/z_en_ge1.o"
endseg

beginseg
    name "ovl_Obj_Blockstop"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Blockstop/z_obj_blockstop.o"
endseg

beginseg
    name "ovl_En_Sda"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Sda/z_en_sda.o"
endseg

beginseg
    name "ovl_En_Clear_Tag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.o"
endseg

beginseg
    name "ovl_En_Niw_Lady"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.o"
endseg

beginseg
    name "ovl_En_Gm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Gm/z_en_gm.o"
endseg

beginseg
    name "ovl_En_Ms"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ms/z_en_ms.o"
endseg

beginseg
    name "ovl_En_Hs"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hs/z_en_hs.o"
endseg

beginseg
    name "ovl_Bg_Ingate"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ingate/z_bg_ingate.o"
endseg

beginseg
    name "ovl_En_Kanban"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kanban/z_en_kanban.o"
endseg

beginseg
    name "ovl_En_Heishi3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Heishi3/z_en_heishi3.o"
endseg

beginseg
    name "ovl_En_Syateki_Niw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.o"
endseg

beginseg
    name "ovl_En_Attack_Niw"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Attack_Niw/z_en_attack_niw.o"
endseg

beginseg
    name "ovl_Bg_Spot01_Idosoko"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot01_Idosoko/z_bg_spot01_idosoko.o"
endseg

beginseg
    name "ovl_En_Sa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Sa/z_en_sa.o"
endseg

beginseg
    name "ovl_En_Wonder_Talk"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wonder_Talk/z_en_wonder_talk.o"
endseg

beginseg
    name "ovl_Bg_Gjyo_Bridge"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gjyo_Bridge/z_bg_gjyo_bridge.o"
endseg

beginseg
    name "ovl_En_Ds"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ds/z_en_ds.o"
endseg

beginseg
    name "ovl_En_Mk"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mk/z_en_mk.o"
endseg

beginseg
    name "ovl_En_Bom_Bowl_Man"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.o"
endseg

beginseg
    name "ovl_En_Bom_Bowl_Pit"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bom_Bowl_Pit/z_en_bom_bowl_pit.o"
endseg

beginseg
    name "ovl_En_Owl"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Owl/z_en_owl.o"
endseg

beginseg
    name "ovl_En_Ishi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ishi/z_en_ishi.o"
endseg

beginseg
    name "ovl_Obj_Hana"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Hana/z_obj_hana.o"
endseg

beginseg
    name "ovl_Obj_Lightswitch"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.o"
endseg

beginseg
    name "ovl_Obj_Mure2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Mure2/z_obj_mure2.o"
endseg

beginseg
    name "ovl_En_Go"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Go/z_en_go.o"
endseg

beginseg
    name "ovl_En_Fu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Fu/z_en_fu.o"
endseg

beginseg
    name "ovl_En_Changer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Changer/z_en_changer.o"
endseg

beginseg
    name "ovl_Bg_Jya_Megami"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Megami/z_bg_jya_megami.o"
endseg

beginseg
    name "ovl_Bg_Jya_Lift"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Lift/z_bg_jya_lift.o"
endseg

beginseg
    name "ovl_Bg_Jya_Bigmirror"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Bigmirror/z_bg_jya_bigmirror.o"
endseg

beginseg
    name "ovl_Bg_Jya_Bombchuiwa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Bombchuiwa/z_bg_jya_bombchuiwa.o"
endseg

beginseg
    name "ovl_Bg_Jya_Amishutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Amishutter/z_bg_jya_amishutter.o"
endseg

beginseg
    name "ovl_Bg_Jya_Bombiwa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Bombiwa/z_bg_jya_bombiwa.o"
endseg

beginseg
    name "ovl_Bg_Spot18_Basket"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot18_Basket/z_bg_spot18_basket.o"
endseg

beginseg
    name "ovl_En_Ganon_Organ"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ganon_Organ/z_en_ganon_organ.o"
endseg

beginseg
    name "ovl_En_Siofuki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Siofuki/z_en_siofuki.o"
endseg

beginseg
    name "ovl_En_Stream"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Stream/z_en_stream.o"
endseg

beginseg
    name "ovl_En_Mm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mm/z_en_mm.o"
endseg

beginseg
    name "ovl_En_Ko"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ko/z_en_ko.o"
endseg

beginseg
    name "ovl_En_Kz"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kz/z_en_kz.o"
endseg

beginseg
    name "ovl_En_Weather_Tag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.o"
endseg

beginseg
    name "ovl_Bg_Sst_Floor"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Sst_Floor/z_bg_sst_floor.o"
endseg

beginseg
    name "ovl_En_Ani"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ani/z_en_ani.o"
endseg

beginseg
    name "ovl_En_Ex_Item"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.o"
endseg

beginseg
    name "ovl_Bg_Jya_Ironobj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Ironobj/z_bg_jya_ironobj.o"
endseg

beginseg
    name "ovl_En_Js"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Js/z_en_js.o"
endseg

beginseg
    name "ovl_En_Jsjutan"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Jsjutan/z_en_jsjutan.o"
endseg

beginseg
    name "ovl_En_Cs"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Cs/z_en_cs.o"
endseg

beginseg
    name "ovl_En_Md"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Md/z_en_md.o"
endseg

beginseg
    name "ovl_En_Hy"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hy/z_en_hy.o"
endseg

beginseg
    name "ovl_En_Ganon_Mant"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ganon_Mant/z_en_ganon_mant.o"
endseg

beginseg
    name "ovl_En_Okarina_Effect"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.o"
endseg

beginseg
    name "ovl_En_Mag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mag/z_en_mag.o"
endseg

beginseg
    name "ovl_Door_Gerudo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Gerudo/z_door_gerudo.o"
endseg

beginseg
    name "ovl_Elf_Msg2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Elf_Msg2/z_elf_msg2.o"
endseg

beginseg
    name "ovl_Demo_Gt"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Gt/z_demo_gt.o"
endseg

beginseg
    name "ovl_En_Po_Field"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Po_Field/z_en_po_field.o"
endseg

beginseg
    name "ovl_Efc_Erupc"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.o"
endseg

beginseg
    name "ovl_Bg_Zg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Zg/z_bg_zg.o"
endseg

beginseg
    name "ovl_En_Heishi4"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.o"
endseg

beginseg
    name "ovl_En_Zl3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zl3/z_en_zl3.o"
endseg

beginseg
    name "ovl_Boss_Ganon2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.o"
endseg

beginseg
    name "ovl_En_Kakasi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.o"
endseg

beginseg
    name "ovl_En_Takara_Man"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Takara_Man/z_en_takara_man.o"
endseg

beginseg
    name "ovl_Obj_Makeoshihiki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Makeoshihiki/z_obj_makeoshihiki.o"
endseg

beginseg
    name "ovl_Oceff_Spot"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Spot/z_oceff_spot.o"
endseg

beginseg
    name "ovl_End_Title"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_End_Title/z_end_title.o"
endseg

beginseg
    name "ovl_En_Torch"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Torch/z_en_torch.o"
endseg

beginseg
    name "ovl_Demo_Ec"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Ec/z_demo_ec.o"
endseg

beginseg
    name "ovl_Shot_Sun"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Shot_Sun/z_shot_sun.o"
endseg

beginseg
    name "ovl_En_Dy_Extra"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.o"
endseg

beginseg
    name "ovl_En_Wonder_Talk2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wonder_Talk2/z_en_wonder_talk2.o"
endseg

beginseg
    name "ovl_En_Ge2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ge2/z_en_ge2.o"
endseg

beginseg
    name "ovl_Obj_Roomtimer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Roomtimer/z_obj_roomtimer.o"
endseg

beginseg
    name "ovl_En_Ssh"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ssh/z_en_ssh.o"
endseg

beginseg
    name "ovl_En_Sth"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Sth/z_en_sth.o"
endseg

beginseg
    name "ovl_Oceff_Wipe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Wipe/z_oceff_wipe.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dust"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dust/z_eff_ss_dust.o"
endseg

beginseg
    name "ovl_Effect_Ss_KiraKira"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_KiraKira/z_eff_ss_kirakira.o"
endseg

beginseg
    name "ovl_Effect_Ss_Bomb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Bomb/z_eff_ss_bomb.o"
endseg

beginseg
    name "ovl_Effect_Ss_Bomb2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Bomb2/z_eff_ss_bomb2.o"
endseg

beginseg
    name "ovl_Effect_Ss_Blast"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Blast/z_eff_ss_blast.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Spk"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Spk/z_eff_ss_g_spk.o"
endseg

beginseg
    name "ovl_Effect_Ss_D_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_D_Fire/z_eff_ss_d_fire.o"
endseg

beginseg
    name "ovl_Effect_Ss_Bubble"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Bubble/z_eff_ss_bubble.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Ripple"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Ripple/z_eff_ss_g_ripple.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Splash"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Splash/z_eff_ss_g_splash.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Magma"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Magma/z_eff_ss_g_magma.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Fire/z_eff_ss_g_fire.o"
endseg

beginseg
    name "ovl_Effect_Ss_Lightning"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Lightning/z_eff_ss_lightning.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dt_Bubble"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dt_Bubble/z_eff_ss_dt_bubble.o"
endseg

beginseg
    name "ovl_Effect_Ss_Hahen"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Hahen/z_eff_ss_hahen.o"
endseg

beginseg
    name "ovl_Effect_Ss_Stick"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Stick/z_eff_ss_stick.o"
endseg

beginseg
    name "ovl_Effect_Ss_Sibuki"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Sibuki/z_eff_ss_sibuki.o"
endseg

beginseg
    name "ovl_Effect_Ss_Sibuki2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Sibuki2/z_eff_ss_sibuki2.o"
endseg

beginseg
    name "ovl_Effect_Ss_G_Magma2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_G_Magma2/z_eff_ss_g_magma2.o"
endseg

beginseg
    name "ovl_Effect_Ss_Stone1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Stone1/z_eff_ss_stone1.o"
endseg

beginseg
    name "ovl_Effect_Ss_HitMark"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_HitMark/z_eff_ss_hitmark.o"
endseg

beginseg
    name "ovl_Effect_Ss_Fhg_Flash"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.o"
endseg

beginseg
    name "ovl_Effect_Ss_K_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_K_Fire/z_eff_ss_k_fire.o"
endseg

beginseg
    name "ovl_Effect_Ss_Solder_Srch_Ball"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Solder_Srch_Ball/z_eff_ss_solder_srch_ball.o"
endseg

beginseg
    name "ovl_Effect_Ss_Kakera"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Kakera/z_eff_ss_kakera.o"
endseg

beginseg
    name "ovl_Effect_Ss_Ice_Piece"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Ice_Piece/z_eff_ss_ice_piece.o"
endseg

beginseg
    name "ovl_Effect_Ss_En_Ice"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_En_Ice/z_eff_ss_en_ice.o"
endseg

beginseg
    name "ovl_Effect_Ss_Fire_Tail"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Fire_Tail/z_eff_ss_fire_tail.o"
endseg

beginseg
    name "ovl_Effect_Ss_En_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_En_Fire/z_eff_ss_en_fire.o"
endseg

beginseg
    name "ovl_Effect_Ss_Extra"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.o"
endseg

beginseg
    name "ovl_Effect_Ss_Fcircle"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Fcircle/z_eff_ss_fcircle.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dead_Db"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dead_Db/z_eff_ss_dead_db.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dead_Dd"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dead_Dd/z_eff_ss_dead_dd.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dead_Ds"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dead_Ds/z_eff_ss_dead_ds.o"
endseg

beginseg
    name "ovl_Effect_Ss_Dead_Sound"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dead_Sound/z_eff_ss_dead_sound.o"
endseg

beginseg
    name "ovl_Oceff_Storm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Storm/z_oceff_storm.o"
endseg

beginseg
    name "ovl_En_Weiyer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Weiyer/z_en_weiyer.o"
endseg

beginseg
    name "ovl_Bg_Spot05_Soko"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot05_Soko/z_bg_spot05_soko.o"
endseg

beginseg
    name "ovl_Bg_Jya_1flift"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_1flift/z_bg_jya_1flift.o"
endseg

beginseg
    name "ovl_Bg_Jya_Haheniron"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Haheniron/z_bg_jya_haheniron.o"
endseg

beginseg
    name "ovl_Bg_Spot12_Gate"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot12_Gate/z_bg_spot12_gate.o"
endseg

beginseg
    name "ovl_Bg_Spot12_Saku"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot12_Saku/z_bg_spot12_saku.o"
endseg

beginseg
    name "ovl_En_Hintnuts"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hintnuts/z_en_hintnuts.o"
endseg

beginseg
    name "ovl_En_Nutsball"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.o"
endseg

beginseg
    name "ovl_Bg_Spot00_Break"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot00_Break/z_bg_spot00_break.o"
endseg

beginseg
    name "ovl_En_Shopnuts"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Shopnuts/z_en_shopnuts.o"
endseg

beginseg
    name "ovl_En_It"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_It/z_en_it.o"
endseg

beginseg
    name "ovl_En_GeldB"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_GeldB/z_en_geldb.o"
endseg

beginseg
    name "ovl_Oceff_Wipe2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Wipe2/z_oceff_wipe2.o"
endseg

beginseg
    name "ovl_Oceff_Wipe3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Wipe3/z_oceff_wipe3.o"
endseg

beginseg
    name "ovl_En_Niw_Girl"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Niw_Girl/z_en_niw_girl.o"
endseg

beginseg
    name "ovl_En_Dog"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dog/z_en_dog.o"
endseg

beginseg
    name "ovl_En_Si"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Si/z_en_si.o"
endseg

beginseg
    name "ovl_Bg_Spot01_Objects2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot01_Objects2/z_bg_spot01_objects2.o"
endseg

beginseg
    name "ovl_Obj_Comb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Comb/z_obj_comb.o"
endseg

beginseg
    name "ovl_Bg_Spot11_Bakudankabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot11_Bakudankabe/z_bg_spot11_bakudankabe.o"
endseg

beginseg
    name "ovl_Obj_Kibako2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Kibako2/z_obj_kibako2.o"
endseg

beginseg
    name "ovl_En_Dnt_Demo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dnt_Demo/z_en_dnt_demo.o"
endseg

beginseg
    name "ovl_En_Dnt_Jiji"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dnt_Jiji/z_en_dnt_jiji.o"
endseg

beginseg
    name "ovl_En_Dnt_Nomal"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dnt_Nomal/z_en_dnt_nomal.o"
endseg

beginseg
    name "ovl_En_Guest"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Guest/z_en_guest.o"
endseg

beginseg
    name "ovl_Bg_Bom_Guard"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Bom_Guard/z_bg_bom_guard.o"
endseg

beginseg
    name "ovl_En_Hs2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hs2/z_en_hs2.o"
endseg

beginseg
    name "ovl_Demo_Kekkai"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Kekkai/z_demo_kekkai.o"
endseg

beginseg
    name "ovl_Bg_Spot08_Bakudankabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot08_Bakudankabe/z_bg_spot08_bakudankabe.o"
endseg

beginseg
    name "ovl_Bg_Spot17_Bakudankabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot17_Bakudankabe/z_bg_spot17_bakudankabe.o"
endseg

beginseg
    name "ovl_Obj_Mure3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Mure3/z_obj_mure3.o"
endseg

beginseg
    name "ovl_En_Tg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tg/z_en_tg.o"
endseg

beginseg
    name "ovl_En_Mu"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mu/z_en_mu.o"
endseg

beginseg
    name "ovl_En_Go2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Go2/z_en_go2.o"
endseg

beginseg
    name "ovl_En_Wf"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wf/z_en_wf.o"
endseg

beginseg
    name "ovl_En_Skb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Skb/z_en_skb.o"
endseg

beginseg
    name "ovl_Demo_Gj"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Gj/z_demo_gj.o"
endseg

beginseg
    name "ovl_Demo_Geff"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Demo_Geff/z_demo_geff.o"
endseg

beginseg
    name "ovl_Bg_Gnd_Firemeiro"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gnd_Firemeiro/z_bg_gnd_firemeiro.o"
endseg

beginseg
    name "ovl_Bg_Gnd_Darkmeiro"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gnd_Darkmeiro/z_bg_gnd_darkmeiro.o"
endseg

beginseg
    name "ovl_Bg_Gnd_Soulmeiro"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gnd_Soulmeiro/z_bg_gnd_soulmeiro.o"
endseg

beginseg
    name "ovl_Bg_Gnd_Nisekabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gnd_Nisekabe/z_bg_gnd_nisekabe.o"
endseg

beginseg
    name "ovl_Bg_Gnd_Iceblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Gnd_Iceblock/z_bg_gnd_iceblock.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Sp"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.o"
endseg

beginseg
    name "ovl_En_Gb"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Gb/z_en_gb.o"
endseg

beginseg
    name "ovl_En_Gs"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Gs/z_en_gs.o"
endseg

beginseg
    name "ovl_Bg_Mizu_Bwall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mizu_Bwall/z_bg_mizu_bwall.o"
endseg

beginseg
    name "ovl_Bg_Mizu_Shutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Mizu_Shutter/z_bg_mizu_shutter.o"
endseg

beginseg
    name "ovl_En_Daiku_Kakariko"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Daiku_Kakariko/z_en_daiku_kakariko.o"
endseg

beginseg
    name "ovl_Bg_Bowl_Wall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Bowl_Wall/z_bg_bowl_wall.o"
endseg

beginseg
    name "ovl_En_Wall_Tubo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Wall_Tubo/z_en_wall_tubo.o"
endseg

beginseg
    name "ovl_En_Po_Desert"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Po_Desert/z_en_po_desert.o"
endseg

beginseg
    name "ovl_En_Crow"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Crow/z_en_crow.o"
endseg

beginseg
    name "ovl_Door_Killer"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Killer/z_door_killer.o"
endseg

beginseg
    name "ovl_Bg_Spot11_Oasis"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot11_Oasis/z_bg_spot11_oasis.o"
endseg

beginseg
    name "ovl_Bg_Spot18_Futa"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot18_Futa/z_bg_spot18_futa.o"
endseg

beginseg
    name "ovl_Bg_Spot18_Shutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Spot18_Shutter/z_bg_spot18_shutter.o"
endseg

beginseg
    name "ovl_En_Ma3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ma3/z_en_ma3.o"
endseg

beginseg
    name "ovl_En_Cow"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Cow/z_en_cow.o"
endseg

beginseg
    name "ovl_Bg_Ice_Turara"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ice_Turara/z_bg_ice_turara.o"
endseg

beginseg
    name "ovl_Bg_Ice_Shutter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ice_Shutter/z_bg_ice_shutter.o"
endseg

beginseg
    name "ovl_En_Kakasi2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kakasi2/z_en_kakasi2.o"
endseg

beginseg
    name "ovl_En_Kakasi3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kakasi3/z_en_kakasi3.o"
endseg

beginseg
    name "ovl_Oceff_Wipe4"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Oceff_Wipe4/z_oceff_wipe4.o"
endseg

beginseg
    name "ovl_En_Eg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Eg/z_en_eg.o"
endseg

beginseg
    name "ovl_Bg_Menkuri_Nisekabe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Menkuri_Nisekabe/z_bg_menkuri_nisekabe.o"
endseg

beginseg
    name "ovl_En_Zo"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zo/z_en_zo.o"
endseg

beginseg
    name "ovl_Effect_Ss_Ice_Smoke"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Ice_Smoke/z_eff_ss_ice_smoke.o"
endseg

beginseg
    name "ovl_Obj_Makekinsuta"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Makekinsuta/z_obj_makekinsuta.o"
endseg

beginseg
    name "ovl_En_Ge3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ge3/z_en_ge3.o"
endseg

beginseg
    name "ovl_Obj_Timeblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Timeblock/z_obj_timeblock.o"
endseg

beginseg
    name "ovl_Obj_Hamishi"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.o"
endseg

beginseg
    name "ovl_En_Zl4"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Zl4/z_en_zl4.o"
endseg

beginseg
    name "ovl_En_Mm2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mm2/z_en_mm2.o"
endseg

beginseg
    name "ovl_Bg_Jya_Block"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Jya_Block/z_bg_jya_block.o"
endseg

beginseg
    name "ovl_Obj_Warp2block"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Warp2block/z_obj_warp2block.o"
endseg
