beginseg
    name "g_pn_01"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_01.o"
endseg

beginseg
    name "g_pn_02"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_02.o"
endseg

beginseg
    name "g_pn_03"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_03.o"
endseg

beginseg
    name "g_pn_04"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_04.o"
endseg

beginseg
    name "g_pn_05"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_05.o"
endseg

beginseg
    name "g_pn_06"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_06.o"
endseg

beginseg
    name "g_pn_07"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_07.o"
endseg

beginseg
    name "g_pn_08"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_08.o"
endseg

beginseg
    name "g_pn_09"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_09.o"
endseg

beginseg
    name "g_pn_10"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_10.o"
endseg

beginseg
    name "g_pn_11"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_11.o"
endseg

beginseg
    name "g_pn_12"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_12.o"
endseg

beginseg
    name "g_pn_13"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_13.o"
endseg

beginseg
    name "g_pn_14"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_14.o"
endseg

beginseg
    name "g_pn_15"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_15.o"
endseg

beginseg
    name "g_pn_16"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_16.o"
endseg

beginseg
    name "g_pn_17"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_17.o"
endseg

beginseg
    name "g_pn_18"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_18.o"
endseg

beginseg
    name "g_pn_19"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_19.o"
endseg

beginseg
    name "g_pn_20"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_20.o"
endseg

beginseg
    name "g_pn_21"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_21.o"
endseg

beginseg
    name "g_pn_22"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_22.o"
endseg

beginseg
    name "g_pn_23"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_23.o"
endseg

beginseg
    name "g_pn_24"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_24.o"
endseg

beginseg
    name "g_pn_25"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_25.o"
endseg

beginseg
    name "g_pn_26"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_26.o"
endseg

beginseg
    name "g_pn_27"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_27.o"
endseg

beginseg
    name "g_pn_28"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_28.o"
endseg

beginseg
    name "g_pn_29"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_29.o"
endseg

beginseg
    name "g_pn_30"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_30.o"
endseg

beginseg
    name "g_pn_31"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_31.o"
endseg

beginseg
    name "g_pn_32"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_32.o"
endseg

beginseg
    name "g_pn_33"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_33.o"
endseg

beginseg
    name "g_pn_34"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_34.o"
endseg

beginseg
    name "g_pn_35"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_35.o"
endseg

beginseg
    name "g_pn_36"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_36.o"
endseg

beginseg
    name "g_pn_37"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_37.o"
endseg

beginseg
    name "g_pn_38"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_38.o"
endseg

beginseg
    name "g_pn_39"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_39.o"
endseg

beginseg
    name "g_pn_40"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_40.o"
endseg

beginseg
    name "g_pn_41"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_41.o"
endseg

beginseg
    name "g_pn_42"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_42.o"
endseg

beginseg
    name "g_pn_43"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_43.o"
endseg

beginseg
    name "g_pn_44"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_44.o"
endseg

beginseg
    name "g_pn_45"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_45.o"
endseg

beginseg
    name "g_pn_46"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_46.o"
endseg

beginseg
    name "g_pn_47"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_47.o"
endseg

beginseg
    name "g_pn_48"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_48.o"
endseg

beginseg
    name "g_pn_49"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_49.o"
endseg

beginseg
    name "g_pn_50"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_50.o"
endseg

beginseg
    name "g_pn_51"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_51.o"
endseg

beginseg
    name "g_pn_52"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_52.o"
endseg

beginseg
    name "g_pn_53"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_53.o"
endseg

beginseg
    name "g_pn_54"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_54.o"
endseg

beginseg
    name "g_pn_55"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_55.o"
endseg

beginseg
    name "g_pn_56"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_56.o"
endseg

beginseg
    name "g_pn_57"
    compress
    romalign 0x1000
    include "$(BUILD_DIR)/assets/textures/place_title_cards/g_pn_57.o"
endseg
