#ifndef OBJECT_DOG_H
#define OBJECT_DOG_H 1

extern s16 sDogBarkAnimFrameData[];
extern JointIndex sDogBarkAnimJointIndices[];
extern AnimationHeader gDogBarkAnim;
extern s16 sDogBowAnimFrameData[];
extern JointIndex sDogBowAnimJointIndices[];
extern AnimationHeader gDogBowAnim;
extern s16 sDogBow2AnimFrameData[];
extern JointIndex sDogBow2AnimJointIndices[];
extern AnimationHeader gDogBow2Anim;
extern s16 sDogRunAnimFrameData[];
extern JointIndex sDogRunAnimJointIndices[];
extern AnimationHeader gDogRunAnim;
extern s16 sDogSitAnimFrameData[];
extern JointIndex sDogSitAnimJointIndices[];
extern AnimationHeader gDogSitAnim;
extern s16 sDogWalkAnimFrameData[];
extern JointIndex sDogWalkAnimJointIndices[];
extern AnimationHeader gDogWalkAnim;
extern u64 gDogFur1Tex[];
extern u64 gDogFur2Tex[];
extern u64 gDogFur3Tex[];
extern u64 gDogFaceEyeTex[];
extern u64 gDogFaceNoseTex[];
extern u64 gDogFur4Tex[];
extern u64 gDogPawTex[];
extern u64 gDogFaceHairTex[];
extern Vtx object_dogVtx_004D80[];
extern Gfx gDogHeadDL[];
extern Gfx gDogRightFaceHairDL[];
extern Gfx gDogLeftFaceHairDL[];
extern Gfx gDogFrontBodyDL[];
extern Gfx gDogFrontRightLegDL[];
extern Gfx gDogFrontLeftLegDL[];
extern Gfx gDogBackBodyDL[];
extern Gfx gDogBackRightLegDL[];
extern Gfx gDogBackLeftLegDL[];
extern Gfx gDogTailDL[];
extern StandardLimb gDogRootLimb;
extern StandardLimb gDogBodyBackLimb;
extern StandardLimb gDogBodyFrontLimb;
extern StandardLimb gDogHeadControlLimb;
extern StandardLimb gDogHeadLimb;
extern StandardLimb gDogRightFaceHairLimb;
extern StandardLimb gDogLeftFaceHairLimb;
extern StandardLimb gDogFrontRightLegLimb;
extern StandardLimb gDogFrontLeftLegLimb;
extern StandardLimb gDogBackRightLegLimb;
extern StandardLimb gDogBackLeftLegLimb;
extern StandardLimb gDogTailLimb;
extern void* gDogSkelLimbs[];
extern FlexSkeletonHeader gDogSkel;

#endif
