#ifndef GAMEPLAY_KEEP_H
#define GAMEPLAY_KEEP_H

#include "hilite_textures.h"
#include "link_textures.h"
#include "player_pause_joint_tables.h"
#include "player_anim_headers.h"
#include "debug_models.h"
#include "gArrow1_Anim.h"
#include "gArrow2_Anim.h"
#include "arrow_skel.h"
#include "unk_eff_blure_tex.h"
#include "bomb_body.h"
#include "bomb_cap.h"
#include "bombchu_body.h"
#include "eff_bomb_explosion.h"
#include "eff_fragments_1.h"
#include "boomerang.h"
#include "compass_arrow.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0xC880.h"
#endif
#include "lock_on_arrow.h"
#include "hilite3_tex.h"
#include "eff_fragments_2_model.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0xCE60.h"
#endif
#include "shopkeeper_controls_tex.h"
#include "rock_fragments_model.h"
#include "rock_fragments_tex.h"
#include "gDoorChildOpeningLeftAnim.h"
#include "gDoorChildOpeningRightAnim.h"
#include "door_skel.h"
#include "gDoorAdultOpeningRightAnim.h"
#include "eff_dust.h"
#include "eff_flash.h"
#include "spin_attack.h"
#include "gameplay_keep_0x13700.h"
#include "fairy_anim.h"
#include "fairy_skel.h"
#include "gameplay_keep_0x16A50.h"
#include "hilite4_tex.h"
#include "gameplay_keep_0x173D0.h"
#include "gFishOutOfWaterAnim.h"
#include "gameplay_keep_0x18610.h"
#include "gFishInWaterAnim.h"
#include "eff_shockwave.h"
#include "eff_bubble.h"
#include "eff_fire_footprint.h"
#include "unused_bubbles.h"
#include "lens_mask_tex.h"
#include "eff_hitmark.h"
#include "gameplay_keep_0x21810.h"
#include "eff_magma_bubble.h"
#include "eff_water_ripple.h"
#include "eff_spark_model.h"
#include "eff_water_splash.h"
#include "unknown_eff_stone.h"
#include "eff_lightning.h"
#include "eff_enemy_death_flame.h"
#include "gameplay_keep_0x32090.h"
#include "gameplay_keep_0x33090.h"
#include "eff_ice_fragments.h"
#include "gameplay_keep_0x33910.h"
#include "gBugCrawlAnim.h"
#include "bug_skel.h"
#include "cuttable_shrub.h"
#include "lens_flare.h"
#include "eff_sparkles.h"
#include "hover_boots_circle.h"
#include "moon.h"
#include "gameplay_keep_0x38FB0.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0x39850.h"
#include "unused_bomb_icon_model_ntsc.h"
#include "unused_heart_icon_model_ntsc.h"
#include "unused_arrow_icon_model_ntsc.h"
#endif
#include "gLargerCubeCol.h"
#include "liftable_rock_model.h"
#include "gameplay_keep_0x39710.h"
#include "gWideTallBlockCol.h"
#include "flat_block_model.h"
#include "gTallBlockCol.h"
#include "gameplay_keep_0x39DF0.h"
#include "small_flat_block_col.h"
#include "flat_rot_block_model.h"
#include "gLargerFlatBlockCol.h"
#include "small_cube_model.h"
#include "small_cube_col.h"
#include "tree_stump_model.h"
#include "grass_blades_model.h"
#include "gameplay_keep_0x3AC30.h"
#include "heart_piece_interior_model.h"
#include "gameplay_keep_0x3B1E0.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0x3C610.h"
#include "unused_heart_container_icon_model_ntsc.h"
#endif
#include "rectangular_sign_model.h"
#include "directional_sign_model.h"
#include "gameplay_keep_0x3C870.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0x3FD80.h"
#endif
#include "drop_recovery_heart_tex.h"
#if OOT_REGION != REGION_EU
#include "unused_heart_piece_icon_tex_ntsc.h"
#endif
#include "item_drop_dl.h"
#include "gameplay_keep_0x3F140.h"
#include "rupee.h"
#if OOT_REGION != REGION_EU
#include "item_drops_ntsc.h"
#endif
#include "rupee_light_red_tex.h"
#if OOT_REGION != REGION_EU
#include "gameplay_keep_ntsc_0x46A40.h"
#endif
#include "gameplay_keep_0x42530.h"
#include "gameplay_keep_0x43530.h"
#include "gameplay_keep_0x44530.h"
#include "gameplay_keep_0x45530.h"
#include "gameplay_keep_0x45D30.h"
#include "sign_textures.h"
#include "raindrop_model.h"
#include "shadow_foot.h"
#include "shadow_circle.h"
#include "shadow_horse.h"
#include "gameplay_keep_0x49F20.h"
#include "gameplay_keep_0x4A090.h"
#include "sun_textures.h"
#include "sun_evening_textures.h"
#include "gameplay_keep_0x4D160.h"
#include "lock_on_reticle.h"
#include "eff_fire.h"
#include "gameplay_keep_0x4E660.h"
#include "gameplay_keep_0x515B0.h"
#include "dust_textures.h"
#include "circle_glow_textures.h"
#include "gameplay_keep_0x55DB0.h"
#include "eff_spark_textures.h"

#endif
