.table_enemy:
entry .enemy_dodongo_walk
entry .enemy_dodongo_breathe
entry .enemy_dodongo_flame
entry .enemy_dodongo_hurt
entry .enemy_dodongo_die
entry .enemy_boss_dodongo_exhale
entry .enemy_boss_dodongo_hurt
entry .enemy_boss_dodongo_die
entry .enemy_boss_dodongo_walk
entry .enemy_boss_dodongo_flame
entry .enemy_boss_gohma_walk
entry .enemy_boss_gohma_walk_ceiling
entry .enemy_boss_gohma_climb
entry .enemy_boss_gohma_fall
entry .enemy_boss_gohma_roar
entry .enemy_boss_gohma_growl
entry .enemy_boss_gohma_hurt
entry .enemy_boss_gohma_hurt_eye
entry .enemy_boss_gohma_die
entry .enemy_boss_gohma_birth
entry .enemy_larvae_egg_land
entry .enemy_larvae_egg_break
entry .enemy_larvae_walk
entry .enemy_larvae_chirp
entry .enemy_larvae_hurt
entry .enemy_larvae_cry
entry .enemy_larvae_die
entry .enemy_boss_gohma_eyeroll
entry .enemy_boss_gohma_dissolve
entry .enemy_boss_gohma_thrust
entry .enemy_boss_gohma_paralyzed
entry .enemy_larvae_paralyzed
entry .enemy_dodongo_jr_yell
entry .enemy_dodongo_jr_die
entry .enemy_dodongo_jr_walk
entry .enemy_dodongo_jr_burrow
entry .enemy_dodongo_jr_emerge
entry .enemy_ganondorf_throw_orb
entry .enemy_dodongo_jr_eat
entry .enemy_ganondorf_hit_light
entry .enemy_lizalfos_land
entry .enemy_lizalfos_cry
entry .enemy_lizalfos_attack_shout
entry .enemy_lizalfos_hurt
entry .enemy_lizalfos_laugh
entry .enemy_lizalfos_die
entry .enemy_lizalfos_walk
entry .enemy_lizalfos_jump
entry .enemy_stalkid_walk
entry .enemy_stalkid_attack
entry .enemy_stalkid_hurt
entry .enemy_stalkid_die
entry .enemy_floormaster_slide
entry .enemy_tektite_turn_water
entry .enemy_destroyed_light_arrow
entry .enemy_pot_fly
entry .enemy_stalfos_laugh
entry .enemy_stalfos_attack
entry .enemy_stalfos_hurt
entry .enemy_stalfos_die
entry .enemy_wolfos_spawn
entry .enemy_stalfos_walk
entry .enemy_wolfos_howl
entry .enemy_wolfos_attack
entry .enemy_keese_attack
entry .enemy_keese_fly
entry .enemy_keese_die
entry .enemy_wolfos_hurt
entry .enemy_armos_hop
entry .enemy_armos_awaken
entry .enemy_armos_die
entry .enemy_armos_hurt
entry .enemy_armos_roar
entry .enemy_shell_open
entry .enemy_shell_die
entry .enemy_wolfos_die
entry .enemy_boss_dodongo_demo_wall
entry .enemy_boss_dodongo_wall_hit
entry .enemy_boss_dodongo_roll
entry .enemy_boss_dodongo_inhale
entry .enemy_boss_dodongo_swallow
entry .enemy_boss_dodongo_paralyzed
entry .enemy_boss_dodongo_roar
entry .enemy_boss_dodongo_dying_groan
entry .enemy_boss_dodongo_fossilize
entry .enemy_boss_dodongo_lava
entry .enemy_ganondorf_fly
entry .enemy_ganondorf_vortex_charge
entry .enemy_dodongo_inhale
entry .enemy_dodongo_swipe
entry .enemy_wolfos_walk
entry .enemy_dodongo_jr_eat
entry .enemy_big_baba_chomp
entry .enemy_big_baba_attack
entry .enemy_big_baba_hurt
entry .enemy_big_baba_die
entry .enemy_deku_baba_chomp
entry .enemy_deku_baba_attack
entry .enemy_deku_baba_die
entry .enemy_deku_baba_slide
entry .enemy_tailpasaran_fly
entry .enemy_tailpasaran_cry
entry .enemy_tailpasaran_die
entry .enemy_ganondorf_charge
entry .enemy_skulltula_drop
entry .enemy_skulltula_climb
entry .enemy_skulltula_quiver
entry .enemy_skulltula_hurt
entry .enemy_stalfos_jump
entry .enemy_tektite_hurt
entry .enemy_tektite_die
entry .enemy_tektite_turn_ground
entry .enemy_poe_attack_charge
entry .enemy_poe_float
entry .enemy_poe_retreat
entry .enemy_poe_appear
entry .enemy_poe_vanish
entry .enemy_poe_hurt
entry .enemy_poe_die
entry .enemy_poe_transform
entry .enemy_dissolve
entry .enemy_goron_land
entry .enemy_lizalfos_land_flat
entry .enemy_dodongo_jr_land
entry .enemy_scrub_emerge
entry .enemy_scrub_burrow
entry .enemy_scrub_spit
entry .enemy_scrub_walk
entry .enemy_scrub_hurt
entry .enemy_scrub_die
entry .enemy_shop_scrub_cry
entry .enemy_big_poe_get_soul
entry .enemy_skulltula_pivot
entry .enemy_skullwall_die
entry .enemy_poe_sister_die
entry .enemy_bari_split
entry .enemy_tektite_flip
entry .enemy_boss_gohma_fall
entry .enemy_tektite_land_water1
entry .enemy_final_hit
entry .enemy_skullwall_rotate
entry .enemy_skullwall_dash
entry .enemy_tektite_jump_water
entry .enemy_tektite_land_water2
entry .enemy_wallmaster_fall
entry .enemy_wallmaster_retreat
entry .enemy_wallmaster_grab
entry .enemy_larvae_egg_land
entry .enemy_floormaster_walk
entry .enemy_floormaster_hurt
entry .enemy_floormaster_die
entry .enemy_guay_fly
entry .enemy_biri_float
entry .enemy_biri_fly
entry .enemy_biri_shock
entry .enemy_biri_die
entry .enemy_biri_die_bubbles
entry .enemy_bari_spin
entry .enemy_larvae_paralyzed
entry .enemy_bari_die
entry .enemy_ganondorf_orb_trail
entry .enemy_phantom_reveal
entry .enemy_phantom_lightning
entry .enemy_ganondorf_charge
entry .enemy_ganondorf_fly
entry .enemy_witch_charge
entry .enemy_phantom_painting_enter
entry .enemy_ganondorf_orb_trail
entry .enemy_ganondorf_lightning_hit
entry .enemy_phantom_attack_unused
entry .enemy_phantom_staff
entry .enemy_phantom_eyes
entry .enemy_phantom_die_roar
entry .enemy_phantom_orb_dissipate
entry .enemy_phantom_hurt
entry .enemy_phantom_die
entry .enemy_phantom_laugh
entry .enemy_phantom_hurt_orb
entry .enemy_phantom_shout
entry .enemy_guay_hurt
entry .enemy_ganondorf_charge_major
entry .enemy_ganondorf_magic_fire
entry .enemy_guay_chirp
entry .enemy_guay_attack
entry .enemy_moblin_walk
entry .enemy_moblin_slide
entry .enemy_moblin_attack_shout
entry .enemy_moblin_grunt
entry .enemy_moblin_spear_point
entry .enemy_moblin_spear_relax
entry .enemy_moblin_die
entry .enemy_moblin_dash
entry .enemy_octorok_rock_break
entry .enemy_octorok_float
entry .enemy_octorok_jump
entry .enemy_tektite_land_water1
entry .enemy_octorok_dive
entry .enemy_octorok_bubble
entry .enemy_octorok_die
entry .enemy_octorok_death_gasp
entry .enemy_keese_fly
entry .enemy_bubble_dash
entry .enemy_bubble_cry
entry .enemy_bubble_attack
entry .enemy_bubble_flame_appear
entry .enemy_bubble_flame_vanish
entry .enemy_bubble_die
entry .enemy_dodongo_flame
entry .enemy_boss_volvagia_hole
entry .enemy_boss_volvagia_roar
entry .enemy_boss_gohma_hurt_eye
entry .enemy_volvagia_fall
entry .enemy_volvagia_paralyzed
entry .enemy_boss_gohma_hurt
entry .enemy_boss_volvagia_cry
entry .enemy_boss_volvagia_rock
entry .enemy_boss_volvagia_swipe
entry .enemy_boss_gohma_die
entry .enemy_boss_dodongo_fossilize
entry .enemy_boss_dodongo_flame
entry .enemy_biri_die
entry .enemy_dodongo_jr_land
entry .enemy_boss_morpha_water_move
entry .enemy_tektite_turn_water
entry .enemy_moblin_club_shockwave
entry .enemy_moblin_club_strike
entry .enemy_moblin_club_lift
entry .enemy_bubble_hurt
entry .enemy_redead_moan
entry .enemy_redead_scream
entry .enemy_redead_hurt
entry .enemy_redead_die
entry .enemy_redead_attack
entry .enemy_spike_trap_roll
entry .enemy_spike_trap_rock
entry .enemy_guay_die
entry .enemy_poe_laugh
entry .enemy_poe_sister_cry
entry .enemy_poe_sister_attack
entry .enemy_poe_sister_laugh
entry .enemy_boss_morpha_rise
entry .enemy_boss_morpha_attack
entry .enemy_boss_morpha_toss
entry .enemy_boss_morpha_grab
entry .enemy_boss_morpha_caught
entry .enemy_boss_morpha_demo_move
entry .enemy_boss_morpha_demo_bubble
entry .enemy_tektite_jump_water
entry .enemy_boss_morpha_die
entry .enemy_boss_morpha_die_cry
entry .enemy_boss_morpha_water_spin
entry .enemy_witch_charge
entry .enemy_goron_wake
entry .enemy_goron_sit
entry .enemy_unused
entry .enemy_cucco_flap
entry .enemy_deadhand_bite
entry .enemy_deadhand_move
entry .enemy_deadhand_grabbed
entry .enemy_deadhand_grab
entry .enemy_big_octo_paralyzed
entry .enemy_big_octo_walk
entry .enemy_big_octo_grunt
entry .enemy_big_octo_hurt
entry .enemy_big_octo_stop
entry .enemy_big_octo_die
entry .enemy_big_octo_die2
entry .enemy_phantom_lightning
entry .enemy_boss_twinrova_appear
entry .enemy_boss_twinrova_transform
entry .enemy_boss_twinrova_fire_charge
entry .enemy_boss_twinrova_fire_hit
entry .enemy_boss_twinrova_charge
entry .enemy_boss_twinrova_ice_beam
entry .enemy_boss_twinrova_ice_charge
entry .enemy_boss_twinrova_cast
entry .enemy_boss_ganondorf_struck
entry .enemy_boss_dodongo_demo_wall
entry .enemy_boss_twinrova_hurt_cry_old
entry .enemy_boss_twinrova_ice_reflected
entry .enemy_boss_twinrova_fire_reflected
entry .enemy_boss_ganondorf_struck
entry .enemy_boss_twinrova_hit_beam_young
entry .enemy_boss_twinrova_die_young
entry .enemy_biggoron_blind
entry .enemy_biggoron_happy
entry .enemy_boss_twinrova_spirit_fly
entry .enemy_boss_twinrova_fly
entry .enemy_boss_twinrova_hover
entry .enemy_poe_sister_attack
entry .enemy_ganondorf_orb_trail
entry .enemy_phantom_painting_enter
entry .enemy_darunia_chest_pound
entry .enemy_darunia_head_pat
entry .enemy_owl_fly
entry .enemy_goron_land
entry .enemy_knuckle_walk
entry .enemy_knuckle_attack
entry .enemy_knuckle_clank
entry .enemy_knuckle_stagger
entry .enemy_knucle_armor_loss
entry .enemy_knuckle_armor_rebound1
entry .enemy_knuckle_armor_rebound2
entry .enemy_knuckle_armor_rebound3
entry .enemy_floormaster_attack
entry .enemy_floormaster_mini_walk
entry .enemy_floormaster_mini_die
entry .enemy_floormaster_mini_grow
entry .enemy_floormaster_grow_done
entry .enemy_floormaster_split
entry .enemy_floormaster_mini_grab
entry .enemy_floormaster_mini_land
entry .enemy_knuckle_warcry
entry .enemy_knuckle_snap
entry .enemy_knuckle_armor_hurt
entry .enemy_boss_ganondorf_struck
entry .enemy_boss_barinade_pulse
entry .enemy_boss_barinade_hurt
entry .enemy_boss_barinade_weak_hurt
entry .enemy_boss_barinade_die
entry .enemy_boss_twinrova_hurt
entry .enemy_boss_barinade_bari_attach
entry .enemy_boss_barinade_beam
entry .enemy_biri_shock
entry .enemy_biri_die
entry .enemy_boss_barinade_tentacle_break
entry .enemy_ganondorf_lightning_hit
entry .enemy_boss_dodongo_roll
entry .enemy_shabom_bounce
entry .enemy_shabom_pop
entry .enemy_blob_wave
entry .enemy_octorok_rock_break
entry .enemy_stinger_hurt
entry .enemy_stinger_die
entry .enemy_stinger_submerge
entry .enemy_stinger_glide
entry .enemy_boss_bongo_drum_low
entry .enemy_boss_bongo_drum_high
entry .enemy_boss_bongo_clap
entry .enemy_deadhand_grab
entry .enemy_peahat_rise
entry .enemy_peahat_fly
entry .enemy_peahat_hurt
entry .enemy_peahat_land
entry .enemy_deadhand_grab
entry .enemy_tentacle_wind_up
entry .enemy_peahat_hurt
entry .enemy_tentacle_die
entry .enemy_larvae_walk
entry .enemy_larvae_chirp
entry .enemy_larvae_hurt
entry .enemy_larvae_cry
entry .enemy_larvae_die
entry .enemy_larvae_egg_land
entry .enemy_larvae_egg_break
entry .enemy_boss_ganon_transform
entry .enemy_boss_bongo_hand_wave
entry .enemy_wallmaster_grab
entry .enemy_goron_land
entry .enemy_boss_bongo_hand_attack
entry .enemy_boss_bongo_hand_shake
entry .enemy_boss_bongo_hurt
entry .enemy_boss_bongo_hand_hurt
entry .enemy_boss_bongo_vanish
entry .enemy_ganondorf_charge_major
entry .enemy_boss_barinade_beam
entry .enemy_boss_bongo_paralyze
entry .enemy_boss_bongo_die
entry .enemy_beamos_idle
entry .enemy_beamos_beam
entry .enemy_beamos_ground_hit
entry .enemy_beamos_charging
entry .enemy_torch_slug_crawl
entry .enemy_torch_slug_target
entry .enemy_tektite_flip
entry .enemy_torch_slug_hurt
entry .enemy_torch_slug_die
entry .enemy_tile_fly
entry .enemy_firedancer_hurt
entry .enemy_boss_twinrova_fly
entry .enemy_firedancer_kick
entry .enemy_moblin_club_shockwave
entry .enemy_firedancer_spin
entry .enemy_firehead_run
entry .enemy_firehead_hurt
entry .enemy_firedancer_laugh
entry .enemy_deku_baba_slide
entry .enemy_boss_volvagia_hole
entry .enemy_peahat_jr_fly
entry .enemy_keese_die
entry .enemy_leever_emerge
entry .enemy_shop_scrub_burrow
entry .enemy_boss_gohma_hurt
entry .enemy_leever_die
entry .enemy_blob_wave
entry .enemy_firehead_cry
entry .enemy_boss_bongo_dissipate
entry .enemy_boss_bongo_charge
entry .enemy_boss_bongo_chant
entry .enemy_boss_ganon_roar
entry .enemy_torch_slug_crawl
entry .enemy_boss_morpha_grab
entry .enemy_boss_dodongo_swallow
entry .enemy_boss_gohma_eyeroll
entry .enemy_scrub_spit
entry .enemy_boss_gohma_hurt
entry .enemy_like_like_die
entry .enemy_boss_ganon_attack
entry .enemy_gerudo_attack
entry .enemy_gerudo_hurt
entry .enemy_gerudo_defeat
entry .enemy_boss_ganon_hurt
entry .enemy_dodongo_flame
entry .enemy_anubis_fire_hit
entry .enemy_boss_ganon_penultimate_hit
entry .enemy_anubis_die
entry .enemy_wolfos_walk
entry .enemy_boss_ganon_die
entry .enemy_stinger_attack
entry .enemy_stinger_cry
entry .enemy_boss_twinrova_ice_beam
entry .enemy_freezard_hurt
entry .enemy_freezard_die
entry .enemy_deadhand_laugh
entry .enemy_deadhand_burrow
entry .enemy_deadhand_hurt
entry .enemy_big_baba_die
entry .enemy_deadhand_die
entry .enemy_knuckle_stump_break
entry .enemy_knuckle_pillar_break
entry .enemy_knuckle_axe_stuck
entry .enemy_boss_ganon_paralyze
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_boss_vocals
entry .enemy_goron_land
entry .enemy_deadhand_burrow
entry .enemy_boss_ganon_growl
entry .enemy_gold_skull_spin
entry .enemy_blob_wave
entry .enemy_armos_hop
entry .enemy_knuckle_stump_break
entry .enemy_armos_hop
entry .enemy_boss_ganon_sword_clank
entry .enemy_deadhand_grab
entry .enemy_skulltula_creak
entry .enemy_floormaster_grow_done
entry .enemy_dodongo_jr_land
entry .enemy_stalfos_walk
entry .enemy_dodongo_jr_land
entry .enemy_stalfos_walk
entry .enemy_boss_twinrova_bicker
entry .enemy_big_poe_caught_soul
entry .enemy_bug_burrow
entry .enemy_gold_skull_cry
entry .enemy_goron_kid_cry
entry .enemy_boss_gohma_hurt
entry .enemy_tektite_land_water1
entry .enemy_deadhand_burrow
entry .enemy_goron_land
entry .enemy_bug_walk
entry .enemy_boss_twinrova_ice_beam
entry .enemy_skulltula_quiver

.enemy_dodongo_walk:
chan_setinstr F1_I_GUNSHOT
chan_setenvelope .envelope_68DC
chan_setlayer 0, .layer_354D
chan_end

.layer_354D:
layer_portamento 0x81, 34, 80
layer_note1 PITCH_C3, 0x1e, 100
layer_end

.enemy_dodongo_breathe:
chan_setlayer 0, .layer_3559
chan_end

.layer_3559:
layer_setinstr F1_I_DODONGO_ROAR
layer_note1 PITCH_D4, 0x50, 100
layer_end

.enemy_dodongo_flame:
chan_setinstr 2
chan_setlayer 0, .layer_3565
chan_end

.layer_3565:
layer_note1 PITCH_F2, 30000, 100
layer_jumprel .layer_3565

.enemy_dodongo_hurt:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_3574
chan_setlayer 1, .layer_4829
chan_end

.layer_3574:
layer_portamento 0x81, 36, 255
layer_note1 PITCH_E4, 0xa, 100
layer_portamento 0x81, 44, 255
layer_note1 PITCH_B3, 0x24, 100
layer_end

.enemy_dodongo_die:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_358F
chan_setlayer 1, .layer_3591
chan_setlayer 2, .layer_4829
chan_end

.layer_358F:
layer_transpose -6

.layer_3591:
layer_portamento 0x81, 38, 255
layer_note1 PITCH_GF4, 0xa, 100
layer_portamento 0x81, 46, 255
layer_note1 PITCH_DF4, 0x5a, 100
layer_end

.enemy_boss_dodongo_exhale:
chan_setinstr F1_I_DODONGO_ROAR
chan_setenvelope .envelope_683C
chan_setlayer 0, .layer_35AC
chan_setlayer 1, .layer_35AE
chan_end

.layer_35AC:
layer_transpose -12

.layer_35AE:
layer_portamento 0x1, 34, 0x14
layer_note1 PITCH_B3, 0x5a, 100
layer_end

.enemy_boss_dodongo_walk:
chan_setinstr F1_I_GUNSHOT
chan_setlayer 0, .layer_35CA
chan_setlayer 1, .layer_35C6
chan_setlayer 2, .layer_35C2
chan_end

.layer_35C2:
layer_note1 PITCH_B3, 0x50, 100
layer_end

.layer_35C6:
layer_note1 PITCH_D3, 0x50, 100
layer_end

.layer_35CA:
layer_note1 PITCH_F2, 0x50, 100
layer_end

.enemy_boss_dodongo_flame:
chan_setinstr 2
chan_setlayer 0, .layer_35D9
chan_setlayer 1, .layer_35D7
chan_end

.layer_35D7:
layer_transpose -12

.layer_35D9:
layer_note1 PITCH_G3, 30000, 100
layer_jumprel .layer_35D9

.enemy_larvae_egg_break:
chan_setinstr F1_I_EGG_CRACK
chan_setlayer 0, .layer_35E5
chan_end

.layer_35E5:
layer_note1 PITCH_F3, 0x50, 100
layer_end

.enemy_boss_gohma_fall:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_35F5
chan_setlayer 1, .layer_35F7
chan_setlayer 2, .layer_3606
chan_end

.layer_35F5:
layer_transpose -8

.layer_35F7:
layer_setenvelope .envelope_69DC, 240
layer_portamento 0x81, 34, 64
layer_note1 PITCH_C3, 0x32, 100
layer_note1 PITCH_C1, 0x5a, 100
layer_end

.layer_3606:
layer_setenvelope .envelope_69DC, 240
layer_portamento 0x81, 38, 64
layer_note1 PITCH_E3, 0x32, 100
layer_end

.enemy_goron_land:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_361B
chan_setlayer 1, .layer_361D
chan_end

.layer_361B:
layer_transpose -8

.layer_361D:
layer_setenvelope .envelope_69DC, 250
layer_portamento 0x81, 34, 64
layer_note1 PITCH_C3, 0x62, 100
layer_end

.enemy_lizalfos_land_flat:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_3631
chan_sethilogain 18
chan_end

.layer_3631:
layer_setenvelope .envelope_690C, 250
layer_portamento 0x81, 29, 150
layer_note1 PITCH_C3, 0x8, 100
layer_setenvelope .envelope_68EC, 250
layer_portamento 0x81, 27, 150
layer_note1 PITCH_F2, 0x1e, 100
layer_end

.enemy_dodongo_jr_land:
chan_setlayer 0, .layer_364C
chan_end

.layer_364C:
layer_setinstr F1_I_SMASH
layer_setenvelope .envelope_68DC, 250
layer_portamento 0x81, 36, 64
layer_note1 PITCH_D3, 0x1e, 100
layer_end

.enemy_boss_gohma_walk:
chan_setinstr F1_I_SMASH
chan_setenvelope .envelope_68EC
chan_setlayer 0, .layer_3665
chan_sethilogain 16
chan_end

.layer_3665:
layer_portamento 0x81, 37, 64
layer_note1 PITCH_EF3, 0x28, 100
layer_end

.enemy_boss_gohma_climb:
chan_setinstr F1_I_TEKTITE_ROTATE
chan_setlayer 1, .layer_3676
chan_setlayer 0, .layer_3678
chan_end

.layer_3676:
layer_transpose 1

.layer_3678:
layer_portamento 0x81, 19, 64
layer_note1 PITCH_G2, 0x14, 100
layer_end

.enemy_boss_gohma_birth:
chan_setinstr F1_I_MONSTER_ROAR
chan_setenvelope .envelope_698C
chan_setlayer 0, .layer_368B
chan_sethilogain 18
chan_end

.layer_368B:
layer_enablelegato
layer_portamento 0x85, 20, 255
layer_note1 PITCH_GF2, 0x28, 100
layer_note1 PITCH_F2, 0x55, 100
layer_end

.enemy_larvae_walk:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_369D
chan_end

.layer_369D:
layer_portamento 0x81, 31, 255
layer_note1 PITCH_C3, 0x5, 100
layer_end

.enemy_larvae_chirp:
chan_setinstr F1_I_MECH
chan_setlayer 0, .layer_36AB
chan_end

.layer_36AB:
layer_portamento 0x81, 48, 255
layer_note1 PITCH_GF4, 0x1e, 100
layer_end

.enemy_larvae_hurt:
chan_setlayer 0, .layer_4829
chan_setlayer 1, .layer_36BD
chan_setlayer 2, .layer_36C1
chan_end

.layer_36BD:
layer_setinstr F1_I_MECH
layer_jumprel .layer_36C3

.layer_36C1:
layer_setinstr F1_I_MONSTER_ROAR
.layer_36C3:
layer_portamento 0x81, 51, 255
layer_note1 PITCH_B5, 0xa, 100
layer_portamento 0x81, 60, 255
layer_note1 PITCH_E5, 0x12, 100
layer_end

.enemy_larvae_cry:
chan_setlayer 0, .layer_36D6
chan_end

.layer_36D6:
layer_setinstr F1_I_MECH
layer_portamento 0x81, 51, 255
layer_note1 PITCH_F5, 0xa, 100
layer_portamento 0x81, 53, 255
layer_note1 PITCH_G5, 0xa, 100
layer_transpose 4
layer_portamento 0x81, 55, 255
layer_note1 PITCH_B5, 0xa, 100
layer_transpose 6
layer_portamento 0x81, 51, 255
layer_note1 PITCH_B5, 0x14, 100
layer_end

.enemy_larvae_die:
chan_setlayer 0, .layer_3700
chan_setlayer 1, .layer_4829
chan_end

.layer_3700:
layer_setinstr F1_I_MECH
layer_portamento 0x81, 56, 255
layer_note1 PITCH_C5, 0x5, 100
layer_portamento 0x81, 54, 255
layer_note1 PITCH_BF4, 0xa, 100
layer_portamento 0x81, 51, 255
layer_note1 PITCH_AF4, 0xa, 100
layer_portamento 0x81, 47, 255
layer_note1 PITCH_DF4, 0x14, 100
layer_end

.enemy_boss_gohma_walk_ceiling:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3728
chan_setlayer 1, .layer_372C
chan_end

.layer_3728:
layer_note1 PITCH_E3, 0x50, 100
layer_end

.layer_372C:
layer_delay 0xf
layer_note1 PITCH_C4, 0x50, 100
layer_end

.enemy_boss_gohma_hurt_eye:
chan_setlayer 0, .layer_374D
chan_setlayer 1, .layer_3739
chan_end

.layer_3739:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_G4, 0x14, 80
layer_note1 PITCH_C4, 0x14, 80
layer_note1 PITCH_E4, 0x14, 80
layer_note1 PITCH_A3, 0x14, 80
layer_end

.layer_374D:
layer_setinstr F1_I_MONSTER_ROAR
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_G4, 0xa, 100
layer_note1 PITCH_C4, 0xa, 100
layer_note1 PITCH_G4, 0xa, 100
layer_note1 PITCH_C4, 0xa, 100
layer_note1 PITCH_G4, 0xa, 100
layer_note1 PITCH_C4, 0x5, 100
layer_end

.enemy_larvae_egg_land:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_376F
chan_sethilogain 18
chan_end

.layer_376F:
layer_enablelegato
layer_setenvelope .envelope_68FC, 255
layer_portamento 0x85, 25, 230
layer_note1 PITCH_EF3, 0x5, 100
layer_note1 PITCH_BF2, 0x5, 100
layer_disablelegato
layer_delay 0x5
layer_enablelegato
layer_setenvelope .envelope_68FC, 255
layer_portamento 0x85, 25, 220
layer_note1 PITCH_EF3, 0x5, 100
layer_note1 PITCH_BF2, 0xa, 100
layer_end

.chan_unused_3791:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_3797
chan_end

.layer_3797:
layer_note1 PITCH_D4, 0x46, 100
layer_end

.enemy_keese_attack:
chan_setinstr F1_I_KEESE
chan_setlayer 0, .layer_37A3
chan_sethilogain 50
chan_end

.layer_37A3:
layer_portamento 0x81, 37, 100
layer_note1 PITCH_EF4, 0x32, 100
layer_end

.enemy_keese_fly:
chan_setlayer 0, .layer_37AF
chan_end

.layer_37AF:
layer_setinstr F1_I_OWL_FLAP
layer_portamento 0x81, 36, 255
layer_note1 PITCH_E4, 0xa, 100
layer_portamento 0x81, 42, 255
layer_note1 PITCH_DF4, 0x6, 100
layer_end

.enemy_dodongo_jr_yell:
chan_setlayer 0, .layer_37C7
chan_setlayer 1, .layer_37D3
chan_end

.layer_37C7:
layer_setinstr F1_I_DODONGO_ROAR
layer_delay 0xa
layer_portamento 0x81, 48, 64
layer_note1 PITCH_D5, 0x28, 100
layer_end

.layer_37D3:
layer_setinstr F1_I_GUNSHOT
layer_setenvelope .envelope_686C, 240
layer_transpose 6
layer_portamento 0x81, 26, 100
layer_note1 PITCH_B5, 0x32, 100
layer_end

.enemy_dodongo_jr_die:
chan_setlayer 0, .layer_37EA
chan_setlayer 1, .layer_4829
chan_end

.layer_37EA:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x81, 48, 255
layer_note1 PITCH_D5, 0xa, 100
layer_portamento 0x81, 55, 255
layer_note1 PITCH_F4, 0x48, 100
layer_end

.enemy_boss_gohma_roar:
chan_setlayer 0, .layer_3809
chan_setlayer 1, .layer_3802
chan_end

.layer_3802:
layer_setinstr F1_I_MONSTER_ROAR
layer_note1 PITCH_E4, 0x96, 70
layer_end

.layer_3809:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 39, 255
layer_note1 PITCH_D4, 0xa, 100
layer_portamento 0x81, 41, 255
layer_note1 PITCH_F4, 0xc8, 100
layer_end

.enemy_boss_gohma_hurt:
chan_setlayer 0, .layer_3838
chan_setlayer 1, .layer_3826
chan_setlayer 2, .layer_4829
chan_end

.layer_3826:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 42, 64
layer_note1 PITCH_BF4, 0x14, 80
layer_portamento 0x81, 47, 255
layer_note1 PITCH_AF3, 0x24, 80
layer_end

.layer_3838:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x81, 39, 255
layer_note1 PITCH_G4, 0xf, 100
layer_portamento 0x81, 44, 255
layer_note1 PITCH_B3, 0x24, 100
layer_end

.enemy_boss_gohma_growl:
chan_setinstr F1_I_EGG_CRACK
chan_setlayer 0, .layer_3854
chan_setlayer 1, .layer_3852
chan_end

.layer_3852:
layer_transpose 2

.layer_3854:
layer_note1 PITCH_C2, 0x64, 100
layer_end

.enemy_dodongo_jr_walk:
chan_setlayer 0, .layer_385C
chan_end

.layer_385C:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_D2, 0x1e, 70
layer_end

.enemy_dodongo_jr_burrow:
chan_setlayer 0, .layer_3866
chan_end

.layer_3866:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_BF2, 0x19, 100
layer_note1 PITCH_AF2, 0x14, 100
layer_note1 PITCH_BF2, 0xf, 100
layer_note1 PITCH_AF2, 0xf, 100
layer_note1 PITCH_BF2, 0xa, 100
layer_note1 PITCH_AF2, 0xf, 100
layer_note1 PITCH_BF2, 0xf, 70
.layer_387D:
layer_note1 PITCH_AF2, 0xf, 70
layer_note1 PITCH_BF2, 0xf, 70
layer_note1 PITCH_AF2, 0xf, 70
layer_note1 PITCH_BF2, 0xa, 60
layer_note1 PITCH_AF2, 0xa, 60
layer_end

.enemy_bug_burrow:
chan_setlayer 0, .layer_3891
chan_end

.layer_3891:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_jumprel .layer_387D

.enemy_bug_walk:
chan_setlayer 0, .layer_3899
chan_end

.layer_3899:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_AF2, 0x8, 40
layer_note1 PITCH_G2, 0x8, 40
layer_end

.enemy_dodongo_jr_emerge:
chan_setlayer 0, .layer_38A6
chan_end

.layer_38A6:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_GF2, 0x19, 100
layer_note1 PITCH_AF2, 0x14, 100
layer_end

.enemy_shop_scrub_burrow:
chan_setlayer 0, .layer_38B6
chan_setlayer 1, .layer_3866
chan_end

.layer_38B6:
layer_transpose -5
layer_jumprel .layer_3866

.enemy_leever_emerge:
chan_setlayer 0, .layer_38C1
chan_setlayer 1, .layer_38A6
chan_end

.layer_38C1:
layer_transpose -2
layer_delay 0x3
layer_jumprel .layer_38A6

.enemy_dodongo_jr_eat:
chan_setinstr F1_I_GULP_SPEAR
chan_setlayer 0, .layer_38CD
chan_end

.layer_38CD:
layer_note1 PITCH_C3, 0x30, 100
layer_end

.enemy_stalfos_walk:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_38D7
chan_end

.layer_38D7:
layer_portamento 0x81, 35, 64
layer_note1 PITCH_DF3, 0xc, 64
layer_end

.enemy_stalfos_laugh:
chan_setlayer 0, .layer_38E5
chan_sethilogain 16
chan_end

.layer_38E5:
layer_setinstr F1_I_PHANTOM_LAUGH_0
layer_note1 PITCH_C4, 0x8c, 100
layer_end

.enemy_lizalfos_hurt:
chan_setlayer 0, .layer_38F6
chan_setlayer 1, .layer_3907
chan_setlayer 2, .layer_4829
chan_end

.layer_38F6:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x81, 33, 255
layer_note1 PITCH_DF4, 0xf, 100
layer_portamento 0x81, 38, 255
layer_note1 PITCH_AF2, 0x28, 100
layer_end

.layer_3907:
layer_setinstr F1_I_MOBLIN_GROWL
layer_note1 PITCH_C5, 0x5, 100
layer_note1 PITCH_B4, 0x5, 100
layer_note1 PITCH_A4, 0x5, 100
layer_note1 PITCH_E4, 0x5, 100
layer_end

.enemy_lizalfos_laugh:
chan_setlayer 0, .layer_391A
chan_end

.layer_391A:
layer_setinstr F1_I_LAUGHTER
layer_portamento 0x81, 44, 255
layer_note1 PITCH_C4, 0x14, 100
layer_end

.enemy_lizalfos_die:
chan_setlayer 0, .layer_392E
chan_setlayer 1, .layer_393F
chan_setlayer 2, .layer_4829
chan_end

.layer_392E:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x81, 35, 255
layer_note1 PITCH_E3, 0xf, 100
layer_portamento 0x81, 31, 255
layer_note1 PITCH_C3, 0x1e, 100
layer_end

.layer_393F:
layer_setinstr F1_I_MOBLIN_GROWL
layer_note1 PITCH_AF5, 0x5, 100
layer_note1 PITCH_F5, 0x5, 100
layer_note1 PITCH_DF5, 0x5, 100
layer_note1 PITCH_BF4, 0x5, 100
layer_end

.enemy_stalfos_hurt:
chan_setlayer 0, .layer_3958
.chan_3951:
chan_setlayer 1, .layer_3962
chan_setlayer 2, .layer_4829
chan_end

.layer_3958:
layer_setinstr F1_I_PHANTOM_MOAN
layer_portamento 0x81, 47, 100
layer_note1 PITCH_G4, 0x50, 100
layer_end

.layer_3962:
layer_setinstr F1_I_POT_BREAK
layer_note1 PITCH_G3, 0x5, 100
layer_note1 PITCH_G3, 0x5, 100
layer_end

.enemy_stalkid_hurt:
chan_setlayer 0, .layer_3970
chan_jumprel .chan_3951

.layer_3970:
layer_transpose 19
layer_jumprel .layer_3958

.enemy_stalfos_die:
chan_setlayer 0, .layer_3984
.chan_3977:
chan_setlayer 1, .layer_3997
chan_setlayer 2, .layer_4829
chan_sethilogain 20
chan_setvibratorate 50
chan_setvibratoextent 10
chan_end

.layer_3984:
layer_setinstr F1_I_PHANTOM_MOAN
layer_enablelegato
layer_portamento 0x85, 43, 200
layer_note1 PITCH_AF4, 0x1e, 100
layer_note1 PITCH_A3, 0x8c, 100
layer_note1 PITCH_E4, 0xc8, 100
layer_end

.layer_3997:
layer_setinstr F1_I_POT_BREAK
layer_note1 PITCH_G3, 0x5, 100
layer_note1 PITCH_G3, 0xf, 100
layer_end

.enemy_stalkid_die:
chan_setlayer 0, .layer_39A5
chan_jumprel .chan_3977

.layer_39A5:
layer_transpose 14
layer_jumprel .layer_3984

.enemy_firehead_cry:
chan_setlayer 0, .layer_39A5
chan_end

.enemy_lizalfos_walk:
chan_setlayer 0, .layer_39B1
chan_end

.layer_39B1:
layer_setinstr F1_I_LIZALFOS
layer_transpose 48
layer_note1 PITCH_DF4, 0xa, 80
layer_end

.enemy_lizalfos_land:
chan_setlayer 0, .layer_39BD
chan_end

.layer_39BD:
layer_setinstr F1_I_LIZALFOS
layer_transpose 48
layer_note1 PITCH_E4, 0xa, 80
layer_note1 PITCH_D4, 0xa, 80
layer_end

.enemy_lizalfos_jump:
chan_setlayer 0, .layer_39DD
chan_setlayer 1, .layer_39D2
chan_setlayer 2, .layer_39ED
chan_end

.layer_39D2:
layer_setinstr F1_I_LIZALFOS
layer_transpose 48
layer_note1 PITCH_E4, 0xa, 100
layer_note1 PITCH_GF4, 0xa, 100
layer_end

.layer_39DD:
layer_setinstr F1_I_GUNSHOT
layer_setenvelope .envelope_686C, 240
layer_transpose 4
layer_portamento 0x81, 26, 50
layer_note1 PITCH_B5, 0x50, 100
layer_end

.layer_39ED:
layer_setinstr F1_I_MOBLIN_GROWL
layer_delay 0xa
layer_note1 PITCH_EF4, 0x5, 100
layer_note1 PITCH_D4, 0x5, 100
layer_note1 PITCH_C4, 0x5, 100
layer_note1 PITCH_C4, 0x5, 100
layer_end

.enemy_armos_hop:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_3A04
chan_end

.layer_3A04:
layer_portamento 0x81, 39, 200
layer_note1 PITCH_A3, 0x14, 100
layer_end

.enemy_armos_awaken:
chan_setinstr F1_I_SMASH
chan_setenvelope .envelope_690C
chan_setlayer 1, .layer_3A18
chan_setlayer 0, .layer_3A2E
chan_end

.layer_3A18:
layer_note1 PITCH_E2, 0xa, 100
layer_note1 PITCH_GF2, 0xa, 100
layer_note1 PITCH_E2, 0xa, 100
layer_note1 PITCH_GF2, 0xa, 100
layer_note1 PITCH_E2, 0xa, 100
layer_note1 PITCH_GF2, 0xa, 100
layer_note1 PITCH_E2, 0xa, 100
layer_end

.layer_3A2E:
layer_setinstr F1_I_PHANTOM_WAIL
layer_setenvelope .envelope_699C, 250
layer_enablelegato
layer_portamento 0x85, 23, 255
layer_note1 PITCH_C4, 0x1e, 100
layer_note1 PITCH_F3, 0x52, 100
layer_end

.enemy_armos_die:
chan_setlayer 0, .layer_3A47
chan_setlayer 1, .layer_4829
chan_end

.layer_3A47:
layer_setinstr F1_I_PHANTOM_WAIL
layer_setenvelope .envelope_699C, 240
layer_enablelegato
layer_portamento 0x85, 37, 200
layer_note1 PITCH_GF4, 0x1e, 100
layer_note1 PITCH_GF3, 0x64, 100
layer_end

.enemy_armos_roar:
chan_setinstr F1_I_PHANTOM_WAIL
chan_setenvelope .envelope_699C
chan_sethilogain 19
chan_setlayer 0, .layer_3A64
chan_end

.layer_3A64:
layer_enablelegato
layer_portamento 0x85, 23, 255
layer_note1 PITCH_C4, 0x1e, 100
layer_note1 PITCH_F3, 0x52, 100
layer_end

.enemy_stalfos_attack:
chan_setlayer 0, .layer_3A79
chan_setlayer 1, .layer_3A87
chan_sethilogain 20
chan_end

.layer_3A79:
layer_setinstr F1_I_STALFOS_ATTACK
layer_enablelegato
layer_portamento 0x85, 30, 30
layer_note1 PITCH_BF4, 0x14, 100
layer_note1 PITCH_A4, 0x14, 100
layer_end

.layer_3A87:
layer_setinstr F1_I_GERUDO_ATTACK
layer_setenvelope .envelope_682C, 240
layer_delay 0xa
layer_note1 PITCH_B3, 0x1e, 100
layer_end

.enemy_armos_hurt:
chan_setlayer 0, .layer_3A9A
chan_setlayer 1, .layer_4829
chan_end

.layer_3A9A:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 39, 100
layer_note1 PITCH_F4, 0x1e, 100
layer_note1 PITCH_C4, 0x1e, 100
layer_end

.enemy_boss_dodongo_demo_wall:
chan_setinstr F1_I_GUNSHOT
chan_setlayer 0, .layer_3AB4
chan_setlayer 1, .layer_3ABF
chan_setlayer 2, .layer_3ACA
chan_end

.layer_3AB4:
layer_note1 PITCH_GF3, 0x14, 100
layer_setenvelope .envelope_688C, 240
layer_note1 PITCH_AF2, 0x64, 100
layer_end

.layer_3ABF:
layer_note1 PITCH_BF3, 0x14, 100
layer_setenvelope .envelope_688C, 240
layer_note1 PITCH_C3, 0x64, 100
layer_end

.layer_3ACA:
layer_note1 PITCH_DF4, 0x14, 100
layer_setenvelope .envelope_688C, 240
layer_note1 PITCH_EF3, 0x64, 100
layer_end

.enemy_boss_dodongo_wall_hit:
chan_setinstr F1_I_GUNSHOT
chan_setlayer 0, .layer_3ADE
chan_setlayer 1, .layer_3AE9
chan_end

.layer_3ADE:
layer_note1 PITCH_GF3, 0x14, 100
layer_setenvelope .envelope_688C, 240
layer_note1 PITCH_AF2, 0x32, 100
layer_end

.layer_3AE9:
layer_note1 PITCH_B3, 0x14, 100
layer_setenvelope .envelope_688C, 240
layer_note1 PITCH_DF3, 0x32, 100
layer_end

.enemy_boss_dodongo_roll:
chan_setlayer 0, .layer_3B01
chan_setlayer 1, .layer_3AFF
chan_setvibratorate 20
chan_setvibratoextent 100
chan_end

.layer_3AFF:
layer_transpose 12

.layer_3B01:
layer_setinstr F1_I_BOULDER
.layer_3B03:
layer_note1 PITCH_C4, 30000, 100
layer_jumprel .layer_3B03

.enemy_boss_dodongo_inhale:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_3B14
chan_setlayer 1, .layer_3B12
chan_end

.layer_3B12:
layer_transpose -4

.layer_3B14:
layer_enablelegato
layer_portamento 0x81, 27, 255
layer_note1 PITCH_F3, 0xaa, 100
.layer_3B1D:
layer_note1 PITCH_F3, 30000, 100
layer_jumprel .layer_3B1D

.enemy_boss_dodongo_swallow:
chan_setinstr F1_I_GULP_SPEAR
chan_setlayer 0, .layer_3B2E
chan_setlayer 1, .layer_3B30
chan_sethilogain 24
chan_end

.layer_3B2E:
layer_transpose -2

.layer_3B30:
layer_note1 PITCH_C3, 0x46, 100
layer_end

.enemy_boss_dodongo_paralyzed:
chan_setinstr F1_I_DODONGO_ROAR
chan_setenvelope .envelope_683C
chan_setlayer 0, .layer_3B40
chan_setlayer 1, .layer_3B42
chan_end

.layer_3B40:
layer_transpose -4

.layer_3B42:
layer_enablelegato
layer_portamento 0x85, 15, 255
layer_note1 PITCH_D2, 0x32, 100
layer_note1 PITCH_B1, 0x32, 100
layer_disablelegato
layer_jumprel .layer_3B42

.enemy_dodongo_inhale:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_3B56
chan_end

.layer_3B56:
layer_note1 PITCH_E3, 30000, 100
layer_jumprel .layer_3B56

.enemy_big_baba_chomp:
chan_setinstr F1_I_BABA_ATTACK
chan_setlayer 0, .layer_3B62
chan_end

.layer_3B62:
layer_note1 PITCH_F3, 0x1e, 100
layer_end

.enemy_big_baba_attack:
chan_setlayer 0, .layer_3B6A
chan_end

.layer_3B6A:
layer_setinstr F1_I_BABA_LUNGE
layer_transpose 48
layer_portamento 0x81, 39, 200
layer_note1 PITCH_E4, 0x32, 100
layer_end

.enemy_big_baba_hurt:
chan_setlayer 0, .layer_3B7D
chan_setlayer 1, .layer_4829
chan_end

.layer_3B7D:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 44, 255
layer_note1 PITCH_C5, 0xa, 100
layer_portamento 0x81, 53, 255
layer_note1 PITCH_F4, 0x1e, 100
layer_end

.enemy_big_baba_die:
chan_setlayer 0, .layer_3B99
chan_setlayer 1, .layer_4829
chan_setvibratorate 100
chan_setvibratoextent 127
chan_end

.layer_3B99:
layer_setinstr F1_I_MONSTER_ROAR
layer_setenvelope .envelope_69AC, 255
layer_enablelegato
layer_portamento 0x85, 31, 255
layer_note1 PITCH_C4, 0x1e, 100
layer_note1 PITCH_C3, 0x78, 100
layer_end

.enemy_shell_die:
chan_setlayer 0, .layer_3BB9
chan_setlayer 1, .layer_4BA9
chan_setlayer 2, .layer_4829
chan_setvibratorate 48
chan_setvibratoextent 128
chan_end

.layer_3BB9:
layer_transpose 3
layer_jumprel .layer_3B99

.enemy_deku_baba_chomp:
chan_setinstr F1_I_BABA_ATTACK
chan_setlayer 0, .layer_3BC3
chan_end

.layer_3BC3:
layer_note1 PITCH_F4, 0xf, 100
layer_end

.enemy_deku_baba_attack:
chan_setlayer 0, .layer_3BCB
chan_end

.layer_3BCB:
layer_setinstr F1_I_BABA_LUNGE
layer_transpose 48
layer_portamento 0x81, 48, 255
layer_note1 PITCH_C5, 0x1e, 100
layer_end

.enemy_deku_baba_die:
chan_setinstr F1_I_MONSTER_ROAR
chan_setenvelope .envelope_684C
chan_setlayer 0, .layer_3BE7
chan_setlayer 1, .layer_4829
chan_setvibratorate 100
chan_setvibratoextent 127
chan_end

.layer_3BE7:
layer_enablelegato
layer_portamento 0x85, 49, 200
layer_note1 PITCH_GF5, 0x1e, 100
layer_note1 PITCH_GF4, 0x32, 100
layer_end

.enemy_deku_baba_slide:
chan_setlayer 0, .layer_3BFC
chan_setinstr F1_I_TEKTITE_ROTATE
chan_setenvelope .envelope_68BC
chan_end

.layer_3BFC:
layer_portamento 0x81, 13, 255
layer_note1 PITCH_G1, 0x38, 80
layer_end

.enemy_keese_die:
chan_setlayer 0, .layer_3C0B
chan_setlayer 1, .layer_4829
chan_end

.layer_3C0B:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 44, 255
layer_note1 PITCH_C5, 0xa, 100
layer_portamento 0x81, 53, 255
layer_note1 PITCH_F4, 0x1e, 100
layer_end

.enemy_tailpasaran_fly:
chan_setinstr F1_I_BABA_LUNGE
chan_setlayer 0, .layer_3C26
chan_setvibratorate 64
chan_setvibratoextent 128
chan_end

.layer_3C26:
layer_note1 PITCH_BF2, 30000, 80
layer_jumprel .layer_3C26

.enemy_tailpasaran_cry:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3C32
chan_end

.layer_3C32:
layer_portamento 0x81, 14, 60
layer_note1 PITCH_E2, 0x32, 100
layer_end

.enemy_tailpasaran_die:
chan_setlayer 0, .layer_3C45
chan_setlayer 1, .layer_4829
chan_setvibratorate 112
chan_setvibratoextent 112
chan_end

.layer_3C45:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 35, 96
layer_note1 PITCH_C5, 0x14, 100
layer_portamento 0x81, 44, 207
layer_note1 PITCH_C4, 0x30, 100
layer_end

.enemy_skulltula_climb:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3C5F
chan_setlayer 1, .layer_3C67
chan_end

.layer_3C5F:
layer_portamento 0x81, 39, 100
layer_note1 PITCH_E4, 0x32, 100
layer_end

.layer_3C67:
layer_delay 0x5
layer_portamento 0x81, 37, 100
layer_note1 PITCH_D4, 0x32, 100
layer_end

.enemy_skulltula_drop:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3C7A
chan_setlayer 1, .layer_3C82
chan_end

.layer_3C7A:
layer_portamento 0x81, 43, 100
layer_note1 PITCH_C4, 0x32, 100
layer_end

.layer_3C82:
layer_delay 0x5
layer_portamento 0x81, 41, 100
layer_note1 PITCH_BF3, 0x32, 100
layer_end

.enemy_skulltula_quiver:
chan_setinstr F1_I_LAUGHTER
chan_setenvelope .envelope_699C
chan_setlayer 0, .layer_3C9B
chan_sethilogain 16
chan_setvibratorate 100
chan_setvibratoextent 127
chan_end

.layer_3C9B:
layer_note1 PITCH_F1, 0x64, 100
layer_end

.enemy_tektite_turn_ground:
chan_setlayer 0, .layer_3CA3
chan_end

.layer_3CA3:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_C4, 0xa, 70
layer_end

.enemy_poe_attack_charge:
chan_setlayer 0, .layer_3CB0
chan_setlayer 1, .layer_3CB6
chan_end

.layer_3CB0:
layer_setinstr F1_I_OWL_FLAP
layer_note1 PITCH_F3, 0x19, 100
layer_end

.layer_3CB6:
layer_setinstr F1_I_POT_BREAK
layer_note1 PITCH_F3, 0xa, 30
layer_end

.enemy_poe_float:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setenvelope .envelope_69AC
chan_setlayer 0, .layer_3CC9
chan_setvibratorate 20
chan_setvibratoextent 127
chan_end

.layer_3CC9:
layer_note1 PITCH_F3, 0x87, 100
layer_jumprel .layer_3CC9

.enemy_poe_retreat:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_3CD9
chan_setvibratorate 60
chan_setvibratoextent 100
chan_end

.layer_3CD9:
layer_note1 PITCH_E4, 0x32, 100
layer_delay 0xa
layer_jumprel .layer_3CD9

.enemy_poe_vanish:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setenvelope .envelope_69BC
chan_setlayer 0, .layer_3CED
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_3CED:
layer_portamento 0x81, 43, 255
layer_note1 PITCH_C2, 0x96, 100
layer_end

.enemy_poe_appear:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_3D00
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_3D00:
layer_portamento 0x81, 15, 200
layer_note1 PITCH_E4, 0x96, 100
layer_end

.enemy_poe_hurt:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_3D14
chan_setlayer 1, .layer_4829
chan_sethilogain 24
chan_end

.layer_3D14:
layer_portamento 0x81, 49, 200
layer_note1 PITCH_A5, 0xa, 100
layer_portamento 0x81, 60, 155
layer_note1 PITCH_E5, 0x1e, 100
layer_end

.enemy_poe_die:
chan_setlayer 0, .layer_3D2C
chan_setlayer 1, .layer_4829
chan_sethilogain 24
chan_end

.layer_3D2C:
layer_setinstr F1_I_POE_DISAPPEAR
layer_portamento 0x81, 49, 200
layer_note1 PITCH_A5, 0xa, 100
layer_portamento 0x81, 60, 155
layer_note1 PITCH_E5, 0x3c, 100
layer_end

.enemy_boss_dodongo_roar:
chan_setlayer 0, .layer_3D47
chan_setlayer 1, .layer_3D52
chan_setlayer 2, .layer_3D5D
chan_end

.layer_3D47:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x85, 11, 50
layer_note1 PITCH_C3, 0x12c, 100
layer_end

.layer_3D52:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x85, 13, 50
layer_note1 PITCH_D3, 0x122, 100
layer_end

.layer_3D5D:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x81, 12, 255
layer_note1 PITCH_DF2, 0xc8, 100
layer_end

.enemy_boss_gohma_eyeroll:
chan_setinstr F1_I_EGG_CRACK
chan_setlayer 0, .layer_3D75
chan_setlayer 1, .layer_3D73
chan_sethilogain 18
chan_end

.layer_3D73:
layer_transpose 4

.layer_3D75:
layer_portamento 0x81, 3, 200
layer_note1 PITCH_E1, 0x8c, 100
layer_end

.enemy_boss_dodongo_die:
chan_setlayer 0, .layer_3DB4
chan_setlayer 1, .layer_3D8F
chan_setlayer 2, .layer_3D91
chan_setlayer 3, .layer_4829
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_3D8F:
layer_transpose -6

.layer_3D91:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x85, 38, 255
layer_note1 PITCH_E4, 0x1e, 100
layer_note1 PITCH_B2, 0x96, 100
layer_transpose -5
layer_setenvelope .envelope_69DC, 127
layer_portamento 0x85, 31, 255
layer_note1 PITCH_A3, 0x3c, 80
layer_setenvelope .envelope_6A3C, 127
layer_note1 PITCH_D2, 0xe6, 80
layer_end

.layer_3DB4:
layer_setinstr F1_I_MONSTER_ROAR
layer_setenvelope .envelope_69CC, 230
layer_portamento 0x81, 15, 20
layer_note1 PITCH_E3, 0x96, 100
layer_setenvelope .envelope_6A2C, 240
layer_portamento 0x81, 31, 100
layer_note1 PITCH_C2, 0x10e, 100
layer_end

.enemy_boss_dodongo_dying_groan:
chan_setlayer 0, .layer_3DDF
chan_setlayer 1, .layer_3DEA
chan_setlayer 2, .layer_3DF5
chan_sethilogain 20
chan_setvibratorate 70
chan_setvibratoextent 50
chan_end

.layer_3DDF:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x81, 13, 50
layer_note1 PITCH_D3, 0x118, 100
layer_end

.layer_3DEA:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x81, 11, 50
layer_note1 PITCH_C3, 0x122, 100
layer_end

.layer_3DF5:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x81, 12, 255
layer_note1 PITCH_DF2, 0xc8, 100
layer_end

.enemy_boss_dodongo_fossilize:
chan_setinstr 2
chan_setlayer 0, .layer_3E0F
chan_setlayer 1, .layer_3E11
chan_sethilogain 16
chan_setvibratorate 10
chan_setvibratoextent 20
chan_end

.layer_3E0F:
layer_transpose -8

.layer_3E11:
layer_note1 PITCH_E2, 30000, 100
layer_jumprel .layer_3E11

.enemy_boss_dodongo_lava:
chan_setinstr F1_I_EXPLOSION_LAVA
chan_setenvelope .envelope_682C
chan_sethilogain 20
chan_setlayer 0, .layer_3E25
chan_setlayer 1, .layer_3E29
chan_end

.layer_3E25:
layer_transpose 42
layer_jumprel .layer_3E2B

.layer_3E29:
layer_transpose 48
.layer_3E2B:
layer_note1 PITCH_C5, 0x46, 100
layer_note1 PITCH_F4, 0x46, 100
layer_note1 PITCH_C4, 0x46, 100
layer_note1 PITCH_BF3, 0x32, 100
layer_note1 PITCH_G3, 0x28, 100
layer_note1 PITCH_EF3, 0x28, 100
layer_note1 PITCH_D3, 0x1e, 100
layer_note1 PITCH_BF2, 0x1e, 100
layer_end

.enemy_boss_dodongo_hurt:
chan_setinstr F1_I_DODONGO_ROAR
chan_setenvelope .envelope_683C
chan_setlayer 0, .layer_3E60
chan_setlayer 1, .layer_3E56
chan_setlayer 2, .layer_3E58
chan_setlayer 3, .layer_4829
chan_end

.layer_3E56:
layer_transpose -8

.layer_3E58:
layer_portamento 0x1, 38, 0x14
layer_note1 PITCH_EF4, 0x50, 100
layer_end

.layer_3E60:
layer_portamento 0x85, 31, 150
layer_note1 PITCH_C4, 0x14, 100
layer_note1 PITCH_B3, 0x46, 100
layer_end

.enemy_stalfos_jump:
chan_setlayer 0, .layer_3E6F
chan_end

.layer_3E6F:
layer_setinstr F1_I_GUNSHOT
layer_setenvelope .envelope_686C, 255
layer_transpose 4
layer_portamento 0x81, 26, 50
layer_note1 PITCH_B5, 0x50, 100
layer_end

.enemy_boss_gohma_die:
chan_setenvelope .envelope_687C
chan_setlayer 0, .layer_3E93
chan_setlayer 1, .layer_3E95
chan_setlayer 2, .layer_3EB4
chan_setlayer 3, .layer_4829
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_3E93:
layer_transpose -6

.layer_3E95:
layer_setinstr F1_I_DINO_ROAR
layer_portamento 0x85, 38, 255
layer_note1 PITCH_E4, 0x1e, 100
layer_note1 PITCH_B2, 0x96, 100
layer_transpose -5
layer_portamento 0x85, 32, 255
layer_note1 PITCH_C4, 0x3c, 80
layer_setenvelope .envelope_6A3C, 200
layer_note1 PITCH_B2, 0xc8, 80
layer_end

.layer_3EB4:
layer_setinstr F1_I_MONSTER_ROAR
layer_setenvelope .envelope_69CC, 200
layer_portamento 0x81, 15, 20
layer_note1 PITCH_E3, 0x96, 100
layer_setenvelope .envelope_6A2C, 200
layer_portamento 0x81, 31, 100
layer_note1 PITCH_C2, 0x12c, 100
layer_end

.enemy_scrub_emerge:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3ED8
chan_setlayer 1, .layer_3EDA
chan_end

.layer_3ED8:
layer_transpose -2

.layer_3EDA:
layer_portamento 0x81, 31, 64
layer_note1 PITCH_C4, 0x32, 100
layer_end

.enemy_scrub_burrow:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_3EEB
chan_setlayer 1, .layer_3EED
chan_end

.layer_3EEB:
layer_transpose -2

.layer_3EED:
layer_portamento 0x81, 39, 64
layer_note1 PITCH_E3, 0x32, 100
layer_end

.enemy_scrub_spit:
chan_setinstr 2
chan_setlayer 0, .layer_3EFD
chan_sethilogain 32
chan_end

.layer_3EFD:
layer_portamento 0x81, 31, 64
layer_note1 PITCH_C4, 0xc, 100
layer_end

.enemy_scrub_walk:
chan_setlayer 0, .layer_3F0C
chan_setlayer 1, .layer_5320
chan_end

.layer_3F0C:
layer_setinstr F1_I_GRASS_RUSTLE
layer_note1 PITCH_DF4, 0x20, 70
layer_end

.enemy_scrub_hurt:
chan_setlayer 0, .layer_3F16
chan_end

.layer_3F16:
layer_setinstr F1_I_SCRUB_DEATH
layer_transpose 4
layer_portamento 0x81, 51, 255
layer_note1 PITCH_B5, 0xa, 100
layer_portamento 0x81, 60, 255
layer_note1 PITCH_E5, 0x19, 100
layer_end

.enemy_scrub_die:
chan_setlayer 0, .layer_3F2D
chan_end

.layer_3F2D:
layer_setinstr F1_I_SCRUB_DEATH
layer_portamento 0x81, 59, 255
layer_note1 PITCH_E5, 0xa, 100
layer_portamento 0x81, 51, 255
layer_note1 PITCH_F4, 0x1e, 100
layer_end

.enemy_boss_gohma_dissolve:
chan_setlayer 0, .layer_3F49
chan_setlayer 1, .layer_3F4B
chan_setvibratorate 10
chan_setvibratoextent 20
chan_end

.layer_3F49:
layer_transpose -1

.layer_3F4B:
layer_setinstr 2
.layer_3F4D:
layer_note1 PITCH_EF1, 30000, 100
layer_jumprel .layer_3F4D

.enemy_tektite_hurt:
chan_setinstr F1_I_GUAY_HURT
chan_setenvelope .envelope_65D8
chan_setlayer 0, .layer_3F5F
chan_setlayer 1, .layer_4829
chan_end

.layer_3F5F:
layer_portamento 0x81, 36, 255
layer_note1 PITCH_E4, 0xa, 100
layer_portamento 0x81, 44, 255
layer_note1 PITCH_B3, 0x1e, 100
layer_end

.enemy_tektite_die:
chan_setlayer 0, .layer_3F78
chan_setlayer 1, .layer_3F89
chan_setlayer 2, .layer_4829
chan_end

.layer_3F78:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x81, 32, 255
layer_note1 PITCH_C4, 0xa, 100
layer_portamento 0x81, 40, 255
layer_note1 PITCH_G3, 0x5c, 100
layer_end

.layer_3F89:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 43, 255
layer_note1 PITCH_B4, 0xf, 80
layer_portamento 0x81, 48, 255
layer_note1 PITCH_EF4, 0x24, 80
layer_end

.enemy_stinger_hurt:
chan_setinstr F1_I_GUAY_HURT
chan_setlayer 0, .layer_3FA7
chan_setlayer 1, .layer_4829
chan_setvibratorate 48
chan_setvibratoextent 48
chan_end

.layer_3FA7:
layer_transpose -10
layer_jumprel .layer_3F5F
layer_end

.enemy_stinger_die:
chan_setlayer 0, .layer_3FBA
chan_setlayer 1, .layer_3FCB
chan_setlayer 2, .layer_4829
chan_setvibratorate 48
chan_setvibratoextent 48
chan_end

.layer_3FBA:
layer_setinstr F1_I_DODONGO_ROAR
layer_portamento 0x81, 22, 127
layer_note1 PITCH_DF4, 0x28, 100
layer_portamento 0x81, 38, 255
layer_note1 PITCH_A2, 0x7f, 100
layer_end

.layer_3FCB:
layer_transpose -12
layer_jumprel .layer_3F89
layer_end

.enemy_skulltula_hurt:
chan_setlayer 0, .layer_4829
chan_setlayer 1, .layer_3FD7
chan_end

.layer_3FD7:
layer_setinstr F1_I_DINO_INHALE
layer_portamento 0x81, 51, 255
layer_note1 PITCH_B5, 0xa, 100
layer_portamento 0x81, 60, 255
layer_note1 PITCH_E5, 0x14, 100
layer_end

.enemy_gold_skull_cry:
chan_setlayer 0, .layer_3FD7
chan_end

.enemy_skulltula_pivot:
chan_setinstr F1_I_OWL_FLAP
chan_setlayer 0, .layer_3FF2
chan_end

.layer_3FF2:
layer_portamento 0x81, 51, 255
layer_note1 PITCH_B5, 0x14, 100
layer_portamento 0x81, 60, 255
layer_note1 PITCH_E5, 0x14, 100
layer_end

.enemy_skullwall_die:
chan_setlayer 0, .layer_400C
chan_setlayer 1, .layer_4829
chan_setvibratorate 100
chan_setvibratoextent 127
chan_end

.layer_400C:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 29, 255
layer_note1 PITCH_BF3, 0x14, 100
layer_note1 PITCH_BF2, 0x3c, 100
layer_end

.enemy_dissolve:
chan_setinstr 2
chan_setenvelope .envelope_68DC
chan_setlayer 0, .layer_4023
chan_end

.layer_4023:
layer_portamento 0x81, 7, 100
layer_note1 PITCH_A1, 0x19, 100
layer_end

.enemy_boss_gohma_thrust:
chan_setinstr F1_I_MONSTER_ROAR
chan_setenvelope .envelope_68EC
chan_setlayer 0, .layer_4038
chan_setvibratorate 100
chan_setvibratoextent 50
chan_end

.layer_4038:
layer_portamento 0x81, 45, 250
layer_note1 PITCH_GF3, 0x28, 100
layer_end

.enemy_lizalfos_cry:
chan_setlayer 0, .layer_404B
chan_setlayer 1, .layer_4057
chan_setvibratorate 50
chan_setvibratoextent 60
chan_end

.layer_404B:
layer_setinstr F1_I_BABA_LUNGE
layer_transpose 48
layer_portamento 0x81, 32, 100
layer_note1 PITCH_D3, 0x23, 80
layer_end

.layer_4057:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x81, 39, 100
layer_note1 PITCH_A3, 0x28, 100
layer_end

.enemy_lizalfos_attack_shout:
chan_setlayer 1, .layer_406B
chan_setlayer 0, .layer_4077
chan_setlayer 2, .layer_4081
chan_end

.layer_406B:
layer_setinstr F1_I_BABA_LUNGE
layer_transpose 48
layer_portamento 0x81, 34, 200
layer_note1 PITCH_B3, 0x23, 80
layer_end

.layer_4077:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x81, 39, 255
layer_note1 PITCH_F4, 0x32, 100
layer_end

.layer_4081:
layer_setinstr F1_I_GERUDO_ATTACK
layer_setenvelope .envelope_682C, 240
layer_delay 0xa
layer_note1 PITCH_D4, 0x1e, 100
layer_end

.enemy_dodongo_swipe:
chan_setinstr F1_I_GUNSHOT
chan_setenvelope .envelope_686C
chan_setlayer 0, .layer_4098
chan_sethilogain 20
chan_end

.layer_4098:
layer_transpose 5
layer_portamento 0x81, 26, 200
layer_note1 PITCH_B5, 0xc8, 100
layer_end

.enemy_poe_transform:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setenvelope .envelope_69BC
chan_setlayer 0, .layer_40B0
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_40B0:
layer_portamento 0x81, 55, 255
layer_note1 PITCH_C3, 0x50, 100
layer_end

.enemy_wallmaster_fall:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_40C1
chan_setlayer 1, .layer_40C3
chan_end

.layer_40C1:
layer_transpose -6

.layer_40C3:
layer_note1 PITCH_C3, 0x1a0, 100
layer_end

.enemy_wallmaster_retreat:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setenvelope .envelope_69FC
chan_setlayer 0, .layer_40D3
chan_sethilogain 16
chan_end

.layer_40D3:
layer_portamento 0x81, 36, 100
layer_note1 PITCH_C4, 0x78, 100
layer_end

.enemy_floormaster_walk:
chan_setinstr F1_I_EGG_CRACK
chan_setlayer 0, .layer_40E3
chan_sethilogain 20
chan_end

.layer_40E3:
layer_portamento 0x81, 9, 128
layer_note1 PITCH_A1, 0xf, 100
layer_end

.enemy_floormaster_hurt:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_40F8
chan_setlayer 1, .layer_4829
chan_setvibratorate 100
chan_setvibratoextent 70
chan_end

.layer_40F8:
layer_enablelegato
layer_portamento 0x85, 42, 128
layer_note1 PITCH_AF4, 0x1e, 100
layer_note1 PITCH_C4, 0x28, 100
layer_end

.enemy_floormaster_die:
chan_setlayer 0, .layer_410F
chan_setlayer 1, .layer_4829
chan_setvibratorate 132
chan_setvibratoextent 70
chan_end

.layer_410F:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 46, 128
layer_note1 PITCH_C5, 0x28, 100
layer_note1 PITCH_E4, 0x30, 100
layer_end

.enemy_biri_float:
chan_setinstr F1_I_STALFOS_ATTACK
chan_setenvelope .envelope_6A0C
chan_setlayer 0, .layer_4126
chan_end

.layer_4126:
layer_enablelegato
layer_portamento 0x85, 31, 255
layer_note1 PITCH_A3, 0x32, 100
layer_note1 PITCH_AF2, 0x46, 100
layer_end

.enemy_biri_fly:
chan_setlayer 0, .layer_414B
chan_setlayer 1, .layer_4139
chan_end

.layer_4139:
layer_setinstr 2
layer_setenvelope .envelope_6A0C, 220
layer_enablelegato
layer_portamento 0x85, 27, 200
layer_note1 PITCH_F3, 0x14, 60
layer_note1 PITCH_E2, 0x32, 60
layer_end

.layer_414B:
layer_setinstr F1_I_STALFOS_ATTACK
layer_setenvelope .envelope_6A0C, 128
layer_enablelegato
layer_portamento 0x85, 31, 200
layer_note1 PITCH_A3, 0x32, 100
layer_note1 PITCH_AF2, 0x46, 100
layer_end

.enemy_biri_shock:
chan_setinstr F1_I_GANONDORF_ATTACK_0
.chan_415F:
chan_setlayer 0, .layer_4179
.chan_4162:
chan_rand 6
chan_writeseq 3, .layer_4179+1
chan_writeseq 3, .chan_4172+1
chan_rand 8
chan_writeseq 91, .layer_4179
.chan_4172:
chan_setval 1
chan_call .delay_varyingvol
chan_jumprel .chan_4162

.layer_4179:
layer_note1 PITCH_C3, 0x50, 80
layer_jumprel .layer_4179

.enemy_boss_ganon_transform:
chan_setinstr F1_I_GANONDORF_ATTACK_0
chan_setdecayrelease 208
chan_jumprel .chan_415F

.enemy_biri_die:
chan_setlayer 0, .layer_4829
chan_setlayer 1, .layer_418B
chan_end

.layer_418B:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 32, 255
layer_note1 PITCH_C4, 0xa, 100
layer_portamento 0x81, 41, 255
layer_note1 PITCH_F3, 0xe, 100
layer_end

.enemy_torch_slug_hurt:
chan_setlayer 0, .layer_41A6
chan_setlayer 1, .layer_41B8
chan_setlayer 2, .layer_4829
chan_end

.layer_41A6:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 32, 64
layer_note1 PITCH_C4, 0x14, 80
layer_portamento 0x81, 37, 255
layer_note1 PITCH_BF2, 0x24, 80
layer_end

.layer_41B8:
layer_transpose -8
layer_jumprel .layer_418B

.enemy_biri_die_bubbles:
chan_setlayer 0, .layer_41C0
chan_end

.layer_41C0:
layer_setinstr F1_I_WATER_BUBBLES
layer_setenvelope .envelope_6A1C, 249
layer_portamento 0x81, 25, 255
layer_note1 PITCH_G3, 0x90, 100
layer_end

.enemy_phantom_reveal:
chan_setinstr F1_I_DINO_ROAR
chan_setenvelope .envelope_69CC
chan_setlayer 0, .layer_41E0
chan_setvibratoratelinear 70, 110, 18
chan_setvibratoextentlinear 20, 80, 10
chan_end

.layer_41E0:
layer_portamento 0x81, 21, 255
layer_note1 PITCH_BF2, 0xe6, 100
layer_end

.enemy_phantom_lightning:
chan_setlayer 0, .layer_41EF
chan_sethilogain 22
chan_end

.layer_41EF:
layer_setinstr F1_I_ELECTRIC_ATTACK
layer_note1 PITCH_C4, 0x118, 100
layer_end

.enemy_ganondorf_charge:
chan_setinstr F1_I_GANONDORF_ATTACK_0
chan_setlayer 0, .layer_41FE
chan_sethilogain 20
chan_end

.layer_41FE:
layer_note1 PITCH_A3, 0x50, 100
layer_end

.enemy_ganondorf_fly:
chan_setinstr F1_I_GANONDORF_FLY
chan_setlayer 0, .layer_4208
chan_end

.layer_4208:
layer_note1 PITCH_D4, 30000, 100
layer_jumprel .layer_4208

.enemy_witch_charge:
chan_setlayer 0, .layer_4214
chan_sethilogain 24
chan_end

.layer_4214:
layer_setinstr F1_I_GANONDORF_CHARGE
layer_note1 PITCH_F4, 0x5a, 100
layer_end

.enemy_phantom_painting_enter:
chan_setlayer 0, .layer_4220
chan_sethilogain 24
chan_end

.layer_4220:
layer_setinstr F1_I_SWOOSH
layer_note1 PITCH_D4, 0x5a, 100
layer_end

.enemy_phantom_shout:
chan_setinstr F1_I_PHANTOM_ATTACK
chan_setlayer 0, .layer_422E
chan_sethilogain 24
chan_end

.layer_422E:
layer_portamento 0x81, 39, 50
layer_note1 PITCH_F4, 0x30, 100
layer_end

.enemy_ganondorf_orb_trail:
chan_setlayer 0, .layer_423E
chan_setvibratorate 128
chan_setvibratoextent 128
chan_end

.layer_423E:
layer_setinstr 2
layer_enablelegato
layer_portamento 0x81, 37, 255
.layer_4245:
layer_note1 PITCH_GF3, 0xc8, 100
layer_jumprel .layer_4245

.enemy_boss_twinrova_ice_reflected:
chan_setlayer 0, .layer_4256
chan_setlayer 1, .layer_4B32
chan_setvibratorate 128
chan_setvibratoextent 96
chan_end

.layer_4256:
layer_setinstr 2
layer_transpose 12
layer_enablelegato
layer_jumprel .layer_4245

.enemy_ganondorf_lightning_hit:
chan_setlayer 0, .layer_4261
chan_end

.layer_4261:
layer_setinstr F1_I_ELECTRIC_ATTACK
layer_note1 PITCH_C5, 0x8c, 100
layer_end

.enemy_phantom_attack_unused:
chan_setinstr F1_I_THUNDERBURST
chan_setenvelope .envelope_6A5C
chan_setlayer 0, .layer_4273
chan_sethilogain 16
chan_end

.layer_4273:
layer_note1 PITCH_E3, 0x1c2, 100
layer_end

.enemy_phantom_staff:
chan_setinstr F1_I_SWOOSH
chan_setlayer 0, .layer_4280
chan_sethilogain 20
chan_end

.layer_4280:
layer_delay 0xf
layer_note1 PITCH_C4, 0x7, 100
layer_note1 PITCH_G4, 0x7, 100
layer_note1 PITCH_C5, 0x7, 100
layer_note1 PITCH_G5, 0x7, 100
layer_note1 PITCH_E4, 0x7, 100
layer_note1 PITCH_B4, 0x7, 100
layer_note1 PITCH_E5, 0x7, 100
layer_note1 PITCH_B5, 0x7, 100
layer_end

.enemy_phantom_eyes:
chan_setinstr F1_I_GANONDORF_CHARGE
chan_setenvelope .envelope_699C
chan_setlayer 0, .layer_42AA
chan_sethilogain 20
chan_setvibratorate 128
chan_setvibratoextent 20
chan_end

.layer_42AA:
layer_portamento 0x81, 33, 255
layer_note1 PITCH_DF3, 0x6e, 100
layer_end

.enemy_phantom_orb_dissipate:
chan_setinstr F1_I_THUNDERBURST
chan_setlayer 0, .layer_42B8
chan_end

.layer_42B8:
layer_portamento 0x81, 60, 200
layer_note1 PITCH_C3, 0x1e, 100
layer_end

.enemy_phantom_die_roar:
chan_setinstr F1_I_PHANTOM_WAIL
chan_setlayer 0, .layer_42E9
chan_setlayer 1, .layer_42DD
chan_setlayer 2, .layer_42D4
chan_sethilogain 20
chan_setdecayrelease 244
chan_setvibratorate 50
chan_setvibratoextent 30
chan_end

.layer_42D4:
layer_portamento 0x81, 46, 100
layer_note1 PITCH_D4, 0xb4, 100
layer_end

.layer_42DD:
layer_delay 0x96
layer_portamento 0x81, 36, 220
layer_note1 PITCH_E3, 0xd2, 100
layer_end

.layer_42E9:
layer_delay 0x14a
layer_portamento 0x81, 31, 200
layer_note1 PITCH_A2, 0x14a, 100
layer_end

.enemy_phantom_hurt:
chan_setlayer 0, .layer_4301
chan_setlayer 1, .layer_430F
chan_setlayer 2, .layer_4829
chan_sethilogain 20
chan_end

.layer_4301:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 39, 100
layer_note1 PITCH_A4, 0x1e, 100
layer_note1 PITCH_C4, 0x3c, 100
layer_end

.layer_430F:
layer_setinstr F1_I_GANONDORF_ATTACK_0
layer_enablelegato
layer_portamento 0x81, 29, 100
layer_note1 PITCH_E4, 0x14, 68
layer_portamento 0x81, 34, 255
layer_note1 PITCH_G2, 0x24, 68
layer_end

.enemy_deadhand_hurt:
chan_setlayer 0, .layer_4328
chan_setlayer 1, .layer_4829
chan_end

.layer_4328:
layer_transpose -7
layer_jumprel .layer_4301

.enemy_phantom_die:
chan_setlayer 0, .layer_433B
chan_setlayer 1, .layer_434A
chan_setlayer 2, .layer_434C
chan_setlayer 3, .layer_4829
chan_sethilogain 20
chan_end

.layer_433B:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 36, 255
layer_note1 PITCH_GF4, 0x50, 100
layer_note1 PITCH_AF2, 500, 100
layer_end

.layer_434A:
layer_transpose -16

.layer_434C:
layer_setinstr F1_I_THUNDERBURST
layer_note1 PITCH_AF4, 0x1c2, 100
layer_end

.enemy_deadhand_die:
chan_setlayer 0, .layer_435A
chan_setlayer 1, .layer_4829
chan_end

.layer_435A:
layer_transpose -8
layer_jumprel .layer_433B

.enemy_phantom_hurt_orb:
chan_setinstr F1_I_PHANTOM_WAIL
chan_setlayer 0, .layer_436C
chan_sethilogain 20
chan_setdecayrelease 249
chan_setvibratorate 127
chan_setvibratoextent 70
chan_end

.layer_436C:
layer_enablelegato
layer_portamento 0x85, 30, 100
layer_note1 PITCH_G3, 0x1e, 100
layer_note1 PITCH_C3, 0x14, 100
layer_end

.enemy_phantom_laugh:
chan_setinstr F1_I_PHANTOM_LAUGH_1
chan_setlayer 0, .layer_4380
chan_sethilogain 16
chan_end

.layer_4380:
layer_note1 PITCH_BF3, 0x160, 100
layer_end

.enemy_moblin_walk:
chan_setinstr F1_I_SMASH
chan_setenvelope .envelope_68EC
chan_setlayer 0, .layer_438E
chan_end

.layer_438E:
layer_portamento 0x81, 28, 64
layer_note1 PITCH_GF2, 0xd, 76
layer_end

.enemy_moblin_dash:
chan_setinstr F1_I_SMASH
chan_setenvelope .envelope_68EC
chan_setlayer 0, .layer_439F
chan_end

.layer_439F:
layer_portamento 0x81, 32, 64
layer_note1 PITCH_BF2, 0x1d, 100
layer_end

.enemy_moblin_slide:
chan_setlayer 0, .layer_43AE
chan_setlayer 1, .layer_43B0
chan_end

.layer_43AE:
layer_transpose -5

.layer_43B0:
layer_setinstr F1_I_TEKTITE_ROTATE
layer_note1 PITCH_C2, 0x78, 100
layer_end

.enemy_octorok_jump:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_43BC
chan_end

.layer_43BC:
layer_portamento 0x81, 40, 100
layer_note1 PITCH_AF4, 0x64, 80
layer_end

.enemy_octorok_dive:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_43CA
chan_end

.layer_43CA:
layer_portamento 0x81, 38, 100
layer_note1 PITCH_E3, 0x30, 100
layer_end

.enemy_octorok_bubble:
chan_setlayer 0, .layer_43D6
chan_end

.layer_43D6:
layer_setinstr F1_I_STEP_WATER
layer_note1 PITCH_B1, 0x66, 100
layer_end

.enemy_octorok_float:
chan_setinstr F1_I_STEP_WATER
chan_setlayer 0, .layer_43E2
chan_end

.layer_43E2:
layer_portamento 0x81, 23, 100
layer_note1 PITCH_BF2, 0x30, 68
layer_end

.enemy_tektite_land_water1:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_43F0
chan_end

.layer_43F0:
layer_portamento 0x81, 47, 100
layer_note1 PITCH_DF4, 0x50, 80
layer_end

.enemy_octorok_rock_break:
chan_setlayer 0, .layer_43FC
chan_end

.layer_43FC:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_setenvelope .envelope_68EC, 251
layer_note1 PITCH_A2, 0x2c, 100
layer_end

.enemy_bubble_dash:
chan_setinstr F1_I_POT_BREAK
chan_setlayer 0, .layer_440C
chan_end

.layer_440C:
layer_portamento 0x81, 8, 255
layer_note1 PITCH_C2, 0x6, 70
layer_portamento 0x81, 14, 255
layer_note1 PITCH_A1, 0x8, 70
layer_end

.enemy_bubble_cry:
chan_setlayer 0, .layer_4423
chan_setvibratorate 96
chan_setvibratoextent 128
chan_end

.layer_4423:
layer_setinstr F1_I_PHANTOM_LAUGH_0
layer_note1 PITCH_E4, 0x54, 100
layer_end

.enemy_bubble_flame_appear:
chan_setinstr F1_I_DODONGO_ROAR
chan_setenvelope .envelope_6A0C
chan_setlayer 0, .layer_443A
chan_setvibratoratelinear 70, 110, 18
chan_setvibratoextentlinear 20, 80, 10
chan_end

.layer_443A:
layer_portamento 0x81, 19, 255
layer_note1 PITCH_AF2, 0x46, 100
layer_end

.enemy_bubble_flame_vanish:
chan_setinstr F1_I_DODONGO_ROAR
chan_setenvelope .envelope_6A0C
chan_setlayer 0, .layer_4453
chan_setvibratoratelinear 70, 110, 18
chan_setvibratoextentlinear 20, 80, 10
chan_end

.layer_4453:
layer_portamento 0x81, 23, 255
layer_note1 PITCH_E2, 0x46, 100
layer_end

.enemy_moblin_attack_shout:
chan_setinstr F1_I_LIZALFOS
chan_setlayer 0, .layer_4463
chan_sethilogain 16
chan_end

.layer_4463:
layer_portamento 0x81, 17, 255
layer_note1 PITCH_A2, 0x96, 100
layer_end

.enemy_moblin_grunt:
chan_setinstr F1_I_MOBLIN_GROWL
chan_setlayer 0, .layer_4474
chan_sethilogain 16
chan_end

.layer_4474:
layer_portamento 0x81, 21, 255
layer_note1 PITCH_DF2, 0x44, 100
layer_end

.enemy_moblin_spear_relax:
chan_setinstr F1_I_GULP_SPEAR
chan_setlayer 0, .layer_4482
chan_end

.layer_4482:
layer_transpose 42
layer_note1 PITCH_F4, 0xa, 100
layer_end

.enemy_moblin_spear_point:
chan_setinstr F1_I_GULP_SPEAR
chan_setlayer 0, .layer_4490
chan_sethilogain 20
chan_end

.layer_4490:
layer_transpose 44
layer_note1 PITCH_B3, 0x1d, 100
layer_end

.enemy_moblin_club_strike:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_449C
chan_end

.layer_449C:
layer_portamento 0x81, 25, 255
layer_note1 PITCH_F2, 0x78, 100
layer_end

.enemy_moblin_club_lift:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_44AA
chan_end

.layer_44AA:
layer_portamento 0x81, 16, 255
layer_note1 PITCH_B2, 0x78, 100
layer_end

.enemy_moblin_die:
chan_setlayer 0, .layer_44B9
chan_setlayer 1, .layer_4829
chan_end

.layer_44B9:
layer_setinstr F1_I_LIZALFOS
layer_enablelegato
layer_portamento 0x85, 23, 200
layer_note1 PITCH_C3, 0x1e, 100
layer_note1 PITCH_DF2, 0x3c, 100
layer_end

.enemy_boss_volvagia_rock:
chan_setinstr F1_I_EXPLOSION_LAVA
chan_setlayer 0, .layer_44D7
chan_sethilogain 20
chan_rand 4
chan_writeseq 107, .layer_44D7
chan_setdecayrelease 232
chan_end

.layer_44D7:
layer_note1 PITCH_F4, 0x32, 100
layer_end

.enemy_boss_volvagia_roar:
chan_setlayer 0, .layer_44EB
chan_setlayer 1, .layer_44E4
chan_sethilogain 20
chan_end

.layer_44E4:
layer_setinstr F1_I_THUNDER_HURT
layer_note1 PITCH_D4, 0xa8, 100
layer_end

.layer_44EB:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 43, 255
layer_note1 PITCH_GF4, 0xa, 100
layer_portamento 0x81, 45, 255
layer_note1 PITCH_A4, 0xa8, 100
layer_end

.enemy_boss_ganon_roar:
chan_setlayer 0, .layer_4508
chan_setlayer 1, .layer_450F
chan_setlayer 2, .layer_4513
chan_end

.layer_4508:
layer_setinstr F1_I_MONSTER_ROAR
layer_note1 PITCH_E4, 0xb4, 100
layer_end

.layer_450F:
layer_transpose -2
layer_jumprel .layer_44EB

.layer_4513:
layer_transpose 6
layer_jumprel .layer_44E4

.enemy_volvagia_fall:
chan_setlayer 0, .layer_4532
chan_setlayer 1, .layer_4524
chan_sethilogain 20
chan_setvibratorate 120
chan_setvibratoextent 64
chan_end

.layer_4524:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_F4, 0x14, 80
layer_note1 PITCH_C3, 0x6e, 80
layer_end

.layer_4532:
layer_setinstr F1_I_THUNDER_HURT
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_A4, 0x14, 100
layer_note1 PITCH_C2, 0xc8, 100
layer_end

.enemy_volvagia_paralyzed:
chan_setinstr F1_I_DINO_ROAR
chan_sethilogain 20
chan_setlayer 0, .layer_4549
chan_end

.layer_4549:
layer_enablelegato
layer_portamento 0x85, 19, 255
layer_note1 PITCH_GF2, 0x1e, 100
layer_note1 PITCH_B1, 0x1e, 100
layer_end

.enemy_boss_volvagia_cry:
chan_setlayer 0, .layer_4564
chan_setlayer 1, .layer_455E
chan_sethilogain 20
chan_end

.layer_455E:
layer_setinstr F1_I_THUNDER_HURT
layer_note1 PITCH_AF4, 0x78, 100
layer_end

.layer_4564:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 49, 255
layer_note1 PITCH_C5, 0xa, 100
layer_portamento 0x81, 51, 255
layer_note1 PITCH_EF5, 0x78, 100
layer_end

.enemy_boss_ganon_hurt:
chan_setlayer 0, .layer_4580
chan_setlayer 1, .layer_4564
chan_setlayer 2, .layer_4584
chan_end

.layer_4580:
layer_transpose -6
layer_jumprel .layer_4564

.layer_4584:
layer_setinstr F1_I_MONSTER_ROAR
layer_enablelegato
layer_portamento 0x85, 40, 200
layer_note1 PITCH_AF4, 0x10, 100
layer_note1 PITCH_D3, 0xb4, 100
layer_end

.enemy_boss_volvagia_hole:
chan_setlayer 0, .layer_45A0
chan_setlayer 1, .layer_45AC
chan_sethilogain 20
chan_setvibratorate 10
chan_setvibratoextent 20
chan_end

.layer_45A0:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_setenvelope .envelope_68B4, 220
.layer_45A6:
layer_note1 PITCH_GF2, 0x118, 100
layer_jumprel .layer_45A6

.layer_45AC:
layer_setinstr 2
.layer_45AE:
layer_note1 PITCH_B0, 30000, 100
layer_jumprel .layer_45AE

.enemy_boss_volvagia_swipe:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_45BA
chan_end

.layer_45BA:
layer_portamento 0x81, 28, 255
layer_note1 PITCH_C4, 0x40, 100
layer_end

.enemy_redead_moan:
chan_setinstr F1_I_GORON_YAWN
chan_setlayer 0, .layer_45CB
chan_setlayer 1, .layer_45CD
chan_end

.layer_45CB:
layer_delay 0x18

.layer_45CD:
layer_note1 PITCH_E3, 0x170, 80
layer_end

.enemy_redead_scream:
chan_setlayer 0, .layer_45D9
chan_setlayer 1, .layer_45DF
chan_end

.layer_45D9:
layer_setinstr INSTR_SFX
layer_note1 F1_E_REDEAD_SCREAM, 0x0, 100
layer_end

.layer_45DF:
layer_setinstr F1_I_DINO_ROAR
layer_portamento 0x81, 30, 255
layer_note1 PITCH_BF3, 0x2e, 100
layer_end

.enemy_redead_hurt:
chan_setinstr F1_I_GORON_YAWN
chan_setlayer 0, .layer_45F5
chan_setlayer 1, .layer_45F7
chan_setlayer 2, .layer_4829
chan_end

.layer_45F5:
layer_delay 0x18

.layer_45F7:
layer_portamento 0x81, 34, 255
layer_note1 PITCH_E2, 0x44, 100
layer_end

.enemy_redead_die:
chan_setinstr F1_I_GORON_YAWN
chan_setlayer 0, .layer_460B
chan_setlayer 1, .layer_460D
chan_setlayer 2, .layer_4829
chan_end

.layer_460B:
layer_delay 0x18

.layer_460D:
layer_enablelegato
layer_portamento 0x85, 30, 255
layer_note1 PITCH_F3, 0x1e, 100
layer_note1 PITCH_EF2, 0x84, 100
layer_end

.enemy_poe_laugh:
chan_setinstr F1_I_PHANTOM_LAUGH_1
chan_sethilogain 20
chan_setlayer 0, .layer_4625
chan_setlayer 1, .layer_4627
chan_end

.layer_4625:
layer_delay 0x16

.layer_4627:
layer_note1 PITCH_BF5, 0x62, 100
layer_end

.enemy_poe_sister_attack:
chan_setinstr F1_I_GUNSHOT
chan_setenvelope .envelope_686C
chan_setlayer 0, .layer_4634
chan_end

.layer_4634:
layer_portamento 0x81, 33, 200
layer_note1 PITCH_GF4, 0x22, 100
layer_end

.enemy_redead_attack:
chan_setlayer 0, .layer_4643
chan_setlayer 1, .layer_4651
chan_end

.layer_4643:
layer_setinstr F1_I_GORON_YAWN
layer_setenvelope .envelope_68EC, 250
layer_portamento 0x81, 30, 255
layer_note1 PITCH_B2, 0x30, 100
layer_end

.layer_4651:
layer_setinstr F1_I_SMASH
layer_setenvelope .envelope_692C, 250
layer_portamento 0x81, 17, 50
layer_note1 PITCH_D1, 0x1e, 100
layer_end

.enemy_poe_sister_laugh:
chan_setinstr F1_I_PHANTOM_LAUGH_1
chan_setlayer 0, .layer_466B
chan_setlayer 1, .layer_466D
chan_setlayer 2, .layer_466F
chan_end

.layer_466B:
layer_delay 0x16

.layer_466D:
layer_delay 0x16

.layer_466F:
layer_note1 PITCH_GF5, 0x72, 100
layer_end

.enemy_poe_sister_cry:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_4679
chan_end

.layer_4679:
layer_portamento 0x81, 53, 120
layer_note1 PITCH_G4, 0x44, 100
layer_end

.enemy_boss_morpha_rise:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_468B
chan_setvibratorate 20
chan_setvibratoextent 36
chan_end

.layer_468B:
layer_setenvelope .envelope_6A4C, 220
.layer_468F:
layer_note1 PITCH_A1, 0xfa, 100
layer_jumprel .layer_468F

.enemy_boss_morpha_attack:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_469F
chan_setvibratorate 127
chan_setvibratoextent 84
chan_end

.layer_469F:
layer_setenvelope .envelope_6A2C, 220
layer_portamento 0x81, 12, 120
.layer_46A7:
layer_note1 PITCH_A3, 0xd0, 100
layer_jumprel .layer_46A7

.enemy_boss_morpha_toss:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_46B7
chan_setvibratorate 20
chan_setvibratoextent 36
chan_end

.layer_46B7:
layer_setenvelope .envelope_69BC, 235
layer_enablelegato
layer_portamento 0x85, 0, 255
layer_note1 PITCH_A2, 0x2a, 100
layer_note1 PITCH_A0, 0x52, 100
layer_end

.enemy_boss_morpha_grab:
chan_setinstr F1_I_PHANTOM_MOAN
chan_setlayer 0, .layer_46CF
chan_sethilogain 16
chan_end

.layer_46CF:
layer_portamento 0x81, 30, 255
layer_note1 PITCH_C3, 0x72, 100
layer_end

.enemy_octorok_death_gasp:
chan_setinstr F1_I_LIZALFOS
chan_setenvelope .envelope_68FC
chan_setlayer 0, .layer_46E0
chan_end

.layer_46E0:
layer_portamento 0x81, 17, 255
layer_note1 PITCH_BF2, 0x8, 100
layer_portamento 0x81, 26, 255
layer_note1 PITCH_EF1, 0xc, 100
layer_end

.enemy_octorok_die:
chan_setinstr F1_I_LIZALFOS
chan_setlayer 0, .layer_46FC
chan_setlayer 1, .layer_4829
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_46FC:
layer_portamento 0x81, 38, 255
layer_note1 PITCH_G3, 0x84, 100
layer_end

.enemy_boss_morpha_demo_move:
chan_setinstr F1_I_WATER_BUBBLES
chan_setlayer 0, .layer_470D
chan_setpanmix 0
chan_end

.layer_470D:
layer_enablelegato
layer_portamento 0x85, 23, 255
.layer_4712:
layer_note1 PITCH_F2, 0x2c, 100
layer_note1 PITCH_AF2, 0x2c, 100
layer_jumprel .layer_4712

.enemy_boss_morpha_demo_bubble:
chan_setinstr F1_I_WATER_BUBBLES
chan_setenvelope .envelope_6A1C
chan_setlayer 0, .layer_472A
chan_setlayer 1, .layer_472C
chan_setpanmix 0
chan_sethilogain 20
chan_end

.layer_472A:
layer_delay 0x8

.layer_472C:
layer_portamento 0x81, 31, 255
layer_note1 PITCH_DF3, 0x74, 100
layer_end

.enemy_boss_morpha_caught:
chan_setlayer 0, .layer_473B
chan_setlayer 1, .layer_4742
chan_end

.layer_473B:
layer_setinstr F1_I_WATER_SPLASH_L
layer_note1 PITCH_D4, 0x86, 100
layer_end

.layer_4742:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x81, 36, 100
layer_note1 PITCH_B4, 0x10, 80
layer_portamento 0x81, 41, 255
layer_note1 PITCH_D3, 0x6, 80
layer_end

.enemy_boss_morpha_die:
chan_setlayer 0, .layer_4781
chan_setlayer 1, .layer_479D
chan_setvibratoextent 144
chan_setvibratorate 196
chan_setval 56
chan_iowriteval 6
.chan_4761:
chan_ioreadval 6
chan_writeseq 0, .layer_4788+1
chan_writeseq 0, .layer_478B+1
chan_writeseq 0, .layer_4794+1
chan_writeseq 0, .layer_4797+1
chan_subtract 1
chan_iowriteval 6
chan_subtract 4
chan_beqzrel .chan_4780
chan_setval 6
chan_call .delay_varyingvol
chan_jumprel .chan_4761
.chan_4780:
chan_end

.layer_4781:
layer_setinstr F1_I_DINO_ROAR
.layer_4783:
layer_enablelegato
layer_portamento 0x85, 37, 255
.layer_4788:
layer_note1 PITCH_EF4, 0x1e, 100
.layer_478B:
layer_note1 PITCH_G3, 0x1e, 100
layer_disablelegato
layer_enablelegato
layer_portamento 0x85, 34, 255
.layer_4794:
layer_note1 PITCH_BF4, 0x1e, 100
.layer_4797:
layer_note1 PITCH_BF3, 0x1e, 100
layer_disablelegato
layer_jumprel .layer_4783

.layer_479D:
layer_setinstr F1_I_GORON_YAWN
layer_portamento 0x85, 35, 255
layer_note1 PITCH_DF4, 0xe8, 100
layer_end

.enemy_boss_morpha_water_spin:
chan_setinstr F1_I_WATER_BUBBLES
chan_setlayer 0, .layer_47AE
chan_end

.layer_47AE:
layer_enablelegato
layer_portamento 0x85, 25, 128
.layer_47B3:
layer_note1 PITCH_EF5, 0xc, 100
layer_note1 PITCH_BF2, 0xc, 100
layer_jumprel .layer_47B3

.enemy_boss_morpha_water_move:
chan_setinstr F1_I_WATER_BUBBLES
chan_setenvelope .envelope_699C
chan_setlayer 0, .layer_47C9
chan_setlayer 1, .layer_47CB
chan_sethilogain 20
chan_end

.layer_47C9:
layer_delay 0x8

.layer_47CB:
layer_portamento 0x81, 31, 255
layer_note1 PITCH_B2, 0x60, 100
layer_end

.enemy_deadhand_bite:
chan_setlayer 0, .layer_47DC
chan_setlayer 1, .layer_47E2
chan_sethilogain 22
chan_end

.layer_47DC:
layer_setinstr F1_I_PHANTOM_GROWL
layer_note1 PITCH_C4, 0x56, 100
layer_end

.layer_47E2:
layer_setinstr F1_I_EGG_CRACK
layer_portamento 0x81, 11, 200
layer_note1 PITCH_C2, 0x29, 100
layer_end

.enemy_deadhand_move:
chan_setlayer 0, .layer_47F2
chan_sethilogain 22
chan_end

.layer_47F2:
layer_setinstr F1_I_EGG_CRACK
layer_portamento 0x81, 9, 200
layer_note1 PITCH_BF1, 0x29, 100
layer_end

.enemy_goron_wake:
chan_setlayer 0, .layer_4800
chan_end

.layer_4800:
layer_setinstr F1_I_GORON
layer_note1 PITCH_GF3, 0x20, 100
layer_end

.enemy_goron_sit:
chan_setlayer 0, .layer_480A
chan_end

.layer_480A:
layer_setinstr F1_I_GORON
layer_transpose 48
layer_note1 PITCH_BF3, 0x84, 100
layer_end

.enemy_deadhand_grabbed:
chan_sethilogain 16
chan_setlayer 0, .layer_481C
chan_setlayer 1, .layer_5095
chan_end

.layer_481C:
layer_setinstr F1_I_PHANTOM_GROWL
layer_portamento 0x81, 35, 255
layer_note1 PITCH_E3, 0x30, 100
layer_end

.enemy_boss_ganondorf_struck:
chan_setlayer 0, .layer_4829
// @bug missing chan_end. This bug turns out to be harmless in practice.

.layer_4829:
layer_setinstr INSTR_SFX
layer_note1 F1_E_ENEMY_HURT, 0x0, 100
layer_end

.chan_unused_482F:
chan_setlayer 0, .layer_4833
chan_end

.layer_4833:
layer_setinstr INSTR_SFX
layer_note1 F1_E_GANONDORF_LAUGH_0, 0x0, 100
layer_end

.enemy_big_octo_paralyzed:
chan_setlayer 0, .layer_4846
chan_setlayer 1, .layer_4850
chan_sethilogain 16
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_4846:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x81, 15, 255
layer_note1 PITCH_AF1, 0x54, 100
layer_end

.layer_4850:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 24, 100
layer_note1 PITCH_D3, 0x1e, 100
layer_note1 PITCH_A2, 0x2e, 100
layer_end

.enemy_big_octo_walk:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_4870
.chan_4863:
chan_rand 4
chan_writeseq 96, .layer_4870
chan_setval 18
chan_call .delay_varyingvol
chan_jumprel .chan_4863

.layer_4870:
layer_note1 PITCH_F3, 0x12, 100
layer_jumprel .layer_4870

.enemy_big_octo_grunt:
chan_setinstr F1_I_GORON
chan_setlayer 0, .layer_487F
chan_sethilogain 18
chan_setdecayrelease 249
chan_end

.layer_487F:
layer_note1 PITCH_DF3, 0x8, 100
layer_note1 PITCH_BF2, 0x1e, 100
layer_end

.enemy_big_octo_hurt:
chan_setlayer 0, .layer_4896
chan_setlayer 1, .layer_48A4
chan_setlayer 2, .layer_4829
chan_sethilogain 16
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_4896:
layer_setinstr F1_I_LIZALFOS
layer_enablelegato
layer_portamento 0x85, 25, 255
layer_note1 PITCH_DF3, 0x18, 100
layer_note1 PITCH_GF1, 0x1c, 100
layer_end

.layer_48A4:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 30, 100
layer_note1 PITCH_AF3, 0xc, 100
layer_note1 PITCH_EF3, 0x12, 100
layer_end

.enemy_big_octo_stop:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_48B8
chan_end

.layer_48B8:
layer_portamento 0x81, 47, 100
layer_note1 PITCH_DF4, 0x12, 100
layer_portamento 0x81, 47, 100
layer_note1 PITCH_DF4, 0x12, 100
layer_portamento 0x81, 47, 100
layer_note1 PITCH_DF4, 0x12, 100
layer_portamento 0x81, 47, 100
layer_note1 PITCH_DF4, 0x50, 100
layer_end

.enemy_big_octo_die:
chan_setlayer 0, .layer_48E5
chan_setlayer 1, .layer_48A4
chan_setlayer 2, .layer_4829
chan_sethilogain 16
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_48E5:
layer_setinstr F1_I_LIZALFOS
layer_portamento 0x85, 27, 255
layer_note1 PITCH_AF3, 0x18, 100
layer_note1 PITCH_AF1, 0x66, 100
layer_end

.enemy_big_octo_die2:
chan_setlayer 0, .layer_48FC
chan_sethilogain 18
chan_setvibratorate 100
chan_setvibratoextent 100
chan_end

.layer_48FC:
layer_setinstr F1_I_PHANTOM_WAIL
layer_portamento 0x85, 42, 100
layer_note1 PITCH_EF3, 0x70, 100
layer_end

.enemy_boss_gohma_paralyzed:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_4913
chan_setlayer 1, .layer_4920
chan_setvibratorate 84
chan_setvibratoextent 100
chan_end

.layer_4913:
layer_note1 PITCH_AF3, 0x110, 100
layer_setenvelope .envelope_68AC, 240
layer_delay 0x88
layer_jumprel .layer_4913

.layer_4920:
layer_setenvelope .envelope_68AC, 240
layer_delay 0xcc
layer_jumprel .layer_4913

.enemy_final_hit:
chan_setinstr F1_I_ELECTRIC_ATTACK
chan_setlayer 0, .layer_4931
chan_sethilogain 20
chan_end

.layer_4931:
layer_transpose 6
layer_portamento 0x81, 48, 54
layer_note1 PITCH_BF5, 0x2c, 100
layer_end

.enemy_boss_morpha_die_cry:
chan_setlayer 0, .layer_4959
chan_setlayer 1, .layer_4949
chan_setlayer 2, .layer_494B
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_4949:
layer_transpose 1

.layer_494B:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 39, 20
layer_note1 PITCH_E4, 0x10, 100
layer_note1 PITCH_B3, 0x56, 100
layer_end

.layer_4959:
layer_setinstr F1_I_DINO_ROAR
layer_portamento 0x85, 38, 255
layer_note1 PITCH_E4, 0x14, 80
layer_note1 PITCH_B2, 0x56, 80
layer_end

.enemy_shop_scrub_cry:
chan_setlayer 0, .layer_496A
chan_end

.layer_496A:
layer_setinstr F1_I_SCRUB_DEATH
layer_portamento 0x81, 43, 255
layer_note1 PITCH_EF5, 0x8, 80
layer_portamento 0x81, 52, 255
layer_note1 PITCH_AF4, 0x8, 80
layer_end

.enemy_skullwall_rotate:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_4984
chan_setlayer 1, .layer_498C
chan_end

.layer_4984:
layer_portamento 0x81, 31, 100
layer_note1 PITCH_C3, 0x32, 64
layer_end

.layer_498C:
layer_delay 0x5
layer_portamento 0x81, 33, 100
layer_note1 PITCH_D3, 0x32, 64
layer_end

.enemy_skullwall_dash:
chan_setinstr F1_I_GRASS_RUSTLE
chan_setlayer 0, .layer_499F
chan_setlayer 1, .layer_49A7
chan_end

.layer_499F:
layer_portamento 0x81, 27, 100
layer_note1 PITCH_E3, 0x32, 64
layer_end

.layer_49A7:
layer_delay 0x5
layer_portamento 0x81, 29, 100
layer_note1 PITCH_GF3, 0x32, 64
layer_end

.enemy_boss_twinrova_appear:
chan_setinstr F1_I_GANONDORF_CHARGE
chan_setenvelope .envelope_699C
chan_setlayer 0, .layer_49C0
chan_sethilogain 18
chan_setvibratorate 128
chan_setvibratoextent 52
chan_end

.layer_49C0:
layer_portamento 0x81, 31, 255
layer_note1 PITCH_B2, 0x64, 100
layer_end

.enemy_boss_twinrova_transform:
chan_setlayer 0, .layer_49D5
chan_setlayer 1, .layer_49DB
chan_sethilogain 20
chan_setvibratorate 240
chan_setvibratoextent 240
chan_end

.layer_49D5:
layer_setinstr F1_I_GUNSHOT
layer_note1 PITCH_D3, 0x64, 100
layer_end

.layer_49DB:
layer_setinstr F1_I_DINO_INHALE
layer_portamento 0x81, 7, 255
layer_note1 PITCH_BF3, 0xe6, 84
layer_end

.enemy_boss_twinrova_fire_charge:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_49F0
chan_setvibratorate 127
chan_setvibratoextent 84
chan_end

.layer_49F0:
layer_enablelegato
layer_portamento 0x85, 15, 120
layer_note1 PITCH_C4, 0xc8, 100
.layer_49F9:
layer_note1 PITCH_C4, 30000, 100
layer_jumprel .layer_49F9

.enemy_boss_twinrova_fire_hit:
chan_setlayer 0, .layer_4A09
chan_setlayer 1, .layer_4A0B
chan_setlayer 2, .layer_4A17
chan_end

.layer_4A09:
layer_transpose -12

.layer_4A0B:
layer_setinstr 2
layer_setenvelope .envelope_6A7C, 200
.layer_4A11:
layer_note1 PITCH_G3, 30000, 100
layer_jumprel .layer_4A11

.layer_4A17:
layer_setinstr F1_I_THUNDERBURST
layer_setenvelope .envelope_6A5C, 200
layer_note1 PITCH_GF2, 0x180, 100
layer_end

.enemy_boss_twinrova_ice_beam:
chan_setinstr F1_I_WIND
chan_setlayer 0, .layer_4A28
chan_end

.layer_4A28:
layer_enablelegato
layer_portamento 0x85, 10, 102
layer_transpose 10
layer_note1 PITCH_F5, 0x28, 100
layer_transpose 0
.layer_4A34:
layer_note1 PITCH_F5, 0x64, 100
layer_jumprel .layer_4A34

.enemy_boss_twinrova_fire_reflected:
chan_setlayer 0, .layer_4A44
chan_setlayer 1, .layer_4B32
chan_setvibratorate 128
chan_setvibratoextent 96
chan_end

.layer_4A44:
layer_setinstr F1_I_WIND
layer_transpose 12
layer_enablelegato
layer_jumprel .layer_4A34
layer_end

.enemy_boss_twinrova_ice_charge:
chan_setinstr F1_I_WIND
chan_setlayer 0, .layer_4A56
chan_setvibratorate 127
chan_setvibratoextent 84
chan_end

.layer_4A56:
layer_enablelegato
layer_portamento 0x85, 35, 120
layer_note1 PITCH_AF5, 0xc8, 100
.layer_4A5F:
layer_note1 PITCH_AF5, 30000, 100
layer_jumprel .layer_4A5F

.enemy_ganondorf_charge_major:
chan_setinstr F1_I_WIND
chan_setlayer 0, .layer_4A94
chan_setlayer 1, .layer_4A96
chan_setlayer 2, .layer_4A9E
chan_setvibratorate 175
chan_setvibratoextent 196
chan_setval 36
chan_iowriteval 6
chan_setval 191
chan_call .delay_varyingvol
.chan_4A7C:
chan_ioreadval 6
chan_writeseq 0, .layer_4AAA+1
chan_writeseq 0, .layer_4AAD+1
chan_subtract 1
chan_iowriteval 6
chan_subtract 4
chan_beqzrel .chan_4A93
chan_setval 8
chan_call .delay_varyingvol
chan_jumprel .chan_4A7C
.chan_4A93:
chan_end

.layer_4A94:
layer_setinstr F1_I_DINO_INHALE

.layer_4A96:
layer_setenvelope .envelope_68B4, 249
layer_transpose -4
layer_jumprel .layer_4A56

.layer_4A9E:
layer_setinstr F1_I_DODONGO_ROAR
layer_delay 0x120
layer_loop 10
layer_enablelegato
layer_portamento 0x85, 27, 255
.layer_4AAA:
layer_note1 PITCH_F3, 0x1e, 100
.layer_4AAD:
layer_note1 PITCH_A2, 0x1e, 100
layer_disablelegato
layer_loopend
layer_end

.enemy_boss_twinrova_cast:
chan_setinstr 2
chan_setlayer 0, .layer_4ABF
chan_sethilogain 20
chan_setvibratorate 144
chan_setvibratoextent 240
chan_end

.layer_4ABF:
layer_note1 PITCH_AF2, 0x30, 100
layer_end

.enemy_darunia_chest_pound:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_4AC9
chan_end

.layer_4AC9:
layer_setenvelope .envelope_68DC, 250
.layer_4ACD:
layer_portamento 0x81, 26, 64
layer_note1 PITCH_E2, 0xc, 100
layer_jumprel .layer_4ACD

.enemy_darunia_head_pat:
chan_setinstr F1_I_SMASH
chan_setenvelope .envelope_692C
chan_setlayer 0, .layer_4ADF
chan_end

.layer_4ADF:
layer_portamento 0x81, 32, 130
layer_note1 PITCH_GF2, 0x1e, 100
layer_end

.enemy_boss_twinrova_hurt_cry_old:
chan_setlayer 0, .layer_4261
chan_setlayer 1, .layer_4AEE
chan_end

.layer_4AEE:
layer_setinstr INSTR_SFX
layer_note1 F1_E_WITCH_HURT, 0x0, 100
layer_end

.enemy_boss_twinrova_hit_beam_young:
chan_setlayer 0, .layer_4261
chan_setlayer 1, .layer_4AFB
chan_end

.layer_4AFB:
layer_setinstr INSTR_SFX
layer_note1 F1_E_WITCH_SHOCK, 0x0, 100
layer_end

.enemy_boss_twinrova_die_young:
chan_setlayer 0, .layer_4B0B
chan_setlayer 1, .layer_4B12
chan_setlayer 2, .layer_4829
chan_end

.layer_4B0B:
layer_setinstr F1_I_THUNDERBURST
layer_note1 PITCH_AF4, 0x110, 100
layer_end

.layer_4B12:
layer_setinstr INSTR_SFX
layer_note1 F1_E_TWINROVA_SCREAM, 0x0, 100
layer_end

.enemy_boss_twinrova_spirit_fly:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_4B22
chan_setvibratorate 112
chan_setvibratoextent 128
chan_end

.layer_4B22:
layer_setenvelope .envelope_69DC, 240
layer_enablelegato
layer_portamento 0x85, 3, 255
layer_note1 PITCH_F2, 0x1a, 100
layer_note1 PITCH_A0, 0x20, 100
layer_end

.layer_4B32:
layer_setinstr INSTR_WV_8PULSE
layer_setenvelope .envelope_6A7C, 249
.layer_4B38:
layer_note1 PITCH_GF3, 30000, 100
layer_jumprel .layer_4B38

.enemy_boss_twinrova_charge:
chan_setlayer 0, .layer_521B
chan_setlayer 1, .layer_5219
chan_setvibratorate 96
chan_setvibratoextent 240
chan_end

.enemy_knuckle_walk:
chan_setlayer 0, .layer_4B59
chan_setlayer 1, .layer_4B50
chan_end

.layer_4B50:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_BF1, 0x8, 64
layer_note1 PITCH_G2, 0x14, 64
layer_end

.layer_4B59:
layer_setinstr F1_I_GUNSHOT
layer_setenvelope .envelope_68DC, 249
layer_portamento 0x81, 26, 96
layer_note1 PITCH_DF2, 0x1e, 100
layer_end

.enemy_knuckle_attack:
chan_setlayer 0, .layer_4B71
chan_setlayer 1, .layer_4B7B
chan_setlayer 2, .layer_4B87
chan_end

.layer_4B71:
layer_setinstr F1_I_GERUDO_ATTACK
layer_portamento 0x81, 27, 255
layer_note1 PITCH_A2, 0x78, 100
layer_end

.layer_4B7B:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_BF1, 0x4, 64
layer_note1 PITCH_G2, 0x6, 64
layer_note1 PITCH_DF3, 0x14, 64
layer_end

.layer_4B87:
layer_setinstr INSTR_SFX
layer_note1 F1_E_KNUCKLE_ATTACK, 0x0, 100
layer_end

.enemy_bubble_die:
chan_setlayer 0, .layer_4B9B
chan_setlayer 2, .layer_4BA9
.chan_4B93:
chan_setlayer 1, .layer_4829
chan_setvibratorate 128
chan_setvibratoextent 48
chan_end

.layer_4B9B:
layer_setinstr F1_I_PHANTOM_MOAN
layer_enablelegato
layer_portamento 0x85, 46, 200
layer_note1 PITCH_C5, 0x20, 100
layer_note1 PITCH_E4, 0x6c, 100
layer_end

.layer_4BA9:
layer_setinstr F1_I_POT_BREAK
layer_note1 PITCH_G3, 0x5, 100
layer_note1 PITCH_G3, 0x5, 100
layer_end

.enemy_bubble_hurt:
chan_setlayer 0, .layer_4BB7
chan_jumprel .chan_4B93

.layer_4BB7:
layer_transpose 5
layer_jumprel .layer_4B9B
layer_end

.enemy_bubble_attack:
chan_setlayer 0, .layer_4BC0
chan_end

.layer_4BC0:
layer_setinstr F1_I_STALFOS_ATTACK
layer_enablelegato
layer_portamento 0x85, 30, 30
layer_note1 PITCH_AF4, 0x8, 100
layer_note1 PITCH_GF4, 0x12, 100
layer_end

.enemy_poe_sister_die:
chan_setlayer 3, .layer_4829
.chan_4BD1:
chan_setlayer 0, .layer_4BDB
chan_setlayer 1, .layer_4BDD
chan_setlayer 2, .layer_4BF3
chan_end

.layer_4BDB:
layer_delay 0x8

.layer_4BDD:
layer_setinstr F1_I_PHANTOM_LAUGH_1
layer_transpose 12
layer_portamento 0x81, 48, 100
layer_note1 PITCH_E5, 0x1e, 100
layer_portamento 0x85, 51, 100
layer_note1 PITCH_F5, 0x14, 100
layer_note1 PITCH_B4, 0x1e, 100
layer_end

.layer_4BF3:
layer_setinstr F1_I_PHANTOM_GROWL
layer_enablelegato
layer_transpose 48
layer_portamento 0x85, 47, 200
layer_note1 PITCH_D5, 0x20, 100
layer_note1 PITCH_B2, 0x64, 100
layer_end

.enemy_big_poe_get_soul:
chan_jumprel .chan_4BD1

.enemy_knuckle_clank:
chan_setlayer 0, .layer_4B7B
chan_end

.enemy_bari_spin:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_4C0F
chan_end

.layer_4C0F:
layer_enablelegato
layer_portamento 0x85, 19, 200
layer_note1 PITCH_EF2, 0x18, 100
layer_note1 PITCH_B2, 0x3c, 100
layer_end

.enemy_larvae_paralyzed:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_4C25
chan_setvibratorate 196
chan_setvibratoextent 196
chan_end

.layer_4C25:
layer_portamento 0x81, 62, 255
layer_note1 PITCH_EF3, 0x40, 100
layer_end

.enemy_bari_die:
chan_setlayer 0, .layer_4C34
chan_setlayer 1, .layer_4829
chan_end

.layer_4C34:
layer_setinstr F1_I_GUAY_HURT
.layer_4C36:
layer_portamento 0x81, 32, 255
layer_note1 PITCH_C4, 0xa, 100
layer_portamento 0x81, 34, 255
layer_note1 PITCH_D4, 0xa, 100
layer_portamento 0x81, 36, 255
layer_note1 PITCH_E4, 0xa, 100
layer_portamento 0x81, 45, 255
layer_note1 PITCH_A3, 0xe, 100
layer_end

.enemy_bari_split:
chan_setlayer 0, .layer_4C57
chan_end

.layer_4C57:
layer_setinstr F1_I_GULP_SPEAR
layer_transpose 4
layer_jumprel .layer_4C36

.enemy_floormaster_attack:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_4C6A
chan_setenvelope .envelope_699C
chan_setvibratorate 112
chan_setvibratoextent 96
chan_end

.layer_4C6A:
layer_note1 PITCH_E2, 0x64, 100
layer_end

.enemy_floormaster_mini_walk:
chan_setinstr F1_I_EGG_CRACK
chan_setlayer 0, .layer_4C74
chan_end

.layer_4C74:
layer_portamento 0x81, 21, 128
layer_note1 PITCH_A2, 0x8, 100
layer_end

.enemy_floormaster_mini_die:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_4C89
chan_setlayer 1, .layer_4829
chan_setvibratorate 132
chan_setvibratoextent 70
chan_end

.layer_4C89:
layer_enablelegato
layer_portamento 0x85, 56, 128
layer_note1 PITCH_BF5, 0x14, 100
layer_note1 PITCH_D5, 0x2c, 100
layer_end

.enemy_floormaster_mini_grow:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_4CA2
chan_setenvelope .envelope_69DC
chan_setvibratorate 62
chan_setvibratoextent 96
chan_end

.layer_4CA2:
layer_note1 PITCH_AF3, 0x3c, 80
layer_jumprel .layer_4CA2

.enemy_floormaster_grow_done:
chan_setlayer 0, .layer_4CAB
chan_end

.layer_4CAB:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_setenvelope .envelope_694C, 249
layer_enablelegato
layer_portamento 0x85, 7, 150
layer_note1 PITCH_DF1, 0xa, 100
layer_note1 PITCH_DF2, 0x16, 100
layer_end

.enemy_floormaster_split:
chan_setlayer 0, .layer_4CC1
chan_end

.layer_4CC1:
layer_transpose 12
layer_jumprel .layer_4CAB
layer_end

.enemy_floormaster_mini_grab:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_4CD3
chan_setenvelope .envelope_69FC
chan_setvibratorate 80
chan_setvibratoextent 64
chan_end

.layer_4CD3:
layer_enablelegato
layer_portamento 0x85, 6, 255
layer_note1 PITCH_EF3, 0x2a, 69
layer_note1 PITCH_G2, 0x40, 69
layer_jumprel .layer_4CD3

.enemy_floormaster_mini_land:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_4CE6
chan_end

.layer_4CE6:
layer_enablelegato
layer_setenvelope .envelope_68FC, 255
layer_portamento 0x85, 25, 230
layer_note1 PITCH_EF3, 0x5, 80
layer_note1 PITCH_BF2, 0x5, 80
layer_disablelegato
layer_delay 0x5
layer_enablelegato
layer_setenvelope .envelope_68FC, 255
layer_portamento 0x85, 25, 220
layer_note1 PITCH_EF3, 0x5, 80
layer_note1 PITCH_BF2, 0xa, 80
layer_end

.enemy_cucco_flap:
chan_setinstr F1_I_OWL_FLAP
chan_setlayer 0, .layer_4D0E
chan_end

.layer_4D0E:
layer_portamento 0x81, 35, 200
layer_note1 PITCH_B3, 0x20, 100
layer_end

.enemy_ganondorf_magic_fire:
chan_setlayer 0, .layer_4D23
chan_setlayer 1, .layer_4A09
chan_setlayer 2, .layer_4A0B
chan_setlayer 3, .layer_4A17
chan_end

.layer_4D23:
layer_delay 0x7f
layer_end

.enemy_floormaster_slide:
chan_setinstr F1_I_SLIDE_BOOTS
chan_setlayer 0, .layer_4D2C
chan_end

.layer_4D2C:
layer_transpose 48
.layer_4D2E:
layer_note1 PITCH_C4, 30000, 100
layer_jumprel .layer_4D2E

.enemy_knuckle_armor_rebound2:
chan_setlayer 0, .layer_4D4D
chan_setlayer 1, .layer_4D3B
chan_end

.layer_4D3B:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_GF1, 0x40, 100
layer_note1 PITCH_GF1, 0x14, 100
layer_note1 PITCH_GF1, 0x10, 84
layer_note1 PITCH_GF1, 0xa, 68
layer_note1 PITCH_GF1, 0xa, 68
layer_end

.layer_4D4D:
layer_transpose -8
layer_delay 0x4
layer_jumprel .layer_4D3B

.enemy_knuckle_armor_rebound3:
chan_setlayer 0, .layer_4D3B
chan_end

.enemy_knuckle_armor_rebound1:
chan_setlayer 0, .layer_4D70
chan_setlayer 1, .layer_4D5E
chan_end

.layer_4D5E:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_GF1, 0x8, 100
layer_note1 PITCH_GF1, 0x40, 100
layer_note1 PITCH_GF1, 0x20, 100
layer_note1 PITCH_GF1, 0x30, 84
layer_note1 PITCH_GF1, 0x40, 68
layer_end

.layer_4D70:
layer_transpose -8
layer_jumprel .layer_4D5E

.enemy_knuckle_stagger:
chan_setlayer 0, .layer_4D87
chan_setlayer 1, .layer_4D7B
chan_end

.layer_4D7B:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_EF1, 0x6, 100
layer_note1 PITCH_GF1, 0xe, 100
layer_note1 PITCH_C2, 0x10, 100
layer_end

.layer_4D87:
layer_transpose -5
layer_jumprel .layer_4D7B

.enemy_knucle_armor_loss:
chan_setlayer 0, .layer_4D9C
chan_setlayer 1, .layer_4D92
chan_end

.layer_4D92:
layer_setinstr F1_I_POT_BREAK
layer_portamento 0x81, 8, 200
layer_note1 PITCH_BF1, 0x20, 100
layer_end

.layer_4D9C:
layer_setinstr F1_I_SLIDE_BOOTS
layer_delay 0xe
layer_note1 PITCH_EF1, 0x14, 64
layer_end

.enemy_knuckle_warcry:
chan_setlayer 0, .layer_4DAB
chan_setlayer 1, .layer_4DBB
chan_end

.layer_4DAB:
layer_setinstr F1_I_SLIDE_BOOTS
layer_setenvelope .envelope_695C, 249
layer_loop 5
layer_note1 PITCH_C2, 0xa, 100
layer_note1 PITCH_G1, 0x8, 100
layer_loopend
layer_end

.layer_4DBB:
layer_setinstr INSTR_SFX
layer_note1 F1_E_KNUCKLE_CHARGE, 0x0, 100
layer_end

.enemy_knuckle_snap:
chan_setlayer 0, .layer_4DC7
chan_sethilogain 32
chan_end

.layer_4DC7:
layer_setinstr INSTR_SFX
layer_note1 F1_E_SNAP, 0x0, 100
layer_end

.enemy_boss_barinade_pulse:
chan_setinstr F1_I_BOULDER
chan_setlayer 0, .layer_4DDA
chan_setlayer 1, .layer_4DDC
chan_setvibratorate 40
chan_setvibratoextent 96
chan_end

.layer_4DDA:
layer_transpose 6

.layer_4DDC:
layer_note1 PITCH_A4, 30000, 100
layer_jumprel .layer_4DDC

.enemy_boss_barinade_hurt:
chan_setlayer 0, .layer_4E03
chan_setlayer 1, .layer_4DF3
chan_setlayer 2, .layer_4DF5
chan_setlayer 3, .layer_4829
chan_setvibratorate 116
chan_setvibratoextent 210
chan_end

.layer_4DF3:
layer_transpose 12

.layer_4DF5:
layer_setinstr F1_I_DINO_ROAR
.layer_4DF7:
layer_portamento 0x85, 32, 255
layer_note1 PITCH_C4, 0x20, 80
layer_note1 PITCH_B2, 0x90, 80
layer_end

.layer_4E03:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x81, 37, 100
layer_note1 PITCH_GF2, 0xb0, 100
layer_end

.enemy_tentacle_die:
chan_setlayer 0, .layer_4E1F
chan_setlayer 1, .layer_4DF5
chan_setlayer 2, .layer_4E77
chan_setlayer 3, .layer_4829
chan_setvibratorate 80
chan_setvibratoextent 48
chan_end

.layer_4E1F:
layer_transpose 4
layer_jumprel .layer_4E03

.enemy_boss_barinade_weak_hurt:
chan_setlayer 0, .layer_4E3A
chan_setlayer 1, .layer_4E34
chan_setlayer 2, .layer_4E36
chan_setlayer 3, .layer_4829
chan_setvibratorate 164
chan_setvibratoextent 162
chan_end

.layer_4E34:
layer_transpose 4

.layer_4E36:
layer_setinstr F1_I_DODONGO_ROAR
layer_jumprel .layer_4DF7

.layer_4E3A:
layer_transpose 2
layer_jumprel .layer_4E03

.enemy_boss_barinade_die:
chan_setlayer 0, .layer_4E47
chan_setlayer 1, .layer_4E45
chan_end

.layer_4E45:
layer_transpose 6

.layer_4E47:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_setenvelope .envelope_694C, 249
layer_enablelegato
layer_portamento 0x85, 19, 150
layer_note1 PITCH_C1, 0xa, 100
layer_note1 PITCH_B2, 0x14, 100
layer_end

.enemy_boss_twinrova_hurt:
chan_setlayer 0, .layer_4E75
chan_setlayer 1, .layer_4E77
chan_setlayer 2, .layer_4E66
chan_setlayer 3, .layer_4E68
chan_end

.layer_4E66:
layer_transpose 2

.layer_4E68:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_portamento 0x85, 34, 255
layer_note1 PITCH_F4, 0x14, 100
layer_note1 PITCH_B2, 0x7f, 100
layer_end

.layer_4E75:
layer_transpose -2

.layer_4E77:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 39, 64
layer_note1 PITCH_F4, 0x12, 100
layer_note1 PITCH_A3, 0xa8, 100
layer_end

.enemy_boss_barinade_tentacle_break:
chan_setlayer 0, .layer_4E66
chan_setlayer 1, .layer_4E68
chan_end

.enemy_boss_barinade_bari_attach:
chan_setlayer 0, .layer_4E94
chan_setlayer 1, .layer_4E9E
chan_end

.layer_4E94:
layer_setinstr F1_I_BABA_LUNGE
layer_portamento 0x81, 35, 50
layer_note1 PITCH_AF2, 0x30, 100
layer_end

.layer_4E9E:
layer_setinstr F1_I_GANONDORF_ATTACK_0
layer_portamento 0x81, 39, 50
layer_note1 PITCH_DF3, 0x40, 100
layer_end

.enemy_boss_barinade_beam:
chan_setinstr F1_I_THUNDERBURST
chan_setlayer 0, .layer_4EB7
chan_setlayer 1, .layer_4EB5
chan_setvibratorate 196
chan_setvibratoextent 48
chan_end

.layer_4EB5:
layer_transpose 8

.layer_4EB7:
layer_note1 PITCH_A3, 0x1a2, 100
layer_end

.enemy_deadhand_grab:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_4EC6
chan_setvibratorate 128
chan_setvibratoextent 160
chan_end

.layer_4EC6:
layer_portamento 0x81, 22, 255
layer_note1 PITCH_DF2, 0x7f, 100
layer_end

.enemy_tentacle_wind_up:
chan_setinstr F1_I_GERUDO_ATTACK
chan_setlayer 0, .layer_4ED8
chan_setvibratorate 128
chan_setvibratoextent 160
chan_end

.layer_4ED8:
layer_portamento 0x81, 16, 255
layer_note1 PITCH_G2, 0x7f, 100
layer_end

.enemy_shabom_pop:
chan_setlayer 0, .layer_4EF4
chan_setlayer 1, .layer_4EEA
chan_setlayer 2, .layer_4EF9
chan_end

.layer_4EEA:
layer_setinstr F1_I_GUNSHOT
layer_portamento 0x81, 54, 100
layer_note1 PITCH_B5, 0x60, 100
layer_end

.layer_4EF4:
layer_delay 0x2
layer_jumprel .layer_4EEA
layer_end

.layer_4EF9:
layer_setinstr F1_I_STEP_WATER
layer_portamento 0x81, 27, 255
layer_note1 PITCH_F3, 0x14, 100
layer_end

.enemy_shabom_bounce:
chan_setinstr F1_I_WATER_BUBBLES
chan_setlayer 0, .layer_4F0C
chan_setenvelope .envelope_692C
chan_end

.layer_4F0C:
layer_portamento 0x85, 39, 100
layer_note1 PITCH_A3, 0x16, 100
layer_note1 PITCH_B4, 0x16, 100
layer_end

.enemy_stinger_submerge:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_4F20
chan_setenvelope .envelope_68CC
chan_end

.layer_4F20:
layer_portamento 0x81, 27, 100
layer_note1 PITCH_F3, 0x34, 100
layer_end

.enemy_stinger_glide:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_4F32
chan_setvibratorate 80
chan_setvibratoextent 96
chan_end

.layer_4F32:
layer_setenvelope .envelope_6A2C, 230
.layer_4F36:
layer_note1 PITCH_E2, 0xd0, 80
layer_jumprel .layer_4F36

.enemy_stinger_attack:
chan_setlayer 0, .layer_4F44
chan_setvibratorate 240
chan_setvibratoextent 160
chan_end

.layer_4F44:
layer_setinstr F1_I_GUAY_HURT
layer_portamento 0x81, 52, 255
layer_note1 PITCH_GF5, 0x40, 100
layer_end

.enemy_stinger_cry:
chan_setlayer 0, .layer_4F55
chan_setlayer 1, .layer_4F57
chan_end

.layer_4F55:
layer_delay 0x6

.layer_4F57:
layer_setinstr F1_I_GUAY_HURT
layer_note1 PITCH_GF5, 0x64, 100
layer_end

.enemy_boss_bongo_drum_low:
chan_setinstr F1_I_BONGO_BONGO
chan_setlayer 0, .layer_4F6A
chan_setlayer 1, .layer_4F68
chan_sethilogain 24
chan_end

.layer_4F68:
layer_transpose 2

.layer_4F6A:
layer_note1 PITCH_C4, 0x40, 100
layer_end

.enemy_boss_bongo_drum_high:
chan_setinstr F1_I_BONGO_BONGO
chan_setlayer 0, .layer_4F7B
chan_setlayer 1, .layer_4F79
chan_sethilogain 24
chan_end

.layer_4F79:
layer_transpose 2

.layer_4F7B:
layer_note1 PITCH_F4, 0x40, 100
layer_end

.enemy_owl_fly:
chan_setinstr F1_I_OWL_FLAP
chan_setlayer 0, .layer_4F8A
chan_setlayer 1, .layer_4F88
chan_end

.layer_4F88:
layer_transpose 2

.layer_4F8A:
layer_portamento 0x81, 23, 200
layer_note1 PITCH_B2, 0x2c, 100
layer_end

.enemy_peahat_fly:
chan_setinstr F1_I_SWOOSH
chan_setlayer 0, .layer_4F98
chan_end

.layer_4F98:
layer_note1 PITCH_E5, 0x6, 100
layer_note1 PITCH_GF5, 0x6, 100
layer_note1 PITCH_AF5, 0x6, 100
layer_note1 PITCH_A5, 0x6, 100
layer_note1 PITCH_AF5, 0x6, 100
layer_note1 PITCH_GF5, 0x6, 100
layer_note1 PITCH_E5, 0x6, 100
layer_jumprel .layer_4F98

.enemy_peahat_land:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_361B
chan_end

.enemy_peahat_rise:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_4FBB
chan_end

.layer_4FBB:
layer_portamento 0x81, 15, 104
layer_note1 PITCH_B3, 0x40, 100
layer_end

.enemy_peahat_hurt:
chan_setlayer 0, .layer_4FDE
chan_setlayer 1, .layer_4FD1
chan_setlayer 2, .layer_4829
chan_setvibratorate 112
chan_setvibratoextent 160
chan_end

.layer_4FD1:
layer_setinstr F1_I_DINO_ROAR
layer_portamento 0x85, 40, 255
layer_note1 PITCH_AF4, 0x20, 80
layer_note1 PITCH_G3, 0x40, 80
layer_end

.layer_4FDE:
layer_setinstr F1_I_MONSTER_ROAR
layer_portamento 0x81, 41, 100
layer_note1 PITCH_EF3, 0x60, 100
layer_end

.enemy_boss_twinrova_fly:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_4FF2
chan_setvibratorate 96
chan_setvibratoextent 128
chan_end

.layer_4FF2:
layer_setenvelope .envelope_6A2C, 230
.layer_4FF6:
layer_note1 PITCH_GF1, 0x70, 100
layer_jumprel .layer_4FF6

.enemy_boss_twinrova_hover:
chan_setlayer 0, .layer_5008
chan_setlayer 1, .layer_5006
chan_setvibratorate 16
chan_setvibratoextent 128
chan_end

.layer_5006:
layer_transpose 2

.layer_5008:
layer_setinstr F1_I_DODONGO_ROAR
layer_setenvelope .envelope_6A2C, 230
.layer_500E:
layer_note1 PITCH_C1, 0x70, 100
layer_jumprel .layer_500E

.enemy_tektite_jump_water:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_5019
chan_end

.layer_5019:
layer_portamento 0x81, 35, 100
layer_note1 PITCH_DF5, 0x38, 80
layer_end

.enemy_tektite_land_water2:
chan_setinstr F1_I_WATER_SPLASH_L
chan_setlayer 0, .layer_5027
chan_end

.layer_5027:
layer_portamento 0x81, 49, 100
layer_note1 PITCH_EF4, 0x38, 80
layer_end

.enemy_tektite_turn_water:
chan_setinstr F1_I_STEP_WATER
chan_setlayer 0, .layer_5035
chan_end

.layer_5035:
layer_portamento 0x81, 16, 100
layer_note1 PITCH_E2, 0x30, 68
layer_end

.enemy_blob_wave:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_5047
chan_setvibratorate 112
chan_setvibratoextent 240
chan_end

.layer_5047:
layer_transpose -19
layer_enablelegato
layer_portamento 0x85, 0, 255
layer_note1 PITCH_A2, 0x20, 100
layer_note1 PITCH_A0, 0x20, 100
layer_end

.enemy_boss_bongo_clap:
chan_setlayer 0, .layer_505C
chan_setlayer 1, .layer_505E
chan_end

.layer_505C:
layer_transpose -6

.layer_505E:
layer_setinstr F1_I_GUNSHOT
layer_note1 PITCH_D5, 0x30, 100
layer_end

.enemy_boss_bongo_hand_wave:
chan_setinstr F1_I_THUNDERBURST
chan_setlayer 0, .layer_506E
chan_setvibratorate 128
chan_setvibratoextent 224
chan_end

.layer_506E:
layer_note1 PITCH_F3, 0x35, 100
layer_end

.enemy_boss_bongo_hand_attack:
chan_setinstr F1_I_DODONGO_ROAR
chan_setlayer 0, .layer_5083
chan_setlayer 1, .layer_5081
chan_setdecayrelease 220
chan_setvibratorate 112
chan_setvibratoextent 96
chan_end

.layer_5081:
layer_transpose 6

.layer_5083:
layer_note1 PITCH_E2, 0x90, 100
layer_jumprel .layer_5083

.enemy_wallmaster_grab:
chan_setlayer 0, .layer_5095
chan_setlayer 1, .layer_5093
chan_setlayer 2, .layer_50A3
chan_end

.layer_5093:
layer_transpose 2

.layer_5095:
layer_setinstr F1_I_SMASH
layer_setenvelope .envelope_696C, 250
layer_portamento 0x81, 19, 50
layer_note1 PITCH_E1, 0x20, 100
layer_end

.layer_50A3:
layer_setinstr F1_I_EGG_CRACK
layer_setenvelope .envelope_696C, 250
layer_portamento 0x81, 15, 50
layer_note1 PITCH_A1, 0x20, 100
layer_end

.enemy_boss_bongo_hand_shake:
chan_setinstr F1_I_OWL_FLAP
chan_setlayer 0, .layer_50B7
chan_end

.layer_50B7:
layer_portamento 0x85, 21, 200
layer_note1 PITCH_D3, 0x13, 100
layer_note1 PITCH_GF2, 0x13, 100
layer_end

.enemy_boss_bongo_hurt:
chan_setlayer 0, .layer_50D3
chan_setlayer 1, .layer_4524
chan_setlayer 2, .layer_4532
chan_setlayer 3, .layer_4829
chan_setvibratorate 48
chan_setvibratoextent 48
chan_end

.layer_50D3:
layer_setinstr F1_I_SCRUB_DEATH
layer_enablelegato
layer_portamento 0x85, 4, 60
layer_note1 PITCH_D2, 0x32, 100
layer_note1 PITCH_AF1, 0x7f, 100
layer_end

.enemy_boss_bongo_hand_hurt:
chan_setlayer 0, .layer_50D3
chan_setvibratorate 48
chan_setvibratoextent 48
chan_end

.enemy_boss_bongo_vanish:
chan_setinstr F1_I_POE_DISAPPEAR
chan_setlayer 0, .layer_50F8
chan_setlayer 1, .layer_50F6
chan_setvibratorate 96
chan_setvibratoextent 80
chan_end

.layer_50F6:
layer_transpose 6

.layer_50F8:
layer_portamento 0x81, 27, 255
layer_note1 PITCH_C2, 0x118, 100
layer_end

.enemy_beamos_beam:
chan_setinstr INSTR_WV_BELL
chan_setlayer 0, .layer_510B
chan_setvibratorate 128
chan_setvibratoextent 116
chan_end

.layer_510B:
layer_note1 PITCH_F4, 30000, 64
layer_jumprel .layer_510B

.enemy_beamos_idle:
chan_setinstr F1_I_BABA_LUNGE
chan_setlayer 0, .layer_511B
chan_setvibratorate 208
chan_setvibratoextent 96
chan_end

.layer_511B:
layer_note1 PITCH_F1, 30000, 64
layer_jumprel .layer_511B

.enemy_beamos_ground_hit:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_5127
chan_end

.layer_5127:
layer_note1 PITCH_DF1, 30000, 100
layer_jumprel .layer_5127

.enemy_beamos_charging:
chan_setlayer 0, .layer_45DF
chan_setvibratorate 160
chan_setvibratoextent 160
chan_end

.enemy_tektite_flip:
chan_setinstr F1_I_WATER_BUBBLES
chan_setlayer 0, .layer_5142
chan_setlayer 1, .layer_5144
chan_setvibratorate 176
chan_setvibratoextent 160
chan_end

.layer_5142:
layer_transpose -5

.layer_5144:
layer_portamento 0x85, 39, 100
layer_note1 PITCH_E3, 0x10, 100
layer_note1 PITCH_DF5, 0x13, 100
layer_end

.enemy_torch_slug_crawl:
chan_setlayer 0, .layer_5160
chan_setlayer 1, .layer_5156
chan_end

.layer_5156:
layer_setinstr F1_I_EGG_CRACK
layer_portamento 0x81, 8, 255
layer_note1 PITCH_C2, 0x40, 100
layer_end

.layer_5160:
layer_delay 0x8
layer_jumprel .layer_5156

.enemy_torch_slug_target:
chan_setlayer 0, .layer_516C
chan_setvibratorate 64
chan_setvibratoextent 96
chan_end

.layer_516C:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_D4, 0x8, 100
layer_note1 PITCH_A3, 0x20, 100
layer_end

.enemy_torch_slug_die:
chan_setlayer 0, .layer_5188
chan_setlayer 1, .layer_418B
chan_setlayer 2, .layer_4829
chan_setvibratorate 64
chan_setvibratoextent 192
chan_end

.layer_5188:
layer_setinstr F1_I_DINO_ROAR
layer_enablelegato
layer_portamento 0x85, 25, 255
layer_note1 PITCH_GF3, 0x14, 80
layer_note1 PITCH_GF2, 0x60, 80
layer_end

.enemy_tile_fly:
chan_setinstr F1_I_SWOOSH
chan_setlayer 0, .layer_519C
chan_end

.layer_519C:
layer_loop 6
layer_note1 PITCH_C5, 0x9, 100
layer_note1 PITCH_D5, 0x9, 100
layer_note1 PITCH_E5, 0x9, 100
layer_loopend

.layer_51A8:
layer_setenvelope .envelope_697C, 255
.layer_51AC:
layer_note1 PITCH_GF5, 0x6, 100
layer_note1 PITCH_AF5, 0x6, 100
layer_note1 PITCH_BF5, 0x6, 100
layer_note1 PITCH_AF5, 0x6, 100
layer_jumprel .layer_51AC

.enemy_firedancer_kick:
chan_setinstr 2
chan_setlayer 0, .layer_51C0
chan_end

.layer_51C0:
layer_note1 PITCH_A2, 0x30, 100
layer_end

.enemy_firedancer_spin:
chan_setlayer 0, .layer_51CB
chan_setlayer 1, .layer_51D9
chan_end

.layer_51CB:
layer_setinstr F1_I_BOULDER
.layer_51CD:
layer_transpose 12
layer_setenvelope .envelope_6A7C, 224
.layer_51D3:
layer_note1 PITCH_C5, 30000, 100
layer_jumprel .layer_51D3

.layer_51D9:
layer_setinstr F1_I_GANONDORF_FLY
layer_jumprel .layer_51CD

.enemy_firehead_run:
chan_setinstr F1_I_SMASH
chan_setlayer 0, .layer_51E3
chan_end

.layer_51E3:
layer_portamento 0x81, 20, 64
layer_note1 PITCH_BF1, 0xd, 100
layer_end

.enemy_firehead_hurt:
chan_setlayer 0, .layer_51F6
chan_setlayer 1, .layer_4829
chan_setvibratorate 64
chan_setvibratoextent 208
chan_end

.layer_51F6:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 47, 100
layer_note1 PITCH_F5, 0x14, 100
layer_note1 PITCH_AF4, 0x24, 100
layer_end

.enemy_firedancer_hurt:
chan_setlayer 0, .layer_4301
chan_end

.enemy_firedancer_laugh:
chan_setlayer 0, .layer_521B
chan_setlayer 1, .layer_5219
chan_setlayer 2, .layer_5226
chan_setlayer 3, .layer_5228
chan_setvibratorate 48
chan_setvibratoextent 32
chan_end

.layer_5219:
layer_transpose 2

.layer_521B:
layer_setinstr 2
layer_portamento 0x81, 21, 255
layer_note1 PITCH_B4, 0xe0, 100
layer_end

.layer_5226:
layer_transpose 1

.layer_5228:
layer_setinstr F1_I_PHANTOM_LAUGH_1
layer_note1 PITCH_F4, 0xe0, 100
layer_end

.enemy_moblin_club_shockwave:
chan_setinstr F1_I_DINO_INHALE
chan_setlayer 0, .layer_523A
chan_setlayer 1, .layer_523C
chan_setdecayrelease 224
chan_end

.layer_523A:
layer_transpose -6

.layer_523C:
layer_note1 PITCH_GF2, 30000, 100
layer_jumprel .layer_523C

.enemy_peahat_jr_fly:
chan_setinstr F1_I_SWOOSH
chan_setlayer 0, .layer_524B
chan_setenvelope .envelope_697C
chan_end

.layer_524B:
layer_note1 PITCH_GF5, 0x6, 80
layer_note1 PITCH_AF5, 0x6, 80
layer_note1 PITCH_BF5, 0x6, 80
layer_note1 PITCH_AF5, 0x6, 80
layer_jumprel .layer_524B

.enemy_boss_bongo_paralyze:
chan_setlayer 0, .layer_4524
chan_setlayer 1, .layer_4532
chan_setvibratorate 48
chan_setvibratoextent 48
chan_end

.enemy_boss_bongo_die:
chan_setlayer 0, .layer_5277
chan_setlayer 1, .layer_5275
chan_setlayer 2, .layer_5286
chan_setlayer 3, .layer_4829
chan_setvibratorate 70
chan_setvibratoextent 86
chan_end

.layer_5275:
layer_transpose 2

.layer_5277:
layer_setinstr F1_I_MONSTER_ROAR
.layer_5279:
layer_enablelegato
layer_portamento 0x85, 27, 127
layer_note1 PITCH_A3, 0x28, 100
layer_note1 PITCH_E3, 0xc8, 100
layer_end

.layer_5286:
layer_setinstr F1_I_THUNDER_HURT
layer_transpose 12
layer_jumprel .layer_5279

.enemy_boss_bongo_dissipate:
chan_setlayer 0, .layer_529A
chan_setlayer 1, .layer_52A6
chan_setlayer 2, .layer_52A8
chan_setvibratorate 20
chan_setvibratoextent 20
chan_end

.layer_529A:
layer_setinstr F1_I_DINO_INHALE
.layer_529C:
layer_setenvelope .envelope_6A7C, 200
.layer_52A0:
layer_note1 PITCH_C2, 30000, 100
layer_jumprel .layer_52A0

.layer_52A6:
layer_transpose -1

.layer_52A8:
layer_setinstr 2
layer_jumprel .layer_529C

.enemy_boss_bongo_charge:
chan_setlayer 0, .layer_52BC
chan_setlayer 1, .layer_52C4
chan_setlayer 2, .layer_52BA
chan_setvibratorate 96
chan_setvibratoextent 84
chan_end

.layer_52BA:
layer_transpose 4

.layer_52BC:
layer_setinstr F1_I_DINO_INHALE
.layer_52BE:
layer_note1 PITCH_A2, 30000, 100
layer_jumprel .layer_52BE

.layer_52C4:
layer_setinstr F1_I_BOULDER
.layer_52C6:
layer_note1 PITCH_A4, 30000, 80
layer_jumprel .layer_52C6

.enemy_boss_bongo_chant:
chan_setinstr F1_I_BONGO_BONGO
chan_setlayer 0, .layer_52D2
chan_end

.layer_52D2:
layer_transpose 48
layer_note1 PITCH_BF2, 0xe0, 100
layer_end

.enemy_like_like_die:
chan_setlayer 0, .layer_3FBA
chan_setlayer 1, .layer_5188
chan_setlayer 2, .layer_4829
chan_setvibratorate 64
chan_setvibratoextent 192
chan_end

.enemy_leever_die:
chan_setlayer 0, .layer_3F78
chan_setlayer 1, .layer_400C
chan_setlayer 2, .layer_4829
chan_setvibratorate 112
chan_setvibratoextent 48
chan_end

.enemy_gerudo_attack:
chan_setlayer 0, .layer_4081
chan_setlayer 1, .layer_52FC
chan_end

.layer_52FC:
layer_setinstr INSTR_SFX
layer_note1 F1_E_GERUDO_ATTACK, 0x0, 80
layer_end

.enemy_gerudo_hurt:
chan_setlayer 0, .layer_5309
chan_setlayer 1, .layer_4829
chan_end

.layer_5309:
layer_setinstr INSTR_SFX
layer_note1 F1_E_GERUDO_HURT, 0x0, 100
layer_end

.enemy_gerudo_defeat:
chan_setlayer 0, .layer_5316
chan_setlayer 1, .layer_4829
chan_end

.layer_5316:
layer_setinstr INSTR_SFX
layer_note1 F1_E_GERUDO_DEFEAT, 0x0, 100
layer_end

.enemy_wolfos_walk:
chan_setlayer 0, .layer_5320
chan_end

.layer_5320:
layer_setinstr F1_I_SMASH
layer_portamento 0x81, 44, 64
layer_note1 PITCH_GF3, 0x5, 72
layer_end

.enemy_anubis_die:
chan_setlayer 0, .layer_5335
chan_setlayer 1, .layer_533C
chan_setvibratorate 56
chan_setvibratoextent 50
chan_end

.layer_5335:
layer_setinstr 2
layer_note1 PITCH_C3, 0xc8, 100
layer_end

.layer_533C:
layer_setinstr F1_I_PHANTOM_WAIL
layer_enablelegato
layer_portamento 0x85, 32, 200
layer_note1 PITCH_D4, 0x10, 100
layer_note1 PITCH_EF3, 0x96, 100
layer_end

.enemy_anubis_fire_hit:
chan_setlayer 0, .layer_534F
chan_end

.layer_534F:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_enablelegato
layer_portamento 0x85, 30, 255
layer_note1 PITCH_B3, 0x20, 100
layer_note1 PITCH_E2, 0x50, 100
layer_end

.enemy_destroyed_light_arrow:
chan_setlayer 0, .layer_5365
chan_setvibratorate 208
chan_setvibratoextent 208
chan_end

.layer_5365:
layer_setinstr F1_I_DINO_INHALE
layer_enablelegato
layer_transpose 15
layer_portamento 0x85, 39, 239
layer_note1 PITCH_DF3, 0x18, 100
layer_note1 PITCH_B5, 0x38, 100
layer_end

.enemy_freezard_hurt:
chan_setlayer 0, .layer_3A9A
chan_setlayer 1, .layer_3962
chan_setlayer 2, .layer_4829
chan_end

.enemy_freezard_die:
chan_setlayer 0, .layer_3A47
chan_setlayer 1, .layer_3962
chan_setlayer 2, .layer_4829
chan_end

.enemy_deadhand_burrow:
chan_setlayer 0, .layer_538D
chan_end

.layer_538D:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_setenvelope .envelope_68B4, 220
layer_note1 PITCH_D4, 0x64, 100
layer_end

.enemy_deadhand_laugh:
chan_setinstr F1_I_PHANTOM_LAUGH_1
chan_setlayer 0, .layer_539F
chan_sethilogain 16
chan_end

.layer_539F:
layer_portamento 0x81, 35, 239
layer_note1 PITCH_AF2, 0xe0, 100
layer_end

.enemy_knuckle_armor_hurt:
chan_setlayer 0, .layer_53B3
chan_setlayer 1, .layer_4829
chan_setvibratorate 224
chan_setvibratoextent 96
chan_end

.layer_53B3:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_A2, 0x40, 100
layer_end

.enemy_knuckle_pillar_break:
chan_setlayer 0, .layer_53C0
chan_setlayer 1, .layer_53B3
chan_end

.layer_53C0:
layer_setinstr F1_I_EXPLOSION_LAVA
layer_note1 PITCH_AF3, 0x4, 100
layer_note1 PITCH_BF3, 0x4, 100
layer_note1 PITCH_DF4, 0x5, 100
layer_note1 PITCH_F4, 0x7, 100
layer_note1 PITCH_B3, 0x30, 100
layer_end

.enemy_knuckle_stump_break:
chan_setlayer 0, .layer_53C0
chan_end

.enemy_knuckle_axe_stuck:
chan_setlayer 0, .layer_364C
chan_setlayer 1, .layer_53B3
chan_end

.enemy_boss_ganon_attack:
chan_setlayer 0, .layer_4220
chan_setlayer 1, .layer_53E4
chan_end

.layer_53E4:
layer_setinstr F1_I_ELECTRIC_ATTACK
layer_note1 PITCH_B5, 0x5a, 70
layer_end

.enemy_pot_fly:
chan_setinstr F1_I_SWOOSH
chan_setlayer 0, .layer_51A8
chan_end

.enemy_ganondorf_vortex_charge:
chan_setlayer 0, .layer_5008
chan_setlayer 1, .layer_53FB
chan_setvibratorate 48
chan_setvibratoextent 240
chan_end

.layer_53FB:
layer_setinstr F1_I_DINO_INHALE
.layer_53FD:
layer_note1 PITCH_A2, 30000, 64
layer_jumprel .layer_53FD

.enemy_boss_vocals:
chan_setinstr INSTR_SFX
chan_ioreadval 4
chan_subtract 176
chan_writeseq 0, .layer_5417  // set semitone = sound id - 176
chan_readseq .addr_541C
chan_writeseq 0, .layer_5417+2
chan_setlayer 0, .layer_5417
chan_end

.layer_5417:
layer_note0 0, 0x0, 100, 0
layer_end

.addr_541C:
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100
.byte 100

.enemy_ganondorf_throw_orb:
chan_setlayer 0, .layer_4220
chan_setlayer 1, .layer_4214
chan_end

.enemy_ganondorf_hit_light:
chan_setlayer 0, .layer_434A
chan_setlayer 1, .layer_434C
chan_end

.enemy_shell_open:
chan_setlayer 0, .layer_5458
chan_setlayer 1, .layer_5460
chan_end

.layer_5458:
layer_setinstr F1_I_EGG_CRACK
layer_delay 0x8
layer_note1 PITCH_G2, 0x25, 100
layer_end

.layer_5460:
layer_setinstr F1_I_BABA_ATTACK
layer_note1 PITCH_DF3, 0x2d, 100
layer_end

.enemy_spike_trap_roll:
chan_setinstr F1_I_SLIDE_BOOTS
chan_setlayer 0, .layer_546C
chan_end

.layer_546C:
layer_note1 PITCH_EF2, 0xa, 50
layer_note1 PITCH_F2, 0xa, 50
layer_note1 PITCH_G2, 0xa, 50
layer_jumprel .layer_546C

.enemy_stalkid_walk:
chan_setlayer 0, .layer_547B
chan_end

.layer_547B:
layer_setinstr F1_I_EGG_CRACK
layer_note1 PITCH_DF3, 0xe, 70
layer_end

.enemy_stalkid_attack:
chan_setlayer 0, .layer_5488
chan_setlayer 1, .layer_4081
chan_end

.layer_5488:
layer_setinstr F1_I_PHANTOM_LAUGH_1
layer_transpose 14
layer_note1 PITCH_C5, 0x30, 100
layer_end

.enemy_boss_ganon_paralyze:
chan_setlayer 0, .layer_549E
chan_setlayer 1, .layer_54A0
chan_setlayer 2, .layer_54AE
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_549E:
layer_delay 0x14

.layer_54A0:
layer_setinstr F1_I_MONSTER_ROAR
.layer_54A2:
layer_enablelegato
layer_portamento 0x85, 28, 255
layer_note1 PITCH_F2, 0x30, 100
layer_note1 PITCH_EF2, 0x48, 100
layer_end

.layer_54AE:
layer_setinstr F1_I_DINO_ROAR
layer_transpose 4
layer_jumprel .layer_54A2

.enemy_boss_ganon_die:
chan_setlayer 0, .layer_54C5
chan_setlayer 1, .layer_54C7
chan_setlayer 2, .layer_54E9
chan_setlayer 3, .layer_54EB
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_54C5:
layer_delay 0xa

.layer_54C7:
layer_setinstr F1_I_MONSTER_ROAR
layer_loop 4
layer_portamento 0x81, 30, 107
layer_note1 PITCH_F4, 0x8c, 100
.layer_54D3:
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_G4, 0x30, 100
layer_note1 PITCH_AF3, 0x48, 100
layer_disablelegato
layer_loopend
layer_portamento 0x81, 35, 255
layer_note1 PITCH_BF2, 0xfa, 100
layer_end

.layer_54E9:
layer_delay 0xa

.layer_54EB:
layer_setinstr F1_I_DINO_ROAR
layer_loop 4
layer_portamento 0x81, 44, 107
layer_note1 PITCH_A4, 0x8c, 100
.layer_54F7:
layer_enablelegato
layer_portamento 0x85, 47, 255
layer_note1 PITCH_BF4, 0x32, 100
layer_note1 PITCH_D4, 0x48, 100
layer_disablelegato
layer_loopend
layer_portamento 0x81, 37, 255
layer_note1 PITCH_C3, 0xc8, 100
layer_end

.enemy_boss_ganon_penultimate_hit:
chan_setlayer 0, .layer_551B
chan_setlayer 1, .layer_551D
chan_setlayer 2, .layer_5523
chan_setvibratorate 20
chan_setvibratoextent 50
chan_end

.layer_551B:
layer_delay 0xd

.layer_551D:
layer_setinstr F1_I_MONSTER_ROAR
layer_loop 1
layer_jumprel .layer_54D3

.layer_5523:
layer_setinstr F1_I_DINO_ROAR
layer_loop 1
layer_jumprel .layer_54F7

.enemy_wolfos_spawn:
chan_setinstr F1_I_ANIMALS
chan_setlayer 0, .layer_552F
chan_end

.layer_552F:
layer_portamento 0x81, 42, 40
layer_note1 PITCH_G4, 0x7f, 100
layer_end

.enemy_wolfos_attack:
chan_setlayer 0, .layer_553E
chan_setlayer 1, .layer_4081
chan_end

.layer_553E:
layer_setinstr F1_I_ANIMALS
layer_portamento 0x81, 35, 72
layer_note1 PITCH_F4, 0x40, 100
layer_end

.enemy_wolfos_hurt:
chan_setinstr F1_I_ANIMALS
chan_setlayer 0, .layer_5551
chan_setlayer 1, .layer_4829
chan_end

.layer_5551:
layer_enablelegato
layer_portamento 0x85, 39, 192
layer_note1 PITCH_F4, 0x20, 100
layer_note1 PITCH_DF4, 0x20, 100
layer_end

.enemy_wolfos_die:
chan_setinstr F1_I_ANIMALS
chan_setlayer 0, .layer_5566
chan_setlayer 1, .layer_4829
chan_end

.layer_5566:
layer_enablelegato
layer_portamento 0x85, 39, 128
layer_note1 PITCH_B4, 0x1c, 100
layer_note1 PITCH_AF4, 0x60, 100
layer_end

.enemy_wolfos_howl:
chan_setinstr F1_I_ANIMALS
chan_setlayer 0, .layer_5578
chan_end

.layer_5578:
layer_note1 PITCH_D4, 0x70, 75
layer_end

.enemy_guay_hurt:
chan_setlayer 0, .layer_5583
chan_setlayer 1, .layer_4829
chan_end

.layer_5583:
layer_setinstr F1_I_GUAY_HURT
layer_enablelegato
layer_portamento 0x85, 34, 255
layer_note1 PITCH_C4, 0xa, 100
layer_note1 PITCH_A3, 0x1e, 100
layer_end

.enemy_guay_die:
chan_setlayer 0, .layer_5598
chan_setlayer 1, .layer_4829
chan_end

.layer_5598:
layer_setinstr F1_I_GUAY_HURT
layer_enablelegato
layer_portamento 0x85, 39, 255
layer_note1 PITCH_G3, 0xf, 100
layer_note1 PITCH_DF2, 0x60, 100
layer_end

.enemy_guay_chirp:
chan_setlayer 0, .layer_55AE
chan_setvibratorate 112
chan_setvibratoextent 64
chan_end

.layer_55AE:
layer_setinstr F1_I_ANIMALS
layer_transpose 48
layer_note1 PITCH_C4, 0xc, 100
layer_note1 PITCH_D4, 0x14, 100
layer_end

.enemy_guay_attack:
chan_setlayer 0, .layer_55C1
chan_setvibratorate 112
chan_setvibratoextent 64
chan_end

.layer_55C1:
layer_setinstr F1_I_ANIMALS
layer_transpose 48
layer_note1 PITCH_F4, 0xc, 100
layer_note1 PITCH_D4, 0x12, 100
layer_note1 PITCH_E4, 0xc, 100
layer_note1 PITCH_D4, 0x10, 100
layer_end

.enemy_guay_fly:
chan_setinstr F1_I_OWL_FLAP
chan_setlayer 0, .layer_55D8
chan_end

.layer_55D8:
layer_portamento 0x81, 22, 200
layer_note1 PITCH_D3, 0x26, 68
layer_end

.enemy_biggoron_blind:
chan_setlayer 0, .layer_55E4
chan_end

.layer_55E4:
layer_setinstr F1_I_GORON
layer_transpose 48
layer_note1 PITCH_BF3, 0x45, 100
layer_end

.enemy_biggoron_happy:
chan_setlayer 0, .layer_55F3
chan_setlayer 1, .layer_55F5
chan_end

.layer_55F3:
layer_delay 0xc

.layer_55F5:
layer_setinstr F1_I_GORON_YAWN
layer_transpose 48
layer_note1 PITCH_C4, 0x7f, 100
layer_end

.enemy_boss_ganon_growl:
chan_setlayer 0, .layer_5604
chan_setlayer 1, .layer_5606
chan_end

.layer_5604:
layer_delay 0x14

.layer_5606:
layer_setinstr F1_I_MONSTER_ROAR
layer_enablelegato
layer_portamento 0x85, 19, 191
layer_note1 PITCH_GF2, 0x34, 100
layer_note1 PITCH_E2, 0xc0, 100
layer_end

.enemy_gold_skull_spin:
chan_setlayer 0, .layer_561C
chan_setlayer 1, .layer_5626
chan_end

.layer_561C:
layer_setinstr F1_I_GRASS_RUSTLE
layer_portamento 0x81, 31, 100
layer_note1 PITCH_C3, 0x32, 80
layer_end

.layer_5626:
layer_setinstr F1_I_SLIDE_BOOTS
layer_delay 0x10
layer_transpose 24
layer_note1 PITCH_C2, 0x6, 36
layer_note1 PITCH_F2, 0x6, 36
layer_note1 PITCH_C3, 0x6, 36
layer_note1 PITCH_F3, 0x6, 36
layer_note1 PITCH_C4, 0x6, 36
layer_end

.enemy_boss_ganon_sword_clank:
chan_setlayer 0, .layer_5643
chan_setlayer 1, .layer_5647
chan_end

.layer_5643:
layer_transpose 44
layer_jumprel .layer_5649

.layer_5647:
layer_transpose 48
.layer_5649:
layer_setinstr F1_I_WITCH_ARGUE
layer_note1 PITCH_EF4, 0x7f, 100
layer_end

.enemy_skulltula_creak:
chan_setinstr F1_I_MECH
chan_setlayer 0, .layer_5655
chan_end

.layer_5655:
layer_note1 PITCH_EF3, 0x40, 100
layer_end

.enemy_boss_twinrova_bicker:
chan_setinstr F1_I_WITCH_ARGUE
chan_setlayer 0, .layer_5675
.chan_565E:
chan_rand 32
chan_writeseq 40, .layer_5675+1
chan_writeseq 40, .chan_566E+1
chan_rand 6
chan_writeseq 100, .layer_5675
.chan_566E:
chan_setval 1
chan_call .delay_varyingvol
chan_jumprel .chan_565E

.layer_5675:
layer_note1 PITCH_C3, 0x50, 100
layer_jumprel .layer_5675

.enemy_big_poe_caught_soul:
chan_setinstr F1_I_DINO_ROAR
chan_setlayer 0, .layer_5684
chan_setvibratorate 56
chan_setvibratoextent 64
chan_end

.layer_5684:
layer_setenvelope .envelope_6A2C, 230
.layer_5688:
layer_note1 PITCH_DF2, 0xd0, 56
layer_jumprel .layer_5688

.enemy_goron_kid_cry:
chan_setlayer 0, .layer_5696
chan_setvibratorate 54
chan_setvibratoextent 128
chan_end

.layer_5696:
layer_setinstr F1_I_GORON
layer_transpose 48
layer_portamento 0x81, 46, 255
layer_note1 PITCH_GF3, 0x70, 88
layer_end

.enemy_spike_trap_rock:
chan_setlayer 0, .layer_56AA
chan_setvibratorate 224
chan_setvibratoextent 96
chan_end

.layer_56AA:
layer_setinstr F1_I_SLIDE_BOOTS
layer_note1 PITCH_A2, 0x40, 76
layer_end

.enemy_unused:
chan_end

.balign 16

.filter_enemy0:
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter_enemy1:
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter_enemy2:
filter 0, 0, 0, 0, 0, 0, 0, 0
