.table_player:
entry .player_kid_step_dirt
entry .player_kid_step_sand
entry .player_kid_step_stone
entry .player_kid_step_jabu
entry .player_kid_step_water
entry .player_kid_step_water_deep
entry .player_kid_step_tall_grass
entry .player_kid_step_lava
entry .player_kid_step_grass
entry .player_kid_step_carpet
entry .player_kid_step_wood
entry .player_kid_step_bridge
entry .player_step_vines
entry .player_step_iron_boots
entry .player_step_unused
entry .player_kid_step_ice
entry .player_kid_jump_dirt
entry .player_kid_jump_sand
entry .player_kid_jump_stone
entry .player_kid_jump_jabu
entry .player_kid_jump_water
entry .player_kid_jump_water_deep
entry .player_kid_jump_tall_grass
entry .player_kid_jump_lava
entry .player_kid_jump_grass
entry .player_kid_jump_carpet
entry .player_kid_jump_wood
entry .player_kid_jump_bridge
entry .player_kid_step_dirt
entry .player_jump_iron_boots
entry .player_jump_unused
entry .player_kid_jump_ice
entry .player_kid_land_dirt
entry .player_kid_land_sand
entry .player_kid_land_stone
entry .player_kid_land_jabu
entry .player_kid_land_water
entry .player_kid_land_water_deep
entry .player_kid_land_tall_grass
entry .player_kid_land_lava
entry .player_kid_land_grass
entry .player_kid_land_carpet
entry .player_kid_land_wood
entry .player_kid_land_bridge
entry .player_kid_step_dirt
entry .player_land_iron_boots
entry .player_land_unused
entry .player_kid_land_ice
entry .player_climb_down_vine_top
entry .player_climb_up_vine_top
entry .player_climb_on_epona
entry .player_jump_off_epona
entry .player_shield_epona
entry .player_change_item_held
entry .player_catch_boomerang
entry .player_large_splash
entry .player_small_splash
entry .player_swim
entry .player_throw
entry .player_hit_wall_old
entry .player_flip
entry .player_sidejump
entry .player_hit_blunt
entry .player_hit_stab
entry .player_slip_dirt
entry .player_slip_sand
entry .player_slip_stone
entry .player_slip_jabu
entry .player_slip_water
entry .player_slip_water_deep
entry .player_slip_tall_grass
entry .player_slip_lava
entry .player_slip_grass
entry .player_slip_carpet
entry .player_slip_wood
entry .player_slip_bridge
entry .player_kid_step_water
entry .player_slip_wood
entry .player_slip_unused
entry .player_slip_stone
entry .player_rebound_dirt
entry .player_rebound_sand
entry .player_rebound_stone
entry .player_rebound_jabu
entry .player_rebound_water
entry .player_rebound_water_deep
entry .player_rebound_tall_grass
entry .player_rebound_lava
entry .player_rebound_grass
entry .player_rebound_carpet
entry .player_rebound_wood
entry .player_rebound_bridge
entry .player_kid_step_dirt
entry .player_rebound_wood
entry .player_rebound_unused
entry .player_rebound_ice
entry .player_step_iron_boots
entry .player_jump_iron_boots
entry .player_land_iron_boots
entry .player_dive_surface
entry .player_dive_down
entry .player_dive_move
entry .player_kid_metalequip
entry .player_old_metalequip
entry .player_electric_shock
entry .player_lift_grass
entry .player_lift_rock
entry .player_morpha_bubble
entry .player_lift_giant_rock
entry .player_sword_charge
entry .player_freeze
entry .player_lift_pot
entry .player_hit_unused
entry .player_idle_shuffle
entry .player_idle_slide
entry .player_dive_unused
entry .player_freeze_short
entry .player_ice_break
entry .player_slip_ice
entry .player_sheathe_item_unused
entry .player_lift_crate
entry .player_cast_fire
entry .player_cast_wind
entry .player_cast_wind_return
entry .player_cast_soul
entry .player_arrow_fire_charge
entry .player_arrow_ice_charge
entry .player_arrow_light_charge
entry .player_old_step_dirt
entry .player_old_step_sand
entry .player_old_step_stone
entry .player_old_step_jabu
entry .player_old_step_water
entry .player_old_step_water_deep
entry .player_old_step_tall_grass
entry .player_old_step_lava
entry .player_old_step_grass
entry .player_old_step_carpet
entry .player_old_step_wood
entry .player_old_step_bridge
entry .player_old_step_vine
entry .player_step_iron_boots
entry .player_kid_step_dirt
entry .player_old_step_ice
entry .player_old_jump_dirt
entry .player_old_jump_sand
entry .player_old_jump_stone
entry .player_old_jump_jabu
entry .player_old_jump_water
entry .player_old_jump_water_deep
entry .player_old_jump_tall_grass
entry .player_old_jump_lava
entry .player_old_jump_grass
entry .player_old_jump_carpet
entry .player_old_jump_wood
entry .player_old_jump_bridge
entry .player_kid_step_dirt
entry .player_jump_iron_boots
entry .player_kid_step_dirt
entry .player_old_jump_ice
entry .player_old_land_dirt
entry .player_old_land_sand
entry .player_old_land_stone
entry .player_old_land_jabu
entry .player_old_land_water
entry .player_old_land_water_deep
entry .player_old_land_tall_grass
entry .player_old_land_lava
entry .player_old_land_grass
entry .player_old_land_carpet
entry .player_old_land_wood
entry .player_old_land_bridge
entry .player_old_step_dirt
entry .player_land_iron_boots
entry .player_kid_step_dirt
entry .player_old_land_ice
entry .player_crawl_dirt
entry .player_crawl_sand
entry .player_crawl_stone
entry .player_crawl_jabu
entry .player_crawl_water
entry .player_crawl_water_deep
entry .player_crawl_tall_grass
entry .player_crawl_lava
entry .player_crawl_grass
entry .player_crawl_carpet
entry .player_crawl_wood
entry .player_crawl_bridge
entry .player_kid_step_dirt
entry .player_kid_step_dirt
entry .player_kid_step_dirt
entry .player_crawl_ice
entry .player_cast_soul_end
entry .player_roll_dust
entry .player_crash_unused
entry .player_cast_soul_appear
entry .player_fairy_heal
entry .player_rebound_unarmed
entry .player_plant_seed
entry .player_plant_grow
entry .player_cast_wind_dismiss
entry .player_hover
entry .player_plant_hover
entry .env_elevator_move
entry .player_kid_step_dirt
entry .player_kid_step_dirt
entry .player_kid_step_dirt
entry .player_kid_step_dirt
entry .player_slip_dirt2  // Used; all other slip values are ignored
entry .player_slip_sand2
entry .player_slip_stone2
entry .player_slip_jabu2
entry .player_slip_jabu2
entry .player_slip_jabu2
entry .player_slip_lava2
entry .player_slip_jabu2
entry .player_slip_grass2
entry .player_slip_dirt2
entry .player_slip_unused2
entry .player_slip_unused2
entry .player_kid_step_water
entry .player_slip_unused2
entry .player_slip_iron_boots_unused
entry .player_slip_stone2

.player_kid_step_dirt:
chan_setlayer 0, .layer_2A7
chan_end

.layer_2A5:
layer_transpose -2

.layer_2A7:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_E3, 0x15, 56
layer_end

.layer_2AD:
layer_transpose -6
layer_delay 0xd
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note0 PITCH_D4, 0x4, 36, 127
layer_setinstr FONT00_INSTR_STEP_FIRE
layer_note1 PITCH_G3, 0x4, 56
layer_end

.player_kid_step_sand:
chan_setlayer 0, .layer_2C3
chan_end

.layer_2C1:
layer_transpose -2

.layer_2C3:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A3, 0x15, 56
layer_end

.player_kid_step_stone:
chan_setval 20
chan_iowriteval 1
chan_setlayer 0, .layer_2D2
chan_end

.layer_2D0:
layer_transpose -2

.layer_2D2:
layer_setinstr FONT00_INSTR_STEP_ROCK
layer_note1 PITCH_GF3, 0x15, 95
layer_end

.player_kid_step_jabu:
chan_setlayer 0, .layer_2DE
chan_end

.layer_2DC:
layer_transpose -2

.layer_2DE:
layer_setinstr FONT00_INSTR_STEP_JABU
layer_portamento 0x82, 31, 255
layer_note1 PITCH_A3, 0x2d, 93
layer_end

.player_kid_step_water:
chan_setlayer 0, .layer_2EE
chan_end

.layer_2EC:
layer_transpose -2

.layer_2EE:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_A3, 0x1e, 56
layer_end

.player_kid_step_water_deep:
chan_setlayer 0, .layer_2FA
chan_end

.layer_2F8:
layer_transpose -2

.layer_2FA:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_F3, 0x1e, 56
layer_end

.player_kid_step_tall_grass:
chan_setlayer 0, .layer_306
chan_end

.layer_304:
layer_transpose -2

.layer_306:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_F3, 0x6, 80
layer_setinstr FONT00_INSTR_STEP_GRASS
layer_setreleaserate 235
layer_note1 PITCH_B3, 0x30, 80
layer_end

.player_kid_step_lava:
chan_setlayer 0, .layer_319
chan_end

.layer_317:
layer_transpose -2

.layer_319:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_C3, 0x4, 42
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_GF2, 0x6, 56
layer_setinstr FONT00_INSTR_BOMB
layer_portamento 0x81, 44, 255
layer_note1 PITCH_F3, 0x16, 64
layer_end

.player_kid_step_grass:
chan_setlayer 0, .layer_333
chan_end

.layer_331:
layer_transpose -2

.layer_333:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_setenvelope .envelope_66B0, 250
layer_note1 PITCH_A3, 0x15, 70
layer_end

.player_kid_step_carpet:
chan_setlayer 0, .layer_343
chan_end

.layer_341:
layer_transpose -2

.layer_343:
layer_setinstr FONT00_INSTR_STEP_CARPET_1
layer_note1 PITCH_GF4, 0x0, 80
layer_end

.player_kid_step_wood:
chan_setlayer 0, .layer_34F
chan_end

.layer_34D:
layer_transpose -2

.layer_34F:
layer_setinstr FONT00_INSTR_STEP_WOOD
layer_note1 PITCH_AF3, 0x14, 86
layer_end

.player_kid_step_bridge:
chan_setlayer 0, .layer_35B
chan_end

.layer_359:
layer_transpose -2

.layer_35B:
layer_setinstr FONT00_INSTR_STEP_BRIDGE
layer_note1 PITCH_C3, 0x18, 76
layer_end

.player_step_vines:
chan_setlayer 0, .layer_36A
chan_setlayer 1, .layer_2AD
chan_end

.layer_368:
layer_transpose -2

.layer_36A:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note0 PITCH_DF3, 0x6, 110, 127
layer_note1 PITCH_E1, 0xa, 110
layer_delay 0x5
layer_end

.player_step_iron_boots:
chan_setinstr FONT00_INSTR_STEP_IRON
chan_setlayer 0, .layer_37C
chan_end

.layer_37C:
layer_note1 PITCH_E3, 0x28, 96
layer_end

.player_step_unused:
chan_setlayer 0, .layer_384
chan_end

.layer_384:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A2, 0x2a, 56
layer_end

.player_kid_step_ice:
chan_setlayer 0, .layer_390
chan_end

.layer_38E:
layer_transpose -2

.layer_390:
layer_setinstr FONT00_INSTR_STEP_ICE
layer_note1 PITCH_A3, 0x15, 85
layer_end

.player_kid_jump_dirt:
chan_setinstr FONT00_INSTR_STEP_GROUND
chan_setlayer 0, .layer_3A1
chan_setlayer 1, .layer_3AA
chan_end

.layer_39F:
layer_transpose -2

.layer_3A1:
layer_note1 PITCH_E3, 0xa, 63
layer_note1 PITCH_C4, 0xa, 63
layer_delay 0x7
layer_end

.layer_3AA:
layer_delay 0x7
layer_setinstr FONT00_INSTR_SWORD_HIT_SHIELD
layer_setenvelope .envelope_6660, 250
layer_note0 PITCH_C5, 0x6, 60, 127
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note0 PITCH_F4, 0x4, 48, 127
layer_setinstr FONT00_INSTR_STEP_FIRE
layer_note1 PITCH_F3, 0x5, 55
layer_note1 PITCH_B3, 0x5, 55
layer_end

.player_kid_jump_sand:
chan_setlayer 0, .layer_3CE
chan_setlayer 1, .layer_3AA
chan_end

.layer_3CC:
layer_transpose -2

.layer_3CE:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A3, 0xa, 63
layer_note1 PITCH_F4, 0xa, 63
layer_delay 0x7
layer_end

.player_kid_jump_stone:
chan_setval 20
chan_iowriteval 1
chan_setlayer 0, .layer_3E5
chan_setlayer 1, .layer_3AA
chan_end

.layer_3E3:
layer_transpose -2

.layer_3E5:
layer_setinstr FONT00_INSTR_STEP_ROCK
layer_note0 PITCH_GF3, 0xa, 95, 127
layer_note0 PITCH_B3, 0xa, 95, 127
layer_delay 0x7
layer_end

.player_kid_jump_jabu:
chan_setlayer 0, .layer_3FB
chan_setlayer 1, .layer_3AA
chan_end

.layer_3F9:
layer_transpose -2

.layer_3FB:
layer_setinstr FONT00_INSTR_STEP_JABU
layer_note1 PITCH_F3, 0xa, 63
layer_note1 PITCH_D4, 0xa, 63
layer_delay 0x7
layer_end

.player_kid_jump_water:
chan_setlayer 0, .layer_40F
chan_setlayer 1, .layer_3AA
chan_end

.layer_40D:
layer_transpose -2

.layer_40F:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_A3, 0xa, 63
layer_note1 PITCH_F4, 0x1e, 63
layer_end

.player_kid_jump_water_deep:
chan_setlayer 0, .layer_421
chan_setlayer 1, .layer_3AA
chan_end

.layer_41F:
layer_transpose -2

.layer_421:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_F3, 0xa, 63
layer_note1 PITCH_D4, 0x1e, 63
layer_end

.player_kid_jump_tall_grass:
chan_setlayer 0, .layer_433
chan_setlayer 1, .layer_3AA
chan_end

.layer_431:
layer_transpose -2

.layer_433:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_E3, 0x6, 80
layer_setinstr FONT00_INSTR_STEP_GRASS
layer_setreleaserate 225
layer_note1 PITCH_A3, 0xa, 75
layer_note1 PITCH_E4, 0x30, 80
layer_end

.player_kid_jump_lava:
chan_setlayer 0, .layer_44C
chan_setlayer 1, .layer_3AA
chan_end

.layer_44A:
layer_transpose -2

.layer_44C:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_BF2, 0x4, 45
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_G2, 0x6, 63
layer_setinstr FONT00_INSTR_BOMB
layer_portamento 0x81, 42, 255
layer_note1 PITCH_E3, 0xe, 49
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_EF3, 0xe, 63
layer_end

.player_kid_jump_grass:
chan_setlayer 0, .layer_46E
chan_setlayer 1, .layer_3AA
chan_end

.layer_46C:
layer_transpose -2

.layer_46E:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_G3, 0xa, 63
layer_note1 PITCH_F4, 0xa, 63
layer_delay 0x7
layer_end

.player_kid_jump_carpet:
chan_setlayer 0, .layer_482
chan_setlayer 1, .layer_3AA
chan_end

.layer_480:
layer_transpose -2

.layer_482:
layer_setinstr FONT00_INSTR_STEP_CARPET_1
layer_note1 PITCH_C4, 0xa, 78
layer_note1 PITCH_A4, 0xa, 78
layer_delay 0x7
layer_end

.player_kid_jump_wood:
chan_setlayer 0, .layer_496
chan_setlayer 1, .layer_3AA
chan_end

.layer_494:
layer_transpose -2

.layer_496:
layer_setinstr FONT00_INSTR_STEP_WOOD
layer_note1 PITCH_AF3, 0xa, 73
layer_note1 PITCH_F4, 0x1e, 73
layer_end

.player_kid_jump_bridge:
chan_setlayer 0, .layer_4A8
chan_setlayer 1, .layer_3AA
chan_end

.layer_4A6:
layer_transpose -2

.layer_4A8:
layer_setinstr FONT00_INSTR_STEP_BRIDGE
layer_note1 PITCH_F3, 0xa, 63
layer_note1 PITCH_B3, 0x19, 63
layer_end

.player_jump_iron_boots:
chan_setinstr FONT00_INSTR_STEP_IRON
chan_setlayer 0, .layer_4B7
chan_end

.layer_4B7:
layer_note1 PITCH_EF3, 0xa, 96
layer_note1 PITCH_A3, 0x18, 96
layer_end

.layer_unused_4BE:
layer_transpose 2
layer_portamento 0x85, 26, 255
layer_note1 PITCH_EF2, 0xa, 80
layer_enablelegato
layer_transpose 5
layer_portamento 0x85, 26, 255
layer_note1 PITCH_EF2, 0xf, 80
layer_note1 PITCH_EF2, 0x12, 80
layer_note1 PITCH_G2, 0xf, 80
layer_end

.player_jump_unused:
chan_setlayer 0, .layer_4DF
chan_setlayer 1, .layer_3AA
chan_end

.layer_4DF:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A2, 0x12, 63
layer_note1 PITCH_F3, 0x12, 63
layer_delay 0x7
layer_end

.player_kid_jump_ice:
chan_setlayer 0, .layer_4F3
chan_setlayer 1, .layer_3AA
chan_end

.layer_4F1:
layer_transpose -2

.layer_4F3:
layer_setinstr FONT00_INSTR_STEP_ICE
layer_note1 PITCH_E3, 0x7, 95
layer_note1 PITCH_B4, 0x12, 95
layer_delay 0x7
layer_end

.player_kid_land_dirt:
chan_setlayer 0, .layer_507
chan_setlayer 1, .layer_512
chan_end

.layer_505:
layer_transpose -2

.layer_507:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_E4, 0xa, 75
layer_note1 PITCH_E3, 0xa, 75
layer_delay 0x7
layer_end

.layer_512:
layer_delay 0x7
layer_setinstr FONT00_INSTR_SWORD_HIT_SHIELD
layer_setenvelope .envelope_6660, 250
layer_note0 PITCH_C5, 0x6, 39, 127
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note0 PITCH_D4, 0x4, 49, 127
layer_setinstr FONT00_INSTR_STEP_FIRE
layer_note1 PITCH_B3, 0x5, 39
layer_note1 PITCH_F3, 0x5, 39
layer_end

.player_kid_land_sand:
chan_setlayer 0, .layer_536
chan_setlayer 1, .layer_512
chan_end

.layer_534:
layer_transpose -2

.layer_536:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A4, 0xa, 75
layer_note1 PITCH_A3, 0xa, 75
layer_end

.player_kid_land_stone:
chan_setval 20
chan_iowriteval 1
chan_setlayer 0, .layer_54B
chan_setlayer 1, .layer_512
chan_end

.layer_549:
layer_transpose -2

.layer_54B:
layer_setinstr FONT00_INSTR_STEP_ROCK
layer_note0 PITCH_GF4, 0xa, 101, 64
layer_note0 PITCH_GF3, 0xa, 101, 64
layer_delay 0x7
layer_end

.player_kid_land_jabu:
chan_setlayer 0, .layer_561
chan_setlayer 1, .layer_512
chan_end

.layer_55F:
layer_transpose -2

.layer_561:
layer_setinstr FONT00_INSTR_STEP_JABU
layer_note1 PITCH_F4, 0xa, 75
layer_note1 PITCH_F3, 0xa, 75
layer_delay 0x7
layer_end

.player_kid_land_water:
chan_setlayer 0, .layer_575
chan_setlayer 1, .layer_512
chan_end

.layer_573:
layer_transpose -2

.layer_575:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_A4, 0xa, 75
layer_note1 PITCH_A3, 0x1e, 75
layer_end

.player_kid_land_water_deep:
chan_setlayer 0, .layer_587
chan_setlayer 1, .layer_512
chan_end

.layer_585:
layer_transpose -2

.layer_587:
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_F4, 0xa, 75
layer_note1 PITCH_F3, 0x1e, 75
layer_end

.player_kid_land_tall_grass:
chan_setlayer 0, .layer_599
chan_setlayer 1, .layer_512
chan_end

.layer_597:
layer_transpose -2

.layer_599:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_A3, 0x6, 56
layer_setinstr FONT00_INSTR_STEP_GRASS
layer_setreleaserate 225
layer_note1 PITCH_F4, 0xa, 80
layer_note1 PITCH_A3, 0x30, 80
layer_end

.player_kid_land_lava:
chan_setlayer 0, .layer_5B2
chan_setlayer 1, .layer_512
chan_end

.layer_5B0:
layer_transpose -2

.layer_5B2:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_B2, 0x4, 68
layer_setinstr FONT00_INSTR_STEP_WATER
layer_note1 PITCH_F3, 0x6, 75
layer_note1 PITCH_G2, 0xa, 75
layer_setinstr FONT00_INSTR_BOMB
layer_portamento 0x81, 38, 255
layer_note1 PITCH_C3, 0x16, 70
layer_end

.player_kid_land_grass:
chan_setlayer 0, .layer_5D2
chan_setlayer 1, .layer_512
chan_end

.layer_5D0:
layer_transpose -2

.layer_5D2:
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_E4, 0xa, 75
layer_note1 PITCH_G3, 0xa, 75
layer_delay 0x7
layer_end

.player_kid_land_carpet:
chan_setlayer 0, .layer_5E6
chan_setlayer 1, .layer_512
chan_end

.layer_5E4:
layer_transpose -2

.layer_5E6:
layer_setinstr FONT00_INSTR_STEP_CARPET_1
layer_note1 PITCH_B4, 0xa, 90
layer_note1 PITCH_F3, 0xa, 90
layer_delay 0x7
layer_end

.player_kid_land_wood:
chan_setlayer 0, .layer_5FA
chan_setlayer 1, .layer_512
chan_end

.layer_5F8:
layer_transpose -2

.layer_5FA:
layer_setinstr FONT00_INSTR_STEP_WOOD
layer_note1 PITCH_AF4, 0xa, 85
layer_note1 PITCH_AF3, 0x1e, 85
layer_end

.player_kid_land_bridge:
chan_setlayer 0, .layer_60C
chan_setlayer 1, .layer_512
chan_end

.layer_60A:
layer_transpose -2

.layer_60C:
layer_setinstr FONT00_INSTR_STEP_BRIDGE
layer_note1 PITCH_F4, 0xa, 75
layer_note1 PITCH_F3, 0x1e, 75
layer_end

.player_land_iron_boots:
chan_setinstr FONT00_INSTR_STEP_IRON
chan_setlayer 0, .layer_61B
chan_end

.layer_61B:
layer_note1 PITCH_B3, 0xa, 96
layer_note1 PITCH_F3, 0x18, 96
layer_end

.player_land_unused:
chan_setlayer 0, .layer_629
chan_setlayer 1, .layer_512
chan_end

.layer_629:
layer_setinstr FONT00_INSTR_STEP_SAND
layer_note1 PITCH_A3, 0x12, 75
layer_note1 PITCH_A2, 0x12, 75
layer_end

.player_kid_land_ice:
chan_setlayer 0, .layer_63B
chan_setlayer 1, .layer_512
chan_end

.layer_639:
layer_transpose -2

.layer_63B:
layer_setinstr FONT00_INSTR_STEP_ICE
layer_note1 PITCH_G4, 0x5, 98
layer_note1 PITCH_E3, 0x12, 98
layer_end

.player_climb_down_vine_top:
chan_setinstr FONT00_INSTR_DROP
chan_setenvelope .envelope_667C
chan_setlayer 0, .layer_64D
chan_end

.layer_64D:
layer_portamento 0x1, 48, 0x10
layer_note1 PITCH_D4, 0x18, 100
layer_end

.player_climb_up_vine_top:
chan_setinstr FONT00_INSTR_WATER_SPLASH_S
chan_setenvelope .envelope_6694
chan_setlayer 0, .layer_65E
chan_end

.layer_65E:
layer_note1 PITCH_A4, 0x16, 127
layer_end

.player_climb_on_epona:
chan_setinstr FONT00_INSTR_STEP_CARPET_0
chan_setenvelope .envelope_6674
chan_setlayer 0, .layer_66B
chan_end

.layer_66B:
layer_note1 PITCH_A2, 0xa, 105
layer_end

.player_jump_off_epona:
chan_setinstr FONT00_INSTR_WATER_SPLASH_S
chan_setenvelope .envelope_6694
chan_setlayer 0, .layer_678
chan_end

.layer_678:
layer_portamento 0x81, 48, 255
layer_note1 PITCH_C4, 0x20, 60
layer_end

.player_shield_epona:
chan_setinstr FONT00_INSTR_WATER_SPLASH_S
chan_setenvelope .envelope_6688
chan_setlayer 0, .layer_693
chan_setlayer 1, .layer_68C
chan_end

.layer_68C:
layer_note1 PITCH_F2, 0x6, 115
layer_note1 PITCH_C3, 0xc, 115
layer_end

.layer_693:
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_portamento 0x81, 20, 255
layer_note1 PITCH_E3, 0x19, 90
layer_end

.player_change_item_held:
chan_setinstr FONT00_INSTR_WATER_SPLASH_S
chan_setenvelope .envelope_66E0
chan_setlayer 0, .layer_6A9
chan_setlayer 1, .layer_6B5
chan_end

.layer_6A9:
layer_note1 PITCH_G3, 0x6, 115
layer_note1 PITCH_C3, 0xc, 115
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_note1 PITCH_D4, 0xf, 90
layer_end

.layer_6B5:
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_portamento 0x81, 31, 255
layer_note1 PITCH_F2, 0x19, 90
layer_end

.player_catch_boomerang:
chan_setinstr FONT00_INSTR_STEP_GROUND
chan_setlayer 0, .layer_6C5
chan_end

.layer_6C5:
layer_portamento 0x81, 27, 200
layer_note1 PITCH_F3, 0x7, 127
layer_end

.player_large_splash:
chan_setinstr FONT00_INSTR_WATER_SPLASH
chan_setenvelope .envelope_65FC
chan_setdecayrelease 127
chan_setlayer 0, .layer_6D8
chan_end

.layer_6D8:
layer_portamento 0x81, 39, 200
layer_note1 PITCH_F3, 0x91, 100
layer_end

.player_small_splash:
chan_setinstr FONT00_INSTR_WATER_SPLASH
chan_setenvelope .envelope_6610
chan_setlayer 0, .layer_6EA
chan_end

.layer_6EA:
layer_portamento 0x81, 34, 48
layer_note1 PITCH_A3, 0x50, 105
layer_end

.player_swim:
chan_setlayer 0, .layer_6F8
chan_end

.layer_unused_6F6:
layer_transpose -6

.layer_6F8:
layer_setinstr FONT00_INSTR_WATER_SWIM
layer_setenvelope .envelope_6624, 251
layer_portamento 0x81, 36, 200
layer_note1 PITCH_C3, 0x30, 105
layer_end

.player_throw:
chan_setinstr FONT00_INSTR_SWORD_MISS
chan_setlayer 0, .layer_70C
chan_end

.layer_70C:
layer_portamento 0x81, 27, 255
layer_note1 PITCH_C2, 0x18, 100
layer_end

.player_hit_wall_old:
chan_sethilogain 15
chan_setlayer 0, .layer_71A
chan_end

.layer_71A:
layer_call .layer_fn_725
layer_portamento 0x81, 45, 255
layer_note1 PITCH_B2, 0xe, 115
layer_end

.layer_fn_725:
layer_setinstr FONT00_INSTR_SLAM_GUNSHOT
layer_setenvelope .envelope_66B0, 245
layer_end

.layer_unused_72C:
layer_transpose 2
layer_jump .layer_800

.player_flip:
chan_setinstr FONT00_INSTR_SWORD_MISS
chan_setlayer 0, .layer_737
chan_end

.layer_737:
layer_enablelegato
layer_portamento 0x85, 29, 225
layer_note1 PITCH_D2, 0x8, 100
layer_note1 PITCH_D1, 0x14, 100
layer_end

.player_sidejump:
chan_setlayer 0, .layer_747
chan_end

.layer_747:
layer_setinstr FONT00_INSTR_SWORD_MISS
layer_setreleaserate 248
layer_portamento 0x81, 26, 225
layer_note1 PITCH_GF1, 0xc, 100
layer_end

.player_hit_blunt:
chan_sethilogain 20
chan_setlayer 0, .layer_1B3F
chan_setlayer 1, .layer_71A
chan_setlayer 2, .layer_75F
chan_end

.layer_75F:
layer_call .layer_fn_725
layer_portamento 0x85, 34, 255
layer_note1 PITCH_BF3, 0x7, 110
layer_end

.player_hit_stab:
chan_setinstr FONT00_INSTR_SWORD_SWING
chan_setenvelope .envelope_66C8
chan_setlayer 0, .layer_776
chan_setlayer 1, .layer_785
chan_end

.layer_776:
layer_portamento 0x81, 55, 127
layer_note1 PITCH_DF1, 0x8, 115
layer_portamento 0x81, 6, 255
layer_note1 PITCH_AF3, 0xb, 105
layer_end

.layer_785:
layer_setinstr FONT00_INSTR_WHISTLE_AIR
layer_portamento 0x81, 49, 222
layer_note1 PITCH_BF2, 0x8, 115
layer_portamento 0x81, 19, 255
layer_note1 PITCH_F3, 0xc, 115
layer_end

.player_slip_dirt:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E0C
chan_end

.layer_79D:
layer_delay 0x30
layer_end

.player_slip_sand:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E1C
chan_end

.player_slip_stone:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E24
chan_end

.player_slip_jabu:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E34
chan_end

.player_slip_water:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E34
chan_end

.player_slip_water_deep:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E34
chan_end

.player_slip_tall_grass:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E3C
chan_end

.player_slip_lava:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E34
chan_end

.player_slip_grass:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E4C
chan_end

.player_slip_carpet:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E0C
chan_end

.player_slip_wood:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E54
chan_end

.player_slip_bridge:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E54
chan_end

.player_slip_unused:
chan_setlayer 0, .layer_79D
chan_setlayer 1, .layer_E64
chan_end

.player_rebound_dirt:
chan_setlayer 1, .layer_80C
.chan_7F7:
chan_sethilogain 25
chan_setlayer 2, .layer_512

.player_rebound_unarmed:
chan_setlayer 0, .layer_800
chan_end

.layer_800:
layer_call .layer_fn_725
layer_portamento 0x81, 38, 200
layer_note0 PITCH_BF3, 0x24, 115, 100
layer_end

.layer_80C:
layer_transpose -6
layer_jump .layer_507

.player_rebound_sand:
chan_setlayer 1, .layer_816
chan_jumprel .chan_7F7

.layer_816:
layer_transpose -6
layer_jump .layer_536

.player_rebound_stone:
chan_setlayer 1, .layer_820
chan_jumprel .chan_7F7

.layer_820:
layer_transpose -6
layer_jump .layer_54B

.player_rebound_jabu:
chan_setlayer 1, .layer_82A
chan_jumprel .chan_7F7

.layer_82A:
layer_transpose -6
layer_jump .layer_561

.player_rebound_water:
chan_setlayer 1, .layer_834
chan_jumprel .chan_7F7

.layer_834:
layer_transpose -6
layer_jump .layer_575

.chan_unused_839:
chan_jumprel .chan_7F7

.player_rebound_water_deep:
chan_setlayer 1, .layer_840
chan_jumprel .chan_7F7

.layer_840:
layer_transpose -6
layer_jump .layer_587

.player_rebound_tall_grass:
chan_setlayer 1, .layer_84A
chan_jumprel .chan_7F7

.layer_84A:
layer_transpose -6
layer_jump .layer_599

.player_rebound_lava:
chan_setlayer 1, .layer_854
chan_jumprel .chan_7F7

.layer_854:
layer_transpose -6
layer_jump .layer_5B2

.player_rebound_grass:
chan_setlayer 1, .layer_85E
chan_jumprel .chan_7F7

.layer_85E:
layer_transpose -6
layer_jump .layer_5D2

.player_rebound_carpet:
chan_setlayer 1, .layer_868
chan_jumprel .chan_7F7

.layer_868:
layer_transpose -6
layer_jump .layer_5E6

.player_rebound_wood:
chan_setlayer 1, .layer_872
chan_jumprel .chan_7F7

.layer_872:
layer_transpose -6
layer_jump .layer_5FA

.player_rebound_bridge:
chan_setlayer 1, .layer_87D
chan_jump .chan_7F7

.layer_87D:
layer_transpose -6
layer_jump .layer_60C

.player_rebound_unused:
chan_setlayer 1, .layer_888
chan_jump .chan_7F7

.layer_888:
layer_transpose -6
layer_jump .layer_629

.player_rebound_ice:
chan_setlayer 1, .layer_893
chan_jump .chan_7F7

.layer_893:
layer_transpose -6
layer_jump .layer_63B

.player_dive_surface:
chan_setlayer 0, .layer_89C
chan_end

.layer_89C:
layer_setinstr FONT00_INSTR_WATER_SPLISH
layer_setenvelope .envelope_66EC, 251
layer_portamento 0x81, 39, 255
layer_note1 PITCH_C5, 0x18, 100
layer_setinstr FONT00_INSTR_WATER_SPLASH
layer_setenvelope .envelope_67A4, 221
layer_portamento 0x81, 32, 200
layer_note1 PITCH_C4, 0x3c, 100
layer_end

.player_dive_down:
chan_setlayer 0, .layer_8BB
chan_end

.layer_8BB:
layer_setinstr FONT00_INSTR_WATER_BUBBLES
layer_setenvelope .envelope_65FC, 221
layer_portamento 0x1, 46, 0x48
layer_note1 PITCH_G3, 0xdc, 100
layer_end

.player_dive_move:
chan_setlayer 0, .layer_8CE
chan_end

.layer_8CE:
layer_setinstr FONT00_INSTR_WATER_BUBBLES
layer_setenvelope .envelope_65D8, 251
layer_portamento 0x81, 39, 255
layer_note1 PITCH_E4, 0x60, 100
layer_end

.player_kid_metalequip:
chan_setlayer 0, .layer_2AD
chan_end

.player_old_metalequip:
chan_setlayer 0, .layer_B7D
chan_end

.player_electric_shock:
chan_setinstr FONT00_INSTR_POTTERY_ELECTRIC
chan_setenvelope .envelope_6674
chan_setlayer 0, .layer_903
.chan_8EC:
chan_rand 10
chan_writeseq 2, .layer_903+1
chan_writeseq 2, .chan_8FC+1
chan_rand 12
chan_writeseq 92, .layer_903
.chan_8FC:
chan_setval 1
chan_call .delay_varyingvol
chan_jumprel .chan_8EC

.layer_903:
layer_note1 PITCH_C3, 0x50, 80
layer_delay 0x5
layer_jumprel .layer_903

.player_lift_grass:
chan_setlayer 1, .layer_936
chan_setlayer 0, .layer_911
chan_end

.layer_911:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_note1 PITCH_A3, 0xa, 64
layer_setinstr FONT00_INSTR_STEP_GRASS
layer_note1 PITCH_D4, 0x18, 90
layer_end

.player_lift_rock:
chan_sethilogain 20
chan_setlayer 0, .layer_927
chan_setlayer 1, .layer_936
chan_end

.layer_925:
layer_transpose -4

.layer_927:
layer_setinstr FONT00_INSTR_STEP_GROUND
layer_portamento 0x83, 27, 255
layer_note1 PITCH_E2, 0x6, 80
layer_setinstr FONT00_INSTR_STEP_CARPET_0
layer_note1 PITCH_E3, 0xf, 95
layer_end

.layer_936:
layer_setinstr FONT00_INSTR_EXPLOSION_0
layer_portamento 0x81, 22, 255
layer_note1 PITCH_A5, 0x1e, 50
layer_end

.player_morpha_bubble:
chan_setlayer 0, .layer_944
chan_end

.layer_944:
layer_setinstr FONT00_INSTR_WATER_BUBBLES
layer_enablelegato
.layer_947:
layer_portamento 0x81, 15, 255
layer_note1 PITCH_E2, 0x60, 75
layer_jumprel .layer_947

.player_lift_giant_rock:
chan_sethilogain 20
chan_setlayer 0, .layer_925
chan_setlayer 1, .layer_2D55
chan_end

.player_sword_charge:
chan_setinstr FONT00_INSTR_SYNTH
chan_setenvelope .envelope_66EC
chan_setlayer 0, .layer_962
chan_end

.layer_962:
layer_portamento 0x81, 36, 255
layer_note1 PITCH_C4, 0x64, 95
layer_end

.player_freeze:
chan_sethilogain 30
chan_setlayer 0, .layer_973
chan_setlayer 1, .layer_97E
chan_end

.layer_973:
layer_setinstr FONT00_INSTR_FIRE_WIND
layer_portamento 0x81, 43, 255
layer_note1 PITCH_E3, 0xb4, 105
layer_end

.layer_97E:
layer_setinstr FONT00_INSTR_CLOTH_TEAR
layer_portamento 0x81, 20, 255
layer_note1 PITCH_B1, 0xb4, 88
layer_end

.player_lift_pot:
chan_setlayer 0, .layer_990
chan_setlayer 1, .layer_99A
chan_end

.layer_990:
layer_transpose 50
.layer_992:
layer_setinstr FONT00_INSTR_POTTERY_ELECTRIC
layer_note1 PITCH_C2, 0x6, 72
layer_end

.layer_998:
layer_transpose -4

.layer_99A:
layer_setinstr FONT00_INSTR_STEP_IRON
layer_note1 PITCH_B3, 0x3, 110
layer_end

.player_hit_unused:
chan_setlayer 0, .layer_9A4
chan_end

.layer_9A4:
layer_setinstr FONT00_INSTR_SLAM_GUNSHOT
layer_setenvelope .envelope_664C, 253
layer_note1 PITCH_BF3, 0x5, 100
layer_end

.player_idle_shuffle:
chan_setlayer 0, .layer_9B2
chan_end

.layer_9B2:
layer_setinstr FONT00_INSTR_EXPLOSION_0
layer_setenvelope .envelope_66E0, 251
layer_note1 PITCH_EF3, 0xa, 80
layer_end

.player_idle_slide:
chan_setlayer 0, .layer_9C0
chan_end

.layer_9C0:
layer_setinstr FONT00_INSTR_WATER_SPLASH
layer_setenvelope .envelope_66E0, 251
layer_note1 PITCH_C3, 0x15, 80
layer_end

.player_dive_unused:
chan_setlayer 0, .layer_9CE
chan_end

.layer_9CE:
layer_setinstr FONT00_INSTR_WATER_SPLISH
layer_setenvelope .envelope_66EC, 251
layer_portamento 0x81, 39, 255
layer_note1 PITCH_C3, 0xc, 100
layer_setinstr FONT00_INSTR_WATER_SPLASH
layer_setenvelope .envelope_67A4, 221
layer_portamento 0x81, 36, 200
layer_note1 PITCH_C3, 0x3c, 100
layer_end

.player_freeze_short:
chan_sethilogain 30
chan_setlayer 0, .layer_9F2
chan_setlayer 1, .layer_9FC
chan_end

.layer_9F2:
layer_setinstr FONT00_INSTR_FIRE_WIND
layer_portamento 0x81, 43, 255
layer_note1 PITCH_E3, 0x1c, 105
layer_end

.layer_9FC:
layer_setinstr FONT00_INSTR_CLOTH_TEAR
layer_portamento 0x81, 20, 255
layer_note1 PITCH_B1, 0x1c, 88
layer_end

.player_ice_break:
chan_setlayer 0, .layer_A0A
chan_end

.layer_A0A:
layer_setinstr FONT00_INSTR_CHATTER
layer_transpose 48
layer_note1 PITCH_F3, 0x14, 100
layer_note1 PITCH_A3, 0x0, 105
layer_end

.player_slip_ice:
chan_setinstr FONT00_INSTR_SLIDE_HEAVY
chan_setenvelope .envelope_66FC
chan_setlayer 0, .layer_A1E
chan_end

.layer_A1E:
layer_note1 PITCH_DF4, 0x7d00, 64
layer_end

.player_sheathe_item_unused:
chan_setinstr FONT00_INSTR_WATER_SPLASH_S
chan_setenvelope .envelope_66EC
chan_setlayer 0, .layer_A2C
chan_end

.layer_A2C:
layer_note1 PITCH_F3, 0x5, 75
layer_note1 PITCH_BF2, 0xa, 75
layer_note1 PITCH_BF2, 0x11, 75
layer_end

.player_lift_crate:
chan_setlayer 0, .layer_A3A
chan_end

.layer_A3A:
layer_setinstr FONT00_INSTR_STICK_ATTACK
layer_note1 PITCH_A2, 0x6, 100
layer_end

.player_cast_fire:
chan_setlayer 0, .layer_A4C
chan_setlayer 1, .layer_A5D
chan_setlayer 2, .layer_A6E
chan_jump .chan_118F

.layer_A4C:
layer_setinstr FONT00_INSTR_FLAME_THUNDER
layer_setreleaserate 221
layer_enablelegato
layer_portamento 0x85, 0, 255
layer_note1 PITCH_A2, 0xfa, 74
layer_note1 PITCH_A4, 0x64, 74
layer_end

.layer_A5D:
layer_setinstr FONT00_INSTR_EXPLOSION_0
layer_setreleaserate 221
layer_note1_long 36, 0x1e, 100
layer_portamento 0x81, 0, 255
layer_note1 PITCH_A3, 0x140, 85
layer_end

.layer_A6E:
layer_setinstr FONT00_INSTR_FAIRY_MAGIC
layer_setreleaserate 221
layer_portamento 0x81, 0, 255
layer_note1 PITCH_A4, 350, 80
layer_end

.player_cast_wind:
chan_setlayer 0, .layer_A85
chan_setlayer 1, .layer_A9E
chan_setlayer 2, .layer_AAF
chan_end

.layer_A85:
layer_call .layer_fn_A95
layer_enablelegato
layer_portamento 0x85, 62, 255
layer_note1 PITCH_C4, 0x3c, 85
layer_note1 PITCH_F5, 500, 85
layer_end

.layer_fn_A95:
layer_setinstr FONT00_INSTR_WIND_HOWL_S
layer_setenvelope .envelope_6808, 200
layer_transpose 12
layer_end

.layer_A9E:
layer_portamento 0x81, 32, 255
layer_setinstr FONT00_INSTR_SLIDE_LINK
layer_transpose 24
layer_setenvelope .envelope_66F4, 200
layer_note1 PITCH_F5, 0x230, 40
layer_end

.layer_AAF:
layer_setinstr FONT00_INSTR_WARP
layer_transpose 12
layer_setenvelope .envelope_67D8, 200
layer_note1 PITCH_F5, 0x230, 70
layer_end

.player_cast_wind_return:
chan_setinstr FONT00_INSTR_WARP
chan_sethilogain 15
chan_setlayer 0, .layer_2130
chan_setlayer 1, .layer_2124
chan_setlayer 2, .layer_2D3A
chan_setval 80
chan_call .delay_varyingvol
chan_setlayer 0, .layer_AD5
chan_setlayer 2, .layer_210B
chan_end

.layer_AD5:
layer_delay 0x30
layer_end

.player_cast_soul:
chan_setval 0
.chan_ADA:
chan_writeseq 244, .layer_AFD+1
chan_writeseq 12, .layer_AF2+1
chan_setvibratorate 255
chan_setinstr FONT00_INSTR_WARP
chan_setenvelope .envelope_6818
chan_setdecayrelease 235
chan_setlayer 0, .layer_AFD
chan_setlayer 1, .layer_AF2
chan_end

.layer_AF2:
layer_transpose 36
layer_portamento 0x83, 44, 127
.layer_AF8:
layer_note1 PITCH_A4, 0x60, 64
layer_jumprel .layer_AF8

.layer_AFD:
layer_transpose 12
layer_portamento 0x83, 44, 127
.layer_B03:
layer_note1 PITCH_A4, 0x60, 64
layer_jumprel .layer_B03

.player_arrow_fire_charge:
chan_setlayer 0, .layer_B23
chan_setlayer 2, .layer_B1D
chan_setval 1
chan_call .delay_varyingvol
chan_setlayer 1, .layer_B2F
chan_setvibratorate 96
chan_setvibratoextentlinear 128, 128, 0
chan_end

.layer_B1D:
layer_setinstr FONT00_INSTR_IGNITE
layer_note1 PITCH_A3, 0x0, 110
layer_end

.layer_B23:
layer_setinstr FONT00_INSTR_WIND_HOWL_S
layer_setenvelope .envelope_66FC, 245
layer_enablelegato
.layer_B2A:
layer_note1 PITCH_A3, 0x64, 74
layer_jumprel .layer_B2A

.layer_B2F:
layer_setinstr FONT00_INSTR_FAIRY_MAGIC
layer_enablelegato
.layer_B32:
layer_note1 PITCH_D3, 0x0, 35
layer_jumprel .layer_B32

.player_arrow_ice_charge:
chan_setlayer 0, .layer_B47
chan_setlayer 1, .layer_B41
chan_setlayer 2, .layer_B57
chan_end

.layer_B41:
layer_setinstr FONT00_INSTR_WARP
layer_transpose 16
layer_jumprel .layer_B49

.layer_B47:
layer_setinstr FONT00_INSTR_SHIMMER
.layer_B49:
layer_setenvelope .envelope_6818, 245
layer_enablelegato
layer_portamento 0x81, 39, 200
.layer_B52:
layer_note1 PITCH_E4, 0x3c, 60
layer_jumprel .layer_B52

.layer_B57:
layer_setinstr FONT00_INSTR_IGNITE
layer_note1 PITCH_F4, 0x0, 110
layer_end

.player_arrow_light_charge:
chan_setlayer 0, .layer_B6D
chan_setlayer 1, .layer_B67
chan_setlayer 2, .layer_B57
chan_end

.layer_B67:
layer_setinstr FONT00_INSTR_WARP
layer_transpose 16
layer_jumprel .layer_B6F

.layer_B6D:
layer_setinstr FONT00_INSTR_FAIRY
.layer_B6F:
layer_setenvelope .envelope_66C8, 240
layer_enablelegato
.layer_B74:
layer_note1 PITCH_G4, 0x51, 42
layer_jumprel .layer_B74

.player_old_step_dirt:
chan_setlayer 0, .layer_2A5
chan_end

.layer_B7D:
layer_delay 0x8
layer_transpose -6
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_setreleaserate 255
layer_note0 PITCH_BF3, 0x4, 64, 64
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note1 PITCH_DF3, 0x5, 24
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_transpose 48
layer_note1 PITCH_AF3, 0x4, 38
layer_end

.player_old_step_sand:
chan_setlayer 0, .layer_2C1
chan_end

.player_old_step_stone:
chan_setlayer 0, .layer_2D0
chan_end

.player_old_step_jabu:
chan_setlayer 0, .layer_2DC
chan_end

.player_old_step_water:
chan_setlayer 0, .layer_2EC
chan_end

.player_old_step_water_deep:
chan_setlayer 0, .layer_2F8
chan_end

.player_old_step_tall_grass:
chan_setlayer 0, .layer_304
chan_end

.player_old_step_lava:
chan_setlayer 0, .layer_317
chan_end

.player_old_step_grass:
chan_setlayer 0, .layer_331
chan_end

.player_old_step_carpet:
chan_setlayer 0, .layer_341
chan_end

.player_old_step_wood:
chan_setlayer 0, .layer_34D
chan_end

.player_old_step_bridge:
chan_setlayer 0, .layer_359
chan_end

.player_old_step_vine:
chan_setlayer 0, .layer_368
chan_setlayer 1, .layer_B7D
chan_end

.player_old_step_ice:
chan_setlayer 0, .layer_38E
chan_end

.player_old_jump_dirt:
chan_setinstr FONT00_INSTR_STEP_GROUND
chan_setlayer 0, .layer_39F
chan_setlayer 1, .layer_BD6
chan_end

.layer_BD6:
layer_delay 0x8
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_setreleaserate 255
layer_note0 PITCH_C4, 0x4, 90, 64
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note1 PITCH_E3, 0x5, 38
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_transpose 48
layer_note1 PITCH_C4, 0x4, 55
layer_end

.player_old_jump_sand:
chan_setlayer 0, .layer_3CC
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_stone:
chan_setlayer 0, .layer_3E3
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_jabu:
chan_setlayer 0, .layer_3F9
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_water:
chan_setlayer 0, .layer_40D
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_water_deep:
chan_setlayer 0, .layer_41F
chan_end

.player_old_jump_tall_grass:
chan_setlayer 0, .layer_431
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_lava:
chan_setlayer 0, .layer_44A
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_grass:
chan_setlayer 0, .layer_46C
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_carpet:
chan_setlayer 0, .layer_480
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_wood:
chan_setlayer 0, .layer_494
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_bridge:
chan_setlayer 0, .layer_4A6
chan_setlayer 1, .layer_BD6
chan_end

.player_old_jump_ice:
chan_setlayer 0, .layer_4F1
chan_setlayer 1, .layer_BD6
chan_end

.player_old_land_dirt:
chan_setlayer 0, .layer_505
chan_setlayer 1, .layer_C45
chan_end

.layer_C45:
layer_delay 0x8
layer_setinstr FONT00_INSTR_SWORD_SHEATHE
layer_setreleaserate 255
layer_note0 PITCH_D4, 0x4, 90, 64
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_note1 PITCH_D3, 0x5, 38
layer_setinstr FONT00_INSTR_SWORD_STRIKE
layer_transpose 48
layer_note1 PITCH_BF3, 0x4, 55
layer_end

.player_old_land_sand:
chan_setlayer 0, .layer_534
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_stone:
chan_setlayer 0, .layer_549
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_jabu:
chan_setlayer 0, .layer_55F
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_water:
chan_setlayer 0, .layer_573
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_water_deep:
chan_setlayer 0, .layer_585
chan_end

.player_old_land_tall_grass:
chan_setlayer 0, .layer_597
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_lava:
chan_setlayer 0, .layer_5B0
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_grass:
chan_setlayer 0, .layer_5D0
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_carpet:
chan_setlayer 0, .layer_5E4
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_wood:
chan_setlayer 0, .layer_5F8
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_bridge:
chan_setlayer 0, .layer_60A
chan_setlayer 1, .layer_C45
chan_end

.player_old_land_ice:
chan_setlayer 0, .layer_639
chan_setlayer 1, .layer_C45
chan_end

.player_crawl_dirt:
chan_setlayer 0, .layer_2A5
chan_setval 2
chan_call .delay_varyingvol
chan_jump .player_slip_dirt

.player_crawl_sand:
chan_setlayer 0, .layer_2C1
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_sand

.player_crawl_stone:
chan_setlayer 0, .layer_2D0
chan_setval 2
chan_call .delay_varyingvol
chan_jump .player_slip_stone

.player_crawl_jabu:
chan_setlayer 0, .layer_2DC
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_jabu

.player_crawl_water:
chan_setlayer 0, .layer_2EC
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_water

.player_crawl_water_deep:
chan_setlayer 0, .layer_2F8
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_water_deep

.player_crawl_tall_grass:
chan_setlayer 0, .layer_304
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_tall_grass

.player_crawl_lava:
chan_setlayer 0, .layer_317
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_lava

.player_crawl_grass:
chan_setlayer 0, .layer_331
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_grass

.player_crawl_carpet:
chan_setlayer 0, .layer_341
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_carpet

.player_crawl_wood:
chan_setlayer 0, .layer_34D
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_wood

.player_crawl_bridge:
chan_setlayer 0, .layer_359
chan_setval 1
chan_call .delay_varyingvol
chan_jump .player_slip_bridge

.player_crawl_ice:
chan_setlayer 0, .layer_38E
chan_setval 5
chan_call .delay_varyingvol
chan_jump .player_slip_stone

.player_cast_soul_end:
chan_setvibratoextent 20
chan_setval 4
chan_jump .chan_ADA

.player_roll_dust:
chan_setlayer 0, .layer_D47
chan_end

.layer_D47:
layer_setinstr FONT00_INSTR_SLIDE_BLOCK
layer_setenvelope .envelope_66A0, 235
layer_note1 PITCH_F4, 0xa, 90
layer_note1 PITCH_G4, 0xe, 90
layer_note1 PITCH_B4, 0x7f, 75
layer_end

.player_crash_unused:
chan_setlayer 0, .layer_D5E
chan_setlayer 1, .layer_1B3F
chan_end

.layer_D5E:
layer_setinstr FONT00_INSTR_MECH_CHARGE
layer_setenvelope .envelope_65D8, 228
layer_note1 PITCH_C5, 0x64, 100
layer_end

.player_cast_soul_appear:
chan_setinstr FONT00_INSTR_WARP
chan_setlayer 0, .layer_D74
chan_setlayer 1, .layer_29FC
chan_setlayer 2, .layer_2A01
chan_end

.layer_D74:
layer_setinstr FONT00_INSTR_SHIMMER
layer_portamento 0x81, 39, 45
layer_note1 PITCH_E4, 0x118, 60
layer_end

.player_fairy_heal:
chan_setlayer 0, .layer_D8A
chan_setlayer 1, .layer_D9A
chan_setvibratorate 192
chan_setvibratoextent 32
chan_end

.layer_D8A:
layer_setinstr INSTR_WV_SQUARE
layer_setenvelope .envelope_6818, 221
layer_enablelegato
layer_portamento 0x81, 36, 64
.layer_D95:
layer_note1 PITCH_A4, 0x78, 34
layer_jumprel .layer_D95

.layer_D9A:
layer_setinstr FONT00_INSTR_FAIRY
layer_setenvelope .envelope_66FC, 237
layer_portamento 0x83, 36, 255
.layer_DA4:
layer_note1 PITCH_C4, 0x14, 85
layer_jumprel .layer_DA4

.player_plant_grow:
chan_setlayer 0, .layer_DB8
chan_setlayer 1, .layer_DB6
.chan_DAF:
chan_setvibratoratelinear 10, 100, 8
chan_setvibratoextent 15
chan_end

.layer_DB6:
layer_transpose 24

.layer_DB8:
layer_portamento 0x81, 15, 255

.layer_DBC:
layer_setinstr INSTR_WV_4PULSE
layer_setenvelope .envelope_6674, 251
layer_enablelegato
.layer_DC3:
layer_note1 PITCH_C4, 500, 35
layer_jumprel .layer_DC3

.player_plant_seed:
chan_setlayer 0, .layer_DB6
chan_jumprel .chan_DAF

.player_cast_wind_dismiss:
chan_setinstr FONT00_INSTR_WARP
chan_setlayer 0, .layer_DD7
chan_setlayer 1, .layer_2A01
chan_end

.layer_DD7:
layer_transpose 30
layer_enablelegato
layer_portamento 0x81, 43, 64
layer_note1 PITCH_D4, 0xaa, 80
layer_end

.player_hover:
chan_setinstr FONT00_INSTR_WARP
chan_setvibratoextent 9
chan_setvibratorate 128
chan_setenvelope .envelope_6818
chan_setdecayrelease 235
chan_setlayer 0, .layer_DF2
chan_end

.layer_DF2:
layer_enablelegato
.layer_DF3:
layer_note1 PITCH_E5, 0x7d00, 95
layer_jumprel .layer_DF3

.player_plant_hover:
chan_setlayer 0, .layer_DBC
chan_setlayer 1, .layer_E04
chan_setvibratorate 100
chan_setvibratoextent 15
chan_end

.layer_E04:
layer_transpose 24
layer_jumprel .layer_DBC

.player_slip_dirt2:
chan_setlayer 0, .layer_E0C
chan_end

.layer_E0C:
layer_setinstr FONT00_INSTR_SLIDE_BLOCK
.layer_E0E:
layer_setenvelope .envelope_6704, 251
layer_enablelegato
.layer_E13:
layer_note1 PITCH_C4, 0x7f, 88
layer_jumprel .layer_E13

.player_slip_sand2:
chan_setlayer 0, .layer_E1C
chan_end

.layer_E1C:
layer_setinstr FONT00_INSTR_SLIDE_LINK
layer_jumprel .layer_E0E

.player_slip_stone2:
chan_setlayer 0, .layer_E24
chan_end

.layer_E24:
layer_setinstr FONT00_INSTR_SLIDE_HEAVY
layer_setenvelope .envelope_6704, 251
layer_enablelegato
.layer_E2B:
layer_note1 PITCH_F4, 0x7f, 80
layer_jumprel .layer_E2B

.player_slip_jabu2:
chan_setlayer 0, .layer_E34
chan_end

.layer_E34:
layer_setinstr FONT00_INSTR_SLIDE_WET
layer_jumprel .layer_E0E

.player_slip_lava2:
chan_setlayer 0, .layer_E3C
chan_end

.layer_E3C:
layer_setinstr FONT00_INSTR_SLIDE_WET
layer_setenvelope .envelope_6704, 251
layer_enablelegato
.layer_E43:
layer_note1 PITCH_C4, 0x7f, 86
layer_jumprel .layer_E43

.player_slip_grass2:
chan_setlayer 0, .layer_E4C
chan_end

.layer_E4C:
layer_setinstr FONT00_INSTR_DISTORTION
layer_jumprel .layer_E0E

.player_slip_unused2:
chan_setlayer 0, .layer_E54
chan_end

.layer_E54:
layer_setinstr FONT00_INSTR_SLIDE_HEAVY
layer_setenvelope .envelope_6704, 251
layer_enablelegato
.layer_E5B:
layer_note1 PITCH_AF3, 0x7f, 80
layer_jumprel .layer_E5B

.player_slip_iron_boots_unused:
chan_setlayer 0, .layer_E64
chan_end

.layer_E64:
layer_setinstr FONT00_INSTR_SLIDE_LINK
layer_setenvelope .envelope_6704, 251
layer_enablelegato
.layer_E6B:
layer_note1 PITCH_DF3, 0x7f, 95
layer_jumprel .layer_E6B

.balign 16

.filter_player0:
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter_player1:
filter 0, 0, 0, 0, 0, 0, 0, 0

.filter_player2:
filter 0, 0, 0, 0, 0, 0, 0, 0
